/**
 * 知识节点树（数据）。树的逻辑在 src/narrative/knowledge.ts。
 *
 * 五层对应 GDD §7.1。层与层之间靠 requires 咬合：
 *   L1 表层 —— 现场证据。任何玩家第一轮都能拿到一两条。
 *   L2 中层 —— 把证据接起来才成立的判断。
 *   L3 深层 —— 承认信号是真的。这一层会掉 SAN。
 *   L4 真层 —— 你是样本。这一层需要跨轮回的物证（前一个你的日志）。
 *   L5 底层 —— 路径就是书写。只有集齐 L4 才能理解。
 *
 * 命名：k.<短语>。正典 31 条，非正典 3 条（apocrypha）。
 * end.author 要求正典全集 + 跨 ≥4 轮回。
 */

import type { KnowledgeDef } from '../../narrative/knowledge';

export const KNOWLEDGE: readonly KnowledgeDef[] = [
  // ------------------------------------------------------------------ L1 表层
  {
    id: 'k.breach-from-inside',
    title: '断口的卷边朝外',
    layer: 1,
    requires: [],
    summary: '船体的破口是从里面撕开的。不是水压。',
    revealText: '卷边朝外。是从里面。',
    corrupted: '卷边朝外。朝外。朝外。',
    source: '压载舱 / 机械层破口处，用灯或触摸检查断口',
  },
  {
    id: 'k.manifest-nineteen',
    title: '十九个名字',
    layer: 1,
    requires: [],
    summary: '船员名单上十九人。没有小孩。也没有你。',
    revealText: '十九个名字。你数了两遍。',
    corrupted: '十九个名字。第二十行有压痕，没有字。',
    source: '指挥层档案 / 名单板',
  },
  {
    id: 'k.no-distress',
    title: '没有人求救',
    layer: 1,
    requires: [],
    summary: '无线电日志里没有 SOS。有一条发出去的，内容是坐标。',
    revealText: '最后一次发讯不是求救。是报位置。',
    source: '声呐室 / 无线电值班簿',
  },
  {
    id: 'k.your-bunk',
    title: '你的铺位是铺好的',
    layer: 1,
    requires: [],
    summary: '铺位牌上是你的名字。床单是新换的。你不记得上船。',
    revealText: '床单是新换的。',
    corrupted: '床单是新换的。上面有你的体温。',
    source: '生活层 / 铺位区',
  },

  // ------------------------------------------------------------------ L2 中层
  {
    id: 'k.not-research',
    title: 'KYRIE-9 不是科考船',
    layer: 2,
    requires: ['k.breach-from-inside', 'k.no-distress'],
    summary: '没有采样设备。所有舱位都朝着一个方向：听。',
    revealText: '船上没有一台采样器。',
    source: '把破口与无线电日志两条对上',
  },
  {
    id: 'k.listening-array',
    title: '聆听阵列',
    layer: 2,
    requires: ['k.not-research'],
    summary: '整条船是一支麦克风。龙骨是振膜。',
    revealText: '龙骨不是承力的。是收音的。',
    corrupted: '龙骨在响。你贴上去，它就更响。',
    source: '机械层 / 龙骨检修口；或万斯讲解阵列',
  },
  {
    id: 'k.all-volunteers',
    title: '全员自愿',
    layer: 2,
    requires: ['k.manifest-nineteen', 'k.not-research'],
    summary: '十九份手写同意书。没有一个人的字是抖的。',
    revealText: '十九份同意书。字都不抖。',
    source: '指挥层档案 / 同意书匣',
  },
  {
    id: 'k.vance-onboard',
    title: '万斯在船上',
    layer: 2,
    requires: ['k.listening-array'],
    summary: '他的坐标越来越准。因为他在用船的阵列，不是用海面的定位。',
    revealText: '他报的深度比你自己的表还准。',
    corrupted: '他报的深度是你下一分钟的深度。',
    source: '连续三次记录万斯给的坐标并与自己的深度表比对',
  },
  {
    id: 'k.mother-is-spliced',
    title: '母亲是剪接的',
    layer: 2,
    requires: ['k.your-bunk'],
    summary: '她的每句话中间都有一下"咔"。她只会说你听过的话。',
    revealText: '每句话中间有一下咔。',
    source: '医务室磁带机 / 慢速回放广播',
  },
  {
    id: 'k.choir-sings-manifest',
    title: '唱诗班在唱名单',
    layer: 2,
    requires: ['k.manifest-nineteen'],
    summary: '六个人在唱十九个名字。唱到第十九个就回到第一个。',
    revealText: '他们在点名。',
    corrupted: '他们在点名。有一个名字你答应了。',
    source: '圣所层礼拜堂 / 听完整一轮',
  },

  // ------------------------------------------------------------------ L3 深层
  {
    id: 'k.signal-is-real',
    title: '信号是真的',
    layer: 3,
    requires: ['k.listening-array', 'k.choir-sings-manifest'],
    summary: '不是设备故障，不是幻听。两个不相连的系统收到同一段。',
    revealText: '两个系统，同一段。那就不是故障。',
    corrupted: '三个系统。第三个是你。',
    source: '声呐室 / 把阵列录音与唱诗班的旋律对齐',
  },
  {
    id: 'k.cult-was-right',
    title: '教团没疯',
    layer: 3,
    requires: ['k.all-volunteers', 'k.signal-is-real'],
    summary: '他们不是被骗下来的。他们下来是为了确认一件事，而且确认到了。',
    revealText: '他们是对的。这比他们疯了难接受得多。',
    source: '圣所层 / 读完最后一次礼拜记录',
  },
  {
    id: 'k.signal-in-blood',
    title: '它在你的血里',
    layer: 3,
    requires: ['k.signal-is-real'],
    summary: '感染不是生物学的。取样放到载玻片上，它还在按那个节拍。',
    revealText: '载玻片上那点东西，在按拍子。',
    corrupted: '载玻片上那点东西，在按你的拍子。',
    source: '医务室 / 自己取血做镜检（需要 infection）',
  },
  {
    id: 'k.dorn-tied-himself',
    title: '多恩自己绑的',
    layer: 3,
    requires: [],
    summary: '绳结在他手能到的地方。收尾的结是用牙咬紧的。',
    revealText: '结在他手边。是他自己收的。',
    source: '指挥层 / 检查多恩的绳结（不要问他）',
  },
  {
    id: 'k.mother-was-crew',
    title: '母亲是船员',
    layer: 3,
    requires: ['k.mother-is-spliced', 'k.listening-array'],
    summary: '广播里的声音是名单上第三个人。她的档案照片你认得。',
    revealText: '第三个名字。你认得那张脸。',
    corrupted: '第三个名字。你认得那张脸。你有那张脸。',
    source: '档案室 / 把磁带音色与人事档案对上',
  },
  {
    id: 'k.pelle-not-on-list',
    title: '佩勒不在名单上',
    layer: 3,
    requires: ['k.manifest-nineteen'],
    summary: '他知道每个舱室的名字，但把顺序说反了——他是从图纸上学的，没走过。',
    revealText: '他把舱室顺序说反了。他没走过这条船。',
    source: '与佩勒对三次舱室名',
  },
  {
    id: 'k.reweave-has-rule',
    title: '重织有规律',
    layer: 3,
    requires: [],
    summary: '只有做了标记的门会变。变的方向总是把你往下推一层。',
    revealText: '它在推你往下走。',
    source: '在两道门上做标记后离开再回来',
  },

  // ------------------------------------------------------------------ L4 真层
  {
    id: 'k.you-are-sample-n',
    title: '你是第 N 个',
    layer: 4,
    requires: ['k.your-bunk', 'k.dorn-tied-himself'],
    summary: '铺位牌换过很多次，钉孔是一排。多恩数过你几次了。',
    revealText: '钉孔是一排。不是一个。',
    corrupted: '钉孔是一排。你数不清，因为你数到哪里就忘。',
    source: '生活层 / 把铺位牌拆下来看背面；或让多恩报数',
  },
  {
    id: 'k.salvage-is-ritual',
    title: '复苏仪式就是打捞',
    layer: 4,
    requires: ['k.you-are-sample-n', 'k.cult-was-right'],
    summary: '他们不是在救你。他们在把样本放回去，并记录这次走到哪。',
    revealText: '"复苏"这个词在他们的文件里写作"回收"。',
    source: '圣所层 / 仪式手册第二部分',
  },
  {
    id: 'k.ship-is-teaching',
    title: '船在教你',
    layer: 4,
    requires: ['k.reweave-has-rule', 'k.you-are-sample-n'],
    summary: '重连不是随机。它在关掉你已经会走的路，只留没走过的。',
    revealText: '它关掉的都是你已经学会的路。',
    corrupted: '它关掉的都是你已经学会的路。你学得很快。它很满意。',
    source: '连续两轮回记录重织方向',
  },
  {
    id: 'k.pelle-is-a-guide',
    title: '佩勒是引导体',
    layer: 4,
    requires: ['k.pelle-not-on-list', 'k.ship-is-teaching'],
    summary: '训练动物走迷宫时，会先放一只已经会走的进去。',
    revealText: '他是先放进去的那只。',
    corrupted: '他是先放进去的那只。他已经走了很多遍。他很累。',
    source: '佩勒第五次对话 / 或零号舱培养架',
  },
  {
    id: 'k.previous-log-predicts',
    title: '前一个你在预言',
    layer: 4,
    requires: ['k.you-are-sample-n'],
    summary: '他的日志写着你三分钟后做的事。字是你的字。',
    revealText: '这一页写的是你刚才做的事。',
    corrupted: '这一页写的是你正在做的事。笔还是热的。',
    source: '你自己的舱室 / 读到第三页',
  },
  {
    id: 'k.vance-is-the-recorder',
    title: '万斯是记录员',
    layer: 4,
    requires: ['k.vance-onboard', 'k.salvage-is-ritual'],
    summary: '他不是救你。他在做观测记录，而且要求记录对象保持通话。',
    revealText: '他一直在让你描述你看到的东西。他从不描述他看到的。',
    source: '万斯第六次通话 / 或找到他的值班簿',
  },
  {
    id: 'k.zero-is-the-berth',
    title: '零号舱是打捞舱',
    layer: 4,
    requires: ['k.salvage-is-ritual', 'k.signal-in-blood'],
    summary: '图纸上没有它，因为它不属于这条船。它是接口。',
    revealText: '零号舱不在图纸上，因为它不是船的一部分。',
    source: '零号舱 / 或对比两份图纸',
  },
  {
    id: 'k.mother-is-sample-three',
    title: '母亲是第三号样本',
    layer: 4,
    requires: ['k.mother-was-crew', 'k.you-are-sample-n'],
    summary: '她走完了，然后被留下来做广播。这就是"成功"的意思。',
    revealText: '她走完了。留下来的这部分，就是奖品。',
    corrupted: '她走完了。她在等你也走完，好有人陪她值班。',
    source: '档案室 / 第三号样本结案报告',
  },

  // ------------------------------------------------------------------ L5 底层
  {
    id: 'k.path-is-a-stroke',
    title: '路径是笔画',
    layer: 5,
    requires: ['k.ship-is-teaching', 'k.previous-log-predicts'],
    summary: '你在海床上留下的航迹是有形状的。前十七次的形状在图纸背面。',
    revealText: '图纸背面有十七条线。第十八条是你今天走的。',
    corrupted: '图纸背面有十七条线。第十八条已经画好了，你只是在描。',
    source: '图纸背面 / 或月池底部的刻痕',
  },
  {
    id: 'k.eight-strokes',
    title: '八个结局是八笔',
    layer: 5,
    requires: ['k.path-is-a-stroke', 'k.vance-is-the-recorder'],
    summary: '八种走法，八种收笔。万斯的记录表有八栏，其中七栏已经打勾。',
    revealText: '八栏。七个勾。',
    source: '万斯的值班簿最后一页',
  },
  {
    id: 'k.the-word',
    title: '正在写的那个字',
    layer: 5,
    requires: ['k.eight-strokes', 'k.zero-is-the-berth'],
    summary: '八笔合起来是一个字。不是名字。是一个动词。',
    revealText: '八笔。一个动词。祈使语气。',
    corrupted: '八笔。一个动词。它是在叫谁做什么。',
    source: '零号舱 / 把八条航迹叠在一起',
  },
  {
    id: 'k.author-is-not-it',
    title: '书写者不是它',
    layer: 5,
    requires: ['k.the-word', 'k.mother-is-sample-three'],
    summary: '它不会写字。它只会听。写字的是那些愿意被听见的人。',
    revealText: '它一直只是在听。是我们在写。',
    source: '档案室 / 教团创会记录第一条',
  },
  {
    id: 'k.pen-can-stop',
    title: '笔可以停',
    layer: 5,
    requires: ['k.author-is-not-it', 'k.pelle-is-a-guide'],
    summary: '样本不能拒绝走。但可以拒绝走到底。差一笔的字不成字。',
    revealText: '差一笔的字不是字。',
    corrupted: '差一笔的字不是字。所以他们会一直捞你，直到你写完。',
    source: '佩勒最后一次对话 / 月池边',
  },
  {
    id: 'k.your-name',
    title: '你的名字',
    layer: 5,
    requires: ['k.pen-can-stop', 'k.choir-sings-manifest'],
    summary: '唱诗班唱到第二十行时停半拍。那半拍是留给你答应的。',
    revealText: '那半拍是留给你的。你可以不填。',
    corrupted: '那半拍是留给你的。你上次填了。',
    source: '礼拜堂 / 集齐 L5 后再听一次合唱',
  },

  // -------------------------------------------------------------- 非正典（3）
  {
    id: 'k.galley-ledger',
    title: '厨房账本',
    layer: 1,
    requires: [],
    apocrypha: true,
    summary: '最后二十天，每天多领一份口粮。多的那份记在"客"名下。',
    revealText: '每天多一份。记在"客"名下。',
    source: '食堂 / 口粮账本',
  },
  {
    id: 'k.dorn-daughter',
    title: '多恩的女儿',
    layer: 2,
    requires: ['k.manifest-nineteen'],
    apocrypha: true,
    summary: '名单第十四行是他女儿。他从不提她，只问水位。',
    revealText: '第十四行姓多恩。',
    source: '名单 / 与多恩谈四次以上',
  },
  {
    id: 'k.pelle-whistle-origin',
    title: '哨子的来历',
    layer: 3,
    requires: ['k.pelle-not-on-list'],
    apocrypha: true,
    summary: '哨子是救生衣配件。编号 03。第三号样本的那件。',
    revealText: '哨子上刻着 03。',
    source: '佩勒的哨子 / 对照救生衣编号',
  },
];

export const KNOWLEDGE_IDS: ReadonlySet<string> = new Set(KNOWLEDGE.map((k) => k.id));
