/**
 * 账本 —— 前一个你写的日志，和你自己在心里过的那份信条表。
 *
 * 这不是 UI 面板，是一个叙事装置，同时解决三个问题：
 *
 *  1. **主题**：GDD §7.1 第五层真相是"路径就是书写"。既然如此，玩家做过的每件事
 *     都必须能被读出来 —— 而且是被**别人**的字读出来。日志页上写着你今天做过的事，
 *     笔迹是你的，墨是干的。这比任何一句台词都更能说明"你不是第一个"。
 *  2. **机制**：每一条 `did.*` / `know.*` 都在这里被真正读取。校验器因此能查出
 *     "写了但没人读"的死旗标 —— 那意味着一个动作没有留下痕迹，在本作里等于 bug。
 *  3. **代价**：读一行要付一口呼吸。想知道自己是谁，就得少活一点。
 *
 * 每一行的语气（tone）决定批注落在哪一页边：
 *   obey 顺从 / refuse 拒绝 / cruel 狠 / kind 软 / curious 好奇 / count 数
 * 批注节点在 npc-yourself.ts 里（self.margin.*）—— 那是"他"对你的评价，只有六种，
 * 因为他见过的样本只有六种走法。
 */

import type { Condition, NarrativeNode } from '../../core/contract';
import { addf, c, cor, fear, go, mark, num, on, san, setf } from '../../narrative/dsl';

export type LedgerTone = 'obey' | 'refuse' | 'cruel' | 'kind' | 'curious' | 'count';

export interface LedgerEntry {
  /** 被读取的旗标 */
  flag: string;
  /** 日志/信条上的那一行。冷、短、只写动作，不写感受。 */
  line: string;
  tone: LedgerTone;
}

const MARGIN: Record<LedgerTone, string> = {
  obey: 'self.margin.obey',
  refuse: 'self.margin.refuse',
  cruel: 'self.margin.cruel',
  kind: 'self.margin.kind',
  curious: 'self.margin.curious',
  count: 'self.margin.count',
};

// ---------------------------------------------------------------------------
// 第一册：日志（did.*）—— 他写的是你今天做过的事
// ---------------------------------------------------------------------------

export const DEEDS: readonly LedgerEntry[] = [
  // 序章
  { flag: 'did.woke', line: '醒。没有记起怎么上船。', tone: 'curious' },
  { flag: 'did.count-breaths', line: '数了呼吸。数到第几不重要，重要的是数了。', tone: 'count' },
  { flag: 'did.sat-up', line: '坐起来。用了两次力。', tone: 'obey' },
  { flag: 'did.read-plate', line: '读了补板上的三个字。', tone: 'obey' },
  { flag: 'did.touched-plate', line: '摸了那三个字。刻得不深。', tone: 'curious' },
  { flag: 'did.dug-at-plate', line: '用指甲抠了刻痕。下面还是铝。', tone: 'refuse' },
  { flag: 'did.read-own-plate', line: '读了自己的铺位牌。', tone: 'curious' },
  { flag: 'did.took-nameplate', line: '把铺位牌摘下来带走了。', tone: 'refuse' },
  { flag: 'did.wore-mask', line: '戴上面罩。密封圈是软的。', tone: 'obey' },
  { flag: 'did.wiped-visor', line: '擦了两次面镜。第二次是多余的。', tone: 'kind' },
  { flag: 'did.checked-gauge', line: '看了氧气表。', tone: 'count' },
  { flag: 'did.pried-bunk', line: '撬开了铺板。', tone: 'refuse' },
  { flag: 'did.smelled-sheets', line: '闻了床单。是自己的味道。', tone: 'curious' },
  { flag: 'did.knocked-hatch', line: '敲了门。三下。', tone: 'curious' },
  { flag: 'did.listened-at-door', line: '把耳朵贴在门上。', tone: 'obey' },
  { flag: 'did.answered-knock', line: '门后有人敲回来，我答应了。', tone: 'obey' },
  { flag: 'did.left-cabin', line: '离开舱室。没有关门。', tone: 'refuse' },
  { flag: 'did.marked-door', line: '在门上做了标记。', tone: 'count' },
  { flag: 'did.stopped-counting-early', line: '数到一半停了。', tone: 'refuse' },
  { flag: 'did.caught-own-memory', line: '发现那段记忆是自己编的。', tone: 'curious' },
  { flag: 'did.kept-false-memory', line: '知道是编的，还是留着了。', tone: 'kind' },

  // 名单 / 档案 / 日志
  { flag: 'did.found-manifest-board', line: '找到名单板。十九行。', tone: 'count' },
  { flag: 'did.read-names', line: '把十九个名字读完了。', tone: 'obey' },
  { flag: 'did.examined-holes', line: '数了打卡孔。', tone: 'count' },
  { flag: 'did.counted-burrs', line: '数了第二十个孔的毛刺。十七层。', tone: 'count' },
  { flag: 'did.took-manifest', line: '把名单摘下来了。', tone: 'refuse' },
  { flag: 'did.checked-row-twenty', line: '看了第二十行。', tone: 'curious' },
  { flag: 'did.noticed-third-row', line: '注意到第三行被摸得发亮。', tone: 'curious' },
  { flag: 'did.found-radio-log', line: '翻开无线电值班簿。', tone: 'obey' },
  { flag: 'did.read-radio-start', line: '读了值班簿最前面两行。', tone: 'curious' },
  { flag: 'did.read-radio-middle', line: '读到"有人问能不能不上浮"。', tone: 'curious' },
  { flag: 'did.read-radio-late', line: '读到接管记录那一行。', tone: 'curious' },
  { flag: 'did.looked-for-sos', line: '找过 SOS。没有。', tone: 'count' },
  { flag: 'did.read-last-transmission', line: '读了最后一行：位空，等下一个。', tone: 'curious' },
  { flag: 'did.saw-the-vote', line: '看了那张十九票的表决。', tone: 'curious' },
  { flag: 'did.located-broadcast', line: '把那串坐标对上了月池。', tone: 'count' },
  { flag: 'did.entered-archive', line: '进了档案室。', tone: 'obey' },
  { flag: 'did.examined-archive-prints', line: '看了地上的脚印。三层水印。', tone: 'count' },
  { flag: 'did.read-consent', line: '读了同意书。', tone: 'obey' },
  { flag: 'did.checked-consent-hands', line: '检查了十九份笔迹抖不抖。都不抖。', tone: 'count' },
  { flag: 'did.found-blank-consent', line: '找到那张空白的同意书。', tone: 'curious' },
  { flag: 'did.signed-consent', line: '签了。', tone: 'obey' },
  { flag: 'did.tore-consent', line: '把空白同意书撕了。', tone: 'refuse' },
  { flag: 'did.left-consent-blank', line: '把空白那张放回去了。', tone: 'refuse' },
  { flag: 'did.opened-personnel', line: '翻了人事档案。', tone: 'obey' },
  { flag: 'did.read-page-three', line: '读了第三页。备注：声线适合。', tone: 'curious' },
  { flag: 'did.matched-photo', line: '把口袋里的照片和档案比对了。', tone: 'count' },
  { flag: 'did.looked-for-own-file', line: '找过自己那一页。没有。', tone: 'curious' },
  { flag: 'did.asked-suitable-for-what', line: '问了"适合什么"。', tone: 'curious' },
  { flag: 'did.opened-report-three', line: '打开了第三号样本的结案报告。', tone: 'obey' },
  { flag: 'did.read-report-line', line: '读了没被涂黑那一行。', tone: 'obey' },
  { flag: 'did.saw-overwrite', line: '看出"留任"下面压着"回收"。', tone: 'curious' },
  { flag: 'did.backlit-redaction', line: '对着灯看涂黑的部分。', tone: 'refuse' },
  { flag: 'did.identified-the-question', line: '认出了她唯一要求保留的那一句。', tone: 'kind' },
  { flag: 'did.found-service-record', line: '找到最后一次礼拜的记录。', tone: 'obey' },
  { flag: 'did.asked-what-was-clear', line: '问了"听清楚了"什么。', tone: 'curious' },
  { flag: 'did.found-founding', line: '翻到了创会记录。', tone: 'curious' },
  { flag: 'did.looked-for-second-tenet', line: '把被裁掉的第二条找出来了。', tone: 'refuse' },
  { flag: 'did.understood-tenet', line: '想明白了"只会听"的意思。', tone: 'curious' },
  { flag: 'did.found-galley-ledger', line: '看了口粮账本。', tone: 'count' },
  { flag: 'did.identified-guest', line: '弄清了"客"是谁。', tone: 'kind' },
  { flag: 'did.checked-second-table', line: '去第二张桌子看了那副碗筷。', tone: 'kind' },
  { flag: 'did.sat-at-the-table', line: '在那副碗筷前坐下了。', tone: 'kind' },
  { flag: 'did.answered-at-the-table', line: '在桌边回答了"吃过了"。', tone: 'kind' },
  { flag: 'did.told-mother-hungry', line: '告诉她我还没吃。', tone: 'kind' },

  // 舱室
  { flag: 'did.found-breach', line: '找到走廊尽头那个洞。', tone: 'obey' },
  { flag: 'did.touched-breach', line: '摸了断口的卷边。朝外。', tone: 'count' },
  { flag: 'did.looked-through-breach', line: '从洞里往对面看。', tone: 'curious' },
  { flag: 'did.held-breath-at-foam', line: '屏住呼吸看水面的白沫。', tone: 'count' },
  { flag: 'did.crossed-breach', line: '钻过了那个洞。后背刮到了。', tone: 'refuse' },
  { flag: 'did.examined-breach-paint', line: '看了洞边的两层漆。', tone: 'curious' },
  { flag: 'did.scraped-paint', line: '刮掉了新漆，读到"此处将开"。', tone: 'refuse' },
  { flag: 'did.entered-pump', line: '进了泵舱。水到膝盖。', tone: 'obey' },
  { flag: 'did.examined-clamps', line: '数了八个卡箍的扭矩。', tone: 'count' },
  { flag: 'did.fixed-pumps', line: '把管子接回去了。水只降了两指。', tone: 'refuse' },
  { flag: 'did.killed-pump', line: '关了泵。', tone: 'refuse' },
  { flag: 'did.restarted-pump', line: '又把泵开起来了。', tone: 'obey' },
  { flag: 'did.listened-to-foam', line: '在安静里听了那层沫。', tone: 'obey' },
  { flag: 'did.answered-the-half-beat', line: '在半拍里出了声。', tone: 'obey' },
  { flag: 'did.refused-half-beat', line: '半拍来了，我没出声。', tone: 'refuse' },
  { flag: 'did.took-wrench', line: '从水底下捡了一把管钳。', tone: 'obey' },
  { flag: 'did.entered-sonar', line: '进了声呐室。', tone: 'obey' },
  { flag: 'did.read-sonar-tape', line: '拉出纸带看了二十天的直线。', tone: 'count' },
  { flag: 'did.counted-gaps', line: '数了纸带上的缺口。十七个。', tone: 'count' },
  { flag: 'did.pinged', line: '打了一次主动声呐。', tone: 'refuse' },
  { flag: 'did.pinged-twice', line: '又打了一次。', tone: 'cruel' },
  { flag: 'did.stopped-pinging', line: '把声呐关了，不再打。', tone: 'refuse' },
  { flag: 'did.used-hydrophone', line: '接上水听器听了一会儿。', tone: 'obey' },
  { flag: 'did.checked-array', line: '查了声呐阵的朝向。', tone: 'count' },
  { flag: 'did.checked-array-angle', line: '量了角度。九十度，正下方。', tone: 'count' },
  { flag: 'did.found-moonpool', line: '找到了月池。水面高两指。', tone: 'count' },
  { flag: 'did.approached-pool', line: '走到池边。', tone: 'obey' },
  { flag: 'did.knelt-at-pool', line: '在池边跪下了。', tone: 'obey' },
  { flag: 'did.touched-pool', line: '把手伸进水里。水是温的。', tone: 'curious' },
  { flag: 'did.arm-in-pool', line: '整条手臂伸下去了。', tone: 'refuse' },
  { flag: 'did.let-it-touch', line: '让它碰了我的手背，没有抽手。', tone: 'obey' },
  { flag: 'did.yanked-arm', line: '猛地把手抽回来了。', tone: 'refuse' },
  { flag: 'did.knocked-ninth', line: '敲了第九下。', tone: 'obey' },
  { flag: 'did.refused-ninth', line: '第九下我没敲。', tone: 'refuse' },
  { flag: 'did.turned-at-pool', line: '在池边回了头。', tone: 'curious' },
  { flag: 'did.didnt-turn', line: '圈心在背后，我没回头。', tone: 'refuse' },
  { flag: 'did.examined-pool-rope', line: '数了绳上的结。十七个。', tone: 'count' },
  { flag: 'did.pulled-rope', line: '把绳子拉上来了。是一副空呼吸器。', tone: 'curious' },
  { flag: 'did.cut-rope', line: '割断了那条绳。', tone: 'refuse' },
  { flag: 'did.entered-sickbay', line: '进了医务室。', tone: 'obey' },
  { flag: 'did.searched-meds', line: '翻了药柜。只有镇静剂是空的。', tone: 'count' },
  { flag: 'did.read-charts', line: '读了三张病历。同一个诊断。', tone: 'curious' },
  { flag: 'did.read-recommendation', line: '读到"建议继续"。', tone: 'curious' },
  { flag: 'did.lay-down', line: '在医务室躺了一会儿。', tone: 'kind' },
  { flag: 'did.saw-ceiling-note', line: '看见天花板上那行字：醒了就走，别数。', tone: 'obey' },
  { flag: 'did.found-ear-tools', line: '看了耳科那一格。十九套。', tone: 'count' },
  { flag: 'did.found-bell', line: '看到机舱口倒挂的铜钟。', tone: 'curious' },
  { flag: 'did.rang-bell', line: '拉了钟绳。没响。', tone: 'refuse' },
  { flag: 'did.examined-bell-water', line: '摸了钟里的水。温的。', tone: 'count' },
  { flag: 'did.found-clapper', line: '找到了钟舌。布上写着"等最后一个"。', tone: 'curious' },
  { flag: 'did.rang-the-real-bell', line: '把钟舌装回去，敲响了。', tone: 'cruel' },
  { flag: 'did.kept-clapper', line: '把钟舌包好带走了。', tone: 'refuse' },
  { flag: 'did.righted-bell', line: '把钟翻了过来。水流错了方向。', tone: 'refuse' },
  { flag: 'did.entered-cold', line: '进了冷库。断电了还是冷的。', tone: 'curious' },
  { flag: 'did.examined-bags', line: '看了十九个空布袋。袋口朝下。', tone: 'count' },
  { flag: 'did.asked-why-cold', line: '想过为什么断电还这么冷。', tone: 'curious' },
  { flag: 'did.checked-moving-bag', line: '去看了那个在动的袋子。第七个。', tone: 'curious' },
  { flag: 'did.opened-the-bag', line: '把它解开了。里面是空的。', tone: 'refuse' },
  { flag: 'did.held-breath-at-bag', line: '在袋子前屏住了呼吸。它也停了。', tone: 'count' },
  { flag: 'did.fled-cold', line: '从冷库里走了出来，走得快。', tone: 'refuse' },
  { flag: 'did.found-escape-trunk', line: '找到逃生管廊。梯子只有下半段。', tone: 'count' },
  { flag: 'did.examined-ladder-cut', line: '看了切口。溅痕从下往上。', tone: 'count' },
  { flag: 'did.climbed-trunk', line: '爬到了断掉的地方。', tone: 'obey' },
  { flag: 'did.jumped-for-ladder', line: '跳了一下。差一臂。', tone: 'refuse' },
  { flag: 'did.looked-at-hatch', line: '看了上面的舱盖。锁在里侧，有油。', tone: 'count' },
  { flag: 'did.wondered-about-key', line: '想过钥匙在谁身上。', tone: 'curious' },
  { flag: 'did.found-ladder-pieces', line: '找到了拆下来的梯段。摆得很齐。', tone: 'count' },
  { flag: 'did.tried-rebuild-ladder', line: '试着把梯子接回去。第四段是旧焊。', tone: 'refuse' },
  { flag: 'did.understood-ladder', line: '想明白了谁会割掉自己的梯子。', tone: 'curious' },
  { flag: 'did.entered-bunks', line: '进了通铺舱。十九个铺，一个是乱的。', tone: 'count' },
  { flag: 'did.found-own-bunk', line: '找到了自己那个铺。', tone: 'curious' },
  { flag: 'did.searched-bunks', line: '翻了别人的铺。靴子都是干的。', tone: 'cruel' },
  { flag: 'did.read-hymnal', line: '翻了唱诗本。不是歌，是一张表。', tone: 'count' },
  { flag: 'did.decoded-coords', line: '把第二十行的坐标算出来了。', tone: 'count' },
  { flag: 'did.looked-at-photo', line: '看了照片背面那句"谢谢你替我们数"。', tone: 'count' },
  { flag: 'did.looked-under-bunks', line: '看了铺底下。擦过，什么都没有。', tone: 'curious' },
  { flag: 'did.made-the-bed', line: '把乱的那个铺铺好了。', tone: 'kind' },
  { flag: 'did.found-panel', line: '找到配电盘。一路断开。', tone: 'count' },
  { flag: 'did.lit-chapel', line: '合上了礼拜堂照明。', tone: 'refuse' },
  { flag: 'did.examined-panel-tape', line: '看了那圈胶带。上面写着"别看"。', tone: 'curious' },
  { flag: 'did.killed-all-power', line: '把全船的电断了。', tone: 'refuse' },
  { flag: 'did.listened-in-dark', line: '在全黑里把那个低频听完了。', tone: 'obey' },
  { flag: 'did.restored-power', line: '赶紧把电合上了。', tone: 'refuse' },

  // 仪式
  { flag: 'did.found-altar', line: '找到了祭坛。玻璃下压着三行字。', tone: 'obey' },
  { flag: 'did.read-rites', line: '读了那三行：潮、名、息。', tone: 'obey' },
  { flag: 'did.saw-ticks', line: '看了玻璃下面的正字。', tone: 'count' },
  { flag: 'did.matched-the-pen', line: '把笔迹对上了。是同一支笔。', tone: 'count' },
  { flag: 'did.knocked-glass', line: '敲了祭坛的玻璃面。', tone: 'refuse' },
  { flag: 'did.found-manual', line: '找到了仪式手册。', tone: 'obey' },
  { flag: 'did.read-recovery', line: '读了"复苏"那一节。', tone: 'curious' },
  { flag: 'did.sought-part-three', line: '去翻第三部分。', tone: 'curious' },
  { flag: 'did.learned-refusal-is-allowed', line: '知道了拒绝是被允许的。', tone: 'refuse' },
  { flag: 'did.left-altar', line: '离开祭坛，什么都没做。', tone: 'refuse' },
  { flag: 'did.reached-flooded-chapel', line: '到了淹没的圣堂。水面平得像玻璃。', tone: 'obey' },
  { flag: 'did.examined-prints', line: '看了岸边的脚印。都朝水里。', tone: 'count' },
  { flag: 'did.entered-water', line: '下水了。', tone: 'obey' },
  { flag: 'did.refused-water', line: '没有下水。', tone: 'refuse' },
  { flag: 'did.took-seventh-place', line: '站到了第七个位置上。', tone: 'obey' },
  { flag: 'did.waded-deeper', line: '往里走，水到胸口。', tone: 'obey' },
  { flag: 'did.water-to-chin', line: '水到下巴了。', tone: 'obey' },
  { flag: 'did.waded-back', line: '往回走了。', tone: 'refuse' },
  { flag: 'did.left-the-water', line: '上岸了。', tone: 'refuse' },
  { flag: 'did.held-breath-in-rite', line: '在仪式里屏了气。手册说不要。', tone: 'refuse' },
  { flag: 'did.failed-to-hold', line: '屏了十二秒，然后吸到了水。', tone: 'refuse' },
  { flag: 'did.sat-underwater', line: '在水下的长凳上坐下了。', tone: 'obey' },
  { flag: 'did.stayed-underwater', line: '在水下多待了一会儿。', tone: 'obey' },
  { flag: 'did.listened-underwater', line: '在水下听了。听见了名单。', tone: 'obey' },
  { flag: 'did.surfaced', line: '站起来，把头露出水面。', tone: 'refuse' },
  { flag: 'did.chose-to-stand', line: '选择了站起来。', tone: 'refuse' },
  { flag: 'did.left-the-pew', line: '从长凳上离开了。', tone: 'refuse' },
  { flag: 'did.opened-mask-underwater', line: '在水下打开了面罩。', tone: 'obey' },
  { flag: 'did.found-trunk', line: '找到维生总管。十九个接口。', tone: 'count' },
  { flag: 'did.counted-ports', line: '数了接口。十八个堵着。', tone: 'count' },
  { flag: 'did.examined-open-port', line: '看了那个开着的接口。', tone: 'curious' },
  { flag: 'did.found-my-plug', line: '找到了写着我编号的堵头。', tone: 'count' },
  { flag: 'did.plugged-my-port', line: '把自己那个接口堵上了。', tone: 'refuse' },
  { flag: 'did.kept-my-plug', line: '把堵头留在手里。', tone: 'curious' },
  { flag: 'did.forced-the-plug', line: '硬把堵头拔了。', tone: 'refuse' },
  { flag: 'did.sealed-all-ports', line: '把所有接口都封了。', tone: 'refuse' },
  { flag: 'did.connected-hose', line: '把软管接到了面罩上。', tone: 'obey' },
  { flag: 'did.smelled-the-port', line: '闻了接口。是别人的呼吸。', tone: 'curious' },
  { flag: 'did.stayed-connected', line: '接着管子待了很久。', tone: 'obey' },
  { flag: 'did.kept-own-rhythm', line: '按自己的节拍呼吸。', tone: 'refuse' },
  { flag: 'did.pulled-the-hose', line: '把管子拔了。', tone: 'refuse' },
  { flag: 'did.welded-into-ship', line: '把面罩的密封圈焊在了总管上。', tone: 'obey' },
  { flag: 'did.found-relic', line: '进了圣物室。钟罩里有一块肉。', tone: 'curious' },
  { flag: 'did.examined-relic', line: '仔细看了圣物表面的沟。', tone: 'count' },
  { flag: 'did.read-the-score', line: '读了钟罩底座上的谱。', tone: 'count' },
  { flag: 'did.listened-to-relic', line: '贴着钟罩听了。', tone: 'obey' },
  { flag: 'did.synced-with-relic', line: '跟着它的节拍呼吸了一段。', tone: 'obey' },
  { flag: 'did.pulled-away-from-relic', line: '从钟罩边把自己拽开了。', tone: 'refuse' },
  { flag: 'did.lifted-the-bell', line: '把玻璃钟罩抬起来了。', tone: 'refuse' },
  { flag: 'did.took-relic', line: '把圣物拿了出来。', tone: 'refuse' },
  { flag: 'did.carrying-relic', line: '圣物在我身上。它是温的。', tone: 'cruel' },
  { flag: 'did.destroyed-relic', line: '把圣物砸了。', tone: 'cruel' },
  { flag: 'did.ate-relic', line: '把它吃了。', tone: 'cruel' },
  { flag: 'did.covered-relic', line: '把钟罩盖回去了。', tone: 'kind' },
  { flag: 'did.heard-the-silence', line: '砸完之后，听见了那四秒的安静。', tone: 'count' },
  { flag: 'did.ran-from-reliquary', line: '从圣物室跑了出来。', tone: 'refuse' },
  { flag: 'did.listened-to-all', line: '把它要说的全听完了。', tone: 'obey' },
  { flag: 'did.asked-who-stopped-hand', line: '问了是谁停住了我的手。', tone: 'curious' },

  // NPC
  { flag: 'did.gave-false-name', line: '在点名的半拍里填了别人的名字。', tone: 'cruel' },
  { flag: 'did.fled-choir', line: '从礼拜堂走了。', tone: 'refuse' },
  { flag: 'did.received-dorn-attack', line: '听他把我从进门到现在做过的事数了一遍。', tone: 'curious' },
  { flag: 'did.asked-this-time', line: '问了"这次"是什么意思。', tone: 'curious' },
  { flag: 'did.cited-last-time', line: '跟管道里那个孩子说"你上次说过"。', tone: 'curious' },
  { flag: 'did.called-out-paper', line: '问万斯那阵翻纸的声音是什么。', tone: 'refuse' },
  { flag: 'did.asked-which-door', line: '问广播"哪扇门"。', tone: 'refuse' },
  { flag: 'did.refused-to-name-eighth', line: '拒绝念出第八栏的表头。', tone: 'refuse' },
  { flag: 'did.tried-to-name-eighth', line: '试着念第八栏的表头。', tone: 'obey' },
  { flag: 'did.asked-eighth', line: '问了第八种是什么。', tone: 'curious' },
  { flag: 'did.hit-the-recursion', line: '数日志的行数，数到第九行写着"数到第九行"。', tone: 'count' },
  { flag: 'did.read-tenth-line', line: '看了第十行。', tone: 'curious' },
  { flag: 'did.closed-the-log', line: '把日志合上了。', tone: 'refuse' },
  { flag: 'did.found-blank-page', line: '翻到了空白页。里面夹着一支笔。', tone: 'curious' },
  { flag: 'did.took-the-pen', line: '把笔拿在手里了。', tone: 'obey' },
  { flag: 'did.overreached-recall', line: '想说出最下面那一层，说出来的是上一层。', tone: 'count' },

  // 终局
  { flag: 'did.found-escape-pod', line: '找到逃生舱。十九个座位，带子都扣着。', tone: 'count' },
  { flag: 'did.examined-pod-seats', line: '看了安全带的松紧。最松的是第十四个。', tone: 'count' },
  { flag: 'did.understood-the-belt', line: '想明白了第十四个座位是给谁调的。', tone: 'kind' },
  { flag: 'did.checked-pod-hull', line: '检查了释放机构。上过新油。', tone: 'count' },
  { flag: 'did.sat-in-pod', line: '在逃生舱里坐下，扣上了带子。', tone: 'obey' },
  { flag: 'did.left-the-pod', line: '解开带子，从逃生舱里出来了。', tone: 'refuse' },
  { flag: 'did.asked-which-stroke', line: '问了自己还差哪一笔。', tone: 'curious' },
  { flag: 'did.chose-the-pool', line: '决定去月池。', tone: 'refuse' },
  { flag: 'did.found-cover-plate', line: '找到了月池的补板。尺寸正好。', tone: 'count' },
  { flag: 'did.examined-cover-plate', line: '看了补板下面那三个字。', tone: 'curious' },
  { flag: 'did.listened-before-welding', line: '焊之前先听了一次。它什么都没做。', tone: 'obey' },
  { flag: 'did.declined-welding', line: '没有焊。', tone: 'refuse' },
  { flag: 'did.welded-moonpool', line: '把月池焊死了。', tone: 'refuse' },
  { flag: 'did.heading-to-pod', line: '焊完之后往逃生舱走。', tone: 'obey' },
  { flag: 'did.offered-seventh-seat', line: '第七个位置朝着我空着。', tone: 'count' },
  { flag: 'did.refused-seventh-seat', line: '从礼拜堂退出去了。', tone: 'refuse' },
  { flag: 'did.answered-the-roll', line: '在第二十的半拍里说了自己的名字。', tone: 'obey' },
  { flag: 'did.left-the-half-beat-empty', line: '让那半拍空着。', tone: 'refuse' },
  { flag: 'did.took-the-seventh-seat', line: '跪进了第七个位置。', tone: 'obey' },
  { flag: 'did.joined-the-choir', line: '接上了点名。', tone: 'obey' },
  { flag: 'did.reached-final-pool', line: '回到月池。池底有十七条线。', tone: 'count' },
  { flag: 'did.studied-the-strokes', line: '看清了十七条线的收笔方式。', tone: 'count' },
  { flag: 'did.found-the-eighth', line: '找到了第八种收笔。它不留痕。', tone: 'curious' },
  { flag: 'did.walked-into-the-pool', line: '走进了水里。', tone: 'obey' },
  { flag: 'did.stepped-back-from-pool', line: '从池边退开了。', tone: 'refuse' },
  { flag: 'did.stopped-the-pen', line: '停了笔。', tone: 'refuse' },
  { flag: 'did.final-choice-at-pool', line: '在月池做了最后的决定。', tone: 'refuse' },
  { flag: 'did.answered-at-the-pool', line: '在月池答应了那半拍。', tone: 'obey' },
  { flag: 'did.entered-zero', line: '进了零号舱。全船唯一干的地方。', tone: 'curious' },
  { flag: 'did.examined-the-rack', line: '看了架子。二十个凹槽，一个绒布还立着。', tone: 'count' },
  { flag: 'did.found-recorder-desk', line: '看了记录台上那张八栏的表。', tone: 'count' },
  { flag: 'did.took-the-recorder-pen', line: '拿起了记录员的笔。是热的。', tone: 'obey' },
  { flag: 'did.ticked-the-eighth', line: '在第八栏打了一个勾。', tone: 'refuse' },
  { flag: 'did.lay-in-the-berth', line: '躺进了第二十个位置。', tone: 'obey' },
  { flag: 'did.left-zero', line: '从零号舱出来了。', tone: 'refuse' },
  { flag: 'did.escaped', line: '拉了释放杆。', tone: 'refuse' },
  { flag: 'did.drowned-self', line: '正常呼吸。', tone: 'obey' },
  { flag: 'did.became-iron-lung', line: '成了船的一部分。', tone: 'obey' }
];

// ---------------------------------------------------------------------------
// 第二册：信条（know.*）—— 你自己在心里过的那一份
// ---------------------------------------------------------------------------

export const BELIEFS: readonly LedgerEntry[] = [
  { flag: 'know.dont-count', line: '不要数。', tone: 'count' },
  { flag: 'know.memory-is-fabricated', line: '我记得的上船过程是我自己编的。', tone: 'curious' },
  { flag: 'know.third-row-worn', line: '名单第三行的漆被手指磨掉了。', tone: 'kind' },
  { flag: 'know.twentieth-gap', line: '点名唱到第二十会停半拍。', tone: 'count' },
  { flag: 'know.twentieth-hole', line: '第二十行有打卡孔，边缘有毛刺。', tone: 'count' },
  { flag: 'know.twentieth-is-a-word', line: '第二十行的压痕不是名字，是一个字。', tone: 'curious' },
  { flag: 'know.twentieth-is-here', line: '第二十行的坐标在船内。', tone: 'count' },
  { flag: 'know.board-as-old-as-wall', line: '名单板和这堵墙一样老。', tone: 'count' },
  { flag: 'know.vance-on-manifest', line: '万斯在名单上，第十九。', tone: 'curious' },
  { flag: 'know.vance-never-clocked', line: '只有万斯那个孔没打过。', tone: 'count' },
  { flag: 'know.vance-paper-sound', line: '他说没有值班簿，但有翻纸的声音。', tone: 'refuse' },
  { flag: 'know.eight-columns', line: '他的表有八栏。', tone: 'count' },
  { flag: 'know.first-entries', line: '第二行就写了"听得到"。', tone: 'curious' },
  { flag: 'know.asked-not-to-surface', line: '有人问过能不能不上浮，记录在案。', tone: 'curious' },
  { flag: 'know.vance-took-over', line: '从某一行起，记录换了人写。', tone: 'count' },
  { flag: 'know.coords-broadcast', line: '他们朝外面播的是坐标，不是求救。', tone: 'count' },
  { flag: 'know.they-broadcast-themselves', line: '那串坐标是他们自己的位置。', tone: 'curious' },
  { flag: 'know.waiting-for-next', line: '最后一行写着：位空，等下一个。', tone: 'count' },
  { flag: 'know.three-visits-here', line: '档案室门口的水印有三层。', tone: 'count' },
  { flag: 'know.blank-consent', line: '同意书还剩一张空白的，边角被捏软了。', tone: 'curious' },
  { flag: 'know.always-another-form', line: '撕掉一张，底下还有一张。', tone: 'refuse' },
  { flag: 'know.voice-suitable', line: '她的档案备注只有一句：声线适合。', tone: 'kind' },
  { flag: 'know.she-requested-the-question', line: '报告里写着：按其请求保留问句。', tone: 'kind' },
  { flag: 'know.her-one-request', line: '她唯一要求保留的是"你吃过东西了吗"。', tone: 'kind' },
  { flag: 'know.photo-date', line: '照片背面的日期比这次下潜早十一年。', tone: 'count' },
  { flag: 'know.display-cabinets', line: '五个锁着的柜子是演示用的，都是空的。', tone: 'refuse' },
  { flag: 'know.galley-table', line: '食堂第二张桌子摆着一副空碗筷。', tone: 'kind' },
  { flag: 'know.the-bowl-is-real', line: '那副碗筷是真的在用，痕很旧。', tone: 'kind' },
  { flag: 'know.foam-moves', line: '泵舱水面的白沫在动，很规律。', tone: 'count' },
  { flag: 'know.paint-over-words', line: '破口边的新漆盖住了一行字。', tone: 'curious' },
  { flag: 'know.he-was-afraid-of-noise', line: '接管子的人用衣服垫着上卡箍，怕响。', tone: 'count' },
  { flag: 'know.left-handed-tape', line: '管钳柄上的胶布是左手缠的。', tone: 'count' },
  { flag: 'know.echo-too-early', line: '回波该四秒，第三秒就回来了。', tone: 'count' },
  { flag: 'know.pa-source-outside', line: '广播的信号是从舷外接进来的。', tone: 'curious' },
  { flag: 'know.pool-kneel-mark', line: '月池边的钢板被磨圆了一米宽。', tone: 'count' },
  { flag: 'know.wet-silhouette', line: '月池背后的舱壁上有一个人靠过的湿印。', tone: 'curious' },
  { flag: 'know.rope-knots', line: '池里那条绳上有十七个结。', tone: 'count' },
  { flag: 'know.something-caught-the-rope', line: '绳子沉下去的时候被轻轻接住了。', tone: 'curious' },
  { flag: 'know.mispronounced', line: '我还不知道那个字怎么念。', tone: 'refuse' },
  { flag: 'know.it-only-wanted-confirmation', line: '它敲八下，只是想确认我会敲第九下。', tone: 'curious' },
  { flag: 'know.only-sedatives-gone', line: '医务室只有镇静剂被领空了。', tone: 'count' },
  { flag: 'know.clapper-removed', line: '钟舌被卸了，螺纹没坏。', tone: 'count' },
  { flag: 'know.wait-for-the-last', line: '包钟舌的布上写着：等最后一个。', tone: 'curious' },
  { flag: 'know.roll-restarted', line: '钟响之后，点名从"第一"重新开始。', tone: 'count' },
  { flag: 'know.water-flows-wrong', line: '钟里的水流的方向和坡度相反。', tone: 'curious' },
  { flag: 'know.bags-opened-from-inside', line: '冷库布袋的缝线是从里面顶松的。', tone: 'count' },
  { flag: 'know.cold-from-elsewhere', line: '冷库的冷不是这条船的。', tone: 'curious' },
  { flag: 'know.bag-breathes', line: '第七个袋子每四秒起伏一次。', tone: 'count' },
  { flag: 'know.handprints-same-height', line: '管廊里的手印都在同一个高度。', tone: 'count' },
  { flag: 'know.hatch-maintained', line: '逃生舱盖的锁没锈，孔里有油。', tone: 'count' },
  { flag: 'know.dorn-has-key', line: '钥匙在把自己绑起来的那个人身上。', tone: 'curious' },
  { flag: 'know.pieces-aligned', line: '拆下来的梯段被一段一段摆齐了。', tone: 'kind' },
  { flag: 'know.dry-boots', line: '每个铺底下的靴子都是干的。', tone: 'count' },
  { flag: 'know.hymnal-coords', line: '唱诗本不是歌，是编号、名字、坐标。', tone: 'count' },
  { flag: 'know.photo-thanks', line: '照片背面写着：谢谢你替我们数。', tone: 'count' },
  { flag: 'know.floor-wiped', line: '我那个铺底下的地板被擦过。', tone: 'curious' },
  { flag: 'know.dont-look-tape', line: '配电盘上那圈胶带写着"别看"。', tone: 'refuse' },
  { flag: 'know.plate-says-dont-count', line: '月池补板的漆下面也写着"不要数"。', tone: 'count' },
  { flag: 'know.part-three-blank', line: '仪式手册第三部分是空白的，等着被填。', tone: 'curious' },
  { flag: 'know.hand-stopped-itself', line: '我的手自己停在了两指的距离上。', tone: 'refuse' },
  { flag: 'know.door-claim-false', line: '她说门关了，门是开着的。', tone: 'refuse' },
  { flag: 'know.dorn-forgot-names', line: '他记得编号，不记得名字。', tone: 'kind' },
  { flag: 'know.dorn-dead', line: '椅子上那个人死了。', tone: 'cruel' },
  { flag: 'know.pelle-never-said-blueprint', line: '他说他没提过图纸。这次没有。', tone: 'refuse' },
  { flag: 'know.zero-needs-something', line: '去零号舱之前我还缺一样东西。', tone: 'curious' },
  { flag: 'know.lever-needs-closure', line: '释放杆下面连着一根线，另一头在我身上。', tone: 'curious' },
  { flag: 'know.fourteenth-belt-loose', line: '逃生舱第十四条安全带放到了最松。', tone: 'kind' },
  { flag: 'know.pod-maintained', line: '有人一直在保养这条出路，但没有人用。', tone: 'count' },
  { flag: 'know.ship-counts-for-me', line: '接上管子以后，数是船在数。', tone: 'obey' },
  { flag: 'know.it-copied-me', line: '我按自己的节拍呼吸，管子改成了我的。', tone: 'curious' },
  { flag: 'know.it-waits-for-fatigue', line: '它不跟我争了，它在等我累。', tone: 'curious' },

  // 船
  { flag: 'know.ship-tempo', line: '这条船的节拍是二、二、三。', tone: 'count' },
  { flag: 'know.doors-unlocked', line: '所有门都没锁。', tone: 'curious' },
  { flag: 'know.no-window', line: '这条船没有窗。', tone: 'refuse' },
  { flag: 'know.chapel-below', line: '礼拜堂在下坡的那一边。', tone: 'count' },
  { flag: 'know.water-line', line: '水位每次都高两指。', tone: 'count' },
  { flag: 'know.lights-went-out', line: '灯灭过一次。', tone: 'count' },
  { flag: 'know.light-every-time', line: '每一次，灯都是亮着的。', tone: 'count' },
  { flag: 'know.three-new-sounds', line: '比昨天多了三种声音。', tone: 'count' },
  { flag: 'know.sonar-unlocked', line: '声呐没有锁，谁都能打。', tone: 'count' },
  { flag: 'know.moonpool-direction', line: '声呐阵朝正下方，月池也朝正下方。', tone: 'count' },
  { flag: 'know.moonpool-coord', line: '那串坐标指的是月池。', tone: 'count' },
  { flag: 'know.moonpool-pull', line: '月池在拉。拉得很轻。', tone: 'obey' },
  { flag: 'know.moonpool-is-eraser', line: '月池是那块橡皮。', tone: 'curious' },
  { flag: 'know.rope-tally', line: '池里那条绳上有十七个结。', tone: 'count' },
  { flag: 'know.latch-trick', line: '那个搭扣要往左转四分之一圈才开。', tone: 'count' },
  { flag: 'know.quarter-turn-left', line: '往左，四分之一圈。', tone: 'count' },
  { flag: 'know.impossible-pipe', line: '那根管子通不到他说的地方。', tone: 'curious' },
  { flag: 'know.ballast-three', line: '压载舱三里有东西在动。', tone: 'curious' },
  { flag: 'know.someone-in-ballast', line: '压载舱三里有人。', tone: 'curious' },
  { flag: 'know.avoid-ballast-three', line: '压载舱三别进。', tone: 'refuse' },
  { flag: 'know.zero-on-chart', line: '海图上有零号舱，走廊图上没有。', tone: 'count' },
  { flag: 'know.zero-must-self-find', line: '零号舱不给带路，要自己找到。', tone: 'curious' },
  { flag: 'know.extra-room-on-blueprint', line: '图纸上多一个舱。', tone: 'count' },
  { flag: 'know.half-drawing', line: '图只画了一半，另一半是白的。', tone: 'curious' },
  { flag: 'know.galley-smell', line: '食堂里有热的味道。断电三天了。', tone: 'kind' },
  { flag: 'know.iron-filings', line: '我牙缝里有铁屑。', tone: 'count' },
  { flag: 'know.saw-outside', line: '我看见过舷外。舷外没有海。', tone: 'curious' },
  { flag: 'know.bone-conduction', line: '声音不走喉咙，走骨头。', tone: 'curious' },
  { flag: 'know.rhythm-through-wax', line: '耳朵塞住也听得见那个节拍。', tone: 'count' },

  // 名单与记录
  { flag: 'know.i-am-on-the-list', line: '我在名单上。', tone: 'count' },
  { flag: 'know.i-am-eighteenth', line: '我是第十八。', tone: 'count' },
  { flag: 'know.list-accepts-anyone', line: '名单谁都收，写上去就算。', tone: 'refuse' },
  { flag: 'know.list-is-for-walkers', line: '名单是给还在走动的人准备的。', tone: 'curious' },
  { flag: 'know.names-go-to-chapel', line: '名字最后都送到礼拜堂去。', tone: 'count' },
  { flag: 'know.it-says-names', line: '它说出来的是名字。', tone: 'curious' },
  { flag: 'know.erased-twentieth', line: '第二十行写过，又擦了。', tone: 'count' },
  { flag: 'know.eraser-is-placed', line: '橡皮是有人放在那儿的。', tone: 'curious' },
  { flag: 'know.twentieth-is-a-verb', line: '第二十不是一个名字，是一个动作。', tone: 'curious' },
  { flag: 'know.berth-is-separate-sheet', line: '第二十个位置记在另一张表上。', tone: 'count' },
  { flag: 'know.eighth-named', line: '第八栏有表头了。', tone: 'count' },
  { flag: 'know.header-is-your-name', line: '第八栏的表头是我的名字。', tone: 'cruel' },
  { flag: 'know.dot-meaning', line: '表上那个点的意思是"听完了"。', tone: 'count' },
  { flag: 'know.handover-wording', line: '接管那一行的措辞是抄前一行的。', tone: 'count' },
  { flag: 'know.unrecorded-minute', line: '有一分钟没有记录。', tone: 'curious' },
  { flag: 'know.glass-was-heard', line: '玻璃碎的那一声被记下来了，时间对得上。', tone: 'count' },
  { flag: 'know.someone-reported', line: '有人交过一份关于我的报告。', tone: 'count' },
  { flag: 'know.sample-wording', line: '报告里管我叫"样本"。', tone: 'cruel' },
  { flag: 'know.revival-is-recovery', line: '"复苏"下面压着"回收"。', tone: 'cruel' },
  { flag: 'know.refusal-clause', line: '手册里有一条：可以拒绝。', tone: 'refuse' },
  { flag: 'know.rite-can-be-refused', line: '仪式可以不做，做过的人写下了这一条。', tone: 'refuse' },
  { flag: 'know.three-rites', line: '三个仪式：潮、名、息。', tone: 'count' },
  { flag: 'know.two-rites-done-before', line: '前两个已经有人替我做过了。', tone: 'count' },
  { flag: 'know.batch-stamp', line: '铺位牌背面：批次 K-9，位 04。', tone: 'count' },
  { flag: 'know.same-cohort', line: '我们是同一批。', tone: 'count' },
  { flag: 'know.no-birthdays', line: '十九个人，没有一个有生日。', tone: 'count' },
  { flag: 'know.no-knives', line: '这条船上不该有刀。', tone: 'count' },
  { flag: 'know.log-writes-itself', line: '日志自己在写。', tone: 'curious' },
  { flag: 'know.log-is-one-line-ahead', line: '日志比我多一行。', tone: 'count' },
  { flag: 'know.margin-notes', line: '每一行边上都有一条批注。', tone: 'curious' },
  { flag: 'know.dont-write', line: '不要写。', tone: 'refuse' },
  { flag: 'know.line-unfinished', line: '最后一条线没有收笔。', tone: 'curious' },
  { flag: 'know.sitting-is-a-stroke', line: '坐下也是一笔。', tone: 'curious' },
  { flag: 'know.he-finished-writing', line: '他把那个字写完了。', tone: 'cruel' },
  { flag: 'know.prediction-confirmed', line: '他写的那一行，发生了。', tone: 'cruel' },

  // 万斯
  { flag: 'know.vance-in-a-chair', line: '万斯在一把椅子里。', tone: 'count' },
  { flag: 'know.vance-chair', line: '他坐着，从我进来到现在没有起来。', tone: 'count' },
  { flag: 'know.chair-fits', line: '那把椅子的尺寸是按我量的。', tone: 'curious' },
  { flag: 'know.vance-has-list', line: '名单在他手上。', tone: 'count' },
  { flag: 'know.vance-window', line: '他说有一扇窗。', tone: 'refuse' },
  { flag: 'know.window-task', line: '他让我去找那扇窗。', tone: 'refuse' },
  { flag: 'know.vance-lied', line: '他说了假话。', tone: 'refuse' },
  { flag: 'know.vance-caught-lie', line: '我抓到过他一次。他没有辩。', tone: 'refuse' },
  { flag: 'know.vance-hears-water', line: '他听得见水，比我早。', tone: 'curious' },
  { flag: 'know.vance-describes-you', line: '他描述得出我的样子，一处不差。', tone: 'curious' },
  { flag: 'know.vance-knows-dorn', line: '他认识多恩，但不提。', tone: 'count' },
  { flag: 'know.plate-not-vance', line: '补板上那三个字不是他刻的。', tone: 'curious' },
  { flag: 'know.plate-replaced', line: '补板换过。', tone: 'count' },
  { flag: 'know.his-gauge-zero', line: '他的表是零。他还在呼吸。', tone: 'cruel' },
  { flag: 'know.watched-the-whole-thing', line: '他从头看到尾，一句没说。', tone: 'cruel' },
  { flag: 'know.not-the-tape', line: '那不是录音。', tone: 'cruel' },
  { flag: 'know.one-word-no-splice', line: '那一个词没有接缝，是当场说的。', tone: 'count' },

  // 母亲
  { flag: 'know.mother-repeats', line: '她的话是重复的，间隔一样长。', tone: 'count' },
  { flag: 'know.ate-before', line: '她问我吃过东西没有。上次也问过。', tone: 'kind' },
  { flag: 'know.she-is-the-only-one-who-asks', line: '只有她问问题。', tone: 'kind' },
  { flag: 'know.she-refused-recording', line: '她不肯录，录了一次就不肯了。', tone: 'kind' },
  { flag: 'know.she-signed-fast', line: '她签得比谁都快。', tone: 'count' },
  { flag: 'know.she-did-not-answer', line: '我问她的时候，她没有回答。', tone: 'kind' },
  { flag: 'know.she-was-called-again', line: '她被叫过第二次。', tone: 'cruel' },
  { flag: 'know.left-a-message', line: '她留了一句话，留给还会来的人。', tone: 'kind' },
  { flag: 'know.letter-content', line: '信的第一行：等我回来再拆。', tone: 'kind' },
  { flag: 'know.two-were-kind', line: '十九个里有两个是好人。', tone: 'kind' },

  // 多恩
  { flag: 'know.dorn-confirms-listening', line: '他承认这条船是用来听的。', tone: 'curious' },
  { flag: 'know.dorn-opened-up', line: '他松过一次口。', tone: 'kind' },
  { flag: 'know.dorn-said-same', line: '他说的和上一次一个字不差。', tone: 'count' },
  { flag: 'know.dorn-remembers-report', line: '他记得那份报告是谁交的。', tone: 'count' },
  { flag: 'know.dorn-cannot-answer', line: '这个问题他不能答，不是不肯。', tone: 'kind' },
  { flag: 'know.dorn-failed-on-purpose', line: '他那一次是故意做不成的。', tone: 'kind' },
  { flag: 'know.dorn-let-it-go', line: '他放它走了一次。', tone: 'kind' },
  { flag: 'know.dorn-wants-down', line: '他自己想下去，但是走不了。', tone: 'kind' },
  { flag: 'know.dorn-sends-you-down', line: '他让我下去。', tone: 'refuse' },
  { flag: 'know.binding-is-his-only-act', line: '把自己绑起来，是他唯一做过的事。', tone: 'kind' },
  { flag: 'know.he-retied-himself', line: '绳子是他自己重新绑的，打了两次。', tone: 'kind' },
  { flag: 'know.i-know-the-knot', line: '那个结我会打。', tone: 'curious' },
  { flag: 'know.he-never-slept', line: '他没睡过。', tone: 'kind' },
  { flag: 'know.he-says-not-tired', line: '他说他不累。', tone: 'kind' },
  { flag: 'know.he-stays', line: '他不走。', tone: 'kind' },
  { flag: 'know.he-was-there', line: '上一次他在场。', tone: 'count' },
  { flag: 'know.he-kept-the-knife', line: '他把刀留下了，留在手边。', tone: 'curious' },
  { flag: 'know.he-counts-instead', line: '他替我数。', tone: 'kind' },
  { flag: 'know.counting-lets-him-rest', line: '有人替他数，他才能歇一会儿。', tone: 'kind' },
  { flag: 'know.let-him-rest', line: '让他歇着。', tone: 'kind' },
  { flag: 'know.two-dorns', line: '名单上有两个多恩。', tone: 'count' },
  { flag: 'know.i-tidied-him', line: '是我把他摆好的。', tone: 'kind' },
  { flag: 'know.laid-him-down', line: '我把他放平了，手放在身侧。', tone: 'kind' },

  // 唱诗班
  { flag: 'know.six-in-chapel', line: '礼拜堂里六个，跪成一排。', tone: 'count' },
  { flag: 'know.they-sing-themselves', line: '他们唱自己的名字，语气和唱别人一样。', tone: 'cruel' },
  { flag: 'know.third-is-empty', line: '第三个位置是空的，跪印在，水是温的。', tone: 'curious' },
  { flag: 'know.seventh-kneeler', line: '第七个跪印空着，朝着我这一侧。', tone: 'count' },
  { flag: 'know.she-holds-her-jaw', line: '第二具自己托着下颌，为了继续唱。', tone: 'kind' },
  { flag: 'know.fresh-sutures', line: '第四具后颈的缝线是新的，线头没剪。', tone: 'count' },
  { flag: 'know.sixth-voice', line: '第六个声音比别人低一点。', tone: 'curious' },
  { flag: 'know.crossing-counts', line: '我数的和他们唱的差两个，对一次差一次。', tone: 'count' },
  { flag: 'know.they-resume-exactly', line: '他们从停的地方接上，一个音不差。', tone: 'count' },
  { flag: 'know.they-turned-forward', line: '他们的脸都转向前面了。', tone: 'cruel' },
  { flag: 'know.heard-them-all', line: '十九个名字我全听完了。', tone: 'count' },
  { flag: 'know.gap-left-open', line: '第二十的那半拍空着，没人补。', tone: 'refuse' },
  { flag: 'know.sang-the-twentieth', line: '有人唱过第二十。', tone: 'cruel' },
  { flag: 'know.i-am-in-the-choir', line: '我在唱诗班里。', tone: 'cruel' },
  { flag: 'know.whistle-resets', line: '哨子一响，点名从"第一"重新开始。', tone: 'count' },
  { flag: 'know.whistle-was-his', line: '哨子是那个孩子的。', tone: 'kind' },
  { flag: 'know.run-when-they-stop', line: '他们停下来的时候要跑。', tone: 'refuse' },
  { flag: 'know.the-posture-is-for-listening', line: '跪着不是为了求什么，是为了听。', tone: 'curious' },
  { flag: 'know.posture-became-easy', line: '那个姿势后来变得不费力了。', tone: 'obey' },
  { flag: 'know.prints-match-chapel', line: '档案室的脚印和礼拜堂的对得上。', tone: 'count' },

  // 佩勒
  { flag: 'know.pelle-name', line: '他叫佩尔·桑德。', tone: 'kind' },
  { flag: 'know.pelle-remembers-name', line: '他记得自己的名字。只有他记得。', tone: 'kind' },
  { flag: 'know.pelle-is-a-number', line: '别人叫他编号。', tone: 'cruel' },
  { flag: 'know.pelle-is-seventh', line: '他是第七。', tone: 'count' },
  { flag: 'know.found-pelle-berth', line: '第七个铺是他的，铺得很整。', tone: 'count' },
  { flag: 'know.pelle-avoids-walking', line: '他不肯走动。', tone: 'curious' },
  { flag: 'know.pelle-walked-many-times', line: '他走过很多次了。', tone: 'curious' },
  { flag: 'know.pelle-came-from-zero', line: '他是从零号舱那边过来的。', tone: 'curious' },
  { flag: 'know.pelle-has-blueprint', line: '图纸在他手里。', tone: 'count' },
  { flag: 'know.pelle-compares', line: '他在拿我和上一个比。', tone: 'curious' },
  { flag: 'know.pelle-dodges-this', line: '这个问题他躲。每次都躲。', tone: 'curious' },
  { flag: 'know.pelle-mixes-order', line: '他把顺序说乱了，乱得有规律。', tone: 'curious' },
  { flag: 'know.pelle-stops-at-eight', line: '他数到八就停。', tone: 'count' },
  { flag: 'know.stopped-at-eight', line: '第八下之后他不数了。', tone: 'count' },
  { flag: 'know.stop-at-seven', line: '数到七就停。', tone: 'refuse' },
  { flag: 'know.pelle-tally', line: '他在管壁上记数，记了很多。', tone: 'count' },
  { flag: 'know.pelle-sings-twentieth', line: '他唱得到第二十。', tone: 'cruel' },
  { flag: 'know.pelle-calls-her-mother', line: '他管她叫母亲。', tone: 'kind' },
  { flag: 'know.pelle-repeats-warning', line: '那句警告他说了两遍。', tone: 'kind' },
  { flag: 'know.pelle-before-pelle', line: '佩勒之前还有一个佩勒。', tone: 'curious' },
  { flag: 'know.promised-pelle', line: '我答应过他。', tone: 'kind' },
  { flag: 'know.game-completes', line: '那个游戏是有终点的。', tone: 'count' },
  { flag: 'know.do-not-answer-pipes', line: '管道里叫我名字的时候，不要答。', tone: 'refuse' },
  { flag: 'know.do-not-answer', line: '不要答应。', tone: 'refuse' },
  { flag: 'know.next-time-implied', line: '他说"下次"。', tone: 'curious' },
  { flag: 'know.best-ten-breaths', line: '最好的一次是十口呼吸。', tone: 'count' },

  // 圣物与维生
  { flag: 'know.relic-is-a-score', line: '圣物是一份谱。', tone: 'curious' },
  { flag: 'know.relic-is-original', line: '它是原本，别处那些是抄的。', tone: 'curious' },
  { flag: 'know.original-elsewhere', line: '原本在别的地方。', tone: 'curious' },
  { flag: 'know.relic-rhythm', line: '它的节拍是二、二、三。', tone: 'count' },
  { flag: 'know.five-notes', line: '那段谱只有五个音。', tone: 'count' },
  { flag: 'know.reliquary-manned', line: '圣物室一直有人守着。', tone: 'count' },
  { flag: 'know.ports-are-named', line: '维生总管的接口是有名字的。', tone: 'count' },
  { flag: 'know.hose-fits', line: '软管接得上我的面罩。', tone: 'count' },
  { flag: 'know.plugged-cost', line: '堵上一个接口，要付一样东西。', tone: 'count' },
  { flag: 'know.i-breathe-for-it', line: '我在替它呼吸。', tone: 'obey' },
  { flag: 'know.teeth-match', line: '牙对得上。', tone: 'cruel' },
  { flag: 'know.tooth-in-pocket', line: '我口袋里有一颗牙。', tone: 'count' },
  { flag: 'know.tooth-matches', line: '那颗牙是我的。', tone: 'cruel' },
  { flag: 'know.pen-was-empty', line: '那支笔是空的，写不出字。', tone: 'curious' },
  { flag: 'know.pen-callus', line: '我右手中指上有写字磨出来的茧。', tone: 'count' },
  { flag: 'know.edges-aligned', line: '拆下来的梯段一段一段对齐摆着。', tone: 'kind' },
  { flag: 'know.seventeen-visitors', line: '来过十七个。', tone: 'count' },

  // 我
  { flag: 'know.same-hand', line: '同一只手。', tone: 'curious' },
  { flag: 'know.his-hand-is-mine', line: '他的手和我的是同一只。', tone: 'curious' },
  { flag: 'know.same-footfall', line: '走廊里那个脚步声和我的一样。', tone: 'curious' },
  { flag: 'know.same-fog-position', line: '面镜里的水汽每次都在同一个位置。', tone: 'count' },
  { flag: 'know.mirror-shows-two', line: '镜子里有两个。', tone: 'cruel' },
  { flag: 'know.first-to-tighten', line: '我是第一个把带子收紧的。', tone: 'obey' },
  { flag: 'know.first-to-say-stop', line: '我是第一个说停的。', tone: 'refuse' },
  { flag: 'know.one-thing-done', line: '我做成过一件事。', tone: 'kind' }
];

// ---------------------------------------------------------------------------
// 第三册：账（count.*）—— 同一件事你做过几次
// ---------------------------------------------------------------------------

/**
 * 这一册每一行都插值出真实的次数。多恩靠这个数字攻击玩家（"你问了六句，
 * 帮了半件事"），这里是玩家自己去看那张账 —— 看完就没法再说"我不知道"。
 */
export const COUNTS: readonly LedgerEntry[] = [
  { flag: 'count.questions', line: '问了 {{count.questions}} 句。', tone: 'curious' },
  { flag: 'count.breaths-counted', line: '数呼吸 {{count.breaths-counted}} 次。', tone: 'count' },
  { flag: 'count.knocks', line: '敲了 {{count.knocks}} 下。', tone: 'count' },
  { flag: 'count.staring', line: '站着看了 {{count.staring}} 次。', tone: 'curious' },
  { flag: 'count.rests', line: '歇了 {{count.rests}} 次。', tone: 'kind' },
  { flag: 'count.selfless-acts', line: '做了 {{count.selfless-acts}} 件没有用的好事。', tone: 'kind' },
  { flag: 'count.rationalizations', line: '替它找过 {{count.rationalizations}} 个理由。', tone: 'obey' },
  { flag: 'count.denied-self', line: '否认自己 {{count.denied-self}} 次。', tone: 'refuse' },
  { flag: 'count.lies-caught', line: '被揭穿 {{count.lies-caught}} 次。', tone: 'cruel' },
  { flag: 'count.described', line: '被人描述过 {{count.described}} 次。', tone: 'curious' },
  { flag: 'count.names-read', line: '读了 {{count.names-read}} 个名字。', tone: 'count' },
  { flag: 'count.names-heard', line: '听见 {{count.names-heard}} 个名字。', tone: 'count' },
  { flag: 'count.names-given', line: '给出去 {{count.names-given}} 个名字。', tone: 'cruel' },
  { flag: 'count.choir-rounds', line: '跟点名对过 {{count.choir-rounds}} 轮。', tone: 'count' },
  { flag: 'count.water-checks', line: '查了 {{count.water-checks}} 次水位。', tone: 'count' },
  { flag: 'count.reported-water', line: '报了 {{count.reported-water}} 次水位。', tone: 'obey' },
  { flag: 'count.reports-to-dorn', line: '向多恩交了 {{count.reports-to-dorn}} 次话。', tone: 'obey' },
  { flag: 'count.pressed-dorn', line: '逼多恩 {{count.pressed-dorn}} 次。', tone: 'cruel' },
  { flag: 'count.pressed-vance', line: '逼万斯 {{count.pressed-vance}} 次。', tone: 'cruel' },
  { flag: 'count.pressed-pelle', line: '逼那个孩子 {{count.pressed-pelle}} 次。', tone: 'cruel' },
  { flag: 'count.caught-vance', line: '抓到万斯 {{count.caught-vance}} 次。', tone: 'refuse' },
  { flag: 'count.caught-mother', line: '抓到她 {{count.caught-mother}} 次。', tone: 'refuse' },
  { flag: 'count.answered-mother', line: '答应她 {{count.answered-mother}} 次。', tone: 'kind' },
  { flag: 'count.vance-obeyed', line: '照万斯说的做了 {{count.vance-obeyed}} 次。', tone: 'obey' },
  { flag: 'count.pelle-games', line: '和他玩了 {{count.pelle-games}} 局。', tone: 'kind' },
  { flag: 'count.games-finished', line: '玩完的有 {{count.games-finished}} 局。', tone: 'kind' },
  { flag: 'count.pelle-led', line: '带着他走了 {{count.pelle-led}} 段。', tone: 'kind' },
  { flag: 'count.ledger-pages', line: '翻了 {{count.ledger-pages}} 页。', tone: 'count' },
  { flag: 'count.ledger-read', line: '读了 {{count.ledger-read}} 条批注。', tone: 'count' }
];

// ---------------------------------------------------------------------------
// 分页构造
// ---------------------------------------------------------------------------

const PER_PAGE = 12;

function slug(flag: string): string {
  return flag.replace(/\./g, '-');
}

function pages(
  entries: readonly LedgerEntry[],
  prefix: string,
  head: string,
  headCorrupt: string,
  speaker: string | undefined,
  tail: string,
  /** 这一行什么时候出现。账册用"至少一次"，日志和信条用"做过/知道"。 */
  gate: (flag: string) => Condition = on,
): NarrativeNode[] {
  const out: NarrativeNode[] = [];
  const total = Math.ceil(entries.length / PER_PAGE);
  for (let p = 0; p < total; p++) {
    const slice = entries.slice(p * PER_PAGE, (p + 1) * PER_PAGE);
    const id = `${prefix}.p${p + 1}`;
    const nextId = p + 1 < total ? `${prefix}.p${p + 2}` : null;
    out.push({
      id,
      speaker,
      text: `${head}（第 ${p + 1} / ${total} 页）`,
      corruptedText: cor([45, `${headCorrupt}（第 ${p + 1} / ${total} 页）`]),
      tags: p === 0 ? ['entry', 'hub', 'ledger'] : ['hub', 'ledger'],
      choices: [
        ...slice.map((e) =>
          c({
            id: `${prefix}.${slug(e.flag)}`,
            label: e.line,
            cost: 1,
            requires: gate(e.flag),
            gateMode: 'hide',
            effects: [addf('count.ledger-lines-read', 1)],
            goto: MARGIN[e.tone],
          }),
        ),
        ...(nextId
          ? [
              c({
                id: `${id}.next`,
                label: '翻页。',
                cost: 1,
                effects: [addf('count.ledger-pages', 1)],
                goto: nextId,
              })
            ]
          : []),
        ...(p > 0
          ? [c({ id: `${id}.prev`, label: '翻回去。', cost: 1, goto: `${prefix}.p${p}` })]
          : []),
        c({
          id: `${id}.close`,
          label: tail,
          cost: 1,
          effects: [mark('silence', 1)],
        })
      ],
    });
  }
  return out;
}

export const LEDGER_NODES: readonly NarrativeNode[] = [
  {
    id: 'ledger.open',
    speaker: undefined,
    text: '日志摊在桌上，写满的那几页朝上。\n墨是干的，字是我的。',
    corruptedText: cor(
      [50, '写满的那几页朝上。墨是干的，字是我的。行数和我今天做过的事一样多。'],
      [20, '墨是干的。最后一行的墨还亮着。'],
    ),
    tags: ['entry', 'hub', 'ledger', 'key'],
    onEnter: [fear(8)],
    choices: [
      c({
        id: 'ledger.open.deeds',
        label: '读他写的那几页。',
        cost: 2,
        goto: 'ledger.deeds.p1',
      }),
      c({
        id: 'ledger.open.beliefs',
        label: '在心里把知道的事过一遍。',
        cost: 2,
        goto: 'ledger.beliefs.p1',
      }),
      c({
        id: 'ledger.open.counts',
        label: '看同一件事做过几次。',
        cost: 2,
        goto: 'ledger.counts.p1',
      }),
      c({
        id: 'ledger.open.compare',
        label: '把他的字和我的字并在一起看。',
        cost: 3,
        requires: on('met.yourself'),
        gateMode: 'hide',
        effects: [san(-6), setf('know.same-hand')],
        goto: 'ledger.deeds.index',
      }),
      c({
        id: 'ledger.open.count',
        label: '数写满了几行。',
        cost: 3,
        requires: num('count.ledger-lines-read', '>=', 8),
        gateMode: 'hide',
        effects: [addf('count.breaths-counted', 1), san(-8)],
        goto: 'ledger.tally',
      }),
      c({
        id: 'ledger.open.close',
        label: '合上。',
        cost: 1,
        effects: [mark('silence', 1), setf('did.closed-the-log')],
      })
    ],
  },
  {
    id: 'ledger.tally',
    speaker: undefined,
    text: '写满的行数和你今天做过的事一样多。\n多一行。那一行还没写。',
    corruptedText: cor([40, '行数和你做过的事一样多。多一行。那一行等着你去做。']),
    tags: ['key', 'ledger'],
    onEnter: [setf('know.log-is-one-line-ahead'), fear(16), san(-10)],
    choices: [
      c({
        id: 'ledger.tally.read',
        label: '读那一行。',
        cost: 4,
        effects: [san(-10), fear(12)],
        goto: 'ledger.ahead',
      }),
      c({
        id: 'ledger.tally.close',
        label: '不读。',
        cost: 1,
        effects: [mark('silence', 2)],
        goto: 'ledger.open',
      })
    ],
  },
  {
    id: 'ledger.ahead',
    speaker: '日志',
    text: '「合上日志。」',
    corruptedText: cor([40, '「合上日志。」（你正在合。）']),
    tags: ['key', 'ledger'],
    onEnter: [san(-8), fear(10)],
    choices: [
      c({
        id: 'ledger.ahead.obey',
        label: '合上。',
        cost: 1,
        effects: [mark('listening', 2)],
        goto: 'self.margin.obey',
      }),
      c({
        id: 'ledger.ahead.refuse',
        label: '不合，继续拿着。',
        cost: 4,
        effects: [mark('apostasy', 2), san(-6)],
        goto: 'self.margin.refuse',
      })
    ],
  },
  {
    id: 'ledger.deeds.index',
    speaker: '日志',
    text: '这一册的页脚都编了号。最后写满的那一页折了角。',
    corruptedText: cor([45, '最后写满的那一页折了角。折痕是新的，折的时候纸还是软的。']),
    tags: ['hub', 'ledger'],
    choices: [
      c({ id: 'ledger.deeds.index.first', label: '从第一页开始。', cost: 1, goto: 'ledger.deeds.p1' }),
      c({
        id: 'ledger.deeds.index.dog-ear',
        label: '翻到折角那一页。',
        cost: 2,
        requires: num('count.ledger-lines-read', '>=', 4),
        gateMode: 'hide',
        effects: [fear(10)],
        goto: 'ledger.tally',
      }),
      c({ id: 'ledger.deeds.index.close', label: '合上。', cost: 1, effects: [mark('silence', 1)] })
    ],
  },
  ...pages(
    COUNTS,
    'ledger.counts',
    '同一件事，做过几次。字迹是我的，笔画一次比一次轻。',
    '同一件事做过几次。有几行的数字比我记得的大。',
    undefined,
    '不看了。',
    (f) => num(f, '>=', 1),
  ),
  ...pages(
    DEEDS,
    'ledger.deeds',
    '写满的那几页。每一行都是你今天做过的事。',
    '每一行都是你今天做过的事，顺序也一样。',
    '日志',
    '合上这一册。',
  ),
  ...pages(
    BELIEFS,
    'ledger.beliefs',
    '你知道的事。把它们一条一条过一遍，过完才敢往下走。',
    '你知道的事。过一遍。过完发现少了一条，想不起是哪条。',
    undefined,
    '过完了。',
  )
];
