/**
 * 可发现的船员日志与档案。
 *
 * 纪律（GDD §7.4「禁止日志倾倒」）：
 * 这里没有一段超过 120 字的独白。每一份文件都被切成可以中途合上的段，
 * 而且**每一段都要玩家付一次呼吸**去翻下一页。信息的价格是氧气，这是本作唯一的货币。
 *
 * 档案室是五层真相里 L2/L3/L4 的主要出土地：名单、同意书、人事档案、
 * 第三号样本结案报告、教团创会记录第一条。
 */

import type { NarrativeNode } from '../../core/contract';
import {
  addf,
  all,
  any,
  c,
  cor,
  fear,
  give,
  go,
  item,
  K,
  learn,
  loud,
  mark,
  noK,
  num,
  off,
  on,
  openDoor,
  san,
  setf,
  sfx,
  silence,
  take,
} from '../../narrative/dsl';

export const LOG_NODES: readonly NarrativeNode[] = [
  // ------------------------------------------------------------------- 名单板
  {
    id: 'doc.manifest',
    speaker: undefined,
    text: '名单板挂在门内侧，铝框，玻璃碎了一角。\n十九行，手写，每行后面有一个打卡孔。',
    corruptedText: cor(
      [50, '十九行，每行后面一个打卡孔。第二十行没有字，但有一个孔，是新的。'],
      [20, '二十行。最后一行的孔里有血，干的。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.found-manifest-board'), learn('k.manifest-nineteen')],
    choices: [
      c({
        id: 'doc.manifest.read',
        label: '读名字。',
        cost: 4,
        effects: [setf('did.read-names'), addf('count.names-read', 19)],
        goto: 'doc.manifest.names',
      }),
      c({
        id: 'doc.manifest.holes',
        label: '看打卡孔。',
        cost: 3,
        effects: [setf('did.examined-holes')],
        goto: 'doc.manifest.holes',
      }),
      c({
        id: 'doc.manifest.take',
        label: '把名单摘下来。',
        cost: 4,
        effects: [give('manifest'), setf('did.took-manifest'), loud(6)],
        goto: 'doc.manifest.taken',
      }),
      c({
        id: 'doc.manifest.twenty',
        label: '看第二十行。',
        cost: 3,
        requires: on('know.twentieth-gap'),
        gateMode: 'hide',
        effects: [setf('did.checked-row-twenty'), san(-8)],
        goto: 'doc.manifest.twenty',
      }),
      c({ id: 'doc.manifest.leave', label: '走开。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'doc.manifest.names',
    speaker: '名单',
    text: '一 哈尔瓦·内斯　二 比约格·利恩　三 安内莉·斯特兰\n四 托尔莫·克瓦姆　五 西格丽·奥斯　六 埃利亚斯·罗特',
    corruptedText: cor([45, '一 哈尔瓦·内斯　二 比约格·利恩　三 安内莉·斯特兰（这一行被摸得发亮）']),
    tags: ['key'],
    onEnter: [addf('count.names-read', 6)],
    choices: [
      c({ id: 'doc.manifest.names.more', label: '接着读。', cost: 3, goto: 'doc.manifest.names2' }),
      c({
        id: 'doc.manifest.names.three',
        label: '第三行被摸得发亮。',
        cost: 2,
        effects: [setf('did.noticed-third-row')],
        goto: 'doc.manifest.third',
      }),
      go('doc.manifest.names.stop', '不读了。', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.names2',
    speaker: '名单',
    text: '七 英格丽·福斯　八 佩尔·桑德　九 玛尔塔·奥伊\n十 约翰·布罗　十一 卡琳·霍尔　十二 斯坦·维克　十三 丽芙·达尔',
    tags: ['key'],
    onEnter: [addf('count.names-read', 7)],
    choices: [
      c({ id: 'doc.manifest.names2.more', label: '接着读。', cost: 3, goto: 'doc.manifest.names3' }),
      go('doc.manifest.names2.stop', '不读了。', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.names3',
    speaker: '名单',
    text: '十四 阿斯特丽·多恩　十五 埃里克·多恩　十六 露特·恩格\n十七 亚尔·穆恩　十八 奥拉夫·莱恩　十九 万斯·基尔',
    corruptedText: cor([45, '十四 阿斯特丽·多恩　十五 埃里克·多恩　……十九 万斯·基尔（十九行的孔是空的）']),
    tags: ['key'],
    onEnter: [addf('count.names-read', 6), setf('know.vance-on-manifest')],
    choices: [
      c({
        id: 'doc.manifest.names3.vance',
        label: '十九，万斯。',
        cost: 2,
        requires: on('met.vance'),
        gateMode: 'hide',
        effects: [learn('k.vance-onboard'), san(-8)],
        goto: 'doc.manifest.vance',
      }),
      c({
        id: 'doc.manifest.names3.dorn',
        label: '两个多恩。',
        cost: 2,
        requires: on('met.dorn'),
        gateMode: 'hide',
        effects: [learn('k.dorn-daughter')],
        goto: 'doc.manifest.dorns',
      }),
      go('doc.manifest.names3.stop', '读完了。', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.third',
    speaker: undefined,
    text: '第三行的漆被手指磨掉了，磨出铝的本色。\n磨的位置在名字上，不在孔上。',
    corruptedText: cor([40, '第三行被磨出铝的本色。磨在名字上，不在孔上。磨的人不想打卡，只想摸。']),
    tags: ['key'],
    onEnter: [setf('know.third-row-worn')],
    choices: [
      c({
        id: 'doc.manifest.third.link',
        label: '广播里那个声音。',
        cost: 2,
        requires: all(on('met.mother'), K('k.mother-is-spliced')),
        gateMode: 'disable',
        effects: [learn('k.mother-was-crew')],
        goto: 'doc.manifest.mother',
      }),
      go('doc.manifest.third.back', '……', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.mother',
    speaker: undefined,
    text: '第三行：安内莉·斯特兰。\n磨掉漆的那只手，磨了很多年。',
    corruptedText: cor([40, '安内莉·斯特兰。磨了很多年。磨的是你的手。']),
    tags: ['key'],
    onEnter: [learn('k.mother-was-crew'), san(-8)],
    choices: [go('doc.manifest.mother.ok', '……', 'doc.manifest')],
  },
  {
    id: 'doc.manifest.vance',
    speaker: undefined,
    text: '十九，万斯·基尔。孔是空的，没有打过。\n其余十八个孔都打了。',
    corruptedText: cor([40, '十九，万斯·基尔。孔是空的。他是唯一没打卡的人。所以他还在值班。']),
    tags: ['key'],
    onEnter: [learn('k.vance-onboard'), setf('know.vance-never-clocked')],
    choices: [go('doc.manifest.vance.ok', '……', 'doc.manifest')],
  },
  {
    id: 'doc.manifest.dorns',
    speaker: undefined,
    text: '十四和十五，姓一样。十四签在十五前面。\n十五的字很用力，纸背透了。',
    corruptedText: cor([40, '十四签在十五前面。十五的字用力到纸背透了。他签的时候在忍。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-daughter'), san(-6)],
    choices: [go('doc.manifest.dorns.ok', '……', 'doc.manifest')],
  },
  {
    id: 'doc.manifest.holes',
    speaker: undefined,
    text: '十八个孔打透了。第十九个没打。\n第二十行没有字，但有一个孔，边缘还有毛刺。',
    corruptedText: cor([40, '第二十行有孔，边缘有毛刺。毛刺说明打过不止一次。']),
    tags: ['key'],
    onEnter: [setf('know.twentieth-hole'), san(-6)],
    choices: [
      c({
        id: 'doc.manifest.holes.count',
        label: '数毛刺。',
        cost: 4,
        effects: [setf('did.counted-burrs'), addf('count.breaths-counted', 17), san(-8)],
        goto: 'doc.manifest.burrs',
      }),
      go('doc.manifest.holes.back', '……', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.burrs',
    speaker: undefined,
    text: '毛刺是一层一层的，像年轮。\n数到十七层就分不清了。',
    corruptedText: cor([40, '像年轮。数到十七层分不清了。第十八层是软的，还没定型。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-8)],
    choices: [go('doc.manifest.burrs.ok', '……', 'doc.manifest')],
  },
  {
    id: 'doc.manifest.twenty',
    speaker: undefined,
    text: '第二十行的位置上有一点铅笔的压痕，被擦过。\n压痕不是名字的形状。是一个字，笔画很少。',
    corruptedText: cor([40, '压痕不是名字的形状。是一个字，笔画很少。你认得那个字。']),
    tags: ['key'],
    onEnter: [setf('know.twentieth-is-a-word'), san(-8)],
    choices: [
      c({
        id: 'doc.manifest.twenty.read',
        label: '认那个字。',
        cost: 4,
        requires: K('k.eight-strokes'),
        gateMode: 'disable',
        effects: [learn('k.the-word'), san(-12)],
        goto: 'doc.manifest.word',
      }),
      go('doc.manifest.twenty.back', '认不出来。', 'doc.manifest')
    ],
  },
  {
    id: 'doc.manifest.word',
    speaker: undefined,
    text: '八笔。祈使语气。对象不是人。\n意思是：听。',
    corruptedText: cor([40, '八笔。祈使语气。意思是：听。（写给它的。不是它写的。）']),
    tags: ['key'],
    onEnter: [learn('k.the-word'), san(-12)],
    choices: [go('doc.manifest.word.ok', '……', 'doc.manifest')],
  },
  {
    id: 'doc.manifest.taken',
    speaker: undefined,
    text: '名单摘下来了。墙上留下一个干净的长方形，四周的漆是黄的。\n长方形里的漆也是黄的。',
    corruptedText: cor([40, '墙上留下一个长方形。里面的漆也是黄的。这块板挂上去的时间和墙一样长。']),
    tags: ['key'],
    onEnter: [setf('know.board-as-old-as-wall')],
    choices: [go('doc.manifest.taken.ok', '……', 'doc.manifest')],
  },

  // ----------------------------------------------------------------- 无线电簿
  {
    id: 'doc.radiolog',
    speaker: undefined,
    text: '无线电值班簿。每一行是时间、频率、内容摘要。\n最后二十天，"内容摘要"这一栏全是同一个字：位。',
    corruptedText: cor(
      [50, '最后二十天，内容摘要栏全是同一个字：位。位。位。位。'],
      [20, '最后二十天的内容摘要栏是空的。空得很整齐，像擦过。'],
    ),
    tags: ['entry', 'key'],
    onEnter: [setf('did.found-radio-log'), learn('k.no-distress')],
    choices: [
      c({
        id: 'doc.radiolog.first',
        label: '翻到最前面。',
        cost: 3,
        effects: [setf('did.read-radio-start')],
        goto: 'doc.radiolog.start',
      }),
      c({
        id: 'doc.radiolog.sos',
        label: '找 SOS。',
        cost: 3,
        effects: [setf('did.looked-for-sos')],
        goto: 'doc.radiolog.nosos',
      }),
      c({
        id: 'doc.radiolog.last',
        label: '最后一行。',
        cost: 3,
        effects: [setf('did.read-last-transmission')],
        goto: 'doc.radiolog.last',
      }),
      c({ id: 'doc.radiolog.close', label: '合上。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'doc.radiolog.start',
    speaker: '值班簿',
    text: '第一行：「离港。全员到齐。」\n第二行：「深度试验完成。听得到。」',
    corruptedText: cor([45, '「离港。全员到齐。」「深度试验完成。听得到。」（"听得到"三个字写得特别慢）']),
    tags: ['key'],
    onEnter: [setf('know.first-entries')],
    choices: [
      c({
        id: 'doc.radiolog.start.on',
        label: '往后翻。',
        cost: 3,
        effects: [setf('did.read-radio-middle')],
        goto: 'doc.radiolog.middle',
      }),
      go('doc.radiolog.start.back', '合上。', 'doc.radiolog')
    ],
  },
  {
    id: 'doc.radiolog.middle',
    speaker: '值班簿',
    text: '「听得更清楚。深度一千二。」\n「有人问能不能不上浮。记录在案。」',
    corruptedText: cor([45, '「听得更清楚。」「有人问能不能不上浮。记录在案。」（记录在案四个字后面有一个勾）']),
    tags: ['key'],
    onEnter: [learn('k.not-research'), setf('know.asked-not-to-surface')],
    choices: [
      c({
        id: 'doc.radiolog.middle.on',
        label: '再往后。',
        cost: 3,
        effects: [setf('did.read-radio-late')],
        goto: 'doc.radiolog.late',
      }),
      go('doc.radiolog.middle.back', '合上。', 'doc.radiolog')
    ],
  },
  {
    id: 'doc.radiolog.late',
    speaker: '值班簿',
    text: '「全体表决。十九票。」\n下一行的字换了人，方正，像填表：「接管记录。」',
    corruptedText: cor([45, '「全体表决。十九票。」「接管记录。」（第二行的字是万斯的。）']),
    tags: ['key'],
    onEnter: [learn('k.all-volunteers'), setf('know.vance-took-over')],
    choices: [
      c({
        id: 'doc.radiolog.late.vote',
        label: '十九票，全票。',
        cost: 2,
        effects: [learn('k.all-volunteers'), setf('did.saw-the-vote')],
        goto: 'doc.radiolog.vote',
      }),
      go('doc.radiolog.late.back', '合上。', 'doc.radiolog')
    ],
  },
  {
    id: 'doc.radiolog.vote',
    speaker: undefined,
    text: '十九个人，十九票。没有反对，也没有弃权。\n弃权那一栏被画了一道横线，划掉了。',
    corruptedText: cor([40, '十九票。弃权那栏被划掉了。划的人手很稳。']),
    tags: ['key'],
    onEnter: [learn('k.all-volunteers'), san(-6)],
    choices: [go('doc.radiolog.vote.ok', '……', 'doc.radiolog')],
  },
  {
    id: 'doc.radiolog.nosos',
    speaker: undefined,
    text: '没有。二十天里一条都没有。\n有一条发出去的，内容是坐标，重复了四十次。',
    corruptedText: cor([40, '没有 SOS。有一条坐标，重复四十次。坐标不是这条船的。']),
    tags: ['key'],
    onEnter: [learn('k.no-distress'), setf('know.coords-broadcast')],
    choices: [
      c({
        id: 'doc.radiolog.nosos.where',
        label: '那个坐标在哪。',
        cost: 3,
        requires: on('know.hymnal-coords'),
        gateMode: 'disable',
        effects: [setf('did.located-broadcast'), san(-6)],
        goto: 'doc.radiolog.coord',
      }),
      go('doc.radiolog.nosos.back', '合上。', 'doc.radiolog')
    ],
  },
  {
    id: 'doc.radiolog.coord',
    speaker: undefined,
    text: '和唱诗本第二十行的坐标一样。\n那是月池。他们朝外面播的是自己的位置。',
    corruptedText: cor([40, '和唱诗本第二十行一样。月池。他们朝外面播自己的位置。播了四十次。']),
    tags: ['key'],
    onEnter: [setf('know.they-broadcast-themselves'), san(-8)],
    choices: [go('doc.radiolog.coord.ok', '……', 'doc.radiolog')],
  },
  {
    id: 'doc.radiolog.last',
    speaker: '值班簿',
    text: '最后一行：「位空。等下一个。」\n后面还有半行的空白，钢笔尖戳了一个点。',
    corruptedText: cor([45, '「位空。等下一个。」后面半行空白，戳了一个点。点很深。']),
    tags: ['key'],
    onEnter: [setf('know.waiting-for-next'), san(-8)],
    choices: [
      c({
        id: 'doc.radiolog.last.next',
        label: '"下一个"是我。',
        cost: 2,
        requires: K('k.your-bunk'),
        gateMode: 'disable',
        effects: [learn('k.you-are-sample-n'), san(-10)],
        goto: 'doc.radiolog.me',
      }),
      go('doc.radiolog.last.back', '合上。', 'doc.radiolog')
    ],
  },
  {
    id: 'doc.radiolog.me',
    speaker: undefined,
    text: '这一行的墨比上一行新。\n上一行的墨比上上一行新。整本簿子只有一页是旧的。',
    corruptedText: cor([40, '只有一页是旧的。其余每一页都比前一页新。这本簿子一直在被续写。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-8)],
    choices: [go('doc.radiolog.me.ok', '……', 'doc.radiolog')],
  },

  // ------------------------------------------------------------------- 档案室
  {
    id: 'doc.archive',
    speaker: undefined,
    text: '档案室。六个铁皮柜，五个锁着。没锁那个的抽屉全拉开了。\n地上有一排脚印，从门口直接走到没锁那个。',
    corruptedText: cor(
      [50, '六个柜子，五个锁着。地上的脚印从门口直接走到没锁那个。脚印右脚重一点。'],
      [20, '六个柜子都开着。都空着。脚印有很多层。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.entered-archive'), openDoor('door.archive')],
    choices: [
      c({
        id: 'doc.archive.consent',
        label: '同意书匣。',
        cost: 4,        goto: 'doc.consent',
      }),
      c({
        id: 'doc.archive.personnel',
        label: '人事档案。',
        cost: 4,        goto: 'doc.personnel',
      }),
      c({
        id: 'doc.archive.sample3',
        label: '一份封起来的报告：第三号。',
        cost: 4,
        requires: K('k.mother-was-crew'),
        gateMode: 'disable',        goto: 'doc.sample3',
      }),
      c({
        id: 'doc.archive.founding',
        label: '最下面一格：创会记录。',
        cost: 5,
        requires: K('k.cult-was-right'),
        gateMode: 'disable',
        effects: [setf('did.found-founding')],
        goto: 'doc.founding',
      }),
      c({
        id: 'doc.archive.service',
        label: '最后一次礼拜的记录。',
        cost: 4,
        requires: K('k.all-volunteers'),
        gateMode: 'disable',
        effects: [setf('did.found-service-record')],
        goto: 'doc.service',
      }),
      c({
        id: 'doc.archive.locked',
        label: '撬开锁着的柜子。',
        cost: 8,
        requires: item('wrench'),
        gateMode: 'lie',
        effects: [loud(20)],
        goto: 'doc.locked',
      }),
      c({
        id: 'doc.archive.prints',
        label: '看地上的脚印。',
        cost: 3,
        effects: [setf('did.examined-archive-prints')],
        goto: 'doc.prints',
      }),
      c({ id: 'doc.archive.leave', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'doc.prints',
    speaker: undefined,
    text: '一排脚印，右脚重一点。走到没锁那个柜子前就停了。\n停的地方站了很久，鞋底的水印有三层。',
    corruptedText: cor([40, '右脚重一点。站了很久，水印三层。三层的意思是三次。']),
    tags: ['key'],
    onEnter: [setf('know.three-visits-here'), san(-6)],
    choices: [go('doc.prints.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.consent',
    speaker: undefined,
    text: '一个木匣，里面十九张纸，都是手写的一句话加签名。\n最上面那张：「我自愿下潜，并自愿留下。」',
    corruptedText: cor([45, '十九张纸。最上面那张：「我自愿下潜，并自愿留下。」第二十张是空白表格。']),
    tags: ['key'],
    onEnter: [learn('k.all-volunteers'), setf('did.read-consent')],
    choices: [
      c({
        id: 'doc.consent.hands',
        label: '看笔迹抖不抖。',
        cost: 3,
        effects: [setf('did.checked-consent-hands')],
        goto: 'doc.consent.steady',
      }),
      c({
        id: 'doc.consent.blank',
        label: '最下面有一张空白的。',
        cost: 3,
        effects: [setf('did.found-blank-consent'), san(-6)],
        goto: 'doc.consent.blank',
      }),
      go('doc.consent.back', '盖上匣子。', 'doc.archive')
    ],
  },
  {
    id: 'doc.consent.steady',
    speaker: undefined,
    text: '十九张，没有一张的字是抖的。\n有三张的字比日常签名还工整——他们誊写过。',
    corruptedText: cor([40, '没有一张是抖的。三张誊写过。誊写是因为第一遍写错了，或者第一遍不好看。']),
    tags: ['key'],
    onEnter: [learn('k.all-volunteers'), learn('k.cult-was-right'), san(-8)],
    choices: [go('doc.consent.steady.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.consent.blank',
    speaker: undefined,
    text: '空白那张已经印好了句子，只差签名。\n句子和别人那张一模一样。纸的边角被手指捏软了。',
    corruptedText: cor([40, '空白那张只差签名。纸的边角被捏软了。捏了很多次，每次都没签。']),
    tags: ['key'],
    onEnter: [setf('know.blank-consent'), san(-6)],
    choices: [
      c({
        id: 'doc.consent.blank.sign',
        label: '签。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.signed-consent'), mark('listening', 3), san(-10)],
        goto: 'doc.consent.signed',
      }),
      c({
        id: 'doc.consent.blank.tear',
        label: '撕掉。',
        cost: 3,
        irreversible: true,
        effects: [setf('did.tore-consent'), mark('apostasy', 2), san(5)],
        goto: 'doc.consent.torn',
      }),
      c({
        id: 'doc.consent.blank.back',
        label: '放回去。',
        cost: 2,
        effects: [setf('did.left-consent-blank'), mark('silence', 1)],
        goto: 'doc.archive',
      })
    ],
  },
  {
    id: 'doc.consent.signed',
    speaker: undefined,
    text: '签完之后匣子里是二十张。\n第二十张的纸比别的新，但捏软的边角一样软。',
    corruptedText: cor([40, '二十张。第二十张的纸新，边角一样软。所以你每次都签。']),
    tags: ['key'],
    onEnter: [setf('did.signed-consent'), san(-8), learn('k.salvage-is-ritual')],
    choices: [go('doc.consent.signed.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.consent.torn',
    speaker: undefined,
    text: '撕成四片，塞进口袋。\n匣子底下还有一张空白的。',
    corruptedText: cor([40, '撕成四片。匣子底下还有一张。底下永远还有一张。']),
    tags: ['key'],
    onEnter: [setf('know.always-another-form'), addf('count.futile-acts', 1)],
    choices: [go('doc.consent.torn.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.personnel',
    speaker: undefined,
    text: '人事档案，一人一页，钉着照片。\n第三页的照片被取下来过，钉孔是两个。',
    corruptedText: cor([45, '第三页的照片被取下来过，钉孔两个。照片现在在你口袋里。']),
    tags: ['key'],
    onEnter: [setf('did.opened-personnel')],
    choices: [
      c({
        id: 'doc.personnel.three',
        label: '看第三页。',
        cost: 3,
        effects: [setf('did.read-page-three')],
        goto: 'doc.personnel.three',
      }),
      c({
        id: 'doc.personnel.photo',
        label: '掏出口袋里的照片比一下。',
        cost: 3,
        requires: item('photo'),
        gateMode: 'disable',
        effects: [setf('did.matched-photo'), san(-10)],
        goto: 'doc.personnel.photo',
      }),
      c({
        id: 'doc.personnel.mine',
        label: '找自己那一页。',
        cost: 4,
        effects: [setf('did.looked-for-own-file')],
        goto: 'doc.personnel.mine',
      }),
      go('doc.personnel.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.personnel.three',
    speaker: '档案',
    text: '安内莉·斯特兰。职务：广播/记录。\n备注一行：「声线适合。」',
    corruptedText: cor([45, '安内莉·斯特兰。职务：广播/记录。备注：「声线适合。」（适合什么没有写。）']),
    tags: ['key'],
    onEnter: [learn('k.mother-was-crew'), setf('know.voice-suitable'), san(-8)],
    choices: [
      c({
        id: 'doc.personnel.three.for',
        label: '适合什么。',
        cost: 2,
        requires: K('k.mother-is-spliced'),
        gateMode: 'disable',
        effects: [learn('k.mother-is-spliced'), setf('did.asked-suitable-for-what')],
        goto: 'doc.personnel.for',
      }),
      go('doc.personnel.three.back', '合上。', 'doc.personnel')
    ],
  },
  {
    id: 'doc.personnel.for',
    speaker: undefined,
    text: '适合被剪。\n她的每句话都是家常话，家常话可以拆成词，词可以重排。',
    corruptedText: cor([40, '适合被剪。家常话可以拆成词，词可以重排。她的句子最好剪。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-spliced'), san(-8)],
    choices: [go('doc.personnel.for.ok', '……', 'doc.personnel')],
  },
  {
    id: 'doc.personnel.photo',
    speaker: undefined,
    text: '同一个人。照片背面写着一个日期，比这次下潜早十一年。\n十一年前你多大，你算不出来。',
    corruptedText: cor([40, '同一个人。背面日期比下潜早十一年。十一年前你多大，你算不出来。']),
    tags: ['key'],
    onEnter: [san(-10), setf('know.photo-date')],
    choices: [go('doc.personnel.photo.ok', '……', 'doc.personnel')],
  },
  {
    id: 'doc.personnel.mine',
    speaker: undefined,
    text: '没有你那一页。\n但是钉书钉的孔位从第十九页往后还有一排，间距和前面一样。',
    corruptedText: cor([40, '没有你那一页。钉孔往后还有一排。一排十七个。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-8)],
    choices: [go('doc.personnel.mine.ok', '……', 'doc.personnel')],
  },
  {
    id: 'doc.sample3',
    speaker: '报告',
    text: '封面：「样本 03 结案」。\n第一页只有三行，其中两行被涂黑。',
    corruptedText: cor([45, '「样本 03 结案」。第一页三行，两行被涂黑。涂的是同一支笔。']),
    tags: ['key'],
    onEnter: [setf('did.opened-report-three')],
    choices: [
      c({
        id: 'doc.sample3.read',
        label: '读没涂黑那行。',
        cost: 3,
        effects: [setf('did.read-report-line')],
        goto: 'doc.sample3.line',
      }),
      c({
        id: 'doc.sample3.light',
        label: '对着灯看涂黑的部分。',
        cost: 5,
        effects: [setf('did.backlit-redaction'), san(-8)],
        goto: 'doc.sample3.redacted',
      }),
      go('doc.sample3.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.sample3.line',
    speaker: '报告',
    text: '「行进完成。终止方式：留任。」',
    corruptedText: cor([45, '「行进完成。终止方式：留任。」（"留任"两个字写在原来的字上面。）']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-sample-three'), san(-10)],
    choices: [
      c({
        id: 'doc.sample3.line.under',
        label: '"留任"下面压着别的字。',
        cost: 3,
        effects: [setf('did.saw-overwrite'), san(-6)],
        goto: 'doc.sample3.under',
      }),
      go('doc.sample3.line.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.sample3.under',
    speaker: undefined,
    text: '下面那两个字笔画少，看得出是「回收」。\n改成「留任」的人用的是同一支笔。',
    corruptedText: cor([40, '下面是「回收」。改成「留任」的是同一支笔。改的时候手抖了一下。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-sample-three'), learn('k.salvage-is-ritual'), san(-8)],
    choices: [go('doc.sample3.under.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.sample3.redacted',
    speaker: undefined,
    text: '涂黑的两行透出来一部分：\n「……不得告知后续样本……」「……按其请求保留问句……」',
    corruptedText: cor([40, '「不得告知后续样本」「按其请求保留问句」。她请求保留的问句是那一句。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-sample-three'), san(-12), setf('know.she-requested-the-question')],
    choices: [
      c({
        id: 'doc.sample3.redacted.which',
        label: '哪一句。',
        cost: 2,
        requires: num('count.mother-asked-food', '>=', 2),
        gateMode: 'disable',
        effects: [setf('did.identified-the-question'), san(-8)],
        goto: 'doc.sample3.question',
      }),
      go('doc.sample3.redacted.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.sample3.question',
    speaker: undefined,
    text: '「你吃过东西了吗。」\n这是她唯一要求保留的东西。别的都可以剪。',
    corruptedText: cor([40, '「你吃过东西了吗。」这是她唯一要求保留的。别的都可以剪。']),
    tags: ['key'],
    onEnter: [san(-8), setf('know.her-one-request')],
    choices: [go('doc.sample3.question.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.service',
    speaker: '记录',
    text: '最后一次礼拜，出席十九人。\n记录只有一句：「今天听清楚了。散会后各自回岗。」',
    corruptedText: cor([45, '出席十九人。「今天听清楚了。散会后各自回岗。」（没有人再写过别的。）']),
    tags: ['key'],
    onEnter: [learn('k.cult-was-right'), san(-8)],
    choices: [
      c({
        id: 'doc.service.what',
        label: '"听清楚了"什么。',
        cost: 3,
        requires: K('k.signal-is-real'),
        gateMode: 'disable',
        effects: [learn('k.cult-was-right'), setf('did.asked-what-was-clear')],
        goto: 'doc.service.clear',
      }),
      go('doc.service.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.service.clear',
    speaker: undefined,
    text: '记录里没有写内容，因为十九个人都听见了，不需要记。\n需要记的是"各自回岗"——他们听清楚之后还去上班了。',
    corruptedText: cor([40, '他们听清楚之后还去上班了。这是全船最可怕的一行字。']),
    tags: ['key'],
    onEnter: [learn('k.cult-was-right'), san(-10)],
    choices: [go('doc.service.clear.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.founding',
    speaker: '创会记录',
    text: '第一条：「它不会回答。它只会听。」\n第二条被裁掉了，只剩一条纸边。',
    corruptedText: cor([45, '「它不会回答。它只会听。」第二条被裁掉了。裁得很齐。']),
    tags: ['key'],
    onEnter: [learn('k.author-is-not-it'), san(-8)],
    choices: [
      c({
        id: 'doc.founding.two',
        label: '找第二条。',
        cost: 4,
        effects: [setf('did.looked-for-second-tenet')],
        goto: 'doc.founding.two',
      }),
      c({
        id: 'doc.founding.mean',
        label: '"只会听"的意思。',
        cost: 3,
        requires: K('k.the-word'),
        gateMode: 'disable',
        effects: [learn('k.author-is-not-it'), setf('did.understood-tenet')],
        goto: 'doc.founding.mean',
      }),
      go('doc.founding.back', '合上。', 'doc.archive')
    ],
  },
  {
    id: 'doc.founding.two',
    speaker: undefined,
    text: '裁下来的那条夹在柜子背板和铁皮之间，折了三折。\n上面一句：「所以写的人是我们。」',
    corruptedText: cor([40, '「所以写的人是我们。」这一条被裁掉，因为它把责任还给了人。']),
    tags: ['key'],
    onEnter: [learn('k.author-is-not-it'), san(-10)],
    choices: [go('doc.founding.two.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.founding.mean',
    speaker: undefined,
    text: '它不发命令。命令是人替它写的，写成祈使语气，八笔。\n然后人再去执行自己写的那个命令。',
    corruptedText: cor([40, '命令是人替它写的。然后人再去执行自己写的命令。它从来没有要求过任何事。']),
    tags: ['key'],
    onEnter: [learn('k.author-is-not-it'), san(-10)],
    choices: [go('doc.founding.mean.ok', '……', 'doc.archive')],
  },
  {
    id: 'doc.locked',
    speaker: undefined,
    text: '撬开了。里面是空的，连灰都没有。\n柜底有一行钢印：本柜为演示用。',
    corruptedText: cor([40, '里面是空的。柜底钢印：本柜为演示用。五个柜子都是。']),
    tags: ['key'],
    onEnter: [setf('know.display-cabinets'), addf('count.futile-acts', 1), san(-4)],
    choices: [go('doc.locked.ok', '……', 'doc.archive')],
  },

  // ------------------------------------------------------------------- 食堂账
  {
    id: 'doc.galley',
    speaker: undefined,
    text: '口粮账本。一天一行，每行后面画正字。\n最后二十天，每天多领一份。多的那份记在"客"名下。',
    corruptedText: cor([45, '最后二十天每天多领一份，记在"客"名下。"客"这个字写得很小。']),
    tags: ['entry', 'key'],
    onEnter: [learn('k.galley-ledger'), setf('did.found-galley-ledger')],
    choices: [
      c({
        id: 'doc.galley.guest',
        label: '"客"是谁。',
        cost: 3,
        requires: on('met.pelle'),
        gateMode: 'disable',
        effects: [learn('k.pelle-not-on-list'), setf('did.identified-guest')],
        goto: 'doc.galley.guest',
      }),
      c({
        id: 'doc.galley.table',
        label: '去第二张桌子看看。',
        cost: 4,
        requires: on('know.galley-table'),
        gateMode: 'hide',
        effects: [setf('did.checked-second-table')],
        goto: 'doc.galley.table',
      }),
      c({ id: 'doc.galley.close', label: '合上。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'doc.galley.guest',
    speaker: undefined,
    text: '"客"不在名单上，但一天一份，二十天没断。\n份量是小份。',
    corruptedText: cor([40, '"客"不在名单上。一天一份，二十天没断。小份。小孩的份。']),
    tags: ['key'],
    onEnter: [learn('k.pelle-not-on-list'), san(-6)],
    choices: [go('doc.galley.guest.ok', '……', 'doc.galley')],
  },
  {
    id: 'doc.galley.table',
    speaker: undefined,
    text: '第二张桌子靠墙那边，摆着一副碗筷，摆得很正。\n碗是空的，干的，里面有一圈很旧的痕。',
    corruptedText: cor([40, '一副碗筷摆得很正。碗是空的，干的。痕很旧。旁边还有一副小的。']),
    tags: ['key'],
    onEnter: [setf('know.the-bowl-is-real'), san(-6)],
    choices: [
      c({
        id: 'doc.galley.table.sit',
        label: '坐下。',
        cost: 6,
        effects: [setf('did.sat-at-the-table'), san(5), addf('count.futile-acts', 1)],
        goto: 'doc.galley.sat',
      }),
      go('doc.galley.table.back', '不坐。', 'doc.galley')
    ],
  },
  {
    id: 'doc.galley.sat',
    speaker: '广播',
    text: '（咔）你吃过东西了吗。',
    corruptedText: cor([40, '（咔）你吃过东西了吗。（咔）碗放着，我收。']),
    tags: ['key'],
    onEnter: [addf('count.mother-asked-food', 1), sfx('mother.tone'), san(-4)],
    choices: [
      c({
        id: 'doc.galley.sat.yes',
        label: '"吃过了。"',
        cost: 2,
        effects: [addf('count.answered-mother', 1), setf('did.answered-at-the-table')],
        goto: 'doc.galley',
      }),
      c({
        id: 'doc.galley.sat.no',
        label: '"没有。"',
        cost: 2,
        effects: [setf('did.told-mother-hungry'), addf('count.answered-mother', 1)],
        goto: 'doc.galley',
      })
    ],
  }
];
