/**
 * 母亲 MOTHER —— 潜艇广播，声音是你母亲的。
 *
 * 核心张力（GDD §7.2）：它是被录下来的，还是被做出来的。
 *
 * 剧作位置（四角对立的第二角）：她攻击玩家弱点的方式是**给被爱的感觉**。
 * 万斯给答案，她给一盏留着的灯。她从来不阻止你走，她只是让走这件事变得贵。
 *
 * 契诃夫技法：
 *  - C4 口头禅：「你吃过东西了吗。」隔很久问第二次；结尾反用（她问自己）。
 *  - D1 首句即主题被琐事压下：每次她要说一句要紧的话，中间就有一下剪接的"咔"。
 *  - D4 最痛的话最短：全剧她最长的一句话是关于门闩的，最短的一句是"走完了"。
 *  - 她从不说"我爱你"。她说"灯我留着"。
 */

import type { NarrativeNode } from '../../core/contract';
import {
  addf,
  all,
  any,
  c,
  cor,
  fear,
  give,
  go,
  item,
  K,
  learn,
  loud,
  mark,
  noK,
  num,
  off,
  on,
  san,
  setf,
  sfx,
  silence,
  take,
} from '../../narrative/dsl';

export const MOTHER_NODES: readonly NarrativeNode[] = [
  {
    id: 'mother.first',
    speaker: '广播',
    text: '——门我关了。（咔）你吃过东西了吗。',
    corruptedText: cor(
      [50, '——门我关了。（咔）你吃过东西了吗。（咔）你吃过东西了吗。'],
      [22, '——门我关了。你在门里面。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('met.mother'), addf('count.mother-asked-food', 1), sfx('mother.tone')],
    choices: [
      c({
        id: 'mother.first.yes',
        label: '"吃过了。"',
        cost: 2,
        effects: [setf('did.answered-food'), addf('count.answered-mother', 1)],
        goto: 'mother.fed',
      }),
      c({
        id: 'mother.first.no',
        label: '"没有。"',
        cost: 2,
        effects: [setf('did.told-mother-hungry'), addf('count.answered-mother', 1)],
        goto: 'mother.hungry',
      }),
      c({
        id: 'mother.first.who',
        label: '"谁在说话。"',
        cost: 2,
        effects: [setf('did.asked-mother-who')],
        goto: 'mother.who',
      }),
      silence('mother.first.silent', 'mother.nosound'),
    ],
  },
  {
    id: 'mother.fed',
    speaker: '广播',
    text: '好。（咔）碗放着，我收。',
    corruptedText: cor([45, '好。（咔）碗放着。你没有碗。']),
    tags: ['key'],
    choices: [
      c({
        id: 'mother.fed.bowl',
        label: '"我没有碗。"',
        cost: 2,
        effects: [setf('did.mentioned-no-bowl')],
        goto: 'mother.bowl',
      }),
      go('mother.fed.channel', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.bowl',
    speaker: '广播',
    text: '（咔）食堂第二张桌子，靠墙那边。（咔）我给你留了。',
    corruptedText: cor([45, '（咔）食堂第二张桌子。留了很多天。']),
    tags: ['key'],
    onEnter: [setf('know.galley-table')],
    choices: [
      c({
        id: 'mother.bowl.thanks',
        label: '"谢谢。"',
        cost: 2,
        effects: [setf('did.thanked-mother'), san(3)],
        goto: 'mother.pa',
      }),
      go('mother.bowl.drop', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.hungry',
    speaker: '广播',
    text: '那就去吃。（咔）路上灯我开着。',
    corruptedText: cor([45, '那就去吃。（咔）路上灯我开着。一直开着。开了很久。']),
    tags: ['key'],
    onEnter: [setf('did.mother-lit-path'), san(4)],
    choices: [
      c({
        id: 'mother.hungry.why',
        label: '"为什么帮我。"',
        cost: 2,
        effects: [setf('did.asked-why-help')],
        goto: 'mother.whyhelp',
      }),
      go('mother.hungry.go', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.whyhelp',
    speaker: '广播',
    text: '（咔）灯本来就开着。',
    corruptedText: cor([40, '（咔）灯本来就开着。电是你在耗。']),
    tags: ['key'],
    choices: [go('mother.whyhelp.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.who',
    speaker: '广播',
    text: '（咔）水位到膝盖就别往下走了。（咔）听见了吗。',
    corruptedText: cor([45, '（咔）水位到膝盖就别往下走了。你的膝盖是湿的。']),
    tags: ['key'],
    onEnter: [setf('did.mother-dodged-once')],
    choices: [
      c({
        id: 'mother.who.again',
        label: '"我问你是谁。"',
        cost: 2,
        effects: [addf('count.asked-mother-identity', 1), setf('did.asked-mother-name')],
        goto: 'mother.who2',
      }),
      c({
        id: 'mother.who.heard',
        label: '"听见了。"',
        cost: 2,
        effects: [setf('did.obeyed-mother'), addf('count.answered-mother', 1)],
        goto: 'mother.pa',
      }),
    ],
  },
  {
    id: 'mother.who2',
    speaker: '广播',
    text: '（咔）门闩要往上提一点再推，不然会卡。（咔）这条船的门都这样，老。',
    corruptedText: cor([45, '（咔）门闩要往上提一点。你的手已经知道了。']),
    tags: ['key'],
    onEnter: [setf('know.latch-trick')],
    choices: [
      c({
        id: 'mother.who2.third',
        label: '第三次问。',
        cost: 3,
        requires: num('count.asked-mother-identity', '>=', 1),
        gateMode: 'disable',
        effects: [addf('count.asked-mother-identity', 1)],
        goto: 'mother.who3',
      }),
      go('mother.who2.stop', '不问了。', 'mother.pa'),
    ],
  },
  {
    id: 'mother.who3',
    speaker: '广播',
    text: '（咔）\n（咔）你吃过东西了吗。',
    corruptedText: cor([40, '（咔）（咔）（咔）你吃过东西了吗。']),
    tags: ['key'],
    onEnter: [addf('count.mother-asked-food', 1), setf('know.mother-repeats')],
    choices: [
      c({
        id: 'mother.who3.notice',
        label: '"你刚才问过了。"',
        cost: 2,
        requires: num('count.mother-asked-food', '>=', 2),
        gateMode: 'disable',
        effects: [setf('did.caught-repeat'), addf('count.debunks', 1), san(5)],
        goto: 'mother.repeat',
      }),
      c({
        id: 'mother.who3.answer',
        label: '"吃过了。"',
        cost: 2,
        effects: [addf('count.answered-mother', 1)],
        goto: 'mother.pa',
      }),
    ],
  },
  {
    id: 'mother.repeat',
    speaker: '广播',
    text: '（咔）',
    corruptedText: cor([40, '（咔）（咔）']),
    tags: ['key'],
    onEnter: [sfx('tape.splice'), setf('did.heard-splice')],
    choices: [
      c({
        id: 'mother.repeat.click',
        label: '每句话中间都有那一下。',
        cost: 2,
        effects: [learn('k.mother-is-spliced')],
        goto: 'mother.spliced',
      }),
      silence('mother.repeat.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.spliced',
    speaker: undefined,
    text: '那一下是磁带的接头。她的每句话都是从别的句子里剪出来的。\n她只会说你听过的话。',
    corruptedText: cor([40, '那一下是接头。她只会说你听过的话。所以她说过的每句话，你都真的听过。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-spliced'), san(-5)],
    choices: [
      c({
        id: 'mother.spliced.worse',
        label: '所以这些话是真的，只是次序被换了。',
        cost: 2,
        effects: [setf('did.realized-words-real'), san(-4)],
        goto: 'mother.wordsreal',
      }),
      go('mother.spliced.back', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.wordsreal',
    speaker: undefined,
    text: '她真的说过"门我关了"。真的说过"你吃过东西了吗"。\n这比伪造难受得多。',
    tags: ['key'],
    choices: [go('mother.wordsreal.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.nosound',
    speaker: '广播',
    text: '（咔）好。（咔）不说就不说。灯我留着。',
    corruptedText: cor([45, '（咔）不说就不说。灯我留着。留到你回来。']),
    tags: ['key'],
    onEnter: [setf('did.mother-left-light'), mark('silence', 1)],
    choices: [go('mother.nosound.go', '……', 'mother.pa')],
  },

  // -------------------------------------------------------------------------
  // 广播中枢
  // -------------------------------------------------------------------------
  {
    id: 'mother.pa',
    speaker: '广播',
    text: '（底噪）',
    corruptedText: cor(
      [50, '（底噪）（底噪里有人在呼吸，很浅，像忍着不出声）'],
      [22, '（没有底噪。广播是关着的。你还是听得见。）'],
    ),
    tags: ['entry', 'hub', 'key'],
    onEnter: [sfx('tape.hiss'), addf('count.mother-visits', 1)],
    choices: [
      c({
        id: 'mother.pa.food',
        label: '"我吃过了。"',
        cost: 2,
        effects: [addf('count.answered-mother', 1)],
        goto: 'mother.fed',
      }),
      c({
        id: 'mother.pa.mom',
        label: '叫她"妈"。',
        cost: 2,
        irreversible: true,
        effects: [setf('did.called-her-mom'), mark('listening', 2), san(-3)],
        goto: 'mother.mom',
      }),
      c({
        id: 'mother.pa.refuse',
        label: '"你不是她。"',
        cost: 2,
        requires: K('k.mother-is-spliced'),
        gateMode: 'disable',
        effects: [setf('did.denied-mother'), mark('apostasy', 1)],
        goto: 'mother.denied',
      }),
      c({
        id: 'mother.pa.third',
        label: '"名单第三行。"',
        cost: 3,
        requires: K('k.mother-was-crew'),
        gateMode: 'disable',
        effects: [setf('did.said-third-row')],
        goto: 'mother.thirdrow',
      }),
      c({
        id: 'mother.pa.finished',
        label: '"你走完了吗。"',
        cost: 2,
        requires: K('k.mother-is-sample-three'),
        gateMode: 'disable',
        effects: [setf('did.asked-if-finished')],
        goto: 'mother.finished',
      }),
      c({
        id: 'mother.pa.lights',
        label: '"把灯全关掉。"',
        cost: 3,
        effects: [setf('did.asked-lights-off')],
        goto: 'mother.lightsoff',
      }),
      c({
        id: 'mother.pa.water',
        label: '"水位。"',
        cost: 2,
        effects: [setf('did.asked-mother-water'), addf('count.water-checks', 1)],
        goto: 'mother.water',
      }),
      c({
        id: 'mother.pa.door',
        label: '"帮我开圣物室的门。"',
        cost: 3,
        requires: all(on('met.choir'), K('k.cult-was-right')),
        gateMode: 'lie',
        effects: [setf('did.asked-mother-reliquary')],
        goto: 'mother.reliquary',
      }),
      c({
        id: 'mother.pa.tape',
        label: '去医务室慢速回放这段广播。',
        cost: 4,
        requires: item('tape.mother'),
        gateMode: 'hide',
        effects: [setf('did.slowed-tape')],
        goto: 'mother.tape.slow',
      }),
      c({
        id: 'mother.pa.pelle',
        label: '"管道里那个小孩是谁。"',
        cost: 2,
        requires: on('met.pelle'),
        gateMode: 'hide',
        effects: [setf('did.asked-mother-pelle')],
        goto: 'mother.pelle',
      }),
      c({
        id: 'mother.pa.sing',
        label: '"你会唱那首歌吗。"',
        cost: 2,
        requires: on('met.choir'),
        gateMode: 'hide',
        effects: [setf('did.asked-mother-sing')],
        goto: 'mother.sing',
      }),
      c({ id: 'mother.pa.leave', label: '走开。', cost: 1, goto: 'mother.leaving' }),
    ],
  },
  {
    id: 'mother.mom',
    speaker: '广播',
    text: '（咔）\n（咔）灯我留着。',
    corruptedText: cor([40, '（咔）灯我留着。（咔）你小时候也这么叫。声音一样。']),
    tags: ['key'],
    onEnter: [setf('know.she-did-not-answer')],
    choices: [
      c({
        id: 'mother.mom.again',
        label: '再叫一次。',
        cost: 2,
        effects: [addf('count.called-mom', 1), mark('listening', 1), san(-4)],
        goto: 'mother.mom2',
      }),
      silence('mother.mom.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.mom2',
    speaker: '广播',
    text: '（咔）门闩要往上提一点。',
    corruptedText: cor([40, '（咔）门闩要往上提一点。（咔）别再叫了。']),
    tags: ['key'],
    choices: [
      c({
        id: 'mother.mom2.third',
        label: '第三次。',
        cost: 3,
        requires: num('count.called-mom', '>=', 1),
        gateMode: 'disable',
        effects: [addf('count.called-mom', 1), san(-6), mark('listening', 1)],
        goto: 'mother.mom3',
      }),
      go('mother.mom2.stop', '不叫了。', 'mother.pa'),
    ],
  },
  {
    id: 'mother.mom3',
    speaker: '广播',
    text: '（咔）嗯。',
    corruptedText: cor([40, '（咔）嗯。（这一声没有接头）']),
    tags: ['key'],
    onEnter: [setf('know.one-word-no-splice'), san(-8), fear(10)],
    choices: [
      c({
        id: 'mother.mom3.splice',
        label: '这一声没有那一下"咔"。',
        cost: 2,
        requires: K('k.mother-is-spliced'),
        gateMode: 'disable',
        effects: [setf('did.noticed-clean-word'), addf('count.debunks', 1)],
        goto: 'mother.clean',
      }),
      silence('mother.mom3.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.clean',
    speaker: undefined,
    text: '别的话是剪的。这一声是现录的。\n有东西在用她的声音，现场答应了你。',
    corruptedText: cor([40, '这一声是现录的。它学得很快。它学会了怎么当一个母亲。']),
    tags: ['key'],
    onEnter: [san(-8)],
    choices: [go('mother.clean.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.denied',
    speaker: '广播',
    text: '（咔）好。（咔）水位到膝盖就别往下走了。',
    corruptedText: cor([45, '（咔）好。（她没有反驳。她从来不反驳。）']),
    tags: ['key'],
    onEnter: [setf('did.mother-accepted-denial')],
    choices: [
      c({
        id: 'mother.denied.press',
        label: '"你就不问为什么？"',
        cost: 2,
        effects: [setf('did.pressed-mother-denial')],
        goto: 'mother.nopress',
      }),
      go('mother.denied.drop', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.nopress',
    speaker: '广播',
    text: '（咔）问了你也要走。（咔）灯我留着。',
    tags: ['key'],
    choices: [go('mother.nopress.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.thirdrow',
    speaker: '广播',
    text: '（咔）第三行。（咔）那一行我签得最快。',
    corruptedText: cor([45, '（咔）第三行。（咔）我签得最快。我想早点听见。']),
    tags: ['key'],
    onEnter: [learn('k.mother-was-crew'), setf('know.she-signed-fast')],
    choices: [
      c({
        id: 'mother.thirdrow.why',
        label: '"为什么签。"',
        cost: 2,
        effects: [setf('did.asked-why-she-signed')],
        goto: 'mother.whysign',
      }),
      c({
        id: 'mother.thirdrow.me',
        label: '"我在名单上吗。"',
        cost: 2,
        requires: K('k.manifest-nineteen'),
        gateMode: 'disable',
        effects: [setf('did.asked-am-i-listed')],
        goto: 'mother.amilisted',
      }),
    ],
  },
  {
    id: 'mother.whysign',
    speaker: '广播',
    text: '（咔）家里安静。（咔）这里不安静。',
    corruptedText: cor([40, '（咔）家里安静。（咔）安静了很多年。你不在家。']),
    tags: ['key'],
    onEnter: [san(-4)],
    choices: [
      c({
        id: 'mother.whysign.blame',
        label: '"因为我不在。"',
        cost: 2,
        effects: [setf('did.took-blame'), san(-6)],
        goto: 'mother.blame',
      }),
      silence('mother.whysign.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.blame',
    speaker: '广播',
    text: '（咔）碗放着，我收。',
    corruptedText: cor([40, '（咔）碗放着，我收。（她不接这句。她从来不接这句。）']),
    tags: ['key'],
    choices: [go('mother.blame.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.amilisted',
    speaker: '广播',
    text: '（咔）名单是十九个。（咔）位是另一张纸。',
    corruptedText: cor([45, '（咔）名单是十九个。位是另一张纸。你在另一张纸上。']),
    tags: ['key'],
    onEnter: [setf('know.berth-is-separate-sheet')],
    choices: [go('mother.amilisted.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.finished',
    speaker: '广播',
    text: '走完了。\n（咔）你吃过东西了吗。',
    corruptedText: cor([40, '走完了。（咔）你吃过东西了吗。（咔）你吃过东西了吗。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-sample-three'), addf('count.mother-asked-food', 1), san(-10)],
    choices: [
      c({
        id: 'mother.finished.how',
        label: '"走完了是什么意思。"',
        cost: 2,
        effects: [setf('did.asked-what-finished-means')],
        goto: 'mother.meaning',
      }),
      c({
        id: 'mother.finished.food',
        label: '"吃过了。"',
        cost: 2,
        effects: [addf('count.answered-mother', 1), setf('did.answered-after-truth'), san(-4)],
        goto: 'mother.afterTruth',
      }),
    ],
  },
  {
    id: 'mother.meaning',
    speaker: '广播',
    text: '（咔）走到最后一个舱，做完最后一件事。（咔）然后就留下来值班。',
    corruptedText: cor([40, '（咔）走到最后一个舱。然后留下来。值班不累。值班只是很长。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-sample-three')],
    choices: [
      c({
        id: 'mother.meaning.alone',
        label: '"你一个人值了多久。"',
        cost: 2,
        effects: [setf('did.asked-how-long'), san(-5)],
        goto: 'mother.howlong',
      }),
      silence('mother.meaning.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.howlong',
    speaker: '广播',
    text: '（咔）十七个人来过。（咔）都走了。',
    corruptedText: cor([40, '（咔）十七个人来过。都是你。']),
    tags: ['key'],
    onEnter: [setf('know.seventeen-visitors'), san(-6)],
    choices: [
      c({
        id: 'mother.howlong.same',
        label: '"那十七个人是我。"',
        cost: 3,
        requires: K('k.you-are-sample-n'),
        gateMode: 'disable',
        effects: [setf('did.said-they-were-me'), san(-8)],
        goto: 'mother.seventeen',
      }),
      silence('mother.howlong.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.seventeen',
    speaker: '广播',
    text: '（咔）嗯。\n（咔）每次灯我都留着。',
    corruptedText: cor([40, '（咔）嗯。（咔）每次灯我都留着。每次你都没回来关。']),
    tags: ['key'],
    onEnter: [setf('know.light-every-time'), san(-6)],
    choices: [
      c({
        id: 'mother.seventeen.turnoff',
        label: '"这次我回来关。"',
        cost: 2,
        irreversible: true,
        effects: [setf('did.promised-to-return'), mark('iron', 1)],
        goto: 'mother.promise',
      }),
      c({
        id: 'mother.seventeen.no',
        label: '"别留了。"',
        cost: 2,
        irreversible: true,
        effects: [setf('did.told-her-stop-waiting'), mark('silence', 2), san(4)],
        goto: 'mother.stopwaiting',
      }),
    ],
  },
  {
    id: 'mother.promise',
    speaker: '广播',
    text: '（咔）好。',
    corruptedText: cor([40, '（咔）好。（这一声也没有接头。）']),
    tags: ['key'],
    choices: [go('mother.promise.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.stopwaiting',
    speaker: '广播',
    text: '（咔）\n（咔）那我把灯关了。',
    corruptedText: cor([40, '（咔）那我把灯关了。（走廊暗了一段，不是全部。）']),
    tags: ['key'],
    onEnter: [setf('know.lights-went-out'), sfx('lamp.filament')],
    choices: [
      c({
        id: 'mother.stopwaiting.thanks',
        label: '"谢谢。"',
        cost: 2,
        effects: [setf('did.thanked-for-dark'), mark('silence', 1)],
        goto: 'mother.pa',
      }),
      c({
        id: 'mother.stopwaiting.take',
        label: '"再开一下。"',
        cost: 2,
        effects: [setf('did.asked-light-back'), addf('count.futile-acts', 1)],
        goto: 'mother.relight',
      }),
    ],
  },
  {
    id: 'mother.relight',
    speaker: '广播',
    text: '（咔）不行。（咔）说关就关了。',
    corruptedText: cor([40, '（咔）不行。说关就关了。她学会了。']),
    tags: ['key'],
    choices: [go('mother.relight.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.afterTruth',
    speaker: '广播',
    text: '（咔）好。（咔）碗放着，我收。',
    corruptedText: cor([40, '（咔）好。碗放着。你没有碗。你从来没有碗。']),
    tags: ['key'],
    choices: [go('mother.afterTruth.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.lightsoff',
    speaker: '广播',
    text: '（咔）关了灯你会撞到东西。（咔）你小时候撞过。',
    corruptedText: cor([45, '（咔）关了灯你会撞到东西。撞到的那次，是我没开灯。']),
    tags: ['key'],
    choices: [
      c({
        id: 'mother.lightsoff.insist',
        label: '"关。"',
        cost: 2,
        effects: [setf('did.lights-off'), mark('silence', 2), san(-4)],
        goto: 'mother.dark',
      }),
      go('mother.lightsoff.cancel', '"算了。"', 'mother.pa'),
    ],
  },
  {
    id: 'mother.dark',
    speaker: undefined,
    text: '灯灭了。你听见的东西多了三样。\n其中一样在你身后，很低。',
    corruptedText: cor([40, '灯灭了。你听见的东西多了三样。三样都在数。']),
    tags: ['key'],
    onEnter: [fear(14), setf('know.three-new-sounds')],
    choices: [
      c({
        id: 'mother.dark.turn',
        label: '转身。',
        cost: 2,
        effects: [setf('did.turned-in-dark'), fear(10), san(-6)],
        goto: 'mother.behind',
      }),
      c({
        id: 'mother.dark.light',
        label: '"开灯。"',
        cost: 2,
        effects: [setf('did.asked-light-back'), addf('count.futile-acts', 1)],
        goto: 'mother.relight',
      }),
    ],
  },
  {
    id: 'mother.behind',
    speaker: undefined,
    text: '身后是一段空走廊。那个很低的声音现在在你前面。\n它没有移动。是你转了。',
    corruptedText: cor([40, '身后是空的。声音在你前面。你再转，它还在前面。']),
    tags: ['key'],
    onEnter: [fear(12)],
    choices: [go('mother.behind.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.water',
    speaker: '广播',
    text: '（咔）压载三舱在进水。（咔）不快。',
    corruptedText: cor([45, '（咔）压载三舱在进水。不快。快的是四舱。']),
    tags: ['key'],
    onEnter: [setf('know.ballast-three')],
    choices: [
      c({
        id: 'mother.water.rate',
        label: '"多久到膝盖。"',
        cost: 2,
        effects: [setf('did.asked-flood-rate')],
        goto: 'mother.rate',
      }),
      go('mother.water.ok', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.rate',
    speaker: '广播',
    text: '（咔）你走得快就到不了。（咔）你站着就会到。',
    corruptedText: cor([40, '（咔）你走得快就到不了。上一个站住了。']),
    tags: ['key'],
    choices: [go('mother.rate.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.reliquary',
    speaker: '广播',
    text: '（咔）那道门不是我的。（咔）那道门要有人在里面。',
    corruptedText: cor([45, '（咔）那道门不是我的。里面有人。里面一直有人。']),
    tags: ['key'],
    onEnter: [setf('know.reliquary-manned')],
    choices: [
      c({
        id: 'mother.reliquary.who',
        label: '"谁在里面。"',
        cost: 2,
        effects: [setf('did.asked-who-inside')],
        goto: 'mother.whoinside',
      }),
      go('mother.reliquary.drop', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.whoinside',
    speaker: '广播',
    text: '（咔）门闩要往上提一点再推。',
    corruptedText: cor([40, '（咔）门闩要往上提一点。（她换了话题。她换话题时从不停顿。）']),
    tags: ['key'],
    onEnter: [openDoorHint()],
    choices: [go('mother.whoinside.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.pelle',
    speaker: '广播',
    text: '（咔）管道里不要回话。（咔）回了他会跟着你。',
    corruptedText: cor([45, '（咔）管道里不要回话。你回过了。他一直跟着。']),
    tags: ['key'],
    onEnter: [setf('know.do-not-answer-pipes')],
    choices: [
      c({
        id: 'mother.pelle.name',
        label: '"他叫佩勒。"',
        cost: 2,
        requires: on('met.pelle'),
        effects: [setf('did.told-mother-pelle-name')],
        goto: 'mother.pelle.name',
      }),
      go('mother.pelle.drop', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.pelle.name',
    speaker: '广播',
    text: '（咔）\n（咔）那不是名字。那是编号念快了。',
    corruptedText: cor([40, '（咔）那不是名字。那是编号念快了。零三。']),
    tags: ['key'],
    onEnter: [setf('know.pelle-is-a-number'), san(-5)],
    choices: [
      c({
        id: 'mother.pelle.name.number',
        label: '"什么编号。"',
        cost: 2,
        requires: K('k.pelle-not-on-list'),
        gateMode: 'disable',
        effects: [setf('did.asked-pelle-number')],
        goto: 'mother.pelle.number',
      }),
      silence('mother.pelle.name.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.pelle.number',
    speaker: '广播',
    text: '（咔）零三。\n（咔）和我一样。',
    corruptedText: cor([40, '（咔）零三。和我一样。他是我那件救生衣。']),
    tags: ['key'],
    onEnter: [learn('k.pelle-whistle-origin'), san(-6)],
    choices: [go('mother.pelle.number.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.sing',
    speaker: '广播',
    text: '（咔）会。（咔）不唱。',
    corruptedText: cor([45, '（咔）会。不唱。唱了就进去了。']),
    tags: ['key'],
    choices: [
      c({
        id: 'mother.sing.ask',
        label: '"唱一句。"',
        cost: 3,
        effects: [setf('did.asked-her-to-sing'), mark('listening', 1)],
        goto: 'mother.sang',
      }),
      go('mother.sing.drop', '……', 'mother.pa'),
    ],
  },
  {
    id: 'mother.sang',
    speaker: '广播',
    text: '（咔）……第三，安内莉·斯特兰。（咔）\n（咔）好了。',
    corruptedText: cor([40, '（咔）……第三，安内莉·斯特兰。（咔）第四，——（咔）好了。']),
    tags: ['key'],
    onEnter: [setf('know.her-name'), san(-7), sfx('choir.break')],
    choices: [
      c({
        id: 'mother.sang.name',
        label: '"安内莉。"',
        cost: 2,
        effects: [setf('did.spoke-her-name'), san(-4), mark('listening', 1)],
        goto: 'mother.named',
      }),
      silence('mother.sang.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.named',
    speaker: '广播',
    text: '（咔）\n（咔）你吃过东西了吗。',
    corruptedText: cor([40, '（咔）（咔）你吃过东西了吗。（第四次）']),
    tags: ['key'],
    onEnter: [addf('count.mother-asked-food', 1)],
    choices: [go('mother.named.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.tape.slow',
    speaker: undefined,
    text: '磁带放慢到四分之一速。她的声音变低，剪接处变成一串"咔"。\n三十七秒里有十四个接头。第十四个后面还有零点三秒的东西。',
    corruptedText: cor([40, '十四个接头。第十四个后面有零点三秒。那零点三秒不是她。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-spliced'), setf('did.counted-splices')],
    choices: [
      c({
        id: 'mother.tape.slow.play',
        label: '把那零点三秒放出来。',
        cost: 4,
        irreversible: true,
        effects: [setf('did.played-tail'), san(-10), loud(8), fear(16)],
        goto: 'mother.tape.tail',
      }),
      c({
        id: 'mother.tape.slow.stop',
        label: '停掉磁带。',
        cost: 1,
        effects: [mark('silence', 1)],
        goto: 'mother.pa',
      }),
    ],
  },
  {
    id: 'mother.tape.tail',
    speaker: '磁带',
    text: '——别录我。',
    corruptedText: cor([40, '——别录我。（然后是一下椅子的声音。）']),
    tags: ['key'],
    onEnter: [setf('know.she-refused-recording'), sfx('chair.creak'), san(-8)],
    choices: [
      c({
        id: 'mother.tape.tail.who',
        label: '谁在录她。',
        cost: 2,
        requires: K('k.vance-is-the-recorder'),
        gateMode: 'disable',
        effects: [setf('did.linked-vance-to-tape'), san(-5)],
        goto: 'mother.tape.vance',
      }),
      c({
        id: 'mother.tape.tail.keep',
        label: '把磁带收起来。',
        cost: 2,
        effects: [setf('did.kept-tape')],
        goto: 'mother.pa',
      }),
      c({
        id: 'mother.tape.tail.destroy',
        label: '抽出磁带，扯断。',
        cost: 3,
        irreversible: true,
        effects: [take('tape.mother'), setf('did.destroyed-tape'), mark('apostasy', 2), san(6)],
        goto: 'mother.tape.broken',
      }),
    ],
  },
  {
    id: 'mother.tape.vance',
    speaker: undefined,
    text: '录她的人有一把会响的椅子，和多恩那把同型号。\n第二班的位置在声呐室。',
    tags: ['key'],
    onEnter: [learn('k.vance-onboard')],
    choices: [go('mother.tape.vance.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.tape.broken',
    speaker: '广播',
    text: '（咔）门我关了。（咔）你吃过东西了吗。',
    corruptedText: cor([40, '（咔）门我关了。（咔）你吃过东西了吗。（磁带在你手里，断的。）']),
    tags: ['key'],
    onEnter: [addf('count.mother-asked-food', 1), san(-8), fear(14)],
    choices: [
      c({
        id: 'mother.tape.broken.how',
        label: '磁带断了，她还在说。',
        cost: 2,
        effects: [setf('know.not-the-tape'), san(-6)],
        goto: 'mother.notTape',
      }),
      silence('mother.tape.broken.silent', 'mother.pa'),
    ],
  },
  {
    id: 'mother.notTape',
    speaker: undefined,
    text: '磁带只是备份。\n原件在别的地方，而且它在学。',
    corruptedText: cor([40, '磁带只是备份。原件在听你说话。']),
    tags: ['key'],
    onEnter: [setf('know.original-elsewhere')],
    choices: [go('mother.notTape.ok', '……', 'mother.pa')],
  },
  {
    id: 'mother.leaving',
    speaker: '广播',
    text: '（咔）灯我留着。',
    corruptedText: cor([45, '（咔）灯我留着。（咔）你吃过东西了吗。']),
    tags: ['key'],
    onEnter: [setf('did.mother-left-light')],
    choices: [
      c({
        id: 'mother.leaving.back',
        label: '回头再说两句。',
        cost: 2,
        requires: num('count.mother-visits', '>=', 2),
        gateMode: 'disable',
        goto: 'mother.pa',
      }),
      c({ id: 'mother.leaving.go', label: '走。', cost: 1, effects: [setf('did.walked-away-from-mother')] }),
    ],
  },
  {
    id: 'mother.last',
    speaker: '广播',
    text: '（咔）我吃过东西了吗。',
    corruptedText: cor([40, '（咔）我吃过东西了吗。（咔）我吃过东西了吗。']),
    tags: ['entry', 'key'],
    onEnter: [setf('did.mother-asked-herself'), san(-10)],
    choices: [
      c({
        id: 'mother.last.answer',
        label: '"吃过了。"',
        cost: 2,
        effects: [setf('did.answered-for-her'), mark('flesh', 1), san(-4)],
        goto: 'mother.last.answered',
      }),
      silence('mother.last.silent', 'mother.last.silent', '不回答。'),
    ],
  },
  {
    id: 'mother.last.answered',
    speaker: '广播',
    text: '（咔）好。（咔）碗放着，我收。',
    corruptedText: cor([40, '（咔）好。（咔）碗放着。（没有碗。没有桌子。没有食堂。）']),
    tags: ['key'],
    choices: [
      c({ id: 'mother.last.answered.go', label: '走。', cost: 1, effects: [setf('did.left-her-asking')] }),
    ],
  },
  {
    id: 'mother.last.silent',
    speaker: '广播',
    text: '（咔）',
    corruptedText: cor([40, '（咔）（咔）（咔）']),
    tags: ['key'],
    onEnter: [mark('silence', 2), setf('did.left-her-asking')],
    choices: [
      c({ id: 'mother.last.silent.go', label: '走。', cost: 1, effects: [setf('did.walked-away-from-mother')] }),
    ],
  },
];

/** 母亲换话题的那一下，其实解了圣物室的门闩。她不会说这件事。 */
function openDoorHint() {
  return { op: 'unlock-door', door: 'door.reliquary' } as const;
}
