/**
 * 多恩 DORN —— 大副。活着。被绑在指挥层的椅子上。
 *
 * 核心张力（GDD §7.2）：是他绑的自己，还是别人绑的。
 *
 * 剧作位置：他是全剧唯一的**盟友**，也是执行 Truby 步骤 13「盟友的攻击」的人。
 * 他会当面说出玩家的道德弱点："你不是想解开我。你是想问我。"
 * 他同时执行契诃夫 C5：把自己和玩家并列为同一种失败——
 * "你和我一样，都想知道。区别是我坐下来了。"
 *
 * 他的口头禅是「别解。」他从不解释为什么。
 * 他要求玩家做的事全是家务：报水位、把帽子捡起来、把窗关上。
 * 他不说的话：名单第十四行姓多恩。
 */

import type { NarrativeNode } from '../../core/contract';
import {
  addf,
  all,
  any,
  c,
  cor,
  fear,
  give,
  go,
  item,
  K,
  learn,
  loud,
  mark,
  noK,
  num,
  off,
  on,
  san,
  setf,
  sfx,
  silence,
  take,
} from '../../narrative/dsl';

export const DORN_NODES: readonly NarrativeNode[] = [
  {
    id: 'dorn.first',
    speaker: '多恩',
    text: '别解。',
    corruptedText: cor(
      [50, '别解。（他的嘴没有动）'],
      [22, '别解。别解。别解。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('met.dorn'), addf('count.dorn-talks', 1), sfx('chair.creak')],
    choices: [
      c({
        id: 'dorn.first.why',
        label: '"为什么。"',
        cost: 2,
        effects: [setf('did.asked-dorn-why')],
        goto: 'dorn.why',
      }),
      c({
        id: 'dorn.first.untie',
        label: '动手解。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.untied-dorn'), loud(8), mark('flesh', 1)],
        goto: 'dorn.untied',
      }),
      c({
        id: 'dorn.first.look',
        label: '先看绳子。',
        cost: 3,
        effects: [setf('did.checked-knot')],
        goto: 'dorn.knot',
      }),
      silence('dorn.first.silent', 'dorn.silence'),
    ],
  },
  {
    id: 'dorn.why',
    speaker: '多恩',
    text: '水位。\n报一下。',
    corruptedText: cor([45, '水位。报一下。（他没有看水，他在看你。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.why.report',
        label: '报水位。',
        cost: 2,
        effects: [setf('did.reported-water'), addf('count.reports-to-dorn', 1)],
        goto: 'dorn.water',
      }),
      c({
        id: 'dorn.why.again',
        label: '"我问你为什么。"',
        cost: 2,
        effects: [setf('did.repeated-question')],
        goto: 'dorn.why2',
      }),
    ],
  },
  {
    id: 'dorn.water',
    speaker: '多恩',
    text: '比上次高两公分。\n［停顿］上次是你报的。',
    corruptedText: cor([45, '比上次高两公分。上次也是你报的。上上次也是。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-remembers-report')],
    choices: [
      c({
        id: 'dorn.water.lasttime',
        label: '"我没有报过。"',
        cost: 2,
        effects: [setf('did.denied-reporting')],
        goto: 'dorn.denied',
      }),
      go('dorn.water.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.denied',
    speaker: '多恩',
    text: '嗯。\n［停顿］那就是我记错了。',
    corruptedText: cor([40, '嗯。那就是我记错了。（他没有记错。他在放你一马。）']),
    tags: ['key'],
    onEnter: [setf('know.dorn-let-it-go')],
    choices: [go('dorn.denied.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.why2',
    speaker: '多恩',
    text: '因为解开以后我要站起来。\n［停顿］站起来以后我会往下走。',
    corruptedText: cor([45, '因为解开以后我会往下走。我很想往下走。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-wants-down')],
    choices: [
      c({
        id: 'dorn.why2.down',
        label: '"往下走有什么。"',
        cost: 2,
        effects: [setf('did.asked-what-below')],
        goto: 'dorn.below',
      }),
      go('dorn.why2.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.below',
    speaker: '多恩',
    text: '月池。\n［停顿］没有什么。就是很想去。',
    corruptedText: cor([45, '月池。没有什么。就是很想去。想得牙疼。']),
    tags: ['key'],
    onEnter: [setf('know.moonpool-pull')],
    choices: [
      c({
        id: 'dorn.below.same',
        label: '"我也想。"',
        cost: 2,
        effects: [setf('did.admitted-pull'), mark('listening', 1), san(-3)],
        goto: 'dorn.sameAs',
      }),
      c({
        id: 'dorn.below.no',
        label: '"我不想。"',
        cost: 2,
        effects: [setf('did.denied-pull'), mark('silence', 1)],
        goto: 'dorn.notyet',
      }),
    ],
  },
  {
    id: 'dorn.sameAs',
    speaker: '多恩',
    text: '嗯。\n［停顿］这一带从前只有两个还算清楚的人。现在是一个半。',
    corruptedText: cor([40, '嗯。［停顿］两个。一个坐着，一个在走。走的那个更糟。']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.sameAs.half',
        label: '"哪个是半个。"',
        cost: 2,
        effects: [setf('did.asked-which-half')],
        goto: 'dorn.half',
      }),
      go('dorn.sameAs.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.half',
    speaker: '多恩',
    text: '坐着的。\n［停顿］站着的那个还不知道自己是谁，所以还算整个。',
    corruptedText: cor([40, '坐着的。站着的那个还不知道自己是谁。这是你唯一的优势。']),
    tags: ['key'],
    choices: [go('dorn.half.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.notyet',
    speaker: '多恩',
    text: '还没到。\n［停顿］水位。报一下。',
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.notyet.report',
        label: '报水位。',
        cost: 2,
        effects: [addf('count.reports-to-dorn', 1), setf('did.reported-water')],
        goto: 'dorn.chair',
      }),
      go('dorn.notyet.no', '不报。', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.knot',
    speaker: undefined,
    text: '绳子绕过椅背，两道，交叉。结在他右手边，离他的手指八公分。\n收尾那个结的绳头上有牙印。',
    corruptedText: cor([45, '结在他右手边。绳头上有牙印。牙印的间距和你的一样。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-tied-himself'), setf('did.checked-knot')],
    choices: [
      c({
        id: 'dorn.knot.say',
        label: '"你自己绑的。"',
        cost: 2,
        effects: [setf('did.said-self-tied')],
        goto: 'dorn.selfTied',
      }),
      c({
        id: 'dorn.knot.teeth',
        label: '看牙印。',
        cost: 2,
        effects: [setf('did.examined-teeth-marks'), san(-4)],
        goto: 'dorn.teeth',
      }),
      go('dorn.knot.back', '不说。', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.selfTied',
    speaker: '多恩',
    text: '嗯。\n［停顿］别解。',
    corruptedText: cor([40, '嗯。别解。这次别解。']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.selfTied.help',
        label: '"我可以帮你绑紧一点。"',
        cost: 4,
        effects: [setf('did.tightened-ropes'), mark('iron', 1), san(-3), sfx('rope.strain')],
        goto: 'dorn.tightened',
      }),
      go('dorn.selfTied.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.tightened',
    speaker: '多恩',
    text: '谢谢。\n［停顿］你是第一个帮我绑的。',
    corruptedText: cor([40, '谢谢。你是第一个帮我绑的。前面几个都解了。']),
    tags: ['key'],
    onEnter: [setf('know.first-to-tighten')],
    choices: [
      c({
        id: 'dorn.tightened.before',
        label: '"前面几个。"',
        cost: 2,
        effects: [setf('did.caught-previous-ones')],
        goto: 'dorn.previous',
      }),
      go('dorn.tightened.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.teeth',
    speaker: undefined,
    text: '牙印在绳头上，很深，咬穿了麻。\n咬的时候他一定在用力，因为绳头是斜的。',
    corruptedText: cor([40, '牙印很深。斜的。你的门牙有一个缺口，形状对得上。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-tied-himself')],
    choices: [
      c({
        id: 'dorn.teeth.mine',
        label: '和自己的牙比一下。',
        cost: 3,
        requires: item('mirror'),
        gateMode: 'lie',
        effects: [setf('did.compared-teeth'), san(-8)],
        goto: 'dorn.teeth.match',
      }),
      go('dorn.teeth.back', '不比。', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.teeth.match',
    speaker: undefined,
    text: '对得上。\n这说明的事情有两种，你希望是第一种。',
    corruptedText: cor([40, '对得上。有两种可能。你已经知道是哪一种了。']),
    tags: ['key'],
    onEnter: [san(-8), setf('know.teeth-match')],
    choices: [go('dorn.teeth.match.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.untied',
    speaker: '多恩',
    text: '［停顿］\n把帽子捡起来。',
    corruptedText: cor([45, '［停顿］把帽子捡起来。（他没有站起来。他在等你先动。）']),
    tags: ['key'],
    onEnter: [setf('did.untied-dorn'), sfx('rope.strain')],
    choices: [
      c({
        id: 'dorn.untied.cap',
        label: '捡帽子。',
        cost: 2,
        effects: [setf('did.picked-up-cap')],
        goto: 'dorn.cap',
      }),
      c({
        id: 'dorn.untied.retie',
        label: '重新绑上。',
        cost: 6,
        effects: [setf('did.retied-dorn'), mark('iron', 1), san(-4)],
        goto: 'dorn.retied',
      }),
      c({
        id: 'dorn.untied.watch',
        label: '站着不动，看他会不会走。',
        cost: 8,
        effects: [setf('did.watched-dorn'), san(-5)],
        goto: 'dorn.watched',
      }),
    ],
  },
  {
    id: 'dorn.cap',
    speaker: '多恩',
    text: '放桌上。\n［停顿］好。现在你出去，把门关上。',
    corruptedText: cor([45, '放桌上。现在你出去，把门关上。［停顿］快。']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.cap.close',
        label: '出去，关门。',
        cost: 3,
        effects: [setf('did.closed-dorn-door'), mark('silence', 1)],
        goto: 'dorn.doorClosed',
      }),
      c({
        id: 'dorn.cap.stay',
        label: '不出去。',
        cost: 2,
        effects: [setf('did.stayed-with-dorn')],
        goto: 'dorn.stayed',
      }),
    ],
  },
  {
    id: 'dorn.doorClosed',
    speaker: undefined,
    text: '门关上以后，里面有绳子的声音，很短。\n再推门，他坐着，绑着。结在右手边，离手指八公分。',
    corruptedText: cor([40, '门关上以后有绳子的声音。再推门，他坐着，绑着。牙印是新的。']),
    tags: ['key'],
    onEnter: [san(-6), setf('know.he-retied-himself'), learn('k.dorn-tied-himself')],
    choices: [go('dorn.doorClosed.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.stayed',
    speaker: '多恩',
    text: '［停顿］\n那你得看着。看完别说出去。',
    corruptedText: cor([40, '［停顿］那你得看着。看完别说出去。你上次说了。']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.stayed.watch',
        label: '看。',
        cost: 10,
        effects: [setf('did.watched-him-retie'), san(-10), fear(12)],
        goto: 'dorn.retieSelf',
      }),
      c({
        id: 'dorn.stayed.leave',
        label: '走开。',
        cost: 2,
        effects: [mark('silence', 1), setf('did.looked-away')],
        goto: 'dorn.chair',
      }),
    ],
  },
  {
    id: 'dorn.retieSelf',
    speaker: undefined,
    text: '他绕了两道，交叉，然后用牙把绳头咬紧。\n全程没有看你。最后一下咬得很深。',
    corruptedText: cor([40, '他绕了两道，交叉，咬紧。全程没有看你。他做过很多次。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-tied-himself'), setf('know.watched-the-whole-thing')],
    choices: [
      c({
        id: 'dorn.retieSelf.why',
        label: '"为什么一定要绑着。"',
        cost: 2,
        effects: [setf('did.asked-why-bound')],
        goto: 'dorn.whyBound',
      }),
      silence('dorn.retieSelf.silent', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.whyBound',
    speaker: '多恩',
    text: '因为我做不到不去。\n［停顿］绑着能做到。',
    corruptedText: cor([40, '因为我做不到不去。绑着能做到。这是我唯一做到过的事。']),
    tags: ['key'],
    onEnter: [setf('know.binding-is-his-only-act')],
    choices: [
      c({
        id: 'dorn.whyBound.mirror',
        label: '"那我呢。"',
        cost: 2,
        effects: [setf('did.asked-about-myself')],
        goto: 'dorn.aboutYou',
      }),
      go('dorn.whyBound.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.aboutYou',
    speaker: '多恩',
    text: '你还在走，所以你还没到那一步。\n［停顿］到了你就知道椅子的好处了。',
    corruptedText: cor([40, '你还在走。到了你就知道椅子的好处了。椅子是我给你留的。']),
    tags: ['key'],
    choices: [go('dorn.aboutYou.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.retied',
    speaker: '多恩',
    text: '紧一点。\n［停顿］再紧一点。',
    corruptedText: cor([40, '紧一点。再紧一点。别问我为什么，你知道为什么。']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.retied.tighter',
        label: '再紧。',
        cost: 4,
        effects: [setf('did.tightened-ropes'), mark('iron', 1), sfx('rope.strain'), san(-3)],
        goto: 'dorn.tightened',
      }),
      go('dorn.retied.enough', '够了。', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.watched',
    speaker: '多恩',
    text: '［停顿］\n［停顿］你不是想解开我。',
    corruptedText: cor([40, '［停顿］你不是想解开我。你想看我走。']),
    tags: ['key'],
    onEnter: [setf('did.dorn-called-it-out')],
    choices: [
      c({
        id: 'dorn.watched.what',
        label: '"那我想干什么。"',
        cost: 2,
        effects: [setf('did.asked-what-i-want')],
        goto: 'dorn.attack',
      }),
      silence('dorn.watched.silent', 'dorn.attack'),
    ],
  },

  // Truby 步骤 13：盟友的攻击。他说的每一句都是对的，玩家会当场合理化。
  {
    id: 'dorn.attack',
    speaker: '多恩',
    text: '你想问我。\n［停顿］从进门到现在，你问了六句，帮了半件事。',
    corruptedText: cor([40, '你想问我。你问了六句。上一个问了十一句。他走得比你远。']),
    tags: ['key'],
    onEnter: [setf('did.received-dorn-attack'), san(-5)],
    choices: [
      c({
        id: 'dorn.attack.justify',
        label: '"我得先搞清楚状况。"',
        cost: 2,
        effects: [setf('did.rationalized'), addf('count.rationalizations', 1)],
        goto: 'dorn.rationalized',
      }),
      c({
        id: 'dorn.attack.admit',
        label: '"是。"',
        cost: 2,
        effects: [setf('did.admitted-using-him'), san(4), mark('apostasy', 1)],
        goto: 'dorn.admitted',
      }),
      c({
        id: 'dorn.attack.help',
        label: '"你要什么。我去拿。"',
        cost: 3,
        effects: [setf('did.offered-help'), addf('count.selfless-acts', 1)],
        goto: 'dorn.wants',
      }),
    ],
  },
  {
    id: 'dorn.rationalized',
    speaker: '多恩',
    text: '嗯。\n［停顿］我也这么说过。',
    corruptedText: cor([40, '嗯。我也这么说过。说完就坐下来了。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-said-same')],
    choices: [go('dorn.rationalized.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.admitted',
    speaker: '多恩',
    text: '好。\n［停顿］那你问吧。省点力气，别绕。',
    corruptedText: cor([40, '好。那你问吧。别绕。你的氧气比我的时间少。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-opened-up'), san(4)],
    choices: [go('dorn.admitted.ok', '问。', 'dorn.chair')],
  },
  {
    id: 'dorn.wants',
    speaker: '多恩',
    text: '把观测窗的盖板放下来。\n［停顿］不是为我。为你。',
    corruptedText: cor([45, '把观测窗的盖板放下来。不是为我。窗外面有东西在等你看它。']),
    tags: ['key'],
    onEnter: [setf('know.window-task')],
    choices: [
      c({
        id: 'dorn.wants.do',
        label: '去放盖板。',
        cost: 6,
        effects: [setf('did.closed-porthole'), mark('silence', 2), addf('count.selfless-acts', 1), san(5)],
        goto: 'dorn.windowClosed',
      }),
      c({
        id: 'dorn.wants.look',
        label: '先看一眼窗外。',
        cost: 4,
        irreversible: true,
        effects: [setf('did.looked-outside'), san(-14), fear(20), mark('listening', 2)],
        goto: 'dorn.looked',
      }),
      go('dorn.wants.refuse', '"不去。"', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.windowClosed',
    speaker: '多恩',
    text: '好。\n［停顿］现在这条船上有一件事是你做完的。',
    corruptedText: cor([40, '好。现在有一件事是你做完的。记住这个感觉。你会很久没有它。']),
    tags: ['key'],
    onEnter: [setf('know.one-thing-done'), san(4)],
    choices: [go('dorn.windowClosed.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.looked',
    speaker: undefined,
    text: '窗外不是水。\n是一个很大的东西的一小块，而那一小块是静止的。',
    corruptedText: cor(
      [45, '窗外不是水。是一小块静止的东西。你看它的时候它也不动。这就是最坏的部分。'],
      [20, '窗外是舱内。你在窗的另一边，正在往里看。'],
    ),
    tags: ['key'],
    onEnter: [san(-14), fear(20), setf('know.saw-outside')],
    choices: [
      c({
        id: 'dorn.looked.close',
        label: '放下盖板。',
        cost: 4,
        effects: [setf('did.closed-porthole'), mark('silence', 1)],
        goto: 'dorn.windowClosed',
      }),
      c({
        id: 'dorn.looked.longer',
        label: '再看一会儿。',
        cost: 8,
        irreversible: true,
        effects: [setf('did.stared-outside'), san(-16), mark('listening', 3), addf('count.staring', 1)],
        goto: 'dorn.stared',
      }),
    ],
  },
  {
    id: 'dorn.stared',
    speaker: undefined,
    text: '看久了以后，它的边缘和舱壁的边缘对齐了。\n你分不出哪边是船。',
    corruptedText: cor([40, '它的边缘和舱壁对齐了。船在里面。']),
    tags: ['key'],
    onEnter: [san(-10), setf('know.edges-aligned')],
    choices: [
      c({
        id: 'dorn.stared.back',
        label: '退开。',
        cost: 3,
        effects: [setf('did.stepped-back'), fear(8)],
        goto: 'dorn.chair',
      }),
    ],
  },

  // -------------------------------------------------------------------------
  // 椅子旁的中枢
  // -------------------------------------------------------------------------
  {
    id: 'dorn.chair',
    speaker: '多恩',
    text: '水位。报一下。',
    corruptedText: cor(
      [50, '水位。报一下。（他每次都先问这个。他是在确认你还会算数。）'],
      [22, '水位。报一下。（椅子上没有人。声音在椅子里。）'],
    ),
    tags: ['entry', 'hub', 'key'],
    onEnter: [addf('count.dorn-talks', 1), sfx('chair.creak')],
    choices: [
      c({
        id: 'dorn.chair.report',
        label: '报水位。',
        cost: 2,
        effects: [addf('count.reports-to-dorn', 1), setf('did.reported-water')],
        goto: 'dorn.reported',
      }),
      c({
        id: 'dorn.chair.ship',
        label: '"这条船是干什么的。"',
        cost: 2,
        effects: [setf('did.asked-dorn-ship')],
        goto: 'dorn.ship',
      }),
      c({
        id: 'dorn.chair.crew',
        label: '"人都去哪了。"',
        cost: 2,
        effects: [setf('did.asked-dorn-crew')],
        goto: 'dorn.crew',
      }),
      c({
        id: 'dorn.chair.count',
        label: '"我是第几个。"',
        cost: 3,
        requires: all(K('k.dorn-tied-himself'), K('k.your-bunk')),
        gateMode: 'disable',
        effects: [setf('did.asked-my-number')],
        goto: 'dorn.number',
      }),
      c({
        id: 'dorn.chair.fourteen',
        label: '"名单第十四行姓多恩。"',
        cost: 3,
        requires: K('k.manifest-nineteen'),
        gateMode: 'hide',
        effects: [setf('did.mentioned-fourteenth')],
        goto: 'dorn.fourteen',
      }),
      c({
        id: 'dorn.chair.vance',
        label: '"万斯说他在声呐室。"',
        cost: 2,
        requires: on('know.vance-location'),
        gateMode: 'hide',
        effects: [setf('did.told-dorn-vance')],
        goto: 'dorn.vance',
      }),
      c({
        id: 'dorn.chair.water',
        label: '给他喂水。',
        cost: 4,
        effects: [setf('did.gave-dorn-water'), addf('count.selfless-acts', 1), san(3)],
        goto: 'dorn.drink',
      }),
      c({
        id: 'dorn.chair.cut',
        label: '割断绳子。',
        cost: 4,
        requires: item('scalpel'),
        gateMode: 'disable',
        irreversible: true,
        effects: [setf('did.cut-dorn-ropes'), mark('flesh', 1), loud(6)],
        goto: 'dorn.cut',
      }),
      c({
        id: 'dorn.chair.kill',
        label: '让他别再等了。',
        cost: 8,
        requires: all(item('scalpel'), K('k.salvage-is-ritual')),
        gateMode: 'lie',
        irreversible: true,
        effects: [setf('did.killed-dorn'), mark('flesh', 3), san(-20), loud(20)],
        goto: 'dorn.killed',
      }),
      c({
        id: 'dorn.chair.teach',
        label: '"船在教我走路。"',
        cost: 3,
        requires: K('k.ship-is-teaching'),
        gateMode: 'disable',
        effects: [setf('did.told-dorn-teaching')],
        goto: 'dorn.teaching',
      }),
      c({
        id: 'dorn.chair.stop',
        label: '"差一笔的字不是字。"',
        cost: 3,
        requires: K('k.pen-can-stop'),
        gateMode: 'disable',
        effects: [setf('did.told-dorn-refusal')],
        goto: 'dorn.refusal',
      }),
      c({ id: 'dorn.chair.leave', label: '走。', cost: 1, goto: 'dorn.leaving' }),
    ],
  },
  {
    id: 'dorn.reported',
    speaker: '多恩',
    text: '记住这个数。\n［停顿］下次你还得报。',
    corruptedText: cor([40, '记住这个数。下次你还得报。数会变，你不会。']),
    tags: ['key'],
    choices: [go('dorn.reported.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.ship',
    speaker: '多恩',
    text: '听东西的。\n［停顿］听得很清楚。这是我们的问题。',
    corruptedText: cor([45, '听东西的。听得很清楚。清楚到我们都听懂了。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-confirms-listening')],
    choices: [
      c({
        id: 'dorn.ship.heard',
        label: '"你听见了什么。"',
        cost: 2,
        effects: [setf('did.asked-what-he-heard')],
        goto: 'dorn.heard',
      }),
      go('dorn.ship.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.heard',
    speaker: '多恩',
    text: '［停顿］\n水位。报一下。',
    corruptedText: cor([40, '［停顿］水位。报一下。（他答不了这个。没人答得了。）']),
    tags: ['key'],
    onEnter: [setf('know.dorn-cannot-answer')],
    choices: [
      c({
        id: 'dorn.heard.press',
        label: '"我问你听见了什么。"',
        cost: 3,
        effects: [addf('count.pressed-dorn', 1), setf('did.pressed-dorn')],
        goto: 'dorn.heard2',
      }),
      go('dorn.heard.report', '报水位。', 'dorn.reported'),
    ],
  },
  {
    id: 'dorn.heard2',
    speaker: '多恩',
    text: '我的名字。\n［停顿］念得比我自己念得准。',
    corruptedText: cor([40, '我的名字。念得比我自己念得准。还有一个名字，是你的。']),
    tags: ['key'],
    onEnter: [san(-6), setf('know.it-says-names')],
    choices: [
      c({
        id: 'dorn.heard2.mine',
        label: '"有我的吗。"',
        cost: 2,
        effects: [setf('did.asked-if-mine')],
        goto: 'dorn.mineToo',
      }),
      silence('dorn.heard2.silent', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.mineToo',
    speaker: '多恩',
    text: '有。\n［停顿］别答应。',
    corruptedText: cor([40, '有。别答应。你答应过。']),
    tags: ['key'],
    onEnter: [setf('know.do-not-answer')],
    choices: [go('dorn.mineToo.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.crew',
    speaker: '多恩',
    text: '礼拜堂六个。剩下的下去了。\n［停顿］"下去"不是往下走的意思。',
    corruptedText: cor([45, '礼拜堂六个。剩下的下去了。下去是一个动作，不是一个方向。']),
    tags: ['key'],
    onEnter: [setf('know.six-in-chapel')],
    choices: [
      c({
        id: 'dorn.crew.six',
        label: '"六个还在唱。"',
        cost: 2,
        requires: on('met.choir'),
        gateMode: 'hide',
        effects: [setf('did.told-dorn-choir')],
        goto: 'dorn.choir',
      }),
      go('dorn.crew.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.choir',
    speaker: '多恩',
    text: '还在唱就好。\n［停顿］停的时候你要跑。',
    corruptedText: cor([40, '还在唱就好。停的时候你要跑。上次你没跑。']),
    tags: ['key'],
    onEnter: [setf('know.run-when-they-stop')],
    choices: [go('dorn.choir.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.number',
    speaker: '多恩',
    text: '第十八。\n［停顿］别问我怎么数的。',
    corruptedText: cor(
      [45, '第十八。别问我怎么数的。我用绳子记，一道一个。'],
      [20, '第十八。（他的绳子上有十七道磨痕。第十八道是新的。）'],
    ),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-10), setf('know.i-am-eighteenth')],
    choices: [
      c({
        id: 'dorn.number.how',
        label: '"你怎么数的。"',
        cost: 2,
        effects: [setf('did.asked-how-he-counts')],
        goto: 'dorn.howCount',
      }),
      c({
        id: 'dorn.number.others',
        label: '"前面十七个呢。"',
        cost: 2,
        effects: [setf('did.asked-about-previous')],
        goto: 'dorn.previous',
      }),
      silence('dorn.number.silent', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.howCount',
    speaker: '多恩',
    text: '绳子上磨一道。\n［停顿］磨到第八道的时候我就不想数了。但手会自己磨。',
    corruptedText: cor([40, '绳子上磨一道。手会自己磨。手比我记得清楚。']),
    tags: ['key'],
    onEnter: [setf('know.rope-tally')],
    choices: [
      c({
        id: 'dorn.howCount.look',
        label: '数绳子上的磨痕。',
        cost: 4,
        effects: [setf('did.counted-rope-marks'), addf('count.breaths-counted', 17), san(-6)],
        goto: 'dorn.ropeMarks',
      }),
      go('dorn.howCount.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.ropeMarks',
    speaker: undefined,
    text: '十七道旧的，一道新的。新的那道还没磨到底。\n他在等这一轮结束。',
    corruptedText: cor([40, '十七道旧的，一道新的。新的那道在你看它的时候深了一点。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n')],
    choices: [go('dorn.ropeMarks.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.previous',
    speaker: '多恩',
    text: '有两个跟我说过话。\n［停顿］一个给我喂了水。一个把我的帽子放桌上了。',
    corruptedText: cor([40, '有两个跟我说过话。一个喂了水。一个放了帽子。你两个都做了。']),
    tags: ['key'],
    onEnter: [setf('know.two-were-kind')],
    choices: [
      c({
        id: 'dorn.previous.both',
        label: '"这两件我都做了。"',
        cost: 2,
        requires: all(on('did.gave-dorn-water'), on('did.picked-up-cap')),
        gateMode: 'hide',
        effects: [setf('did.realized-i-am-both'), san(-8)],
        goto: 'dorn.bothMe',
      }),
      silence('dorn.previous.silent', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.bothMe',
    speaker: '多恩',
    text: '嗯。\n［停顿］你们做的事越来越像。',
    corruptedText: cor([40, '嗯。你们做的事越来越像。这说明教得有效。']),
    tags: ['key'],
    onEnter: [learn('k.ship-is-teaching'), san(-6)],
    choices: [go('dorn.bothMe.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.fourteen',
    speaker: '多恩',
    text: '水位。报一下。',
    corruptedText: cor([45, '水位。报一下。（他的下巴在动，但不是在说话。）']),
    tags: ['key'],
    onEnter: [setf('did.dorn-dodged-daughter')],
    choices: [
      c({
        id: 'dorn.fourteen.again',
        label: '"第十四行。"',
        cost: 2,
        effects: [addf('count.pressed-dorn', 1)],
        goto: 'dorn.fourteen2',
      }),
      c({
        id: 'dorn.fourteen.report',
        label: '报水位。',
        cost: 2,
        effects: [addf('count.reports-to-dorn', 1), setf('did.respected-silence'), mark('silence', 1)],
        goto: 'dorn.respected',
      }),
    ],
  },
  {
    id: 'dorn.fourteen2',
    speaker: '多恩',
    text: '［停顿］她签在我前面。\n［停顿］水位。报一下。',
    corruptedText: cor([40, '［停顿］她签在我前面。我想拦，但我当时在写别的东西。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-daughter'), san(-6)],
    choices: [go('dorn.fourteen2.report', '报水位。', 'dorn.reported')],
  },
  {
    id: 'dorn.respected',
    speaker: '多恩',
    text: '谢谢。\n［停顿］这也是一件做完的事。',
    corruptedText: cor([40, '谢谢。这也是一件做完的事。没几个人给我留这个。']),
    tags: ['key'],
    onEnter: [san(4), setf('know.one-thing-done')],
    choices: [go('dorn.respected.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.vance',
    speaker: '多恩',
    text: '万斯不在声呐室。\n［停顿］万斯在椅子上。',
    corruptedText: cor([45, '万斯不在声呐室。万斯在椅子上。（他动了一下右手。）']),
    tags: ['key'],
    onEnter: [san(-8), fear(14), setf('know.vance-in-a-chair')],
    choices: [
      c({
        id: 'dorn.vance.which',
        label: '"哪把椅子。"',
        cost: 2,
        effects: [setf('did.asked-which-chair')],
        goto: 'dorn.whichChair',
      }),
      silence('dorn.vance.silent', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.whichChair',
    speaker: '多恩',
    text: '［停顿］\n水位。报一下。',
    corruptedText: cor([40, '［停顿］水位。报一下。（他的右手在绳子里动。绳子没有响。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.whichChair.name',
        label: '"你叫万斯。"',
        cost: 3,
        requires: all(K('k.vance-onboard'), on('did.heard-vance-chair')),
        gateMode: 'lie',
        effects: [setf('did.accused-dorn-of-being-vance'), san(-10)],
        goto: 'dorn.notVance',
      }),
      go('dorn.whichChair.report', '报水位。', 'dorn.reported'),
    ],
  },
  {
    id: 'dorn.notVance',
    speaker: '多恩',
    text: '不是。\n［停顿］我们同期。同期的人坐一样的椅子。',
    corruptedText: cor([40, '不是。我们同期。同期的人坐一样的椅子，说一样的话。']),
    tags: ['key'],
    onEnter: [setf('know.same-cohort')],
    choices: [go('dorn.notVance.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.drink',
    speaker: '多恩',
    text: '慢点。\n［停顿］够了。',
    corruptedText: cor([40, '慢点。够了。（他喝的时候闭着眼。这是他今天唯一闭眼的时候。）']),
    tags: ['key'],
    onEnter: [setf('did.gave-dorn-water'), san(3)],
    choices: [
      c({
        id: 'dorn.drink.more',
        label: '再喂一点。',
        cost: 3,
        effects: [addf('count.selfless-acts', 1), setf('did.fed-him-twice')],
        goto: 'dorn.drink2',
      }),
      go('dorn.drink.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.drink2',
    speaker: '多恩',
    text: '［停顿］上一个也喂了两次。\n［停顿］别解。',
    corruptedText: cor([40, '［停顿］上一个也喂了两次。你们连次数都一样。']),
    tags: ['key'],
    choices: [go('dorn.drink2.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.cut',
    speaker: '多恩',
    text: '［停顿］\n把刀给我。',
    corruptedText: cor([45, '［停顿］把刀给我。（他的手不是伸向刀。是伸向你。）']),
    tags: ['key'],
    onEnter: [sfx('rope.strain')],
    choices: [
      c({
        id: 'dorn.cut.give',
        label: '给他。',
        cost: 2,
        irreversible: true,
        effects: [take('scalpel'), setf('did.gave-dorn-knife'), mark('flesh', 1)],
        goto: 'dorn.knife',
      }),
      c({
        id: 'dorn.cut.keep',
        label: '不给。',
        cost: 2,
        effects: [setf('did.kept-knife'), mark('iron', 1)],
        goto: 'dorn.keptKnife',
      }),
    ],
  },
  {
    id: 'dorn.knife',
    speaker: undefined,
    text: '他用刀割了新的绳子，长度留得比原来短。\n然后自己绑回去，比原来紧。刀留在他手里。',
    corruptedText: cor([40, '他割了新绳子，绑得比原来紧。刀留在他手里。他会用它做一件事，但不是今天。']),
    tags: ['key'],
    onEnter: [setf('know.he-kept-the-knife'), san(-4)],
    choices: [go('dorn.knife.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.keptKnife',
    speaker: '多恩',
    text: '对。\n［停顿］别给任何人刀。包括你自己。',
    corruptedText: cor([40, '对。别给任何人刀。包括你自己。特别是你自己。']),
    tags: ['key'],
    onEnter: [setf('know.no-knives')],
    choices: [go('dorn.keptKnife.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.killed',
    speaker: undefined,
    text: '很快。他没有挣，也没有看你。\n最后那口气是往里吸的，不是往外呼的。',
    corruptedText: cor([40, '很快。最后那口气是往里吸的。船跟着吸了一下。']),
    tags: ['key'],
    onEnter: [san(-20), mark('flesh', 2), setf('know.dorn-dead'), sfx('silence.total')],
    choices: [
      c({
        id: 'dorn.killed.rope',
        label: '看绳子上的磨痕。',
        cost: 3,
        effects: [setf('did.counted-rope-marks'), san(-6)],
        goto: 'dorn.ropeMarks',
      }),
      c({
        id: 'dorn.killed.sit',
        label: '坐到椅子上。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.sat-in-chair'), mark('iron', 2), san(-10)],
        goto: 'dorn.sat',
      }),
    ],
  },
  {
    id: 'dorn.sat',
    speaker: undefined,
    text: '椅子是温的。扶手上有两道被手指磨出来的凹。\n你的手指落进去，正好。',
    corruptedText: cor([40, '椅子是温的。凹的位置正好。你坐过这把椅子。']),
    tags: ['key'],
    onEnter: [san(-8), setf('know.chair-fits')],
    choices: [
      c({
        id: 'dorn.sat.tie',
        label: '把绳子绕上。',
        cost: 8,
        irreversible: true,
        effects: [setf('did.tied-myself'), mark('iron', 3), san(-10)],
        goto: 'dorn.tiedSelf',
      }),
      c({
        id: 'dorn.sat.up',
        label: '站起来。',
        cost: 3,
        effects: [setf('did.stood-up'), san(4)],
        goto: 'dorn.stoodUp',
      }),
    ],
  },
  {
    id: 'dorn.tiedSelf',
    speaker: undefined,
    text: '两道，交叉，结在右手边八公分。\n最后一下你用了牙。你不记得自己学过。',
    corruptedText: cor([40, '两道，交叉，八公分，牙。你不记得学过。你不需要学。']),
    tags: ['key'],
    onEnter: [san(-10), setf('know.i-know-the-knot'), learn('k.previous-log-predicts')],
    choices: [
      c({
        id: 'dorn.tiedSelf.wait',
        label: '等。',
        cost: 20,
        effects: [setf('did.waited-in-chair'), addf('count.futile-acts', 1), san(-8)],
        goto: 'dorn.waited',
      }),
      c({
        id: 'dorn.tiedSelf.free',
        label: '用牙解开。',
        cost: 10,
        effects: [setf('did.freed-myself'), san(6), mark('apostasy', 1)],
        goto: 'dorn.stoodUp',
      }),
    ],
  },
  {
    id: 'dorn.waited',
    speaker: undefined,
    text: '水位上升了两公分。\n有人在门口报了一句水位，声音是你的。',
    corruptedText: cor([40, '水位上升了两公分。有人在门口报水位。他的声音比你年轻。']),
    tags: ['key'],
    onEnter: [san(-12), fear(18), setf('know.someone-reported')],
    choices: [
      c({
        id: 'dorn.waited.answer',
        label: '说"别解"。',
        cost: 2,
        irreversible: true,
        effects: [setf('did.said-dont-untie'), mark('iron', 2), san(-8)],
        goto: 'dorn.becameDorn',
      }),
      c({
        id: 'dorn.waited.free',
        label: '用牙解开。',
        cost: 10,
        effects: [setf('did.freed-myself'), san(4)],
        goto: 'dorn.stoodUp',
      }),
    ],
  },
  {
    id: 'dorn.becameDorn',
    speaker: undefined,
    text: '门口的人停了一下，然后问了水位。\n你报了。你报得很准。',
    corruptedText: cor([40, '门口的人问了水位。你报了。报完你想磨一道绳子。']),
    tags: ['key'],
    onEnter: [setf('did.became-dorn'), mark('iron', 2)],
    choices: [
      c({
        id: 'dorn.becameDorn.stay',
        label: '坐着。',
        cost: 4,
        effects: [setf('did.stayed-seated')],
      }),
    ],
  },
  {
    id: 'dorn.stoodUp',
    speaker: undefined,
    text: '你站起来。腿麻。\n椅子上那两道凹现在有三道。',
    corruptedText: cor([40, '你站起来。凹有三道。你只坐了一次。']),
    tags: ['key'],
    onEnter: [setf('did.stood-up')],
    choices: [go('dorn.stoodUp.go', '走。', 'dorn.leaving')],
  },
  {
    id: 'dorn.teaching',
    speaker: '多恩',
    text: '嗯。\n［停顿］教得好的会走完。走完的留下来值班。',
    corruptedText: cor([40, '嗯。教得好的会走完。走完的留下来值班。我教得不好，所以我还在。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-failed-on-purpose')],
    choices: [
      c({
        id: 'dorn.teaching.fail',
        label: '"你是故意学不好的。"',
        cost: 3,
        requires: K('k.salvage-is-ritual'),
        gateMode: 'disable',
        effects: [setf('did.understood-dorns-method'), san(6)],
        goto: 'dorn.method',
      }),
      go('dorn.teaching.ok', '……', 'dorn.chair'),
    ],
  },
  {
    id: 'dorn.method',
    speaker: '多恩',
    text: '［停顿］我不算故意。\n［停顿］我只是坐下来了，然后发现坐着也算一种走法。',
    corruptedText: cor([40, '［停顿］坐着也算一种走法。只是这一笔很短。']),
    tags: ['key'],
    onEnter: [san(5), setf('know.sitting-is-a-stroke')],
    choices: [go('dorn.method.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.refusal',
    speaker: '多恩',
    text: '［停顿］\n［停顿］那你去月池。别坐下来。',
    corruptedText: cor([40, '［停顿］那你去月池。别坐下来。我坐下来，所以我的那一笔算完了。']),
    tags: ['key'],
    onEnter: [setf('know.dorn-sends-you-down'), san(4)],
    choices: [
      c({
        id: 'dorn.refusal.you',
        label: '"你怎么办。"',
        cost: 2,
        effects: [setf('did.asked-dorn-fate')],
        goto: 'dorn.fate',
      }),
      go('dorn.refusal.go', '走。', 'dorn.leaving'),
    ],
  },
  {
    id: 'dorn.fate',
    speaker: '多恩',
    text: '水位。\n［停顿］我在这儿报。',
    corruptedText: cor([40, '水位。我在这儿报。总得有人报。']),
    tags: ['key'],
    onEnter: [setf('know.he-stays')],
    choices: [go('dorn.fate.ok', '……', 'dorn.leaving')],
  },
  {
    id: 'dorn.silence',
    speaker: '多恩',
    text: '［停顿］\n好。那就别解。',
    corruptedText: cor([40, '［停顿］好。那就别解。你上次也没解。']),
    tags: ['key'],
    onEnter: [mark('silence', 1), setf('did.stayed-silent-with-dorn')],
    choices: [go('dorn.silence.ok', '……', 'dorn.chair')],
  },
  {
    id: 'dorn.leaving',
    speaker: '多恩',
    text: '别解。',
    corruptedText: cor([45, '别解。（这次他是对自己说的。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'dorn.leaving.back',
        label: '再问两句。',
        cost: 2,
        requires: num('count.dorn-talks', '>=', 2),
        gateMode: 'disable',
        goto: 'dorn.chair',
      }),
      c({
        id: 'dorn.leaving.go',
        label: '走。',
        cost: 1,
        effects: [setf('did.left-dorn')],
      }),
    ],
  },
];
