/**
 * 唱诗班 THE CHOIR —— 六具还在唱歌的尸体。
 *
 * 核心张力（GDD §7.2）：他们唱的是你的名字。
 *
 * 剧作位置（四角对立第三角）：他们攻击玩家弱点的方式是**给归属**。
 * 万斯给答案，母亲给爱，唱诗班给一个位置——名单上的第二十行。
 *
 * 契诃夫技法：
 *  - S6 群戏用机械节拍：整场戏的骨架是点名，从第一到第十九，然后回到第一。
 *    所有重要的事都发生在两个名字之间。
 *  - 他们从不说话，只唱。回答问题的方式是唱下一个名字。
 *  - 第二十行有半拍的空。那半拍是留给回答的人的。
 */

import type { NarrativeNode } from '../../core/contract';
import {
  addf,
  all,
  any,
  c,
  cor,
  fear,
  fight,
  give,
  go,
  item,
  K,
  learn,
  loud,
  mark,
  noK,
  num,
  off,
  on,
  san,
  setf,
  sfx,
  silence,
  status,
  take,
} from '../../narrative/dsl';

export const CHOIR_NODES: readonly NarrativeNode[] = [
  {
    id: 'choir.enter',
    speaker: undefined,
    text: '礼拜堂。六个人跪成一排，面朝下坡的那一边。\n他们在唱。喉咙已经不能发声了，但是在唱。',
    corruptedText: cor(
      [50, '六个人跪成一排。他们在唱。声音不是从喉咙来的，是从舱壁来的。'],
      [20, '七个人跪成一排。最后一个背影是你的。'],
    ),
    tags: ['entry', 'key'],
    onEnter: [setf('met.choir'), sfx('choir.unison'), fear(12), san(-6)],
    choices: [
      c({
        id: 'choir.enter.listen',
        label: '站在门口听。',
        cost: 4,
        effects: [setf('did.listened-to-choir'), addf('count.choir-time', 1)],
        goto: 'choir.first-names',
      }),
      c({
        id: 'choir.enter.close',
        label: '靠近。',
        cost: 3,
        effects: [setf('did.approached-choir'), fear(8), loud(2)],
        goto: 'choir.close',
      }),
      c({
        id: 'choir.enter.leave',
        label: '退出去。',
        cost: 2,
        effects: [mark('silence', 1), setf('did.backed-out-of-chapel')],
      }),
    ],
  },
  {
    id: 'choir.first-names',
    speaker: '唱诗班',
    text: '……第七，英格丽·福斯。\n第八，佩尔·桑德。',
    corruptedText: cor([45, '……第七，英格丽·福斯。第八，佩尔·桑德。第八，佩尔·桑德。第八——']),
    tags: ['key'],
    onEnter: [addf('count.names-heard', 2)],
    choices: [
      c({
        id: 'choir.first-names.wait',
        label: '等下一个。',
        cost: 2,
        effects: [addf('count.names-heard', 1), addf('count.choir-time', 1)],
        goto: 'choir.nine',
      }),
      c({
        id: 'choir.first-names.count',
        label: '数他们唱到第几个。',
        cost: 2,
        effects: [setf('did.counting-names'), mark('listening', 1)],
        goto: 'choir.counting',
      }),
      go('choir.first-names.hub', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.nine',
    speaker: '唱诗班',
    text: '第九，玛尔塔·奥伊。\n第十，约翰·布罗。',
    corruptedText: cor([45, '第九，玛尔塔·奥伊。（她就在最左边那个位置。她在唱自己。）']),
    tags: ['key'],
    onEnter: [addf('count.names-heard', 2)],
    choices: [
      c({
        id: 'choir.nine.check',
        label: '看最左边那个人的胸牌。',
        cost: 3,
        effects: [setf('did.checked-nametag'), san(-6)],
        goto: 'choir.selfsinging',
      }),
      go('choir.nine.on', '继续听。', 'choir.fourteen'),
    ],
  },
  {
    id: 'choir.selfsinging',
    speaker: undefined,
    text: '胸牌：M. ØYE。\n她刚才唱的是自己的名字，语气和唱别人一样。',
    corruptedText: cor([40, '胸牌：M. ØYE。她唱自己的时候没有停顿。所以她不知道那是自己。']),
    tags: ['key'],
    onEnter: [setf('know.they-sing-themselves'), san(-6)],
    choices: [go('choir.selfsinging.on', '继续听。', 'choir.fourteen')],
  },
  {
    id: 'choir.fourteen',
    speaker: '唱诗班',
    text: '第十四，阿斯特丽·多恩。\n第十五，埃里克·多恩。',
    corruptedText: cor([45, '第十四，阿斯特丽·多恩。第十五，埃里克·多恩。（两个都唱完了。一个还坐着。）']),
    tags: ['key'],
    onEnter: [addf('count.names-heard', 2), setf('know.two-dorns')],
    choices: [
      c({
        id: 'choir.fourteen.note',
        label: '两个多恩。',
        cost: 2,
        requires: on('met.dorn'),
        gateMode: 'hide',
        effects: [learn('k.dorn-daughter')],
        goto: 'choir.twodorns',
      }),
      go('choir.fourteen.on', '继续听。', 'choir.nineteen'),
    ],
  },
  {
    id: 'choir.twodorns',
    speaker: undefined,
    text: '大副在椅子上。他的名字已经被唱过了。\n被唱过的人不一定死了。这条规律有一个例外，而例外是他。',
    corruptedText: cor([40, '他的名字已经被唱过了。所以他在等的不是死。他在等被唱第二遍。']),
    tags: ['key'],
    onEnter: [san(-5)],
    choices: [go('choir.twodorns.on', '继续听。', 'choir.nineteen')],
  },
  {
    id: 'choir.nineteen',
    speaker: '唱诗班',
    text: '第十八，奥拉夫·莱恩。\n第十九，万斯·基尔。',
    corruptedText: cor([45, '第十八，奥拉夫·莱恩。第十九，万斯·基尔。（他也在名单上。他也唱完了。）']),
    tags: ['key'],
    onEnter: [addf('count.names-heard', 2), setf('know.vance-on-manifest'), fear(14)],
    choices: [
      c({
        id: 'choir.nineteen.vance',
        label: '万斯。',
        cost: 2,
        requires: on('met.vance'),
        gateMode: 'hide',
        effects: [setf('did.heard-vance-sung'), san(-8)],
        goto: 'choir.vanceSung',
      }),
      c({
        id: 'choir.nineteen.wait',
        label: '等第二十个。',
        cost: 3,
        effects: [setf('did.waited-for-twentieth')],
        goto: 'choir.twenty',
      }),
    ],
  },
  {
    id: 'choir.vanceSung',
    speaker: undefined,
    text: '第十九。\n那把椅子的声音你在无线电里听过。',
    corruptedText: cor([40, '第十九。那把椅子的声音你听过。椅子比人活得久。']),
    tags: ['key'],
    onEnter: [learn('k.vance-onboard'), san(-6)],
    choices: [go('choir.vanceSung.on', '等第二十个。', 'choir.twenty')],
  },
  {
    id: 'choir.twenty',
    speaker: '唱诗班',
    text: '第二十，——',
    corruptedText: cor(
      [45, '第二十，——（半拍。六张嘴都张着。）'],
      [18, '第二十，（你的名字。他们已经唱出来了，是你没听见。）'],
    ),
    tags: ['key'],
    onEnter: [sfx('choir.break'), fear(20), san(-8), setf('know.twentieth-gap')],
    choices: [
      c({
        id: 'choir.twenty.answer',
        label: '答应。',
        cost: 2,
        irreversible: true,
        effects: [
          setf('did.answered-twentieth'),
          mark('listening', 3),
          san(-14),
          loud(24),
          status('status.humming', 200),
        ],
        goto: 'choir.answered',
      }),
      c({
        id: 'choir.twenty.silent',
        label: '不答应。',
        cost: 2,
        irreversible: true,
        effects: [setf('did.refused-twentieth'), mark('silence', 3), san(4)],
        goto: 'choir.refused',
      }),
      c({
        id: 'choir.twenty.other',
        label: '报一个别人的名字。',
        cost: 3,
        requires: on('know.her-name'),
        gateMode: 'hide',
        irreversible: true,
        effects: [setf('did.gave-false-name'), mark('apostasy', 2), san(-6), loud(18)],
        goto: 'choir.falseName',
      }),
      c({
        id: 'choir.twenty.hers',
        label: '"安内莉·斯特兰。"',
        cost: 3,
        requires: K('k.mother-is-sample-three'),
        gateMode: 'lie',
        effects: [setf('did.offered-mother')],
        goto: 'choir.offeredMother',
      }),
    ],
  },
  {
    id: 'choir.answered',
    speaker: '唱诗班',
    text: '（六个声音同时补上了那半拍。补的是你的名字。）\n第一，哈尔瓦·内斯。',
    corruptedText: cor([40, '（六个声音补上了那半拍。）第一，哈尔瓦·内斯。（名单现在是二十个。）']),
    tags: ['key'],
    onEnter: [
      learn('k.choir-sings-manifest'),
      setf('know.i-am-on-the-list'),
      addf('count.choir-rounds', 1),
      san(-10),
    ],
    choices: [
      c({
        id: 'choir.answered.listen',
        label: '听完整一轮。',
        cost: 12,
        effects: [setf('did.heard-full-round'), addf('count.choir-rounds', 1), san(-8)],
        goto: 'choir.fullRound',
      }),
      c({
        id: 'choir.answered.run',
        label: '走。',
        cost: 3,
        effects: [fear(10), setf('did.fled-chapel')],
        goto: 'choir.pews',
      }),
    ],
  },
  {
    id: 'choir.refused',
    speaker: '唱诗班',
    text: '（半拍过去了。没有人补。）\n第一，哈尔瓦·内斯。',
    corruptedText: cor([40, '（半拍过去了。没有人补。）第一，哈尔瓦·内斯。（他们会再唱到第二十。）']),
    tags: ['key'],
    onEnter: [learn('k.choir-sings-manifest'), addf('count.choir-rounds', 1), san(4)],
    choices: [
      c({
        id: 'choir.refused.listen',
        label: '听完整一轮。',
        cost: 12,
        effects: [setf('did.heard-full-round'), addf('count.choir-rounds', 1)],
        goto: 'choir.fullRound',
      }),
      go('choir.refused.hub', '在长凳上坐一会儿。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.falseName',
    speaker: '唱诗班',
    text: '（他们唱了那个名字。唱完，回到第一。）\n第一，哈尔瓦·内斯。',
    corruptedText: cor([40, '（他们唱了那个名字。名单上多了一行，不是你。）']),
    tags: ['key'],
    onEnter: [learn('k.choir-sings-manifest'), addf('count.choir-rounds', 1), setf('know.list-accepts-anyone')],
    choices: [
      c({
        id: 'choir.falseName.guilt',
        label: '那个名字现在在名单上。',
        cost: 2,
        effects: [setf('did.realized-i-added-someone'), san(-8)],
        goto: 'choir.addedSomeone',
      }),
      go('choir.falseName.hub', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.addedSomeone',
    speaker: undefined,
    text: '你用一个名字换了半拍的安静。\n名字是别人的。安静是你的。',
    corruptedText: cor([40, '名字是别人的。安静是你的。这是这条船上最公平的一次交易。']),
    tags: ['key'],
    onEnter: [mark('apostasy', 1)],
    choices: [go('choir.addedSomeone.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.offeredMother',
    speaker: '唱诗班',
    text: '（他们停了。整整两拍。）\n第三，安内莉·斯特兰。',
    corruptedText: cor([40, '（他们停了两拍。）第三，安内莉·斯特兰。（广播里同时响了一下。）']),
    tags: ['key'],
    onEnter: [sfx('mother.tone'), san(-12), setf('know.she-was-called-again')],
    choices: [
      c({
        id: 'choir.offeredMother.listen',
        label: '听广播。',
        cost: 3,
        effects: [setf('did.heard-mother-called')],
        goto: 'choir.motherAnswers',
      }),
      c({
        id: 'choir.offeredMother.take',
        label: '"不是她。是我。"',
        cost: 3,
        irreversible: true,
        effects: [setf('did.took-it-back'), mark('listening', 2), san(-8)],
        goto: 'choir.answered',
      }),
    ],
  },
  {
    id: 'choir.motherAnswers',
    speaker: '广播',
    text: '（咔）我在。',
    corruptedText: cor([40, '（咔）我在。（咔）你吃过东西了吗。']),
    tags: ['key'],
    onEnter: [setf('did.mother-answered-choir'), san(-10)],
    choices: [
      c({
        id: 'choir.motherAnswers.sorry',
        label: '"对不起。"',
        cost: 2,
        effects: [setf('did.apologized-to-mother'), san(-4)],
        goto: 'choir.pews',
      }),
      silence('choir.motherAnswers.silent', 'choir.pews'),
    ],
  },
  {
    id: 'choir.fullRound',
    speaker: undefined,
    text: '一整轮四分钟。十九个名字，然后回到第一。\n第二十行每次都有那半拍。',
    corruptedText: cor([40, '一整轮四分钟。第二十行每次都有那半拍。他们在等，很有耐心。']),
    tags: ['key'],
    onEnter: [learn('k.choir-sings-manifest'), setf('did.heard-full-round')],
    choices: [
      c({
        id: 'choir.fullRound.melody',
        label: '记住旋律。',
        cost: 4,
        effects: [setf('did.memorized-melody'), mark('listening', 1)],
        goto: 'choir.melody',
      }),
      go('choir.fullRound.hub', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.melody',
    speaker: undefined,
    text: '旋律只有五个音，反复。最后两个音之间差一个很小的间隔。\n那个间隔你在别的地方听过。',
    corruptedText: cor([40, '五个音，反复。那个间隔你在别的地方听过。在你自己的呼吸里。']),
    tags: ['key'],
    onEnter: [setf('know.five-notes')],
    choices: [
      c({
        id: 'choir.melody.match',
        label: '和声呐阵列的录音对齐。',
        cost: 5,
        requires: K('k.listening-array'),
        gateMode: 'disable',
        effects: [learn('k.signal-is-real'), san(-10)],
        goto: 'choir.aligned',
      }),
      go('choir.melody.hub', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.aligned',
    speaker: undefined,
    text: '两条曲线重合。一条是六具尸体，一条是一支麦克风。\n两个不相连的系统收到同一段，那就不是故障。',
    corruptedText: cor([40, '两条曲线重合。第三条是你的呼吸，也重合。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), san(-8)],
    choices: [go('choir.aligned.ok', '……', 'choir.pews')],
  },

  // -------------------------------------------------------------------------
  // 长凳中枢
  // -------------------------------------------------------------------------
  {
    id: 'choir.pews',
    speaker: '唱诗班',
    text: '（点名继续。你现在能从任何一个数字接上去。）',
    corruptedText: cor(
      [50, '（点名继续。你嘴里有一个数字在动，你没有让它动。）'],
      [20, '（点名停了。他们都在看你。他们的脸朝着地。）'],
    ),
    tags: ['entry', 'hub', 'key'],
    onEnter: [addf('count.choir-time', 1), sfx('choir.unison')],
    choices: [
      c({
        id: 'choir.pews.body1',
        label: '看第一具。',
        cost: 3,
        effects: [setf('did.examined-body-1'), addf('count.bodies-examined', 1)],
        goto: 'choir.body1',
      }),
      c({
        id: 'choir.pews.body2',
        label: '看第二具。',
        cost: 3,
        effects: [setf('did.examined-body-2'), addf('count.bodies-examined', 1)],
        goto: 'choir.body2',
      }),
      c({
        id: 'choir.pews.body3',
        label: '看第三具。',
        cost: 3,
        effects: [setf('did.examined-body-3'), addf('count.bodies-examined', 1)],
        goto: 'choir.body3',
      }),
      c({
        id: 'choir.pews.body4',
        label: '看第四具。',
        cost: 3,
        requires: num('count.bodies-examined', '>=', 2),
        gateMode: 'disable',
        effects: [setf('did.examined-body-4'), addf('count.bodies-examined', 1)],
        goto: 'choir.body4',
      }),
      c({
        id: 'choir.pews.body5',
        label: '看第五具。',
        cost: 3,
        requires: num('count.bodies-examined', '>=', 3),
        gateMode: 'disable',
        effects: [setf('did.examined-body-5'), addf('count.bodies-examined', 1)],
        goto: 'choir.body5',
      }),
      c({
        id: 'choir.pews.body6',
        label: '看第六具。',
        cost: 3,
        requires: num('count.bodies-examined', '>=', 4),
        gateMode: 'disable',
        effects: [setf('did.examined-body-6'), addf('count.bodies-examined', 1)],
        goto: 'choir.body6',
      }),
      c({
        id: 'choir.pews.hymnal',
        label: '拿唱诗本。',
        cost: 3,
        effects: [give('hymnal'), setf('did.took-hymnal'), loud(3)],
        goto: 'choir.hymnal',
      }),
      c({
        id: 'choir.pews.interrupt',
        label: '打断他们。',
        cost: 2,
        irreversible: true,
        effects: [setf('did.interrupted-choir'), loud(30), fear(20), mark('apostasy', 2)],
        goto: 'choir.interrupted',
      }),
      c({
        id: 'choir.pews.sing',
        label: '跟着唱。',
        cost: 4,
        requires: on('did.memorized-melody'),
        gateMode: 'hide',
        effects: [setf('did.sang-along'), mark('listening', 2), loud(20), san(-10)],
        goto: 'choir.sangAlong',
      }),
      c({
        id: 'choir.pews.wax',
        label: '把蜡塞进耳朵。',
        cost: 3,
        requires: item('earwax'),
        gateMode: 'disable',
        effects: [setf('did.plugged-ears'), take('earwax'), mark('silence', 2), status('status.ringing', 300)],
        goto: 'choir.plugged',
      }),
      c({
        id: 'choir.pews.name',
        label: '听第二十行。',
        cost: 4,
        requires: K('k.pen-can-stop'),
        gateMode: 'disable',
        effects: [learn('k.your-name')],
        goto: 'choir.myName',
      }),
      c({
        id: 'choir.pews.leave',
        label: '离开礼拜堂。',
        cost: 2,
        effects: [setf('did.left-chapel')],
        goto: 'choir.leaving',
      }),
    ],
  },
  {
    id: 'choir.body1',
    speaker: undefined,
    text: '男性，膝盖磨破了，磨到骨头。他跪了很久才停下来。\n手里握着一根断掉的铅笔。',
    corruptedText: cor([40, '他跪了很久。手里握着断铅笔。铅笔头是新削的。']),
    tags: ['key'],
    onEnter: [san(-4)],
    choices: [
      c({
        id: 'choir.body1.pencil',
        label: '取铅笔。',
        cost: 2,
        effects: [setf('did.took-pencil'), mark('flesh', 1)],
        goto: 'choir.pencil',
      }),
      go('choir.body1.back', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.pencil',
    speaker: undefined,
    text: '铅笔断在离笔尖一公分的地方。断口很新。\n他写完了才断的。',
    corruptedText: cor([40, '断口很新。他写完了才断的。你的手很想握住它。']),
    tags: ['key'],
    onEnter: [setf('know.he-finished-writing')],
    choices: [go('choir.pencil.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.body2',
    speaker: undefined,
    text: '女性。胸牌 B. LIEN。她的下颌被自己的手托着，托得很稳。\n托了很久，指关节压出了印。',
    corruptedText: cor([40, '胸牌 B. LIEN。她自己托着下颌。为了继续唱。']),
    tags: ['key'],
    onEnter: [san(-4), setf('know.she-holds-her-jaw')],
    choices: [go('choir.body2.back', '……', 'choir.pews')],
  },
  {
    id: 'choir.body3',
    speaker: undefined,
    text: '这一具的位置是空的。跪印在，人不在。\n跪印里有水，水是温的。',
    corruptedText: cor([40, '跪印在，人不在。水是温的。（唱的还是六个声音。）']),
    tags: ['key'],
    onEnter: [fear(16), san(-8), setf('know.third-is-empty')],
    choices: [
      c({
        id: 'choir.body3.count',
        label: '数声音。',
        cost: 3,
        effects: [setf('did.counted-voices'), san(-8), addf('count.debunks', 1)],
        goto: 'choir.sixVoices',
      }),
      go('choir.body3.back', '不数。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.sixVoices',
    speaker: undefined,
    text: '六个声音，五个人。\n第六个来自你左边一米的空气，而那块空气是温的。',
    corruptedText: cor([40, '六个声音，五个人。第六个是你的。你的嘴在动。']),
    tags: ['key'],
    onEnter: [fear(22), san(-10), setf('know.sixth-voice')],
    choices: [
      c({
        id: 'choir.sixVoices.mouth',
        label: '摸自己的嘴。',
        cost: 2,
        effects: [setf('did.touched-own-mouth'), san(-10)],
        goto: 'choir.myMouth',
      }),
      c({
        id: 'choir.sixVoices.debunk',
        label: '这是龙骨的共振，不是第六个人。',
        cost: 2,
        requires: K('k.listening-array'),
        gateMode: 'disable',
        effects: [addf('count.debunks', 1), san(10), setf('did.debunked-sixth')],
        goto: 'choir.debunkedSixth',
      }),
    ],
  },
  {
    id: 'choir.myMouth',
    speaker: undefined,
    text: '在动。\n你停下来。六个声音变成五个，然后第六个又回来了，但慢了半拍。',
    corruptedText: cor([40, '在动。你停下来。第六个慢了半拍回来。它在等你。']),
    tags: ['key'],
    onEnter: [san(-10), status('status.humming', 240), setf('did.was-humming')],
    choices: [go('choir.myMouth.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.debunkedSixth',
    speaker: undefined,
    text: '五个人跪成的弧正好是一个聚焦面。中心在你站的地方。\n第六个声音是你自己的回声被聚起来。',
    tags: ['key'],
    onEnter: [san(8)],
    choices: [go('choir.debunkedSixth.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.body4',
    speaker: undefined,
    text: '这一具是趴着的，脸朝下，但声音还在。\n他的后颈上有一道缝合线，缝得很整齐，线是新的。',
    corruptedText: cor([40, '他趴着，脸朝下。后颈的缝合线是新的。线头还没剪。']),
    tags: ['key'],
    onEnter: [san(-6), setf('know.fresh-sutures')],
    choices: [
      c({
        id: 'choir.body4.open',
        label: '拆开看。',
        cost: 6,
        requires: item('scalpel'),
        gateMode: 'disable',
        irreversible: true,
        effects: [setf('did.opened-body'), mark('flesh', 2), san(-12), loud(8)],
        goto: 'choir.opened',
      }),
      go('choir.body4.back', '不拆。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.opened',
    speaker: undefined,
    text: '颈后是一个小腔，里面是空的，内壁很光滑，像用过很多次。\n腔的形状和一个耳机的形状一样。',
    corruptedText: cor([40, '腔是空的，内壁光滑。形状和你的耳机一样。你摸了一下自己的后颈。']),
    tags: ['key'],
    onEnter: [san(-10), setf('know.neck-socket')],
    choices: [
      c({
        id: 'choir.opened.neck',
        label: '摸自己的后颈。',
        cost: 2,
        effects: [setf('did.felt-own-neck'), san(-10), fear(20)],
        goto: 'choir.ownNeck',
      }),
      go('choir.opened.back', '缝回去。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.ownNeck',
    speaker: undefined,
    text: '有。\n缝合线是旧的，已经长平了。',
    corruptedText: cor([40, '有。线是旧的。长平了。长了十七次才长平。']),
    tags: ['key'],
    onEnter: [san(-12), learn('k.signal-in-blood')],
    choices: [go('choir.ownNeck.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.body5',
    speaker: undefined,
    text: '这一具年纪最小，二十出头。口袋里有一封写好的信，没有封口。\n第一行：「等我回来再拆。」',
    corruptedText: cor([40, '口袋里有一封信。第一行：等我回来再拆。（信纸是新的。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'choir.body5.read',
        label: '拆开读。',
        cost: 4,
        irreversible: true,
        effects: [setf('did.read-letter'), san(-6), mark('apostasy', 1)],
        goto: 'choir.letter',
      }),
      c({
        id: 'choir.body5.leave',
        label: '放回去。',
        cost: 2,
        effects: [mark('silence', 1), setf('did.left-letter'), san(3)],
        goto: 'choir.pews',
      }),
    ],
  },
  {
    id: 'choir.letter',
    speaker: undefined,
    text: '整封信只有一句：「我听见了，很好听，别来。」\n下面的签名被水泡开了。',
    corruptedText: cor([40, '「我听见了，很好听，别来。」签名被泡开了。字迹是你的。']),
    tags: ['key'],
    onEnter: [setf('know.letter-content'), san(-6)],
    choices: [
      c({
        id: 'choir.letter.sign',
        label: '看签名。',
        cost: 3,
        effects: [setf('did.checked-signature'), san(-8)],
        goto: 'choir.signature',
      }),
      go('choir.letter.back', '折好放回去。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.signature',
    speaker: undefined,
    text: '起笔在右上。中间有一次停顿。\n和补板上那三个字一样。',
    corruptedText: cor([40, '起笔在右上。中间停了一次。和补板上一样。和你一样。']),
    tags: ['key'],
    onEnter: [san(-8), setf('know.same-hand')],
    choices: [go('choir.signature.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.body6',
    speaker: undefined,
    text: '这一具的手是合在一起的，中间夹着一枚铁哨。\n哨子上刻着 03。',
    corruptedText: cor([40, '手合在一起，夹着铁哨，刻着 03。（管道里有人在等这枚哨子。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'choir.body6.whistle',
        label: '取哨子。',
        cost: 3,
        effects: [give('whistle.pelle'), setf('did.took-whistle'), mark('flesh', 1)],
        goto: 'choir.whistle',
      }),
      go('choir.body6.back', '不动。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.whistle',
    speaker: undefined,
    text: '哨子是救生衣配件，编号 03。\n第三号那件。',
    corruptedText: cor([40, '编号 03。第三号那件。（广播里响了一下。）']),
    tags: ['key'],
    onEnter: [learn('k.pelle-whistle-origin'), sfx('mother.tone')],
    choices: [
      c({
        id: 'choir.whistle.blow',
        label: '吹一下。',
        cost: 2,
        irreversible: true,
        effects: [setf('did.blew-whistle'), loud(34), fear(18), mark('listening', 1)],
        goto: 'choir.blown',
      }),
      go('choir.whistle.pocket', '收起来。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.blown',
    speaker: undefined,
    text: '哨声在礼拜堂里来回撞了四次才停。\n六个声音停了。然后从第一个名字重新开始。',
    corruptedText: cor([40, '哨声撞了四次。六个声音停了。管道里有人也停了。']),
    tags: ['key'],
    onEnter: [addf('count.choir-rounds', 1), sfx('pipe.knock'), setf('know.whistle-resets')],
    choices: [go('choir.blown.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.hymnal',
    speaker: undefined,
    text: '唱诗本。五线谱下面不是歌词，是一列坐标。\n每一行坐标对应一个名字。',
    corruptedText: cor([40, '五线谱下面是坐标。每行对应一个名字。第二十行的坐标是空的。']),
    tags: ['key'],
    onEnter: [setf('know.hymnal-coords')],
    choices: [
      c({
        id: 'choir.hymnal.compare',
        label: '和万斯给的坐标对一下。',
        cost: 4,
        requires: num('count.coords-given', '>=', 2),
        gateMode: 'disable',
        effects: [setf('did.compared-coords'), san(-6)],
        goto: 'choir.coordsMatch',
      }),
      c({
        id: 'choir.hymnal.twenty',
        label: '看第二十行。',
        cost: 3,
        effects: [setf('did.checked-twentieth-line')],
        goto: 'choir.twentiethLine',
      }),
      go('choir.hymnal.back', '合上。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.coordsMatch',
    speaker: undefined,
    text: '万斯给你的三个坐标，是本子上第十七、十八、十九行。\n他在照本子念。',
    corruptedText: cor([40, '他在照本子念。念到第二十行的时候他会停半拍。']),
    tags: ['key'],
    onEnter: [learn('k.vance-onboard'), san(-6)],
    choices: [go('choir.coordsMatch.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.twentiethLine',
    speaker: undefined,
    text: '第二十行的坐标位置是空白的，但纸上有压痕。\n有人用铅笔写过，又擦掉了。擦得很干净，只留下笔压。',
    corruptedText: cor([40, '第二十行有压痕。擦得很干净。擦的人用了很多次橡皮。']),
    tags: ['key'],
    onEnter: [setf('know.erased-twentieth')],
    choices: [
      c({
        id: 'choir.twentiethLine.rub',
        label: '用铅笔侧面拓一下。',
        cost: 4,
        requires: on('did.took-pencil'),
        gateMode: 'disable',
        effects: [setf('did.rubbed-impression'), san(-8)],
        goto: 'choir.impression',
      }),
      go('choir.twentiethLine.back', '合上。', 'choir.pews'),
    ],
  },
  {
    id: 'choir.impression',
    speaker: undefined,
    text: '拓出来的是月池的坐标。\n写的人不确定，写了又擦了，擦了又写。压痕有四层。',
    corruptedText: cor([40, '拓出来的是月池。压痕有四层。第五层正在被写。']),
    tags: ['key'],
    onEnter: [setf('know.moonpool-coord'), learn('k.path-is-a-stroke')],
    choices: [go('choir.impression.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.interrupted',
    speaker: undefined,
    text: '你喊了一声。合唱断在一个音的中间。\n断了三秒。三秒里，有一个人转过头来。',
    corruptedText: cor([40, '合唱断了三秒。有一个人转过头。他的脸是你在镜子里见过的那张。']),
    tags: ['key'],
    onEnter: [sfx('choir.break'), fear(24), san(-12)],
    choices: [
      c({
        id: 'choir.interrupted.run',
        label: '跑。',
        cost: 6,
        effects: [setf('did.ran-from-choir'), loud(12), fear(10)],
        goto: 'choir.leaving',
      }),
      c({
        id: 'choir.interrupted.stay',
        label: '站着。',
        cost: 4,
        irreversible: true,
        effects: [setf('did.faced-choir'), fight('enc.choir-rise')],
        goto: 'choir.faced',
      }),
      c({
        id: 'choir.interrupted.apologize',
        label: '"对不起。接着唱。"',
        cost: 3,
        effects: [setf('did.apologized-to-choir'), mark('listening', 1), san(-4)],
        goto: 'choir.resumed',
      }),
    ],
  },
  {
    id: 'choir.faced',
    speaker: undefined,
    text: '他转回去了。\n合唱从被打断的那个音接上，音高一模一样。',
    corruptedText: cor([40, '他转回去了。合唱从那个音接上。他们记得被打断的位置。']),
    tags: ['key'],
    onEnter: [setf('know.they-resume-exactly')],
    choices: [go('choir.faced.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.resumed',
    speaker: '唱诗班',
    text: '（从被打断的那个音接上。）\n第十二，斯坦·维克。',
    corruptedText: cor([40, '（从那个音接上。）第十二，斯坦·维克。（谁都没有看你。）']),
    tags: ['key'],
    choices: [go('choir.resumed.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.sangAlong',
    speaker: undefined,
    text: '你唱到第十九的时候，六个声音让出了一个位置给你。\n第二十行，只有你一个人在唱。',
    corruptedText: cor([40, '第二十行只有你一个人在唱。你唱的是一个名字。你听不清是谁的。']),
    tags: ['key'],
    onEnter: [mark('listening', 3), san(-14), setf('know.sang-the-twentieth')],
    choices: [
      c({
        id: 'choir.sangAlong.stop',
        label: '停住。',
        cost: 3,
        effects: [setf('did.stopped-singing'), mark('silence', 2), san(4)],
        goto: 'choir.stopped',
      }),
      c({
        id: 'choir.sangAlong.finish',
        label: '唱完。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.finished-the-twentieth'), mark('listening', 3), san(-12), loud(26)],
        goto: 'choir.finishedName',
      }),
    ],
  },
  {
    id: 'choir.stopped',
    speaker: undefined,
    text: '你停在半个音上。六个声音也停在那里，等着。\n等了很久。然后回到第一个名字。',
    corruptedText: cor([40, '你停在半个音上。他们等了很久。他们很会等。']),
    tags: ['key'],
    onEnter: [addf('count.choir-rounds', 1)],
    choices: [go('choir.stopped.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.finishedName',
    speaker: undefined,
    text: '唱完了。名单现在是二十行。\n第一到第十九是别人。第二十是一个动词。',
    corruptedText: cor([40, '名单是二十行。第二十行是一个动词，祈使语气，对象是它。']),
    tags: ['key'],
    onEnter: [setf('know.twentieth-is-a-verb'), san(-10)],
    choices: [
      c({
        id: 'choir.finishedName.what',
        label: '什么动词。',
        cost: 3,
        requires: K('k.the-word'),
        gateMode: 'disable',
        effects: [learn('k.your-name')],
        goto: 'choir.myName',
      }),
      go('choir.finishedName.back', '……', 'choir.pews'),
    ],
  },
  {
    id: 'choir.myName',
    speaker: '唱诗班',
    text: '第二十，——\n（半拍。这半拍是留给你的。它一直是留给你的。）',
    corruptedText: cor([40, '第二十，——（半拍。你上次填了。他们在等你再填一次。）']),
    tags: ['key'],
    onEnter: [learn('k.your-name'), san(-8), sfx('choir.break')],
    choices: [
      c({
        id: 'choir.myName.leave',
        label: '留着这半拍。走。',
        cost: 3,
        irreversible: true,
        effects: [setf('did.left-the-gap'), mark('silence', 3), setf('know.gap-left-open'), san(6)],
        goto: 'choir.leaving',
      }),
      c({
        id: 'choir.myName.fill',
        label: '填上。',
        cost: 3,
        irreversible: true,
        effects: [setf('did.filled-the-gap'), mark('listening', 4), san(-16), loud(30)],
        goto: 'choir.filled',
      }),
    ],
  },
  {
    id: 'choir.filled',
    speaker: undefined,
    text: '填上了。第二十行不再是空的。\n合唱现在多了一个声音，而你的嘴不需要动了。',
    corruptedText: cor([40, '第二十行不再是空的。你的嘴不需要动了。方便很多。']),
    tags: ['key'],
    onEnter: [status('status.humming', 600), setf('know.i-am-in-the-choir'), san(-12)],
    choices: [
      c({
        id: 'choir.filled.kneel',
        label: '跪下。',
        cost: 8,
        irreversible: true,
        effects: [setf('ritual.name'), mark('listening', 3), san(-10)],
        goto: 'choir.kneeled',
      }),
      c({
        id: 'choir.filled.walk',
        label: '走出去。',
        cost: 4,
        effects: [setf('did.walked-out-humming')],
        goto: 'choir.leaving',
      }),
    ],
  },
  {
    id: 'choir.kneeled',
    speaker: undefined,
    text: '膝盖落在第三具的跪印里。跪印是温的。\n你现在能从任何一个数字接上去，而且不用想。',
    corruptedText: cor([40, '膝盖落进跪印里。温的。你不用想了。这是今天最舒服的时刻。']),
    tags: ['key'],
    onEnter: [setf('ritual.name'), addf('ritual.count', 1), mark('listening', 2)],
    choices: [
      c({
        id: 'choir.kneeled.rise',
        label: '站起来。',
        cost: 10,
        effects: [setf('did.rose-from-kneeling'), san(6), mark('apostasy', 1)],
        goto: 'choir.leaving',
      }),
      c({
        id: 'choir.kneeled.stay',
        label: '不站起来。',
        cost: 20,
        irreversible: true,
        effects: [setf('did.stayed-kneeling'), mark('listening', 4), san(-14)],
        goto: 'choir.stayed',
      }),
    ],
  },
  {
    id: 'choir.stayed',
    speaker: undefined,
    text: '第七具的跪印是你压出来的。\n再过一会儿，会有人进来数声音，数出七个。',
    corruptedText: cor([40, '第七具的跪印是你压的。会有人进来数，数出七个。他会摸自己的嘴。']),
    tags: ['key'],
    onEnter: [setf('know.seventh-kneeler'), san(-10)],
    choices: [
      c({
        id: 'choir.stayed.wait',
        label: '等他进来。',
        cost: 20,
        effects: [setf('did.waited-for-next-me'), addf('count.futile-acts', 1)],
      }),
      c({
        id: 'choir.stayed.rise',
        label: '站起来。',
        cost: 12,
        effects: [setf('did.rose-from-kneeling'), san(4)],
        goto: 'choir.leaving',
      }),
    ],
  },
  {
    id: 'choir.plugged',
    speaker: undefined,
    text: '塞上了。合唱变成一层闷响，听不出名字。\n也听不出自己的呼吸。',
    corruptedText: cor([40, '塞上了。听不出名字，也听不出自己的呼吸。只剩下一层很稳的拍子。']),
    tags: ['key'],
    onEnter: [mark('silence', 1), setf('know.plugged-cost')],
    choices: [
      c({
        id: 'choir.plugged.pull',
        label: '取出来。',
        cost: 2,
        effects: [setf('did.unplugged-ears'), give('earwax')],
        goto: 'choir.pews',
      }),
      c({
        id: 'choir.plugged.stay',
        label: '就这样待一会儿。',
        cost: 8,
        effects: [setf('did.stayed-deaf'), san(6), mark('silence', 1)],
        goto: 'choir.deafRest',
      }),
    ],
  },
  {
    id: 'choir.deafRest',
    speaker: undefined,
    text: '八个呼吸的安静。这是今天最安静的八个呼吸。\n第九个呼吸的时候，蜡里面传来了那个拍子。',
    corruptedText: cor([40, '八个呼吸的安静。第九个，蜡里面有那个拍子。蜡是它做的。']),
    tags: ['key'],
    onEnter: [san(4), setf('know.rhythm-through-wax')],
    choices: [go('choir.deafRest.ok', '……', 'choir.pews')],
  },
  {
    id: 'choir.leaving',
    speaker: '唱诗班',
    text: '第一，哈尔瓦·内斯。',
    corruptedText: cor([45, '第一，哈尔瓦·内斯。（他们从来不送客。）']),
    tags: ['key'],
    choices: [
      c({
        id: 'choir.leaving.back',
        label: '回去。',
        cost: 2,
        requires: num('count.choir-time', '>=', 2),
        gateMode: 'disable',
        goto: 'choir.pews',
      }),
      c({
        id: 'choir.leaving.go',
        label: '走。',
        cost: 2,
        effects: [setf('did.left-chapel')],
      }),
    ],
  },
];
