/**
 * 舱室事件 —— 不带 NPC 的场景。
 *
 * 设计原则（GDD §7.4）：
 * 每个舱室只做一件事，而且这件事必须能被"看得更仔细"。
 * 恐惧来自细节的精度（卷边朝外、水印三层、毛刺十七层），不来自形容词。
 *
 * 结构上这些节点承担 Truby 22 步骤里的"对手的计划暴露"与"探访死亡"：
 * 断口告诉你门是从里面打开的；月池告诉你外面有东西在等；
 * 声呐室告诉你这条船本来就不是为了返航造的。
 */

import type { NarrativeNode } from '../../core/contract';
import {
  addf,
  all,
  any,
  c,
  cor,
  fear,
  fight,
  give,
  go,
  item,
  K,
  learn,
  loud,
  mark,
  noK,
  num,
  off,
  on,
  openDoor,
  san,
  setf,
  sfx,
  silence,
  status,
  take,
} from '../../narrative/dsl';

export const ROOM_NODES: readonly NarrativeNode[] = [
  // --------------------------------------------------------------------- 断口
  {
    id: 'room.breach',
    speaker: undefined,
    text: '走廊尽头的隔壁舱门上有一个洞，一米宽。\n钢板的断口卷着边。',
    corruptedText: cor(
      [50, '钢板的断口卷着边。卷的方向朝外。'],
      [20, '断口朝外。这个洞是从你站的这一侧撞开的。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.found-breach'), sfx('hull.groan')],
    choices: [
      c({
        id: 'room.breach.curl',
        label: '摸断口的卷边。',
        cost: 3,
        effects: [learn('k.breach-from-inside'), setf('did.touched-breach')],
        goto: 'room.breach.curl',
      }),
      c({
        id: 'room.breach.look',
        label: '往洞里看。',
        cost: 3,
        effects: [setf('did.looked-through-breach'), fear(10)],
        goto: 'room.breach.look',
      }),
      c({
        id: 'room.breach.through',
        label: '钻过去。',
        cost: 8,
        effects: [setf('did.crossed-breach'), loud(10)],
        goto: 'room.breach.through',
      }),
      c({
        id: 'room.breach.paint',
        label: '看洞边的漆。',
        cost: 2,
        requires: on('did.touched-breach'),
        gateMode: 'hide',
        effects: [setf('did.examined-breach-paint')],
        goto: 'room.breach.paint',
      }),
      c({ id: 'room.breach.back', label: '退回走廊。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'room.breach.curl',
    speaker: undefined,
    text: '卷边朝外。\n水压是从外往里的，所以撞的人在里面。',
    corruptedText: cor([45, '卷边朝外。撞的人在里面。撞的时候水已经进来了。']),
    tags: ['key'],
    onEnter: [learn('k.breach-from-inside'), san(-6)],
    choices: [
      c({
        id: 'room.breach.curl.why',
        label: '为什么要往外撞。',
        cost: 3,
        requires: K('k.signal-is-real'),
        gateMode: 'disable',
        effects: [learn('k.they-wanted-out-to-it'), san(-8)],
        goto: 'room.breach.why',
      }),
      go('room.breach.curl.back', '……', 'room.breach')
    ],
  },
  {
    id: 'room.breach.why',
    speaker: undefined,
    text: '不是为了逃。往外是水，逃不了。\n是为了离那个声音更近一米。',
    corruptedText: cor([40, '不是为了逃。是为了近一米。一米也算。']),
    tags: ['key'],
    onEnter: [learn('k.they-wanted-out-to-it'), san(-10), fear(12)],
    choices: [go('room.breach.why.ok', '……', 'room.breach')],
  },
  {
    id: 'room.breach.look',
    speaker: undefined,
    text: '对面那间是泵舱。水到膝盖，水面上浮着一层白色的沫。\n沫在动，动得很规律。',
    corruptedText: cor([45, '水到膝盖，浮着白沫。沫在动。规律和你的呼吸一样。']),
    tags: ['key'],
    onEnter: [fear(10), setf('know.foam-moves')],
    choices: [
      c({
        id: 'room.breach.look.hold',
        label: '屏住呼吸再看。',
        cost: 5,
        effects: [setf('did.held-breath-at-foam'), san(-10), fear(14)],
        goto: 'room.breach.foam',
      }),
      go('room.breach.look.back', '不看了。', 'room.breach')
    ],
  },
  {
    id: 'room.breach.foam',
    speaker: undefined,
    text: '沫停了。\n你一呼气，它又开始动。',
    corruptedText: cor([40, '你屏气，沫停。你呼气，沫动。它跟着你，不是跟着水。']),
    tags: ['key'],
    onEnter: [learn('k.ship-breathes-with-you'), san(-10), fear(16)],
    choices: [go('room.breach.foam.ok', '……', 'room.breach')],
  },
  {
    id: 'room.breach.paint',
    speaker: undefined,
    text: '洞边的漆有两层。外面那层新，盖住了一行字的一半。\n露出来的是：「此处将」。',
    corruptedText: cor([40, '漆两层。外层盖住一行字：「此处将」。后面被盖了。']),
    tags: ['key'],
    onEnter: [setf('know.paint-over-words'), san(-6)],
    choices: [
      c({
        id: 'room.breach.paint.scrape',
        label: '刮掉新漆。',
        cost: 6,
        requires: item('wrench'),
        gateMode: 'disable',
        effects: [setf('did.scraped-paint'), loud(8), san(-8)],
        goto: 'room.breach.words',
      }),
      go('room.breach.paint.back', '……', 'room.breach')
    ],
  },
  {
    id: 'room.breach.words',
    speaker: undefined,
    text: '「此处将开。」\n字是在造船的时候刷上去的。比这个洞早很多年。',
    corruptedText: cor([40, '「此处将开。」刷在造船的时候。洞是后来按字开的。']),
    tags: ['key'],
    onEnter: [learn('k.hull-was-designed-to-open'), san(-12), fear(14)],
    choices: [go('room.breach.words.ok', '……', 'room.breach')],
  },
  {
    id: 'room.breach.through',
    speaker: undefined,
    text: '钻过去的时候后背刮到卷边。衣服破了，皮没破。\n卷边的锋口朝你这边——它是被从你这边推弯的。',
    corruptedText: cor([40, '锋口朝你这边。你是第十八个从这边钻过去的人。']),
    tags: ['key'],
    onEnter: [learn('k.breach-from-inside'), setf('did.crossed-breach'), fear(8)],
    choices: [
      go('room.breach.through.pump', '进泵舱。', 'room.pump'),
      go('room.breach.through.back', '钻回去。', 'room.breach')
    ],
  },

  // --------------------------------------------------------------------- 泵舱
  {
    id: 'room.pump',
    speaker: undefined,
    text: '泵舱。水到膝盖，凉。泵在转，但排出口朝里。\n有人把管子接反了，接得很仔细，每个卡箍都上了螺丝。',
    corruptedText: cor(
      [50, '泵在转，排出口朝里。管子接反了，每个卡箍都上了螺丝。'],
      [20, '管子接反了。上螺丝的是你，你记得那个扭矩。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.entered-pump'), sfx('pump.reverse'), fear(8)],
    choices: [
      c({
        id: 'room.pump.clamps',
        label: '看卡箍。',
        cost: 3,
        effects: [learn('k.pumps-reversed'), setf('did.examined-clamps')],
        goto: 'room.pump.clamps',
      }),
      c({
        id: 'room.pump.fix',
        label: '把管子接回去。',
        cost: 12,
        requires: item('wrench'),
        gateMode: 'disable',
        effects: [setf('did.fixed-pumps'), loud(18), mark('apostasy', 2)],
        goto: 'room.pump.fixed',
      }),
      c({
        id: 'room.pump.off',
        label: '关泵。',
        cost: 6,
        effects: [setf('did.killed-pump'), loud(-4), mark('silence', 1)],
        goto: 'room.pump.off',
      }),
      c({
        id: 'room.pump.wrench',
        label: '水底下有东西。',
        cost: 5,
        requires: off('did.took-wrench'),
        gateMode: 'hide',
        effects: [give('wrench'), setf('did.took-wrench')],
        goto: 'room.pump.wrench',
      }),
      c({ id: 'room.pump.out', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.pump.clamps',
    speaker: undefined,
    text: '八个卡箍，扭矩一样。装的人不慌。\n最后一个卡箍上有一圈布纹的印子——他用衣服垫着上的，怕响。',
    corruptedText: cor([40, '八个卡箍扭矩一样。最后一个垫了衣服，怕响。他知道有东西在听。']),
    tags: ['key'],
    onEnter: [learn('k.pumps-reversed'), setf('know.he-was-afraid-of-noise'), san(-6)],
    choices: [go('room.pump.clamps.ok', '……', 'room.pump')],
  },
  {
    id: 'room.pump.fixed',
    speaker: undefined,
    text: '管子接回去了，水位开始降。\n降了两指，停住。外面的进水和泵的排量刚好相等。',
    corruptedText: cor([40, '水降了两指就停。进水和排量刚好相等。这个平衡是设计出来的。']),
    tags: ['key'],
    onEnter: [setf('did.fixed-pumps'), learn('k.hull-was-designed-to-open'), addf('count.futile-acts', 1)],
    choices: [go('room.pump.fixed.ok', '……', 'room.pump')],
  },
  {
    id: 'room.pump.off',
    speaker: undefined,
    text: '泵停了。舱里安静下来，能听见水面上那层沫的声音。\n沫的声音是细的，像有人在嘴里含着水说话。',
    corruptedText: cor([40, '泵停了。能听见沫的声音。像有人含着水说话。它在说你的名字。']),
    tags: ['key'],
    onEnter: [setf('did.killed-pump'), fear(12), san(-6), sfx('silence.total')],
    choices: [
      c({
        id: 'room.pump.off.listen',
        label: '听。',
        cost: 6,
        effects: [mark('listening', 2), san(-10), setf('did.listened-to-foam')],
        goto: 'room.pump.foamvoice',
      }),
      c({
        id: 'room.pump.off.restart',
        label: '重新开泵。',
        cost: 4,
        effects: [setf('did.restarted-pump'), loud(14)],
        goto: 'room.pump',
      })
    ],
  },
  {
    id: 'room.pump.foamvoice',
    speaker: undefined,
    text: '不是名字。是一个音节，重复，八次一组。\n八次之后停半拍，再来。',
    corruptedText: cor([40, '一个音节，八次一组，停半拍。半拍是给你接的。']),
    tags: ['key'],
    onEnter: [learn('k.eight-strokes'), mark('listening', 1), san(-10)],
    choices: [
      c({
        id: 'room.pump.foamvoice.join',
        label: '在半拍里出声。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.answered-the-half-beat'), mark('listening', 3), san(-14), fear(18)],
        goto: 'room.pump.answered',
      }),
      c({
        id: 'room.pump.foamvoice.stop',
        label: '闭嘴，走。',
        cost: 3,
        effects: [mark('silence', 2), setf('did.refused-half-beat')],
        goto: 'room.pump',
      })
    ],
  },
  {
    id: 'room.pump.answered',
    speaker: undefined,
    text: '你出声之后，沫不动了。\n半拍之后，它把你刚才那个音节还给你。还得很准。',
    corruptedText: cor([40, '沫不动了。它把你的音节还给你，还得很准。它学会了。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), san(-12), fear(20), sfx('deep.answer')],
    choices: [go('room.pump.answered.ok', '……', 'room.pump')],
  },
  {
    id: 'room.pump.wrench',
    speaker: undefined,
    text: '水底下是一把管钳，柄上缠着胶布。\n胶布的缠法是左手缠的。',
    corruptedText: cor([40, '一把管钳，胶布左手缠的。你是左手。']),
    tags: ['key'],
    onEnter: [give('wrench'), setf('know.left-handed-tape')],
    choices: [go('room.pump.wrench.ok', '……', 'room.pump')],
  },

  // ------------------------------------------------------------------- 声呐室
  {
    id: 'room.sonar',
    speaker: undefined,
    text: '声呐室。屏幕黑着，但纸带走纸机还在走，一格一格地吐。\n吐出来的纸带上没有回波，只有一条直线。',
    corruptedText: cor(
      [50, '纸带上只有一条直线。直线在第二十格的位置有一个小缺口。'],
      [20, '直线上每隔二十格有一个缺口。缺口的数量是十七个。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.entered-sonar'), sfx('sonar.paper')],
    choices: [
      c({
        id: 'room.sonar.tape',
        label: '拉出纸带看。',
        cost: 4,
        effects: [setf('did.read-sonar-tape'), learn('k.sonar-line')],
        goto: 'room.sonar.tape',
      }),
      c({
        id: 'room.sonar.active',
        label: '打一次主动声呐。',
        cost: 10,
        effects: [setf('did.pinged'), loud(40), sfx('sonar.ping')],
        goto: 'room.sonar.ping',
      }),
      c({
        id: 'room.sonar.hydro',
        label: '接上水听器听。',
        cost: 6,
        effects: [setf('did.used-hydrophone'), mark('listening', 1)],
        goto: 'room.sonar.hydro',
      }),
      c({
        id: 'room.sonar.array',
        label: '查一下声呐阵的朝向。',
        cost: 5,
        requires: K('k.sonar-line'),
        gateMode: 'disable',
        effects: [setf('did.checked-array')],
        goto: 'room.sonar.array',
      }),
      c({ id: 'room.sonar.out', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.sonar.tape',
    speaker: undefined,
    text: '直线，二十天的直线。二十天里这条船周围什么都没有。\n直线上每隔一段有一个小缺口，缺口的宽度是半拍。',
    corruptedText: cor([45, '二十天的直线。每隔一段一个缺口，宽度半拍。缺口不是故障。']),
    tags: ['key'],
    onEnter: [learn('k.sonar-line'), san(-6)],
    choices: [
      c({
        id: 'room.sonar.tape.count',
        label: '数缺口。',
        cost: 5,
        effects: [setf('did.counted-gaps'), addf('count.breaths-counted', 17), san(-8)],
        goto: 'room.sonar.gaps',
      }),
      go('room.sonar.tape.back', '放手。', 'room.sonar')
    ],
  },
  {
    id: 'room.sonar.gaps',
    speaker: undefined,
    text: '十七个。\n第十八个缺口正在被吐出来，吐到一半。',
    corruptedText: cor([40, '十七个。第十八个正在吐，吐到一半。你就是这一半。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-10), fear(14)],
    choices: [go('room.sonar.gaps.ok', '……', 'room.sonar')],
  },
  {
    id: 'room.sonar.ping',
    speaker: undefined,
    text: '一声。整条船都听见了。\n回波该在四秒后回来。第三秒的时候回来了。',
    corruptedText: cor([45, '回波该四秒，第三秒回来了。东西比你想的近一半。']),
    tags: ['key'],
    onEnter: [fear(20), san(-8), setf('know.echo-too-early'), loud(30)],
    choices: [
      c({
        id: 'room.sonar.ping.again',
        label: '再打一次。',
        cost: 10,
        effects: [setf('did.pinged-twice'), loud(40), fear(20), san(-10)],
        goto: 'room.sonar.ping2',
      }),
      c({
        id: 'room.sonar.ping.stop',
        label: '关掉，别再打。',
        cost: 2,
        effects: [mark('silence', 1), setf('did.stopped-pinging')],
        goto: 'room.sonar',
      })
    ],
  },
  {
    id: 'room.sonar.ping2',
    speaker: undefined,
    text: '第二声。回波在第二秒回来。\n第三声不用打了：它在往这边来，而且它知道你在数。',
    corruptedText: cor([40, '第二声，回波两秒。它在过来，而且知道你在数。']),
    tags: ['key'],
    onEnter: [fear(26), san(-12), fight('enc.hymn-hunter')],
    choices: [go('room.sonar.ping2.flee', '离开声呐室。', 'room.sonar')],
  },
  {
    id: 'room.sonar.hydro',
    speaker: undefined,
    text: '水听器里是低频的底噪，和广播里那层底噪一样。\n一样到你能听出同一个磁带缺陷的位置。',
    corruptedText: cor([45, '水听器的底噪和广播的一样。同一个磁带缺陷。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-spliced'), san(-8), mark('listening', 1)],
    choices: [
      c({
        id: 'room.sonar.hydro.mean',
        label: '广播的底噪来自外面。',
        cost: 3,
        requires: on('met.mother'),
        gateMode: 'disable',
        effects: [learn('k.mother-is-spliced'), setf('know.pa-source-outside'), san(-10)],
        goto: 'room.sonar.source',
      }),
      go('room.sonar.hydro.back', '拔下来。', 'room.sonar')
    ],
  },
  {
    id: 'room.sonar.source',
    speaker: undefined,
    text: '广播的信号不是从舱内发出的。是从舷外接进来，再放大。\n放大器上贴着一张手写标签：「转接：母」。',
    corruptedText: cor([40, '广播从舷外接进来再放大。标签：「转接：母」。她在外面。']),
    tags: ['key'],
    onEnter: [learn('k.mother-is-spliced'), learn('k.mother-is-sample-three'), san(-12), fear(16)],
    choices: [go('room.sonar.source.ok', '……', 'room.sonar')],
  },
  {
    id: 'room.sonar.array',
    speaker: undefined,
    text: '声呐阵不是装在艏部。是装在腹部，朝下。\n一条船把耳朵装在肚子上，就不是为了看前面。',
    corruptedText: cor([40, '声呐阵在腹部朝下。耳朵装在肚子上，不是为了看前面。']),
    tags: ['key'],
    onEnter: [learn('k.listening-array'), san(-8)],
    choices: [
      c({
        id: 'room.sonar.array.down',
        label: '朝下多少度。',
        cost: 3,
        effects: [setf('did.checked-array-angle'), learn('k.listening-array')],
        goto: 'room.sonar.angle',
      }),
      go('room.sonar.array.back', '……', 'room.sonar')
    ],
  },
  {
    id: 'room.sonar.angle',
    speaker: undefined,
    text: '九十度。正下方。\n这条船设计的时候，就已经知道那个东西在哪一层。',
    corruptedText: cor([40, '九十度，正下方。造船的时候就知道它在哪一层。船是照着它造的。']),
    tags: ['key'],
    onEnter: [learn('k.listening-array'), learn('k.not-research'), san(-10)],
    choices: [go('room.sonar.angle.ok', '……', 'room.sonar')],
  },

  // --------------------------------------------------------------------- 月池
  {
    id: 'room.moonpool',
    speaker: undefined,
    text: '月池。舱底一个方口，直通外面的水。水面比舱底高两指，不溢。\n两指的高度没有变过。',
    corruptedText: cor(
      [50, '水面高两指，不溢。两指没有变过。压力上这不可能。'],
      [20, '水面高两指。你数过很多次，每次都是两指。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.found-moonpool'), fear(14), sfx('water.still')],
    choices: [
      c({
        id: 'room.moonpool.edge',
        label: '走到池边。',
        cost: 3,
        effects: [setf('did.approached-pool'), fear(10)],
        goto: 'room.moonpool.edge',
      }),
      c({
        id: 'room.moonpool.hand',
        label: '把手伸进水里。',
        cost: 5,
        effects: [setf('did.touched-pool'), fear(16), san(-8)],
        goto: 'room.moonpool.hand',
      }),
      c({
        id: 'room.moonpool.speak',
        label: '对着水说一句话。',
        cost: 6,
        requires: K('k.the-word'),
        gateMode: 'lie',
        effects: [mark('listening', 2)],
        goto: 'room.moonpool.spoke',
      }),
      c({
        id: 'room.moonpool.rope',
        label: '看池边的绳子。',
        cost: 3,
        effects: [setf('did.examined-pool-rope')],
        goto: 'room.moonpool.rope',
      }),
      c({ id: 'room.moonpool.leave', label: '离开月池。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.moonpool.edge',
    speaker: undefined,
    text: '池边的钢板被磨圆了，磨的位置在一米宽的一段上。\n那一段正好是一个人跪着的宽度。',
    corruptedText: cor([45, '钢板磨圆了一米宽。正好是一个人跪着的宽度。磨了很多年。']),
    tags: ['key'],
    onEnter: [setf('know.pool-kneel-mark'), san(-6)],
    choices: [
      c({
        id: 'room.moonpool.edge.kneel',
        label: '跪下去。',
        cost: 4,
        effects: [setf('did.knelt-at-pool'), mark('listening', 1), san(-8)],
        goto: 'room.moonpool.kneel',
      }),
      go('room.moonpool.edge.back', '站着。', 'room.moonpool')
    ],
  },
  {
    id: 'room.moonpool.kneel',
    speaker: undefined,
    text: '跪下去以后，膝盖正好落在磨圆的地方。\n磨痕的宽度和你的膝距一样。',
    corruptedText: cor([40, '膝盖正好落在磨痕上。宽度和你的膝距一样。一样是因为一直是你。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-10), fear(12)],
    choices: [go('room.moonpool.kneel.ok', '……', 'room.moonpool')],
  },
  {
    id: 'room.moonpool.hand',
    speaker: undefined,
    text: '水是温的。\n这个深度的海水应该是两度。',
    corruptedText: cor([45, '水是温的。这个深度应该两度。温的东西在下面。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), fear(18), san(-8)],
    choices: [
      c({
        id: 'room.moonpool.hand.deeper',
        label: '整条手臂伸下去。',
        cost: 8,
        effects: [setf('did.arm-in-pool'), fear(22), san(-12), mark('drowned', 1)],
        goto: 'room.moonpool.arm',
      }),
      c({
        id: 'room.moonpool.hand.out',
        label: '把手抽出来。',
        cost: 2,
        effects: [mark('silence', 1)],
        goto: 'room.moonpool',
      })
    ],
  },
  {
    id: 'room.moonpool.arm',
    speaker: undefined,
    text: '手臂下去到肘，有东西碰了一下你的手背。\n不是推，是碰。碰的力度像认人。',
    corruptedText: cor([40, '有东西碰了你的手背。不是推，是碰。力度像认人。它认得。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), fear(26), san(-14), sfx('deep.answer')],
    choices: [
      c({
        id: 'room.moonpool.arm.stay',
        label: '不动。',
        cost: 6,
        effects: [setf('did.let-it-touch'), mark('listening', 2), san(-12)],
        goto: 'room.moonpool.touched',
      }),
      c({
        id: 'room.moonpool.arm.yank',
        label: '猛地抽回来。',
        cost: 4,
        effects: [setf('did.yanked-arm'), loud(12), fear(10)],
        goto: 'room.moonpool',
      })
    ],
  },
  {
    id: 'room.moonpool.touched',
    speaker: undefined,
    text: '它在你手背上敲了八下。\n第九下没有来。它在等。',
    corruptedText: cor([40, '它敲了八下。第九下没来。它在等你敲。']),
    tags: ['key'],
    onEnter: [learn('k.eight-strokes'), learn('k.signal-is-real'), san(-12), fear(20)],
    choices: [
      c({
        id: 'room.moonpool.touched.knock',
        label: '敲第九下。',
        cost: 6,
        irreversible: true,
        effects: [setf('did.knocked-ninth'), mark('listening', 3), san(-16)],
        goto: 'room.moonpool.ninth',
      }),
      c({
        id: 'room.moonpool.touched.no',
        label: '不敲。抽手。',
        cost: 4,
        effects: [mark('silence', 2), setf('did.refused-ninth')],
        goto: 'room.moonpool',
      })
    ],
  },
  {
    id: 'room.moonpool.ninth',
    speaker: undefined,
    text: '你敲了。它松开手。\n水面还是高两指。',
    corruptedText: cor([40, '你敲了。它松手。水面还是两指。它只是想确认你会敲。']),
    tags: ['key'],
    onEnter: [setf('know.it-only-wanted-confirmation'), learn('k.author-is-not-it'), san(-10)],
    choices: [go('room.moonpool.ninth.ok', '……', 'room.moonpool')],
  },
  {
    id: 'room.moonpool.spoke',
    speaker: undefined,
    text: '你说了那个八笔的字。\n水面上起了一圈，从中心往外，圈的中心不在你脚下。',
    corruptedText: cor([40, '你说了那个字。水面起圈。圈的中心不在你脚下，在你背后。']),
    tags: ['key'],
    onEnter: [mark('listening', 2), fear(20), san(-12), sfx('water.ring')],
    choices: [
      c({
        id: 'room.moonpool.spoke.turn',
        label: '回头。',
        cost: 3,
        effects: [setf('did.turned-at-pool'), fear(16)],
        goto: 'room.moonpool.behind',
      }),
      c({
        id: 'room.moonpool.spoke.no',
        label: '不回头。',
        cost: 3,
        effects: [mark('silence', 1), setf('did.didnt-turn'), san(4)],
        goto: 'room.moonpool',
      })
    ],
  },
  {
    id: 'room.moonpool.behind',
    speaker: undefined,
    text: '背后是一堵舱壁，湿的。\n湿的形状是一个人靠过的形状，还在往下滴。',
    corruptedText: cor([40, '舱壁上有一个人靠过的湿印，还在滴。印子的肩宽和你一样。']),
    tags: ['key'],
    onEnter: [fear(20), san(-10), setf('know.wet-silhouette')],
    choices: [go('room.moonpool.behind.ok', '……', 'room.moonpool')],
  },
  {
    id: 'room.moonpool.rope',
    speaker: undefined,
    text: '池边系着一条绳，另一头在水里。绳很紧。\n绳上每隔一臂长打一个结，一共十七个结。',
    corruptedText: cor([40, '绳上十七个结。第十八个结打了一半，线头还散着。']),
    tags: ['key'],
    onEnter: [setf('know.rope-knots'), san(-6)],
    choices: [
      c({
        id: 'room.moonpool.rope.pull',
        label: '拉绳。',
        cost: 10,
        effects: [setf('did.pulled-rope'), fear(18), loud(10)],
        goto: 'room.moonpool.pulled',
      }),
      c({
        id: 'room.moonpool.rope.cut',
        label: '割断。',
        cost: 5,
        requires: item('scalpel'),
        gateMode: 'disable',
        effects: [setf('did.cut-rope'), mark('apostasy', 2)],
        goto: 'room.moonpool.cut',
      }),
      go('room.moonpool.rope.back', '放手。', 'room.moonpool')
    ],
  },
  {
    id: 'room.moonpool.pulled',
    speaker: undefined,
    text: '拉上来的是一副空的呼吸器，带子扣着，扣得很整齐。\n扣的那个人不是急着解开跑掉的。',
    corruptedText: cor([40, '一副空呼吸器，带子扣得整齐。他不是急着跑。他是脱下来放好的。']),
    tags: ['key'],
    onEnter: [give('rebreather'), learn('k.they-wanted-out-to-it'), san(-8)],
    choices: [go('room.moonpool.pulled.ok', '……', 'room.moonpool')],
  },
  {
    id: 'room.moonpool.cut',
    speaker: undefined,
    text: '绳断了，那头沉下去，很慢。\n慢到你能看清它是被什么东西轻轻接住的。',
    corruptedText: cor([40, '绳沉得很慢。慢到看清它被接住了。接的时候很小心。']),
    tags: ['key'],
    onEnter: [fear(18), san(-10), setf('know.something-caught-the-rope')],
    choices: [go('room.moonpool.cut.ok', '……', 'room.moonpool')],
  },

  // ------------------------------------------------------------------- 医务室
  {
    id: 'room.sickbay',
    speaker: undefined,
    text: '医务室。三张床，床单都叠成同一个角度。\n药柜开着，里面缺的只有镇静剂。',
    corruptedText: cor(
      [50, '床单叠成同一个角度。缺的只有镇静剂。'],
      [20, '床单叠得一样。缺的只有镇静剂。三张床都睡过，都叠回去了。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.entered-sickbay')],
    choices: [
      c({
        id: 'room.sickbay.cabinet',
        label: '翻药柜。',
        cost: 4,
        effects: [setf('did.searched-meds'), give('sedative')],
        goto: 'room.sickbay.meds',
      }),
      c({
        id: 'room.sickbay.chart',
        label: '看床头的病历。',
        cost: 3,
        effects: [setf('did.read-charts')],
        goto: 'room.sickbay.chart',
      }),
      c({
        id: 'room.sickbay.bed',
        label: '躺一下。',
        cost: 8,
        effects: [setf('did.lay-down'), san(8), addf('count.rests', 1)],
        goto: 'room.sickbay.bed',
      }),
      c({
        id: 'room.sickbay.ears',
        label: '看耳科器械那一格。',
        cost: 4,
        requires: K('k.listening-array'),
        gateMode: 'disable',
        effects: [setf('did.found-ear-tools')],
        goto: 'room.sickbay.ears',
      }),
      c({ id: 'room.sickbay.out', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.sickbay.meds',
    speaker: undefined,
    text: '别的药一瓶不少：止疼、抗生素、维生素。\n只有镇静剂空了，空瓶整齐地放回了原位。',
    corruptedText: cor([45, '只有镇静剂空了。空瓶放回原位。放回去的人有条理。']),
    tags: ['key'],
    onEnter: [setf('know.only-sedatives-gone'), give('sedative')],
    choices: [go('room.sickbay.meds.ok', '……', 'room.sickbay')],
  },
  {
    id: 'room.sickbay.chart',
    speaker: '病历',
    text: '三张病历，同一个诊断，同一支笔。\n诊断那一栏写的是：「听力过敏。建议继续。」',
    corruptedText: cor([45, '三张病历，同一个诊断：「听力过敏。建议继续。」建议继续什么没有写。']),
    tags: ['key'],
    onEnter: [learn('k.not-research'), san(-8)],
    choices: [
      c({
        id: 'room.sickbay.chart.continue',
        label: '"建议继续"。',
        cost: 3,
        requires: K('k.not-research'),
        gateMode: 'disable',
        effects: [learn('k.cult-was-right'), setf('did.read-recommendation')],
        goto: 'room.sickbay.continue',
      }),
      go('room.sickbay.chart.back', '放下。', 'room.sickbay')
    ],
  },
  {
    id: 'room.sickbay.continue',
    speaker: undefined,
    text: '医生把"听得见"当成一种症状记录，然后建议继续暴露。\n他自己的病历在最下面，诊断一样。',
    corruptedText: cor([40, '他把听得见当症状，然后建议继续。他自己的病历在最下面，一样。']),
    tags: ['key'],
    onEnter: [learn('k.cult-was-right'), san(-10)],
    choices: [go('room.sickbay.continue.ok', '……', 'room.sickbay')],
  },
  {
    id: 'room.sickbay.bed',
    speaker: undefined,
    text: '躺下之后，天花板上有一行铅笔字，只有躺着才看得见。\n「醒了就走。别数。」',
    corruptedText: cor([45, '天花板上：「醒了就走。别数。」笔迹是你的。']),
    tags: ['key'],
    onEnter: [setf('did.saw-ceiling-note'), setf('know.dont-count'), san(-6)],
    choices: [
      c({
        id: 'room.sickbay.bed.hand',
        label: '这是谁的字。',
        cost: 3,
        requires: on('did.found-blank-page'),
        gateMode: 'disable',
        effects: [learn('k.previous-log-predicts'), san(-10)],
        goto: 'room.sickbay.hand',
      }),
      go('room.sickbay.bed.up', '起来。', 'room.sickbay')
    ],
  },
  {
    id: 'room.sickbay.hand',
    speaker: undefined,
    text: '和日志里那三页是同一只手。\n写在天花板上，是因为写的人知道下一个人会躺在这儿。',
    corruptedText: cor([40, '同一只手。写在天花板上，因为他知道下一个人会躺这儿。']),
    tags: ['key'],
    onEnter: [learn('k.previous-log-predicts'), san(-8)],
    choices: [go('room.sickbay.hand.ok', '……', 'room.sickbay')],
  },
  {
    id: 'room.sickbay.ears',
    speaker: undefined,
    text: '耳科那一格的器械比别的科齐全得多，而且有十九套。\n每套上刻着编号，从一到十九。',
    corruptedText: cor([40, '耳科器械十九套，刻着一到十九。第二十套的位置是空的，凹槽是新的。']),
    tags: ['key'],
    onEnter: [learn('k.listening-array'), san(-8), give('otoscope')],
    choices: [
      c({
        id: 'room.sickbay.ears.twenty',
        label: '第二十套的位置。',
        cost: 3,
        requires: on('know.twentieth-gap'),
        gateMode: 'hide',
        effects: [learn('k.you-are-sample-n'), san(-10)],
        goto: 'room.sickbay.twenty',
      }),
      go('room.sickbay.ears.back', '合上。', 'room.sickbay')
    ],
  },
  {
    id: 'room.sickbay.twenty',
    speaker: undefined,
    text: '凹槽是新的，绒布还立着。\n器械不在里面，因为正在用。',
    corruptedText: cor([40, '凹槽新的，绒布立着。器械正在用。用在你身上。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), fear(18), san(-10)],
    choices: [go('room.sickbay.twenty.ok', '……', 'room.sickbay')],
  },

  // ------------------------------------------------------------------- 机舱钟
  {
    id: 'room.bell',
    speaker: undefined,
    text: '机舱口挂着一口铜钟，绳子垂到膝盖。\n钟口朝上，里面积了一点水。',
    corruptedText: cor(
      [50, '钟口朝上，里面积了水。钟是倒挂的。倒挂的钟敲不响。'],
      [20, '钟倒挂着，里面的水是温的。'],
    ),
    tags: ['entry', 'key'],
    onEnter: [setf('did.found-bell'), sfx('ritual.bell')],
    choices: [
      c({
        id: 'room.bell.ring',
        label: '拉绳。',
        cost: 5,
        effects: [setf('did.rang-bell'), loud(26), sfx('bell.dead')],
        goto: 'room.bell.rung',
      }),
      c({
        id: 'room.bell.water',
        label: '看钟里的水。',
        cost: 3,
        effects: [setf('did.examined-bell-water')],
        goto: 'room.bell.water',
      }),
      c({
        id: 'room.bell.right',
        label: '把钟翻过来。',
        cost: 8,
        requires: item('wrench'),
        gateMode: 'disable',
        effects: [setf('did.righted-bell'), mark('apostasy', 1), loud(16)],
        goto: 'room.bell.righted',
      }),
      c({ id: 'room.bell.leave', label: '走开。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'room.bell.rung',
    speaker: undefined,
    text: '钟不响。钟舌被卸了，挂钉还在。\n卸的时候没有弄坏螺纹。',
    corruptedText: cor([40, '钟舌被卸了，螺纹没坏。卸的人打算装回去。']),
    tags: ['key'],
    onEnter: [setf('know.clapper-removed'), addf('count.futile-acts', 1)],
    choices: [
      c({
        id: 'room.bell.rung.find',
        label: '找钟舌。',
        cost: 6,
        effects: [give('clapper'), setf('did.found-clapper')],
        goto: 'room.bell.clapper',
      }),
      go('room.bell.rung.back', '算了。', 'room.bell')
    ],
  },
  {
    id: 'room.bell.clapper',
    speaker: undefined,
    text: '钟舌在旁边的工具箱里，用布包着，布是干的。\n布上有一行字：「等最后一个。」',
    corruptedText: cor([40, '钟舌用干布包着。布上：「等最后一个。」']),
    tags: ['key'],
    onEnter: [give('clapper'), setf('know.wait-for-the-last'), san(-8)],
    choices: [
      c({
        id: 'room.bell.clapper.install',
        label: '装回去，敲。',
        cost: 12,
        irreversible: true,
        effects: [setf('did.rang-the-real-bell'), loud(50), mark('apostasy', 3), sfx('bell.real')],
        goto: 'room.bell.real',
      }),
      c({
        id: 'room.bell.clapper.keep',
        label: '包好，带走。',
        cost: 3,
        effects: [setf('did.kept-clapper'), mark('silence', 1)],
        goto: 'room.bell',
      })
    ],
  },
  {
    id: 'room.bell.real',
    speaker: undefined,
    text: '钟响了。整条船都听见了，包括外面。\n响完之后，礼拜堂那边的点名停了一拍，然后从头开始。',
    corruptedText: cor([40, '钟响了。点名停了一拍，然后从头开始。从"第一"开始。']),
    tags: ['key'],
    onEnter: [setf('did.rang-the-real-bell'), fear(24), loud(40), setf('know.roll-restarted')],
    choices: [go('room.bell.real.ok', '……', 'room.bell')],
  },
  {
    id: 'room.bell.water',
    speaker: undefined,
    text: '钟里的水是温的，和月池一个温度。\n钟口朝上，所以水是从上面滴进去的。上面是舱顶。',
    corruptedText: cor([40, '水是温的，和月池一样。从舱顶滴进去的。舱顶上面还是水。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), san(-6), fear(10)],
    choices: [go('room.bell.water.ok', '……', 'room.bell')],
  },
  {
    id: 'room.bell.righted',
    speaker: undefined,
    text: '钟翻过来了，水倒在甲板上，流向舱口。\n流的方向和坡度相反。',
    corruptedText: cor([40, '水流的方向和坡度相反。它自己在往那边走。']),
    tags: ['key'],
    onEnter: [fear(16), san(-8), setf('know.water-flows-wrong')],
    choices: [go('room.bell.righted.ok', '……', 'room.bell')],
  },

  // --------------------------------------------------------------------- 冷库
  {
    id: 'room.cold',
    speaker: undefined,
    text: '冷库。断电了，但里面还是冷的。\n挂钩上挂着十九个空的布袋，袋口都朝下。',
    corruptedText: cor(
      [50, '十九个空布袋，袋口朝下。第二十个钩是空的。'],
      [20, '十九个袋子，袋口朝下。有一个在动。'],
    ),
    tags: ['entry', 'key'],
    onEnter: [setf('did.entered-cold'), fear(10)],
    choices: [
      c({
        id: 'room.cold.bags',
        label: '看布袋。',
        cost: 3,
        effects: [setf('did.examined-bags')],
        goto: 'room.cold.bags',
      }),
      c({
        id: 'room.cold.why',
        label: '断电了为什么还冷。',
        cost: 4,
        effects: [setf('did.asked-why-cold'), san(-6)],
        goto: 'room.cold.why',
      }),
      c({
        id: 'room.cold.moving',
        label: '有一个在动。',
        cost: 5,
        requires: on('did.examined-bags'),
        gateMode: 'hide',
        effects: [setf('did.checked-moving-bag'), fear(20)],
        goto: 'room.cold.moving',
      }),
      c({ id: 'room.cold.out', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.cold.bags',
    speaker: undefined,
    text: '袋口朝下，说明装过东西，倒空过。\n袋底的缝线都被从里面顶松了。',
    corruptedText: cor([40, '袋口朝下，倒空过。袋底缝线从里面顶松了。']),
    tags: ['key'],
    onEnter: [setf('know.bags-opened-from-inside'), fear(14), san(-8)],
    choices: [go('room.cold.bags.ok', '……', 'room.cold')],
  },
  {
    id: 'room.cold.why',
    speaker: undefined,
    text: '断电三天以上，冷库该回到舷外水温。\n舷外水温是两度。这里是零下。',
    corruptedText: cor([40, '舷外两度，这里零下。冷是从别处来的。']),
    tags: ['key'],
    onEnter: [setf('know.cold-from-elsewhere'), san(-8)],
    choices: [go('room.cold.why.ok', '……', 'room.cold')],
  },
  {
    id: 'room.cold.moving',
    speaker: undefined,
    text: '第七个袋子在动，很轻，一起一伏。\n频率是每四秒一次。你的呼吸也是每四秒一次。',
    corruptedText: cor([40, '第七个袋子一起一伏，四秒一次。和你的呼吸一样。']),
    tags: ['key'],
    onEnter: [fear(24), san(-12), setf('know.bag-breathes')],
    choices: [
      c({
        id: 'room.cold.moving.open',
        label: '解开它。',
        cost: 8,
        irreversible: true,
        effects: [setf('did.opened-the-bag'), fear(26), san(-16)],
        goto: 'room.cold.opened',
      }),
      c({
        id: 'room.cold.moving.hold',
        label: '屏住自己的呼吸。',
        cost: 6,
        effects: [setf('did.held-breath-at-bag'), san(-10), fear(18)],
        goto: 'room.cold.held',
      }),
      c({
        id: 'room.cold.moving.out',
        label: '出去，快。',
        cost: 3,
        effects: [setf('did.fled-cold'), mark('silence', 1)],
        goto: 'room.cold',
      })
    ],
  },
  {
    id: 'room.cold.opened',
    speaker: undefined,
    text: '袋子里是空的。\n但是袋子的内壁是湿的，湿得均匀，像刚被呼过。',
    corruptedText: cor([40, '袋子空的。内壁湿得均匀，像刚被呼过。呼的是你。']),
    tags: ['key'],
    onEnter: [learn('k.ship-breathes-with-you'), fear(22), san(-14)],
    choices: [go('room.cold.opened.ok', '……', 'room.cold')],
  },
  {
    id: 'room.cold.held',
    speaker: undefined,
    text: '你屏气的四秒里，袋子没有动。\n第五秒你吸气，它跟着起来。',
    corruptedText: cor([40, '你屏气，它不动。你吸气，它起来。它不是在呼吸。它在跟。']),
    tags: ['key'],
    onEnter: [learn('k.ship-breathes-with-you'), fear(20), san(-12)],
    choices: [go('room.cold.held.ok', '……', 'room.cold')],
  },

  // ----------------------------------------------------------------- 逃生管廊
  {
    id: 'room.trunk',
    speaker: undefined,
    text: '逃生管廊。一条垂直的钢管往上，梯子焊在内壁。\n梯子只有下半段。上半段被人拆了，切口是新的。',
    corruptedText: cor(
      [50, '梯子只有下半段。上半段被拆了，切口是新的。'],
      [20, '梯子只有下半段。上半段在你身后的地板上，摆得很整齐。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.found-escape-trunk'), sfx('hull.tick')],
    choices: [
      c({
        id: 'room.trunk.cut',
        label: '看切口。',
        cost: 3,
        effects: [setf('did.examined-ladder-cut'), learn('k.ladder-cut-from-below')],
        goto: 'room.trunk.cut',
      }),
      c({
        id: 'room.trunk.climb',
        label: '爬到断掉的地方。',
        cost: 10,
        effects: [setf('did.climbed-trunk'), fear(12)],
        goto: 'room.trunk.top',
      }),
      c({
        id: 'room.trunk.hatch',
        label: '抬头看上面的舱盖。',
        cost: 3,
        effects: [setf('did.looked-at-hatch')],
        goto: 'room.trunk.hatch',
      }),
      c({
        id: 'room.trunk.pieces',
        label: '找拆下来的梯段。',
        cost: 5,
        requires: on('did.examined-ladder-cut'),
        gateMode: 'hide',
        effects: [setf('did.found-ladder-pieces')],
        goto: 'room.trunk.pieces',
      }),
      c({ id: 'room.trunk.leave', label: '离开管廊。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.trunk.cut',
    speaker: undefined,
    text: '切口是气割的，割痕从下往上溅。\n站在下面割自己的出路，割得很平。',
    corruptedText: cor([40, '气割，溅痕从下往上。有人站在下面割掉了自己的出路，割得很平。']),
    tags: ['key'],
    onEnter: [learn('k.ladder-cut-from-below'), san(-8)],
    choices: [
      c({
        id: 'room.trunk.cut.who',
        label: '谁会割掉自己的梯子。',
        cost: 3,
        requires: K('k.all-volunteers'),
        gateMode: 'disable',
        effects: [learn('k.cult-was-right'), setf('did.understood-ladder')],
        goto: 'room.trunk.who',
      }),
      go('room.trunk.cut.back', '……', 'room.trunk')
    ],
  },
  {
    id: 'room.trunk.who',
    speaker: undefined,
    text: '十九个人里，只要有一个人想上去，梯子就不会被割。\n梯子被割了。',
    corruptedText: cor([40, '只要一个人想上去，梯子就不会被割。梯子被割了。十九票。']),
    tags: ['key'],
    onEnter: [learn('k.all-volunteers'), learn('k.cult-was-right'), san(-10)],
    choices: [go('room.trunk.who.ok', '……', 'room.trunk')],
  },
  {
    id: 'room.trunk.top',
    speaker: undefined,
    text: '爬到断口，上面还有四米。\n四米的管壁上有很多手抓的痕，叠在一起，都在同一个高度。',
    corruptedText: cor([40, '上面还有四米。管壁上很多手印，都在同一个高度。都没上去。']),
    tags: ['key'],
    onEnter: [fear(14), san(-8), setf('know.handprints-same-height')],
    choices: [
      c({
        id: 'room.trunk.top.jump',
        label: '跳一下试试。',
        cost: 10,
        effects: [setf('did.jumped-for-ladder'), addf('count.futile-acts', 1), loud(14)],
        goto: 'room.trunk.jump',
      }),
      go('room.trunk.top.down', '下去。', 'room.trunk')
    ],
  },
  {
    id: 'room.trunk.jump',
    speaker: undefined,
    text: '差一臂。落地的时候脚踝扭了一下。\n手抓的新痕加在那一层旧痕上，位置正好重合。',
    corruptedText: cor([40, '差一臂。你的新手印落在旧手印上，正好重合。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), san(-8), fear(10)],
    choices: [go('room.trunk.jump.ok', '……', 'room.trunk')],
  },
  {
    id: 'room.trunk.hatch',
    speaker: undefined,
    text: '舱盖是内开的，锁在里侧。锁着。\n锁上没有锈，钥匙孔里有油。',
    corruptedText: cor([40, '舱盖内开，锁在里侧，锁着。锁没锈，孔里有油。有人在保养它。']),
    tags: ['key'],
    onEnter: [setf('know.hatch-maintained'), san(-6)],
    choices: [
      c({
        id: 'room.trunk.hatch.key',
        label: '钥匙会在谁身上。',
        cost: 3,
        requires: on('met.dorn'),
        gateMode: 'disable',
        effects: [setf('did.wondered-about-key'), learn('k.dorn-tied-himself')],
        goto: 'room.trunk.key',
      }),
      go('room.trunk.hatch.back', '……', 'room.trunk')
    ],
  },
  {
    id: 'room.trunk.key',
    speaker: undefined,
    text: '大副管钥匙。大副把自己绑在了椅子上。\n绑的人如果拿着钥匙，绑就有意义。',
    corruptedText: cor([40, '大副管钥匙。大副把自己绑在椅子上。他拿着钥匙，所以绑才有意义。']),
    tags: ['key'],
    onEnter: [learn('k.dorn-tied-himself'), setf('know.dorn-has-key'), san(-8)],
    choices: [go('room.trunk.key.ok', '……', 'room.trunk')],
  },
  {
    id: 'room.trunk.pieces',
    speaker: undefined,
    text: '拆下来的梯段在管廊底下，靠墙摆着，一段一段对齐。\n对齐这件事没有任何用处。',
    corruptedText: cor([40, '梯段靠墙摆着，一段一段对齐。对齐没有用处。他只是习惯把东西摆好。']),
    tags: ['key'],
    onEnter: [setf('know.pieces-aligned'), san(-4)],
    choices: [
      c({
        id: 'room.trunk.pieces.rebuild',
        label: '把梯子接回去。',
        cost: 16,
        requires: item('wrench'),
        gateMode: 'lie',
        effects: [setf('did.tried-rebuild-ladder'), loud(24)],
        goto: 'room.trunk.rebuilt',
      }),
      go('room.trunk.pieces.back', '……', 'room.trunk')
    ],
  },
  {
    id: 'room.trunk.rebuilt',
    speaker: undefined,
    text: '接上了三段，第四段的焊点断了。\n断的地方是旧焊——有人接过，也断过。',
    corruptedText: cor([40, '第四段焊点断了，是旧焊。有人接过，也断过。接了十七次。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), addf('count.futile-acts', 1), san(-8)],
    choices: [go('room.trunk.rebuilt.ok', '……', 'room.trunk')],
  },

  // --------------------------------------------------------------------- 铺位
  {
    id: 'room.bunks',
    speaker: undefined,
    text: '通铺舱。十九个铺位，铺得一样平。\n只有一个铺是乱的，被子往一边掀开，形状还在。',
    corruptedText: cor(
      [50, '十九个铺位，一个是乱的。被子掀开的形状还在，是你刚起来那个形状。'],
      [20, '十九个铺位。乱的那个每次都是同一个。'],
    ),
    tags: ['entry', 'key', 'hub'],
    onEnter: [setf('did.entered-bunks')],
    choices: [
      c({
        id: 'room.bunks.mine',
        label: '找自己那个铺。',
        cost: 3,
        effects: [setf('did.found-own-bunk'), learn('k.your-bunk')],
        goto: 'room.bunks.mine',
      }),
      c({
        id: 'room.bunks.others',
        label: '翻别人的铺。',
        cost: 5,
        effects: [setf('did.searched-bunks'), give('photo')],
        goto: 'room.bunks.others',
      }),
      c({
        id: 'room.bunks.under',
        label: '看铺底下。',
        cost: 4,
        effects: [setf('did.looked-under-bunks')],
        goto: 'room.bunks.under',
      }),
      c({
        id: 'room.bunks.make',
        label: '把乱的那个铺好。',
        cost: 5,
        effects: [setf('did.made-the-bed'), mark('silence', 1), san(4)],
        goto: 'room.bunks.made',
      }),
      c({ id: 'room.bunks.out', label: '出去。', cost: 2, effects: [] })
    ],
  },
  {
    id: 'room.bunks.mine',
    speaker: undefined,
    text: '铺位牌上是你的名字。牌是铝的，字是刻的。\n刻痕的深度和别的牌不一样——浅，像刻了又磨平再刻。',
    corruptedText: cor([45, '你的名字刻痕浅，像刻了又磨平再刻。磨过十七次。']),
    tags: ['key'],
    onEnter: [learn('k.your-bunk'), setf('did.read-own-plate'), san(-8)],
    choices: [
      c({
        id: 'room.bunks.mine.take',
        label: '把牌摘下来。',
        cost: 3,
        effects: [give('nameplate'), setf('did.took-nameplate')],
        goto: 'room.bunks.plate',
      }),
      go('room.bunks.mine.back', '留着。', 'room.bunks')
    ],
  },
  {
    id: 'room.bunks.plate',
    speaker: undefined,
    text: '牌背面有一排很小的刻痕，正字。\n数到十七画的时候，第十八画只刻了一横。',
    corruptedText: cor([40, '牌背面是正字。十七画，第十八画只有一横。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), give('nameplate'), san(-10)],
    choices: [go('room.bunks.plate.ok', '……', 'room.bunks')],
  },
  {
    id: 'room.bunks.others',
    speaker: undefined,
    text: '别人的铺底下都放着同样的东西：一双干的靴子，一张照片，一本唱诗本。\n靴子都是干的。',
    corruptedText: cor([45, '每个铺底下：干靴子、照片、唱诗本。靴子都是干的。谁都没打算再走路。']),
    tags: ['key'],
    onEnter: [give('photo'), give('hymnal'), setf('know.dry-boots')],
    choices: [
      c({
        id: 'room.bunks.others.hymnal',
        label: '翻唱诗本。',
        cost: 4,
        effects: [setf('did.read-hymnal'), setf('know.hymnal-coords')],
        goto: 'room.bunks.hymnal',
      }),
      c({
        id: 'room.bunks.others.photo',
        label: '看照片。',
        cost: 3,
        effects: [setf('did.looked-at-photo')],
        goto: 'room.bunks.photo',
      }),
      go('room.bunks.others.back', '放回去。', 'room.bunks')
    ],
  },
  {
    id: 'room.bunks.hymnal',
    speaker: '唱诗本',
    text: '不是歌。是一张表：编号、名字、坐标。\n十九行，第二十行只有坐标。',
    corruptedText: cor([45, '编号、名字、坐标。十九行。第二十行只有坐标，没有名字。']),
    tags: ['key'],
    onEnter: [setf('know.hymnal-coords'), learn('k.manifest-nineteen'), san(-6)],
    choices: [
      c({
        id: 'room.bunks.hymnal.coord',
        label: '第二十行的坐标是哪。',
        cost: 4,
        requires: on('did.found-moonpool'),
        gateMode: 'disable',
        effects: [setf('did.decoded-coords'), san(-8)],
        goto: 'room.bunks.coord',
      }),
      go('room.bunks.hymnal.back', '合上。', 'room.bunks')
    ],
  },
  {
    id: 'room.bunks.coord',
    speaker: undefined,
    text: '就是这条船的月池。\n名单上的第二十个位置，坐标在船内。',
    corruptedText: cor([40, '第二十行的坐标在船内。在月池。位置一直留着。']),
    tags: ['key'],
    onEnter: [learn('k.you-are-sample-n'), setf('know.twentieth-is-here'), san(-10)],
    choices: [go('room.bunks.coord.ok', '……', 'room.bunks')],
  },
  {
    id: 'room.bunks.photo',
    speaker: undefined,
    text: '照片上是码头，十九个人站成两排。\n拍照的人不在照片里。照片背面写着：「谢谢你替我们数。」',
    corruptedText: cor([45, '十九个人两排。背面：「谢谢你替我们数。」']),
    tags: ['key'],
    onEnter: [give('photo'), san(-10), setf('know.photo-thanks')],
    choices: [
      c({
        id: 'room.bunks.photo.who',
        label: '"替我们数"。',
        cost: 3,
        requires: on('know.dont-count'),
        gateMode: 'disable',
        effects: [learn('k.counting-is-the-ritual'), san(-12)],
        goto: 'room.bunks.counting',
      }),
      go('room.bunks.photo.back', '收起来。', 'room.bunks')
    ],
  },
  {
    id: 'room.bunks.counting',
    speaker: undefined,
    text: '数是仪式的一部分。不是禁令，是分工。\n他们不数了，所以需要一个人来数。',
    corruptedText: cor([40, '数不是禁令，是分工。他们不数了，所以需要你数。']),
    tags: ['key'],
    onEnter: [learn('k.counting-is-the-ritual'), san(-12), fear(14)],
    choices: [go('room.bunks.counting.ok', '……', 'room.bunks')],
  },
  {
    id: 'room.bunks.under',
    speaker: undefined,
    text: '乱的那个铺底下什么都没有，连灰都没有。\n地板被擦过，擦的范围正好是一个人躺下的长度。',
    corruptedText: cor([40, '你的铺底下什么都没有，地板擦过，范围正好一个人的长度。']),
    tags: ['key'],
    onEnter: [setf('know.floor-wiped'), san(-8), fear(10)],
    choices: [go('room.bunks.under.ok', '……', 'room.bunks')],
  },
  {
    id: 'room.bunks.made',
    speaker: undefined,
    text: '铺好了。十九个铺现在一样平。\n你站着看了一会儿，然后意识到这个舱室现在没有人睡。',
    corruptedText: cor([40, '十九个铺一样平。这个舱室现在没有人睡。包括你。']),
    tags: ['key'],
    onEnter: [setf('did.made-the-bed'), san(-4), mark('silence', 1)],
    choices: [go('room.bunks.made.ok', '……', 'room.bunks')],
  },

  // ------------------------------------------------------------------- 配电盘
  {
    id: 'room.power',
    speaker: undefined,
    text: '配电盘。十九路开关，十八路合上，一路断开。\n断开那一路的标签是：礼拜堂照明。',
    corruptedText: cor(
      [50, '十九路开关，一路断开：礼拜堂照明。断开的那个扳手被胶带缠住了。'],
      [20, '一路断开，缠着胶带。缠的人不想让任何人再合上它。'],
    ),
    tags: ['entry', 'key'],
    onEnter: [setf('did.found-panel')],
    choices: [
      c({
        id: 'room.power.on',
        label: '合上礼拜堂照明。',
        cost: 6,
        effects: [setf('did.lit-chapel'), loud(10), sfx('light.hum')],
        goto: 'room.power.lit',
      }),
      c({
        id: 'room.power.tape',
        label: '看胶带。',
        cost: 3,
        effects: [setf('did.examined-panel-tape')],
        goto: 'room.power.tape',
      }),
      c({
        id: 'room.power.all',
        label: '全断。',
        cost: 8,
        effects: [setf('did.killed-all-power'), loud(-10), mark('silence', 2), fear(16)],
        goto: 'room.power.dark',
      }),
      c({ id: 'room.power.leave', label: '不碰。', cost: 1, effects: [] })
    ],
  },
  {
    id: 'room.power.lit',
    speaker: undefined,
    text: '礼拜堂那边亮了。点名的声音大了一点。\n亮光里能看清跪着的六个人后面还有十三个位置，位置上有压痕。',
    corruptedText: cor([40, '礼拜堂亮了。六个人后面还有十三个位置，位置上有压痕。十九个。']),
    tags: ['key'],
    onEnter: [setf('did.lit-chapel'), learn('k.choir-sings-manifest'), fear(14), san(-8)],
    choices: [go('room.power.lit.ok', '……', 'room.power')],
  },
  {
    id: 'room.power.tape',
    speaker: undefined,
    text: '胶带缠了七圈，缠得很紧。\n胶带上写着两个字：别看。',
    corruptedText: cor([40, '胶带七圈，上面写着：别看。字迹和天花板上那行一样。']),
    tags: ['key'],
    onEnter: [setf('know.dont-look-tape'), san(-6)],
    choices: [go('room.power.tape.ok', '……', 'room.power')],
  },
  {
    id: 'room.power.dark',
    speaker: undefined,
    text: '全黑。船里所有的机器停了。\n停了之后你才听见，一直有一个低频在下面，比机器更低。',
    corruptedText: cor([40, '全黑。机器停了。有一个低频在下面，一直都在，比机器更低。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), fear(22), san(-12), mark('listening', 2), sfx('deep.hum')],
    choices: [
      c({
        id: 'room.power.dark.listen',
        label: '在黑里听完它。',
        cost: 10,
        effects: [mark('listening', 3), san(-14), setf('did.listened-in-dark')],
        goto: 'room.power.heard',
      }),
      c({
        id: 'room.power.dark.on',
        label: '赶紧合上。',
        cost: 6,
        effects: [setf('did.restored-power'), loud(12)],
        goto: 'room.power',
      })
    ],
  },
  {
    id: 'room.power.heard',
    speaker: undefined,
    text: '低频是有节奏的。八个一组，停半拍。\n它不是在说话。它在点名。',
    corruptedText: cor([40, '八个一组，停半拍。它在点名。点到第二十的时候停了。']),
    tags: ['key'],
    onEnter: [learn('k.signal-is-real'), learn('k.eight-strokes'), san(-14), fear(20)],
    choices: [go('room.power.heard.ok', '……', 'room.power')],
  }
];
