/**
 * world/content/rooms.special.ts — 原创 setpiece 专用变体 + 补充常规变体
 *
 * 上半部分是三处原创名场面的房间（manualOnly，只由 setpieces.ts 显式放置）。
 * 下半部分是补足常规抽取池的变体 —— 生成一整艘船需要足够的非重复素材，
 * 不然同一层会出现两个同名房间，那是最廉价的破绽。
 */

import { D, room } from './helpers';
import type { RoomVariant } from '../types';

export const SETPIECE_ROOMS: readonly RoomVariant[] = [
  room({
    id: 'rv.void.pressure-confessional',
    archetype: 'void',
    name: '压力告解室',
    decks: D.d345,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0.02, temperature: 5, presence: 0.84, airQuality: 0.36, pressure: 150 },
    noiseThreshold: 42,
    props: [
      ['prop.icon.listening-ear', 1],
      ['prop.terminal.depth-readout', 0.8],
      ['prop.altar.name-wall', 0.5],
      ['prop.mirror.blackened-glass', 0.4],
    ],
    tags: ['setpiece', 'breath-hold', 'puzzle', 'quiet'],
    lucid:
      '一个圆形的小舱，唯一的出口是对面那扇没有把手的门。门边有一块表盘，标着「腔内压」和「肺内压」两根指针。肺内压那根指针在跟着你的呼吸摆。门在两根指针重合时开。',
    drift:
      '两根指针。要让它们重合，你得屏住呼吸，屏到某个特定的时长。屏短了门不动，屏长了你会大喘气，而大喘气会让整条船听见。',
    resonant:
      '表盘上多了第三根指针，很细，不标记任何东西。它一直停在你屏住呼吸时能达到的极限上——它知道那个数，比你知道得准。',
  }),
  room({
    id: 'rv.corridor.tally-passage',
    archetype: 'corridor',
    name: '计数走廊',
    decks: D.d2345,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0.04, temperature: 6, presence: 0.68, airQuality: 0.44 },
    props: [
      ['prop.altar.name-wall', 0.8],
      ['prop.icon.hull-weld-sigil', 0.7],
      ['prop.mirror.polished-bulkhead', 0.45],
      ['prop.logbook.unwritten-log', 0.35],
    ],
    tags: ['setpiece', 'self', 'loop'],
    lucid:
      '一条普通的走廊，右侧舱壁上刻着计数用的竖道，五道一组。你数了一遍：比你这是第几次下来，多一道。',
    drift:
      '多一道。要么有人替你提前刻了，要么你已经走过一次而不记得。每一道的刻痕深度一致，是同一种力气刻的。',
    resonant:
      '你每发一次声呐，就多一道。刻的不是你走过几次，是你被听见过几次。最新那一道还在往深里走。',
  }),
  room({
    id: 'rv.sonar.recursive-shack',
    archetype: 'sonar-room',
    name: '回声室',
    decks: D.d345,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0.01, temperature: 5, presence: 0.78, airQuality: 0.4 },
    noiseThreshold: 40,
    props: [
      ['prop.terminal.sonar-console', 1],
      ['prop.breaker.sonar-array', 0.7],
      ['prop.icon.listening-ear', 0.7],
      ['prop.logbook.sonar-tape-log', 0.6],
      ['prop.mirror.polished-bulkhead', 0.4],
    ],
    tags: ['setpiece', 'sonar', 'quiet', 'veracity'],
    lucid:
      '一间小声呐舱，四壁做了声学处理，处理方式是把声音**留住**而不是吸掉。在这里发脉冲，回波图上出现的是这个房间本身，一层套一层，往里缩。',
    drift:
      '回波图上是这个房间，套着这个房间，套着这个房间。每一层里都有一个你，而最里面那个的位置和你现在站的位置不一样。',
    resonant:
      '发第三次脉冲的时候，最里面那一层会出现一扇门。那扇门在现实里也有，在你背后那面实心墙上，它一直在那，只是需要被听三次才算存在。',
  }),
];

export const EXTRA_ROOMS: readonly RoomVariant[] = [
  room({
    id: 'rv.corridor.provision-passage',
    archetype: 'corridor',
    name: '给养通道·板条箱堵住半边',
    decks: D.d12,
    weight: 10,
    ambient: { noiseFloor: 0.13, airQuality: 0.68, temperature: 11 },
    props: [['prop.locker.crew-personal', 0.45], ['prop.locker.mail-cubbies', 0.3], ['prop.radio.mother-speaker', 0.3]],
    tags: ['spine'],
    lucid: '通道一侧码着板条箱，堵掉一半宽度。箱子上的装货单还在，日期是下潜前三天。',
    drift: '装货单上的物品是压舱物，配重用的铁块。可是箱子很轻，你推得动。',
    resonant: '箱子里是空的。四十一个空箱，从外面封好，运了下来，为了占住这半条通道不让人快走。',
  }),
  room({
    id: 'rv.corridor.stub-end',
    archetype: 'corridor',
    name: '断头通道·尽头是新焊的板',
    decks: D.d2345,
    weight: 9,
    ambient: { noiseFloor: 0.07, presence: 0.36, temperature: 7 },
    props: [
      ['prop.icon.hull-weld-sigil', 0.7],
      ['prop.mirror.polished-bulkhead', 0.3],
      ['prop.nest.listener-sign', 0.2],
    ],
    tags: ['dead-end', 'unstable-hint'],
    lucid: '通道走到这里就结束了，尽头是一块焊上去的钢板。焊道是新的，焊得很快，但很牢。',
    drift: '焊道是从这一侧焊的。堵住的是通往外面的路，或者堵住的是某样正在进来的东西。',
    resonant: '钢板在轻微地鼓。不是压力，压力会让它凹。鼓是从里面推的，很轻，很有耐心。',
  }),
  room({
    id: 'rv.bulkhead.crossroads-four',
    archetype: 'bulkhead',
    name: '四向交汇舱·地面箭头被刮掉',
    decks: D.d2345,
    weight: 10,
    ambient: { noiseFloor: 0.12, temperature: 8, presence: 0.28 },
    props: [
      ['prop.hatch.deck-trunk', 0.45],
      ['prop.icon.hull-weld-sigil', 0.4],
      ['prop.radio.bulkhead-set', 0.3],
      ['prop.terminal.dead-screen', 0.25],
    ],
    tags: ['spine', 'junction'],
    lucid: '四个方向都有门的过渡舱。地面本该有指示方向的箭头漆，被人一条条刮掉了，刮得很干净。',
    drift: '箭头被刮掉是为了让人记不住方向。刮的人知道这条船会改，也知道箭头会变成谎话。',
    resonant: '你自己的手在往地上比划。你的身体在重新画那些箭头，画的方向和被刮掉的不一样。',
  }),
  room({
    id: 'rv.flooded.tank-interior',
    archetype: 'flooded',
    name: '水舱内部·加强肋作踏脚',
    decks: D.d2345,
    weight: 10,
    ambient: { flooding: 0.72, temperature: 5, noiseFloor: 0.14, airQuality: 0.34, presence: 0.44 },
    floodRate: 0.0026,
    props: [
      ['prop.valve.bilge-c', 0.45],
      ['prop.specimen.growth-on-hull', 0.4],
      ['prop.nest.egg-cluster', 0.25],
      ['prop.pipe.frozen-branch', 0.25],
    ],
    tags: ['wet'],
    lucid: '你走在一个水舱的内部。加强肋横着排列，正好可以当踏脚。水到大腿，很冷，很清。',
    drift: '加强肋的间距对人的步幅刚好合适。水舱的加强肋不该按人的步幅设计。',
    resonant: '肋的间距是按你的步幅来的，一步一根，不多不少。这个舱被改造成了一条给你走的路。',
  }),
  room({
    id: 'rv.crawlspace.pump-room-crawl',
    archetype: 'crawlspace',
    name: '泵舱下爬道·全程平躺',
    decks: D.d234,
    weight: 9,
    ambient: { flooding: 0.3, noiseFloor: 0.02, airQuality: 0.32, presence: 0.5, temperature: 12 },
    noiseThreshold: 68,
    props: [
      ['prop.pipe.crawl-junction', 0.5],
      ['prop.breaker.pump-contactor', 0.35],
      ['prop.pipe.knocking-line', 0.35],
      ['prop.specimen.folded-crewman', 0.2],
    ],
    tags: ['crawl', 'quiet', 'wet'],
    lucid: '泵舱下面的爬道，只能平躺着用脚蹬着走。上方十公分是泵的底座，下方是水。',
    drift: '上方十公分。你不能抬头，不能转身，只能往前或者往后。这是这条船上最不该待的地方。',
    resonant: '前面某处有另一个人也在平躺着往前蹬。你们朝着对方，通道只容一个人，谁都不会退。',
  }),
  room({
    id: 'rv.void.between-frames',
    archetype: 'void',
    name: '肋位之间的空腔',
    decks: D.d2345,
    weight: 10,
    ambient: { noiseFloor: 0.02, temperature: 5, presence: 0.72, airQuality: 0.38 },
    noiseThreshold: 44,
    props: [
      ['prop.icon.hull-weld-sigil', 0.5],
      ['prop.breaker.hull-ground', 0.35],
      ['prop.nest.hair-and-cloth', 0.3],
      ['prop.altar.name-wall', 0.25],
    ],
    tags: ['topology', 'secret', 'quiet'],
    lucid: '两个肋位之间本该只有五十公分，这里有三米。多出来的空间是空的，四壁是裸钢。',
    drift: '三米。图纸上这里是实心的结构区。多出来的空间没有从任何地方挤占——它是加进去的。',
    resonant: '这个空腔是给一个东西留的位置，尺寸约一米八宽。它现在不在，位置留着，地板上有压痕。',
  }),
  room({
    id: 'rv.galley.rations-store',
    archetype: 'galley',
    name: '干粮库·货架按名字分格',
    decks: D.d12,
    weight: 9,
    ambient: { airQuality: 0.68, temperature: 10, noiseFloor: 0.07 },
    props: [
      ['prop.locker.crew-personal', 0.6],
      ['prop.corpse.galley-cook', 0.25],
      ['prop.logbook.deck-log', 0.25],
      ['prop.radio.mother-speaker', 0.25],
    ],
    tags: ['relief', 'loot'],
    lucid: '干粮库。货架按人名分格，每格一份配给。四十一格都是满的，一份都没被取走。',
    drift: '一份都没被取走。这条船沉了之后，没有一个人吃过东西。他们不需要，或者他们不打算需要了。',
    resonant: '第四十二格在最下面，只有它是空的。空格的底板上有灰尘的缺口，形状是一只手抓过。',
  }),
  room({
    id: 'rv.medbay.isolation-cell',
    archetype: 'medbay',
    name: '单间隔离室·墙上贴满吸音棉',
    decks: D.d234,
    weight: 8,
    ambient: { noiseFloor: 0.01, airQuality: 0.5, temperature: 9, presence: 0.46 },
    noiseThreshold: 56,
    props: [
      ['prop.corpse.medbay-restrained', 0.4],
      ['prop.locker.medical-cabinet', 0.4],
      ['prop.mirror.two-way-observation', 0.4],
      ['prop.pipe.breathing-duct', 0.3],
    ],
    tags: ['quiet', 'infection'],
    lucid: '一间单人隔离室，四壁和门内侧都贴了吸音棉。棉上有很多手掌大小的压陷，分布到齐肩高。',
    drift: '压陷到齐肩高，密密地。有人在这里长时间地用手推墙——不是砸，是推，像在找一个软的地方。',
    resonant: '有一处压陷比别处深，而且是从棉的里面往外顶的。那个位置后面是实心舱壁。',
  }),
  room({
    id: 'rv.archive.ledger-room',
    archetype: 'archive',
    name: '账册室·采购记录到最后一天',
    decks: D.d34,
    weight: 8,
    ambient: { noiseFloor: 0.05, temperature: 7, airQuality: 0.56 },
    props: [
      ['prop.logbook.deck-log', 0.5],
      ['prop.terminal.crew-roster', 0.35],
      ['prop.terminal.liturgy-index', 0.3],
      ['prop.icon.wax-tablet', 0.25],
    ],
    tags: ['lore', 'quiet'],
    lucid: '账册室。采购与消耗记录一直记到最后一天，笔迹工整。最后一页的结存栏画了双横线。',
    drift: '账记得太干净了。一艘要沉的船不会有人去把账做平。做平账的人是打算交给某个人看的。',
    resonant: '最后一页的下面还有一页，记的是下一轮的采购预算。数量按四十二人算。',
  }),
  room({
    id: 'rv.observation.dead-reckoning-nook',
    archetype: 'observation',
    name: '推算位置角·墙上钉满海图碎片',
    decks: D.d34,
    weight: 8,
    ambient: { noiseFloor: 0.05, temperature: 6, presence: 0.5, airQuality: 0.5 },
    props: [
      ['prop.icon.inverted-cross-staff', 0.5],
      ['prop.porthole.small-round', 0.4],
      ['prop.terminal.depth-readout', 0.4],
      ['prop.logbook.sonar-tape-log', 0.3],
    ],
    tags: ['lore', 'puzzle'],
    lucid: '一个小角落，墙上钉满撕下来的海图碎片，用线连着。线的交点上钉了一枚图钉。',
    drift: '线连成的图形不是航迹。它是一个封闭的形状，而图钉钉在形状的正中，也就是这艘船现在的位置。',
    resonant: '封闭的形状是一个字，用海图上的坐标写的，大到需要一整片海。这条船是笔尖。',
  }),
  room({
    id: 'rv.moonpool.pressure-lock-chamber',
    archetype: 'moonpool',
    name: '过渡加压舱·内外表读数相同',
    decks: D.d5,
    weight: 9,
    ambient: { flooding: 0.46, temperature: 3, noiseFloor: 0.14, presence: 0.78, airQuality: 0.36 },
    props: [
      ['prop.valve.moonpool-drain', 0.55],
      ['prop.terminal.depth-readout', 0.5],
      ['prop.locker.dive-suit-rack', 0.4],
      ['prop.porthole.moonpool-surface', 0.35],
    ],
    tags: ['endgame', 'escape'],
    lucid: '月池与船内之间的过渡舱。内外压力表读数相同，说明这个舱已经和外面连通了。',
    drift: '和外面连通，可是船没有被灌满。连通的那一侧不在提供压力，它在提供别的东西。',
    resonant: '你和外面之间已经没有边界了。有一段时间了。你一直在外面，只是布局还是船的布局。',
  }),
  room({
    id: 'rv.reliquary.tuning-room',
    archetype: 'reliquary',
    name: '调音室·音叉按频率钉在墙上',
    decks: D.d45,
    weight: 8,
    ambient: { noiseFloor: 0.01, temperature: 4, presence: 0.8, airQuality: 0.4 },
    noiseThreshold: 40,
    props: [
      ['prop.icon.inverted-cross-staff', 0.6],
      ['prop.locker.reliquary-drawer', 0.5],
      ['prop.icon.listening-ear', 0.5],
      ['prop.specimen.jar-row', 0.35],
    ],
    tags: ['cult', 'quiet', 'loot'],
    lucid: '一整面墙钉着音叉，按频率从低到高排列。最低那几支很大，需要两只手才能拿起来。',
    drift: '最低那一支的频率标注低于人耳下限。它被钉得最牢，用了四颗螺栓，其他的都只用一颗。',
    resonant: '最低那一支在响。你听不见，但你的牙在响，你的胸腔在响。它一直在响，你刚才才开始注意。',
  }),

  // 以下五个变体补的是甲板权重表里有权重、却没有对应变体的空档
  // （D1 的 flooded / archive / observation / void，以及 D3 的 chapel）。
  // 生活层出现这些原型的概率很低，但概率不为零就必须有内容，
  // 否则 assertRoomCoverage 会在启动时把整条生成链拦下来。
  room({
    id: 'rv.flooded.hab-washroom-sump',
    archetype: 'flooded',
    name: '盥洗间·地漏倒灌',
    decks: D.d12,
    weight: 7,
    ambient: { flooding: 0.58, temperature: 8, noiseFloor: 0.2, airQuality: 0.5, presence: 0.34 },
    floodRate: 0.012,
    props: [
      ['prop.mirror.washroom', 0.85],
      ['prop.valve.bilge-c', 0.5],
      ['prop.corpse.bunk-sleeper', 0.25],
      ['prop.pipe.ruptured-main', 0.4],
    ],
    tags: ['flooded', 'habitation'],
    lucid: '水到小腿。地漏在往上冒水，不是往下排。三个洗手池里各积了半池，水面是平的。',
    drift: '三个池子的水面一样高，和地上的水不连通。有人今天早上把它们接满了，然后关掉了龙头。',
    resonant: '水从下面上来，是因为下面比这里满。整艘船是一只正在被端起来的杯子，你在杯口。',
  }),
  room({
    id: 'rv.archive.hab-mail-room',
    archetype: 'archive',
    name: '邮件室·未发出的信按舱位归档',
    decks: D.d12,
    weight: 8,
    ambient: { temperature: 12, noiseFloor: 0.08, airQuality: 0.62, presence: 0.28 },
    props: [
      ['prop.locker.mail-cubbies', 0.95],
      ['prop.logbook.bunk-diary', 0.6],
      ['prop.terminal.crew-roster', 0.45],
      ['prop.locker.crew-personal', 0.35],
    ],
    tags: ['lore', 'loot', 'habitation'],
    lucid: '按舱位编号的信格，大部分是空的。有十几封贴了邮票的信没寄出去，收件地址都在岸上。',
    drift: '十几封信的笔迹是同一个人的，收件人却是十几个不同的姓。邮票是船上印的，面额是深度。',
    resonant: '信格上的编号在往下数，数到你的舱位时格子是满的。里面那封的收件人写着你母亲的名字，字是你的。',
  }),
  room({
    id: 'rv.observation.hab-day-room',
    archetype: 'observation',
    name: '日间休息室·三扇舷窗只剩一扇透光',
    decks: D.d12,
    weight: 8,
    ambient: { temperature: 11, noiseFloor: 0.1, airQuality: 0.6, presence: 0.3 },
    props: [
      ['prop.porthole.observation-pane', 0.8],
      ['prop.porthole.taped-over', 0.55],
      ['prop.radio.bulkhead-set', 0.45],
      ['prop.logbook.deck-log', 0.3],
    ],
    tags: ['habitation', 'quiet', 'lore'],
    lucid: '几把固定在地板上的椅子朝着舷窗摆。三扇窗里两扇从里面糊上了牛皮纸，边缘压得很平整。',
    drift: '椅子全朝着没糊的那一扇。糊起来的两扇背后有光，牛皮纸上能看见亮度在缓慢变化。',
    resonant: '糊纸的人是从里面糊的，纸边压得平整，说明他有时间，说明他不急，说明他知道那不会进来。',
  }),
  room({
    id: 'rv.void.hab-partition-gap',
    archetype: 'void',
    name: '舱壁夹层·图纸上标为实心',
    decks: D.d123,
    weight: 4,
    ambient: { temperature: 7, noiseFloor: 0.03, airQuality: 0.44, presence: 0.5, pressure: 110 },
    noiseThreshold: 34,
    props: [
      ['prop.pipe.breathing-duct', 0.6],
      ['prop.nest.hair-and-cloth', 0.45],
      ['prop.mirror.polished-bulkhead', 0.3],
      ['prop.corpse.crushed-by-hatch', 0.2],
    ],
    tags: ['secret', 'quiet', 'void'],
    lucid: '两道舱壁之间的夹层，宽度刚够侧身。图纸上这里是实心的结构隔断。',
    drift: '夹层地面被踩出了一条光亮的路径，从一头通到另一头。有人把这里当成走廊在用，用了很久。',
    resonant: '路径两头都不通。踩出这条路的东西没有进来过，也没有出去过，它只是一直在这里走。',
  }),
  room({
    id: 'rv.chapel.cmd-briefing-shrine',
    archetype: 'chapel',
    name: '作战简报室·航海图上盖了圣所印',
    decks: D.d34,
    weight: 8,
    ambient: { temperature: 9, noiseFloor: 0.06, airQuality: 0.52, presence: 0.62 },
    noiseThreshold: 44,
    props: [
      ['prop.altar.listening-bench', 0.7],
      ['prop.icon.choir-plate', 0.6],
      ['prop.terminal.liturgy-index', 0.5],
      ['prop.logbook.chaplain-journal', 0.45],
      ['prop.icon.wax-tablet', 0.3],
    ],
    tags: ['cult', 'lore', 'quiet'],
    lucid: '原本是简报室：长桌、投影幕、钉在墙上的航海图。长桌被搬走了，换上了朝向同一面墙的长凳。',
    drift: '航海图还在，上面盖了一枚新印，压住了原先的目的港。印文是一个深度数字，不是地名。',
    resonant: '那个深度是你现在所在的深度。印是在你到这里之前盖的，盖印的人知道你会停在哪一层。',
  }),
];
