/**
 * world/content/rooms.hab.ts — 生活层系房间变体
 *
 * 通道 / 隔舱 / 食堂 / 铺位 / 医务室 / 气闸。
 * D1 的任务是**教规则**，所以这一层的房间必须最可读：每个房间都有一个
 * 一眼能看懂的事实，和一个看第二眼才发现的不对。
 */

import { D, room } from './helpers';
import type { RoomVariant } from '../types';

export const HAB_ROOMS: readonly RoomVariant[] = [
  // ============================================================ 通道 corridor
  room({
    id: 'rv.corridor.transverse-3',
    archetype: 'corridor',
    name: '三号横贯通道·已部分坍塌',
    decks: D.d123,
    weight: 14,
    ambient: { noiseFloor: 0.14, airQuality: 0.7 },
    props: [['prop.breaker.lighting-panel', 0.45], ['prop.icon.hull-weld-sigil', 0.3], ['prop.radio.bulkhead-set', 0.25]],
    tags: ['spine'],
    lucid: '横贯通道，中段舱顶下陷，钢梁把通路压成一个需要低头的高度。地上的水不到脚踝，静止。',
    drift: '下陷的钢梁上有划痕，成组，位置在你低头时额头会碰到的地方。之前经过的人都留了一道。',
    resonant: '你每次低头，通道就变长一点。划痕的组数在增加，而增加的那几道还是湿的。',
  }),
  room({
    id: 'rv.corridor.port-longitudinal',
    archetype: 'corridor',
    name: '左舷纵通道·灯具全数摘除',
    decks: D.d123,
    weight: 12,
    ambient: { noiseFloor: 0.08, airQuality: 0.68, presence: 0.16 },
    props: [['prop.breaker.lighting-panel', 0.55], ['prop.terminal.dead-screen', 0.3], ['prop.locker.mail-cubbies', 0.2]],
    tags: ['spine', 'dark'],
    lucid: '长直通道。所有灯具都被拆走了，只剩接线盒和吊架，线头被仔细地用胶带包好。',
    drift: '线头被包好了，说明拆灯的人不打算再装回去，但也不想触电——他还要在黑里长期走动。',
    resonant: '黑不是缺光。你的手电照到一半就被吃掉了，光锥有一个整齐的截面。',
  }),
  room({
    id: 'rv.corridor.frame-41',
    archetype: 'corridor',
    name: '第四十一肋位·地板已揭开',
    decks: D.d12,
    weight: 11,
    ambient: { flooding: 0.16, noiseFloor: 0.2 },
    props: [['prop.hatch.bilge-plate', 0.6], ['prop.pipe.conduit-bundle', 0.4], ['prop.pipe.knocking-line', 0.25]],
    tags: ['spine'],
    lucid: '这一段地板被整块揭开，露出舱底管线。踏板靠边立着，编号朝外，是准备装回去的样子。',
    drift: '踏板靠边立着，四十一块，编号连续。可是这一段只需要三十九块。',
    resonant: '多出来的两块底下是两个洞，洞里有人在往上看。他们不催你，他们有时间。',
  }),
  room({
    id: 'rv.corridor.galley-approach',
    archetype: 'corridor',
    name: '食堂前廊·餐具散落',
    decks: D.d1,
    weight: 10,
    ambient: { airQuality: 0.72, temperature: 12 },
    props: [['prop.locker.mail-cubbies', 0.4], ['prop.radio.mother-speaker', 0.4], ['prop.porthole.small-round', 0.3]],
    lucid: '通往食堂的短廊，地上散着餐具，全朝一个方向。像是有人端着托盘走到这里，把整盘倒了。',
    drift: '餐具全朝一个方向——朝食堂里。倒的人是在往里走，不是往外跑。',
    resonant: '餐具在你走过之后重新排好。它们排成一条通向食堂的线，刀尖朝前。',
  }),
  room({
    id: 'rv.corridor.bunk-alley',
    archetype: 'corridor',
    name: '铺位过道·帘幕全部拉合',
    decks: D.d1,
    weight: 10,
    ambient: { noiseFloor: 0.07, presence: 0.2 },
    props: [['prop.mirror.washroom', 0.35], ['prop.logbook.bunk-diary', 0.25], ['prop.radio.pipe-voice', 0.3]],
    tags: ['quiet'],
    lucid: '两侧是铺位的入口，每个入口的布帘都从内侧拉合了。一共十六个铺位，十六道帘子。',
    drift: '帘子是从内侧拉的。要从内侧拉合，人得在里面。十六道都是。',
    resonant: '你数第二遍是十七道。最后那一道后面的呼吸比其他十六道加起来都响。',
  }),
  room({
    id: 'rv.corridor.flooded-step-down',
    archetype: 'corridor',
    name: '下沉通道·水没到腰',
    decks: D.d12,
    weight: 9,
    ambient: { flooding: 0.52, temperature: 9, noiseFloor: 0.24 },
    floodRate: 0.0022,
    props: [['prop.pipe.ruptured-main', 0.5], ['prop.corpse.crushed-by-hatch', 0.25], ['prop.specimen.growth-on-hull', 0.2]],
    tags: ['wet'],
    lucid: '通道在此下降两级，水面齐腰。水很清，能看见踏板的编号，一直延伸到看不见的地方。',
    drift: '水很清，但水面没有你走动产生的波纹。波纹在你身后一米处才出现。',
    resonant: '水是有方向的。它在缓慢地朝一个地方流，而那个地方比船低。',
  }),

  // ============================================================ 隔舱 bulkhead
  room({
    id: 'rv.bulkhead.watertight-c',
    archetype: 'bulkhead',
    name: 'C 号水密隔舱·压紧螺栓齐全',
    decks: D.d123,
    weight: 13,
    ambient: { noiseFloor: 0.1 },
    props: [['prop.hatch.deck-trunk', 0.5], ['prop.icon.hull-weld-sigil', 0.3], ['prop.radio.bulkhead-set', 0.3]],
    tags: ['spine', 'junction'],
    lucid: '一个只有过渡功能的小舱，四面都是门。每扇门的压紧螺栓都是全的，说明这里被当作最后防线。',
    drift: '四面都是门，可是这艘船的横剖面只允许三面。第四面的门开在你进来的那一侧的正对面。',
    resonant: '门的数量随你数的次数变。你闭上眼再睁开，永远会多一扇 —— 多的那扇通向更深的地方。',
  }),
  room({
    id: 'rv.bulkhead.blast-vestibule',
    archetype: 'bulkhead',
    name: '防爆前室·地面有拖行痕',
    decks: D.d123,
    weight: 11,
    ambient: { noiseFloor: 0.12, presence: 0.18 },
    props: [['prop.corpse.crushed-by-hatch', 0.35], ['prop.locker.dive-suit-rack', 0.3], ['prop.hatch.deck-trunk', 0.4]],
    tags: ['spine', 'junction'],
    lucid: '双层门的前室。地面有两道平行的拖行痕，从内门通到外门，宽度像是两只鞋跟。',
    drift: '拖痕是从内往外的。被拖的人脚尖朝后，说明他被拖着往前走，头在前面。',
    resonant: '拖痕的尽头是外门内侧的一片干净地面。他在那里站起来了，然后自己走了出去。',
  }),
  room({
    id: 'rv.bulkhead.frame-junction',
    archetype: 'bulkhead',
    name: '肋骨交汇处·钢梁裸露',
    decks: D.d1234,
    weight: 10,
    ambient: { noiseFloor: 0.16 },
    props: [['prop.pipe.conduit-bundle', 0.45], ['prop.icon.hull-weld-sigil', 0.35], ['prop.nest.listener-sign', 0.18]],
    tags: ['spine', 'junction'],
    lucid: '内衬板被拆掉，露出船体的肋骨和纵桁。结构很清楚，你能第一次看清这条船的骨架怎么搭的。',
    drift: '肋骨的间距不均匀。有一段的间距是别处的两倍，而那一段没有任何加强件，它就是那样空着。',
    resonant: '骨架是对的，只是你在里面。肋骨从两侧往上收，在头顶合成一道脊。你在胸腔里。',
  }),
  room({
    id: 'rv.bulkhead.sealed-by-crew',
    archetype: 'bulkhead',
    name: '被船员自行封死的隔舱',
    decks: D.d123,
    weight: 8,
    ambient: { noiseFloor: 0.06, presence: 0.26 },
    props: [['prop.hatch.deck-trunk', 0.5], ['prop.radio.bulkhead-set', 0.35], ['prop.porthole.taped-over', 0.4]],
    tags: ['junction', 'quiet'],
    lucid:
      '一扇门被从这一侧焊死了，焊道是手工的，很急，有很多补焊。旁边用粉笔写了一行字，已经花了。',
    drift: '粉笔字能认出三个字：「别开」。下面还有一行，笔迹不同，写的是「已开」。',
    resonant: '焊道在你这一侧，字在你这一侧。也就是说，被关在里面的一直是你们。',
  }),

  // ============================================================== 食堂 galley
  room({
    id: 'rv.galley.mess-deck',
    archetype: 'galley',
    name: '士兵食堂·餐具已摆好',
    decks: D.d1,
    weight: 13,
    ambient: { airQuality: 0.74, temperature: 13, noiseFloor: 0.1 },
    props: [
      ['prop.corpse.galley-cook', 0.55],
      ['prop.radio.mother-speaker', 0.4],
      ['prop.locker.crew-personal', 0.4],
      ['prop.porthole.small-round', 0.3],
    ],
    tags: ['anchor', 'relief'],
    lucid:
      '四张长桌，餐具摆好，杯子倒扣。每个座位前都摊开了餐巾，折成同一个形状。没有一份被吃过。',
    drift: '餐巾的折法是同一个人折的四十二次。第四十二个座位在最靠门的位置，餐具是新的。',
    resonant: '第四十二个座位的椅子被拉开了，正对着门。你刚从门进来。它是给你留的。',
  }),
  room({
    id: 'rv.galley.scullery',
    archetype: 'galley',
    name: '洗碗间·水槽溢出',
    decks: D.d1,
    weight: 10,
    ambient: { flooding: 0.14, airQuality: 0.62, noiseFloor: 0.18 },
    props: [['prop.locker.crew-personal', 0.4], ['prop.mirror.washroom', 0.35], ['prop.pipe.ruptured-main', 0.3]],
    lucid: '三格水槽，水一直在流，溢到地上。下水被堵住了，堵的东西是一团布。',
    drift: '堵水的是一件工作服，叠好了塞进去的。叠得很整齐，是先叠好再塞的。',
    resonant: '水槽里的水是温的，而且在轻微晃动，频率固定，像有东西在下面呼吸。',
  }),
  room({
    id: 'rv.galley.cold-store',
    archetype: 'galley',
    name: '冷藏库·门从内侧闩着',
    decks: D.d1,
    weight: 9,
    ambient: { temperature: 2, airQuality: 0.58, noiseFloor: 0.05, presence: 0.22 },
    props: [['prop.locker.crew-personal', 0.45], ['prop.corpse.bunk-sleeper', 0.3], ['prop.pipe.frozen-branch', 0.35]],
    tags: ['cold'],
    lucid: '冷藏库还是冷的。货架上的东西按类别码放，一丝不乱。门闩在内侧，是被从里面闩上的。',
    drift: '货架上有一格是空的，地面上有相应的压痕。被搬走的那一格东西的重量，约等于一个人。',
    resonant: '冷藏库的深度超过了这一段船体的宽度。最里面那一排货架后面还有路，越走越冷。',
  }),
  room({
    id: 'rv.galley.bakery-nook',
    archetype: 'galley',
    name: '烘焙角·烤箱仍有余温',
    decks: D.d1,
    weight: 8,
    ambient: { temperature: 21, airQuality: 0.66 },
    props: [['prop.locker.crew-personal', 0.35], ['prop.radio.mother-speaker', 0.35], ['prop.logbook.deck-log', 0.2]],
    tags: ['relief', 'warm'],
    lucid: '一个很小的角落，一台烤箱，里面有四十一个面团，都发过了头。烤箱还有余温。',
    drift: '面团发过头的程度一致，说明它们是同时被放进去的，然后被同时忘记。烤箱的定时器停在 0。',
    resonant: '烤箱里现在是四十二个。最新的那一个还在缓慢地长，形状不像面团。',
  }),
  room({
    id: 'rv.galley.crew-lounge',
    archetype: 'galley',
    name: '休息室·牌局未散',
    decks: D.d1,
    weight: 8,
    ambient: { airQuality: 0.72, noiseFloor: 0.09, presence: 0.14 },
    props: [
      ['prop.locker.mail-cubbies', 0.45],
      ['prop.terminal.dead-screen', 0.35],
      ['prop.radio.mother-speaker', 0.3],
      ['prop.mirror.washroom', 0.2],
    ],
    tags: ['relief'],
    lucid: '几把固定在地板上的椅子，中间小桌上有一局没打完的牌。四手牌摊开，第五手扣着。',
    drift: '四手牌都是输的牌。扣着的第五手不用翻你也知道是赢的，因为这一局本来就不是在赌钱。',
    resonant: '第五手是你的手牌。你伸手去翻，牌面朝上的一瞬间，你想起你上一轮就翻过这张。',
  }),

  // =============================================================== 铺位 bunks
  room({
    id: 'rv.bunks.forward-berthing',
    archetype: 'bunks',
    name: '前部住舱·十六个铺位',
    decks: D.d1,
    weight: 13,
    ambient: { airQuality: 0.7, noiseFloor: 0.08, presence: 0.14 },
    props: [
      ['prop.corpse.bunk-sleeper', 0.5],
      ['prop.locker.crew-personal', 0.6],
      ['prop.logbook.bunk-diary', 0.35],
      ['prop.mirror.washroom', 0.3],
    ],
    tags: ['anchor', 'relief', 'start'],
    lucid: '三层铺，十六个位置，被褥都铺着。每个铺位的枕头都摆在同一侧，摆法一致。',
    drift: '枕头都摆在靠舱壁那一侧，可是舱壁那一侧是冷的。没有人会主动把头靠向冷的一侧。',
    resonant: '每个枕头上都有一个头的凹陷，凹陷是新的。十六个人刚刚同时坐了起来。',
  }),
  room({
    id: 'rv.bunks.officer-stateroom',
    archetype: 'bunks',
    name: '士官单人舱·门牌被刮掉',
    decks: D.d1,
    weight: 10,
    ambient: { airQuality: 0.72, noiseFloor: 0.06 },
    props: [
      ['prop.locker.crew-personal', 0.55],
      ['prop.logbook.deck-log', 0.35],
      ['prop.mirror.blackened-glass', 0.3],
      ['prop.porthole.small-round', 0.35],
    ],
    lucid: '单人舱，写字台、床、一个洗手池。门牌槽是空的。桌上的东西按用途分组，摆得很讲究。',
    drift: '桌上有一块方形的无灰区域，尺寸是一个相框。相框不在房间里，也不在抽屉里。',
    resonant: '无灰区域里现在有相框了，背面朝上。你不需要翻它。你知道里面是谁。',
  }),
  room({
    id: 'rv.bunks.hot-bunk-row',
    archetype: 'bunks',
    name: '轮铺舱·被褥还是温的',
    decks: D.d1,
    weight: 9,
    ambient: { temperature: 15, airQuality: 0.64, presence: 0.24 },
    props: [['prop.corpse.bunk-sleeper', 0.4], ['prop.nest.hair-and-cloth', 0.3], ['prop.radio.pipe-voice', 0.3]],
    lucid: '轮流使用的铺位，被褥没有归属。所有被褥都是温的——上一班刚起，下一班还没来。',
    drift: '这艘船沉了。没有上一班，也没有下一班。温度只能来自还在里面的东西。',
    resonant: '被褥的温度在你靠近时升高。它在为你预热，就像它知道你需要休息，也知道你会需要。',
  }),
  room({
    id: 'rv.bunks.quarantine-berth',
    archetype: 'bunks',
    name: '隔离铺位·塑料帘封起',
    decks: D.d12,
    weight: 8,
    ambient: { airQuality: 0.5, presence: 0.3, temperature: 13 },
    props: [
      ['prop.corpse.medbay-restrained', 0.35],
      ['prop.locker.medical-cabinet', 0.35],
      ['prop.pipe.breathing-duct', 0.3],
    ],
    tags: ['infection'],
    lucid: '四个铺位被塑料帘隔起来，帘子上贴了手写的标签：耳、耳、耳、耳。',
    drift: '四张标签都写「耳」。这不是症状记录，这是分类 —— 按他们被取走了哪个部分分类。',
    resonant: '塑料帘在动。不是气流，是里面的人在慢慢贴过来，想听清你的动静。',
  }),
  room({
    id: 'rv.bunks.washroom',
    archetype: 'bunks',
    name: '盥洗舱·全部镜子被涂黑',
    decks: D.d12,
    weight: 8,
    ambient: { flooding: 0.1, airQuality: 0.62, noiseFloor: 0.14 },
    props: [
      ['prop.mirror.blackened-glass', 0.7],
      ['prop.mirror.washroom', 0.35],
      ['prop.pipe.ruptured-main', 0.25],
    ],
    tags: ['veracity'],
    lucid: '一排洗手池和淋浴位。池子上方的四面镜子全被黑漆涂满，涂漆的手法很急。',
    drift: '四面镜子涂了黑漆，但淋浴间的不锈钢隔板没涂。那块板照得出人，只是模糊。',
    resonant: '不锈钢隔板上的模糊人影比你多一个。第五个站在最里面那个淋浴位，没有在洗。',
  }),
  room({
    id: 'rv.bunks.your-quarters',
    archetype: 'bunks',
    name: '你自己的舱室',
    decks: D.d12,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { airQuality: 0.66, noiseFloor: 0.04, presence: 0.52, temperature: 12 },
    props: [
      ['prop.corpse.your-double', 1],
      ['prop.logbook.unwritten-log', 1],
      ['prop.mirror.washroom', 0.6],
      ['prop.locker.crew-personal', 0.8],
    ],
    tags: ['setpiece', 'self'],
    lucid:
      '一间单人舱。桌上的东西按你的习惯摆着：杯子在右手边，笔尖朝外。铺位上躺着一个人，穿着你身上这一套。',
    drift:
      '杯子在右手边，笔尖朝外，这是你的习惯，你从没跟人说过。铺位上那个人的呼吸间隔和你一致。',
    resonant:
      '这是你的舱室。你在这里睡过很多次，多到你记不清是哪一次。躺着那个是上一次的你，他做完了他那一份。',
  }),

  // ============================================================= 医务室 medbay
  room({
    id: 'rv.medbay.sick-bay',
    archetype: 'medbay',
    name: '医务舱·四张固定床位',
    decks: D.d123,
    weight: 13,
    ambient: { airQuality: 0.6, temperature: 10, presence: 0.2 },
    props: [
      ['prop.corpse.medbay-restrained', 0.5],
      ['prop.locker.medical-cabinet', 0.65],
      ['prop.logbook.medical-chart', 0.55],
      ['prop.specimen.jar-row', 0.3],
    ],
    tags: ['anchor'],
    lucid: '四张床，都有约束带。器械车停在中间，托盘里的器械按使用顺序排列，排到第七件断了。',
    drift: '第七件之后的器械不在托盘里，在墙上的挂钩上——按同样的顺序挂着，尖端全朝下。',
    resonant: '床是四张，人是四十一个。他们一批一批地上这四张床，每一批出来的都少了一点什么。',
  }),
  room({
    id: 'rv.medbay.operating-nook',
    archetype: 'medbay',
    name: '手术间·无影灯还亮着',
    decks: D.d123,
    weight: 10,
    ambient: { airQuality: 0.54, temperature: 11, noiseFloor: 0.08, presence: 0.28 },
    props: [
      ['prop.locker.medical-cabinet', 0.6],
      ['prop.specimen.jar-row', 0.45],
      ['prop.specimen.your-own-lung', 0.2],
      ['prop.mirror.two-way-observation', 0.3],
    ],
    tags: ['gore'],
    lucid: '很小的手术间，无影灯还有电，照着一张空手术台。台面干净，排水沟里也干净。',
    drift: '台面和排水沟都干净，但天花板上有喷溅。喷溅的角度是从下往上，力量很大。',
    resonant: '无影灯照着的地方有一个人形的阴影，而没有东西投出它。台子在等。',
  }),
  room({
    id: 'rv.medbay.dispensary',
    archetype: 'medbay',
    name: '药房·镇静剂那一格是空的',
    decks: D.d12,
    weight: 9,
    ambient: { airQuality: 0.62, temperature: 11 },
    props: [
      ['prop.locker.medical-cabinet', 0.8],
      ['prop.logbook.medical-chart', 0.45],
      ['prop.terminal.crew-roster', 0.25],
    ],
    lucid: '一整墙的药柜。标签清楚，库存卡还在。只有镇静剂和镇痛剂的格子是空的，其他都满。',
    drift: '库存卡上的领用记录很整齐，笔迹一致，日期一致，剂量递增。最后一栏领用人签的是同一个符号。',
    resonant: '空掉的那两格里现在长了东西，白色，有绒毛。绒毛朝着你的方向倒。',
  }),
  room({
    id: 'rv.medbay.autopsy-alcove',
    archetype: 'medbay',
    name: '尸检凹间·抽屉编号至四十一',
    decks: D.d23,
    weight: 8,
    ambient: { temperature: 3, airQuality: 0.5, noiseFloor: 0.05, presence: 0.34 },
    props: [
      ['prop.specimen.jar-row', 0.55],
      ['prop.specimen.your-own-lung', 0.3],
      ['prop.logbook.medical-chart', 0.4],
      ['prop.corpse.medbay-restrained', 0.3],
    ],
    tags: ['cold', 'gore'],
    lucid: '冷藏抽屉，编号到四十一。全部推入到底。抽屉外侧的把手上都有一层薄霜，霜是完整的。',
    drift: '霜是完整的，说明没人打开过。可是第四十一号的霜在把手内侧缺了一圈——从里面握过。',
    resonant: '抽屉编号到四十二了。第四十二号没有霜，是温的，而且它开着一条缝。',
  }),
  room({
    id: 'rv.medbay.psych-observation',
    archetype: 'medbay',
    name: '心理观察室·记录桌朝着镜子',
    decks: D.d23,
    weight: 7,
    ambient: { airQuality: 0.58, noiseFloor: 0.04, presence: 0.4 },
    props: [
      ['prop.mirror.two-way-observation', 0.75],
      ['prop.logbook.medical-chart', 0.45],
      ['prop.altar.iron-chair', 0.25],
      ['prop.terminal.dead-screen', 0.3],
    ],
    tags: ['veracity'],
    lucid: '一间小房间：一把椅子，一张桌子，一面单向观察窗。椅子面朝窗。桌子也面朝窗。',
    drift: '按设计，桌子该在窗的另一侧。它在这一侧。观察者和被观察者是同一个人。',
    resonant: '你坐下，窗里的房间也有人坐下。他开始记录。你能看见他的笔在动，速度比你的思维快。',
  }),

  // ============================================================= 气闸 airlock
  room({
    id: 'rv.airlock.forward-trunk',
    archetype: 'airlock',
    name: '前部逃生筒底舱',
    decks: D.d12,
    weight: 12,
    ambient: { flooding: 0.2, pressure: 36, airQuality: 0.6, noiseFloor: 0.16 },
    props: [
      ['prop.hatch.escape-trunk', 0.8],
      ['prop.locker.dive-suit-rack', 0.6],
      ['prop.terminal.depth-readout', 0.4],
      ['prop.radio.emergency-beacon', 0.3],
    ],
    tags: ['anchor', 'escape'],
    lucid: '圆筒形小舱，顶上是逃生筒下盖。墙上挂着潜水服，地上有排水格栅。格栅下有水声。',
    drift: '挂了九套服，挂位是八个。排水格栅下的水声有节奏，不是滴水的节奏。',
    resonant: '格栅下的水在往上涌，但没有涌上来。它在等你打开上面那个盖子，制造一个压力差。',
  }),
  room({
    id: 'rv.airlock.diver-lockout',
    archetype: 'airlock',
    name: '潜水员出入舱·加压表读数不合理',
    decks: D.d45,
    weight: 11,
    ambient: { flooding: 0.42, temperature: 4, airQuality: 0.44, presence: 0.5 },
    props: [
      ['prop.locker.dive-suit-rack', 0.65],
      ['prop.terminal.depth-readout', 0.55],
      ['prop.valve.moonpool-drain', 0.35],
      ['prop.porthole.moonpool-surface', 0.3],
    ],
    tags: ['anchor', 'escape'],
    lucid: '双人加压舱，内外两道门。加压表在零位——在这个深度，内外压差归零意味着外面也是一个大气压。',
    drift: '外压表读零。要么表坏了，要么外面不是海。你敲了敲表壳，指针没动。',
    resonant: '外面确实是一个大气压。因为外面已经不是海了，是一个正在呼吸的腔体，而你在它的气管里。',
  }),
  room({
    id: 'rv.airlock.sample-lock',
    archetype: 'airlock',
    name: '取样闸·采样篮仍在外',
    decks: D.d345,
    weight: 9,
    ambient: { flooding: 0.3, temperature: 4, airQuality: 0.5, presence: 0.44 },
    props: [
      ['prop.specimen.dredge-tray', 0.6],
      ['prop.specimen.growth-on-hull', 0.4],
      ['prop.hatch.escape-trunk', 0.35],
      ['prop.terminal.depth-readout', 0.3],
    ],
    lucid: '一个小型取样闸，带机械臂。操作面板显示采样篮仍在外侧，收回指令已发出四十一次。',
    drift: '收回指令发了四十一次，全部失败。日志里失败原因一栏写的是「负载超限」。篮子里装了很重的东西。',
    resonant: '篮子回来了，就在闸里。里面装的东西太大，装不进这个尺寸，可它装进去了。',
  }),
  room({
    id: 'rv.airlock.decompression-cell',
    archetype: 'airlock',
    name: '减压舱·门从外面顶住了',
    // D2–D4 的权重表里 airlock 权重极低，这个变体实际抽不到；
    // 减压舱在逃生筒层和潜水层同样说得通，所以开放到全部甲板
    decks: D.all,
    weight: 8,
    ambient: { airQuality: 0.46, noiseFloor: 0.06, presence: 0.38, temperature: 8 },
    props: [
      ['prop.porthole.small-round', 0.5],
      ['prop.corpse.crushed-by-hatch', 0.3],
      ['prop.radio.bulkhead-set', 0.4],
      ['prop.terminal.depth-readout', 0.35],
    ],
    tags: ['quiet'],
    lucid: '一个躺人的减压舱，圆形窗口开在侧面。门外侧插了一根撬棍当顶杠。',
    drift: '顶杠插在外侧。里面的人出不来，外面的人也不打算再进去。撬棍上没有挣扎的弯折。',
    resonant: '你从窗口往里看，里面有人在往外看。你们的视线对齐了，因为你们在同一个位置。',
  }),
];
