/**
 * world/content/rooms.deep.ts — 圣所层 / 月池层 / 淹水区 / 虚舱
 *
 * 礼拜堂 / 圣物室 / 月池 / 虚舱 / 淹水区。
 * D4–D5 的写作纪律反过来：这里**不需要**解释。上面三层已经把证据给完了，
 * 这两层只呈现结果。清明档也不再"客观"——因为到这个深度，
 * 客观描述本身就已经是不可能的了。
 */

import { D, room } from './helpers';
import type { RoomVariant } from '../types';

export const DEEP_ROOMS: readonly RoomVariant[] = [
  // ============================================================= 礼拜堂 chapel
  room({
    id: 'rv.chapel.main-nave',
    archetype: 'chapel',
    name: '正殿·座位朝着舱壁',
    decks: D.d4,
    weight: 14,
    ambient: { flooding: 0.24, noiseFloor: 0.07, temperature: 5, presence: 0.66, airQuality: 0.46 },
    noiseThreshold: 46,
    props: [
      ['prop.altar.threshold-stone', 0.45],
      ['prop.altar.listening-bench', 0.7],
      ['prop.icon.listening-ear', 0.55],
      ['prop.corpse.choir-member', 0.45, 2],
      ['prop.valve.chapel-font', 0.35],
    ],
    tags: ['anchor', 'cult'],
    lucid:
      '一个被打通两个舱段做成的礼拜空间。没有神像，没有讲台。所有长凳都朝着左舷那面舱壁，那面墙上只有一道横贯的焊缝。',
    drift: '焊缝在齐耳的高度。长凳的间距是按人跪下后耳朵能贴到墙的距离排的。',
    resonant: '焊缝是张开的。它一直是张开的，只是需要你跪到那个高度才看得见里面。',
  }),
  room({
    id: 'rv.chapel.confessional-row',
    archetype: 'chapel',
    name: '告解间·隔板两侧都朝内',
    decks: D.d4,
    weight: 11,
    ambient: { noiseFloor: 0.04, temperature: 5, presence: 0.7, airQuality: 0.44 },
    noiseThreshold: 42,
    props: [
      ['prop.icon.listening-ear', 0.6],
      ['prop.altar.name-wall', 0.4],
      ['prop.mirror.blackened-glass', 0.35],
      ['prop.radio.bulkhead-set', 0.3],
    ],
    tags: ['cult', 'quiet'],
    lucid: '三个并排的告解间，木格栅隔板。按设计，一侧坐忏悔者，一侧坐听者。这三个的两侧都朝内。',
    drift: '两侧都朝内，意味着两个人隔着格栅互相说，互相听。没有人在赦免谁。',
    resonant: '每个间里都有人在说。三个间，六个声音，全都在说同一句，错开半拍，形成一个滚动的圆。',
  }),
  room({
    id: 'rv.chapel.immersion-chapel',
    archetype: 'chapel',
    name: '浸礼堂·池水与地板齐平',
    decks: D.d45,
    weight: 10,
    ambient: { flooding: 0.58, noiseFloor: 0.08, temperature: 4, presence: 0.72, airQuality: 0.42 },
    floodRate: 0.0022,
    props: [
      ['prop.altar.drowning-basin', 0.7],
      ['prop.valve.chapel-font', 0.5],
      ['prop.icon.listening-ear', 0.4],
      ['prop.corpse.choir-member', 0.35],
    ],
    tags: ['cult', 'wet', 'ritual'],
    lucid: '一个下沉的池子占了整个房间，水与地板齐平，没有围栏。水面平静，深不见底。',
    drift: '水面平静得像固体。你扔一枚螺钉进去，它停在水面上，然后慢慢陷下去，没有声音。',
    resonant: '池底有人站着，很多人，仰着脸。他们在水下排着队，队尾一直排到你脚边。',
  }),
  room({
    id: 'rv.chapel.drowned-sanctuary',
    archetype: 'chapel',
    name: '淹没的圣堂',
    decks: D.d45,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { flooding: 0.97, noiseFloor: 0.01, temperature: 2, presence: 0.88, airQuality: 0.08 },
    noiseThreshold: 120,
    floodRate: 0,
    props: [
      ['prop.altar.drowning-basin', 1],
      ['prop.corpse.choir-member', 1, 4],
      ['prop.icon.choir-plate', 0.8],
      ['prop.altar.name-wall', 0.7],
      ['prop.porthole.observation-pane', 0.5],
    ],
    tags: ['setpiece', 'cult', 'no-sonar', 'breath-hold'],
    lucid:
      '这个舱完全在水下。你必须屏住呼吸游过去。水里悬着四个人，跪姿，被某种东西固定在应有的位置上，朝着同一面墙。声呐在这里不能用——水会把脉冲送出去，让每一个听的东西知道你在这。',
    drift:
      '完全在水下。四个人跪在水里，位置精确，间距相等。水很清，你能看见他们的嘴在动。你的肺开始要东西。',
    resonant:
      '你在水里，他们在唱，你听得见。水传声，比空气好得多。他们唱的时候，你的胸腔在共鸣，替他们发声。你再屏一会儿就会加入。',
  }),
  room({
    id: 'rv.chapel.bell-space',
    archetype: 'chapel',
    name: '钟舱·钟被灌满了蜡',
    decks: D.d4,
    weight: 9,
    ambient: { noiseFloor: 0.02, temperature: 5, presence: 0.62, airQuality: 0.46 },
    noiseThreshold: 44,
    props: [
      ['prop.icon.wax-tablet', 0.5],
      ['prop.altar.offering-slab', 0.45],
      ['prop.icon.inverted-cross-staff', 0.35],
      ['prop.mirror.blackened-glass', 0.3],
    ],
    tags: ['cult', 'quiet'],
    lucid: '一口舰钟悬在舱顶，钟腔里被灌满了蜡，灌得很实。钟锤被拆下来，放在地上，摆得很正。',
    drift: '钟被灌蜡是为了让它不响。拆下钟锤也是。做了两重措施的人非常怕它响一次。',
    resonant: '蜡在往下滴。钟在发声，声音穿过蜡出来，变成一个低到只能用骨头听的音。它已经响了很久。',
  }),

  // =========================================================== 圣物室 reliquary
  room({
    id: 'rv.reliquary.main-vault',
    archetype: 'reliquary',
    name: '圣物库·四十一格抽屉',
    decks: D.d4,
    weight: 14,
    ambient: { noiseFloor: 0.03, temperature: 4, presence: 0.74, airQuality: 0.44 },
    noiseThreshold: 44,
    props: [
      ['prop.locker.reliquary-drawer', 0.9],
      ['prop.icon.choir-plate', 0.5],
      ['prop.specimen.jar-row', 0.5],
      ['prop.altar.offering-slab', 0.45],
      ['prop.icon.listening-ear', 0.35],
    ],
    tags: ['anchor', 'cult', 'loot', 'quiet'],
    lucid: '恒温的小库房，一整面抽屉柜。四十一格，每格一个名字和同一个日期。抽屉里是牙齿。',
    drift: '四十一格，加上一个没有标签、没有把手的第四十二格。它是拉得开的。',
    resonant: '第四十二格开着。里面那颗牙是你的，而你嘴里那个位置现在是空的，刚刚空的。',
  }),
  room({
    id: 'rv.reliquary.ear-collection',
    archetype: 'reliquary',
    name: '耳室·标本按听力排序',
    decks: D.d45,
    weight: 11,
    ambient: { noiseFloor: 0.02, temperature: 3, presence: 0.78, airQuality: 0.42 },
    noiseThreshold: 40,
    props: [
      ['prop.specimen.jar-row', 0.8],
      ['prop.icon.listening-ear', 0.6],
      ['prop.specimen.your-own-lung', 0.3],
      ['prop.locker.reliquary-drawer', 0.4],
    ],
    tags: ['cult', 'gore', 'quiet'],
    lucid:
      '四壁的架子上是标本瓶，里面都是内耳的一部分，带着一小段颞骨。标签上不是名字，是一个频率值。',
    drift: '按频率排序，从低到高。最低那一瓶的频率低于人耳下限。取它的人生前听得见那个频率。',
    resonant: '所有瓶子都在朝你转。它们不需要神经，也不需要脑。听是一种更简单的行为。',
  }),
  room({
    id: 'rv.reliquary.wax-room',
    archetype: 'reliquary',
    name: '蜡室·地面积了一层蜡壳',
    decks: D.d4,
    weight: 9,
    ambient: { noiseFloor: 0.03, temperature: 6, presence: 0.66, airQuality: 0.4 },
    props: [
      ['prop.icon.wax-tablet', 0.75],
      ['prop.altar.offering-slab', 0.5],
      ['prop.locker.reliquary-drawer', 0.4],
      ['prop.corpse.choir-member', 0.3],
    ],
    tags: ['cult', 'quiet'],
    lucid: '一个存放蜡制品的小舱。地面积了厚厚一层滴落凝结的蜡，踩上去是软的。蜡里嵌着东西。',
    drift: '蜡里嵌着牙、纽扣、一枚身份牌。它们是一层一层被埋进去的，像年轮。',
    resonant: '最新的一层蜡还是软的，上面有一个脚印，尺码和你一样，但方向是从房间里往外走。',
  }),
  room({
    id: 'rv.reliquary.inner-sanctum',
    archetype: 'reliquary',
    name: '内殿·只有一件东西',
    decks: D.d45,
    weight: 7,
    ambient: { noiseFloor: 0.01, temperature: 2, presence: 0.86, airQuality: 0.38 },
    noiseThreshold: 38,
    props: [
      ['prop.altar.threshold-stone', 0.6],
      ['prop.icon.choir-plate', 0.55],
      ['prop.altar.iron-chair', 0.35],
      ['prop.specimen.folded-crewman', 0.3],
    ],
    tags: ['cult', 'ritual', 'quiet'],
    lucid:
      '一个很小的舱室，什么都没有，除了正中的一件东西。四壁光滑，没有装饰，因为装饰会分散注意。',
    drift: '这个房间的声学设计极好。它是为了让人在这里听清一个极小的声音而建的，代价是一切别的。',
    resonant: '房间是空的。正中那件东西是你带进来的，是你身上最响的那一样。它已经被要求交出来了。',
  }),

  // ============================================================ 月池 moonpool
  room({
    id: 'rv.moonpool.main-well',
    archetype: 'moonpool',
    name: '月池·水面与甲板齐平',
    decks: D.d5,
    weight: 15,
    ambient: { flooding: 0.62, noiseFloor: 0.18, temperature: 2.5, presence: 0.86, airQuality: 0.34 },
    props: [
      ['prop.porthole.moonpool-surface', 1],
      ['prop.valve.moonpool-drain', 0.6],
      ['prop.locker.dive-suit-rack', 0.45],
      ['prop.terminal.depth-readout', 0.4],
      ['prop.nest.bone-arrangement', 0.35],
    ],
    tags: ['anchor', 'endgame', 'exit'],
    lucid:
      '一个直通外海的方形开口，四米见方，水面与甲板齐平。在 -2,100 m，这个开口本该在一秒内灌满全船。它没有。',
    drift: '水面纹丝不动，和甲板齐平。压力算不平。有东西从下面顶住了这一整片水，而且一直在顶。',
    resonant: '水面是温的。它不是海面，是某个张着的东西的表面。它张着，是因为它在等你进去。',
  }),
  room({
    id: 'rv.moonpool.launch-platform',
    archetype: 'moonpool',
    name: '下放平台·吊架载荷已归零',
    decks: D.d5,
    weight: 11,
    ambient: { flooding: 0.5, noiseFloor: 0.2, temperature: 3, presence: 0.8, airQuality: 0.36 },
    props: [
      ['prop.locker.dive-suit-rack', 0.6],
      ['prop.valve.moonpool-drain', 0.45],
      ['prop.specimen.dredge-tray', 0.4],
      ['prop.radio.emergency-beacon', 0.35],
    ],
    tags: ['endgame', 'escape'],
    lucid: '下放设备用的平台，吊架和绞车都在。载荷指示归零，钢缆放到底，缆长计数器停在四位数。',
    drift: '缆长四位数，超过了海沟在这个位置的深度。缆放下去了，而且还没到底。',
    resonant: '缆在动。绞车没上电，缆在被往下拽，每次一点，节奏是三短两长一短。',
  }),
  room({
    id: 'rv.moonpool.dive-staging',
    archetype: 'moonpool',
    name: '潜水准备区·九套服，八个挂位',
    decks: D.d5,
    weight: 10,
    ambient: { flooding: 0.42, noiseFloor: 0.16, temperature: 3.5, presence: 0.76, airQuality: 0.38 },
    props: [
      ['prop.locker.dive-suit-rack', 0.85],
      ['prop.hatch.escape-trunk', 0.5],
      ['prop.terminal.depth-readout', 0.4],
      ['prop.corpse.your-double', 0.15],
    ],
    tags: ['escape', 'loot'],
    lucid: '潜水准备区，长凳、挂位、气瓶架。八个挂位挂了九套服。第九套没有挂钩，它自己立着。',
    drift: '第九套立着，面镜朝着房间的出口。气瓶是满的，是这个房间里唯一满的气瓶。',
    resonant: '第九套是给你准备的。尺码对，磨损的位置和你的习惯对得上。它已经被穿过很多次了。',
  }),
  room({
    id: 'rv.moonpool.flooded-well-head',
    archetype: 'moonpool',
    name: '井口舱·已完全上水',
    decks: D.d5,
    weight: 8,
    ambient: { flooding: 0.92, noiseFloor: 0.1, temperature: 2, presence: 0.88, airQuality: 0.14 },
    noiseThreshold: 100,
    props: [
      ['prop.porthole.moonpool-surface', 0.7],
      ['prop.specimen.growth-on-hull', 0.55],
      ['prop.nest.egg-cluster', 0.4],
      ['prop.specimen.folded-crewman', 0.3],
    ],
    tags: ['wet', 'breath-hold', 'endgame'],
    lucid: '井口舱已经完全上水。要过去必须屏住呼吸游过整个舱。舱壁上长满了东西，密度很高。',
    drift: '长满的东西在水里轻微地摆。它们都朝着同一个方向摆，而那个方向是你游进来的方向。',
    resonant: '你在水里，它们在你周围。它们不攻击，它们只是记录你经过时的形状，然后传下去。',
  }),

  // =============================================================== 虚舱 void
  room({
    id: 'rv.void.unlisted-compartment',
    archetype: 'void',
    name: '未列入总图的舱段',
    decks: D.d345,
    weight: 12,
    ambient: { noiseFloor: 0.01, temperature: 4, presence: 0.8, airQuality: 0.4 },
    noiseThreshold: 40,
    props: [
      ['prop.icon.hull-weld-sigil', 0.5],
      ['prop.terminal.blueprint-station', 0.3],
      ['prop.nest.bone-arrangement', 0.4],
      ['prop.mirror.mirrored-room-seam', 0.3],
    ],
    tags: ['topology', 'quiet', 'secret'],
    lucid:
      '一个空的舱段。四壁是裸钢，没有管路，没有线缆，没有任何设备接口。它不在任何一张图纸上。',
    drift: '没有任何接口，说明它从来没有被使用过；可是地面有磨损，集中在中央，形状是一个圆。',
    resonant: '中央那个圆是站位。这个房间是为了让某个东西站在正中而建的，四壁的裸钢是为了反射。',
  }),
  room({
    id: 'rv.void.room-zero',
    archetype: 'void',
    name: '零号舱',
    decks: D.d345,
    weight: 3,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0, temperature: 0.5, presence: 0.96, airQuality: 0.3 },
    noiseThreshold: 36,
    props: [
      ['prop.altar.name-wall', 1],
      ['prop.logbook.unwritten-log', 0.7],
      ['prop.nest.bone-arrangement', 0.8],
      ['prop.specimen.your-own-lung', 0.6],
      ['prop.mirror.two-way-observation', 0.5],
    ],
    tags: ['setpiece', 'secret', 'off-blueprint', 'quiet'],
    lucid:
      '这个舱室不在任何图纸上，声呐在清醒时也扫不到它。四壁刻满名字，从下往上，刻到齐胸高就停了——因为再往上刻的人不够高。地面正中有一个磨出来的圆。',
    drift:
      '名字从下往上刻。最上面一行墨没干。你的手自己抬起来，摸到了应该继续刻的那个位置，高度正合适。',
    resonant:
      '零号舱一直在这里。你前面每一次都进来过，每一次都在墙上加了一行。这是第四十二行的位置，它在等。',
  }),
  room({
    id: 'rv.void.mirrored-cell',
    archetype: 'void',
    name: '镜像舱',
    decks: D.d2345,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0.02, temperature: 6, presence: 0.7, airQuality: 0.44 },
    props: [
      ['prop.mirror.mirrored-room-seam', 1],
      ['prop.mirror.polished-bulkhead', 0.6],
      ['prop.terminal.dead-screen', 0.4],
    ],
    tags: ['setpiece', 'veracity', 'topology'],
    lucid:
      '这个房间和你刚走过的那一个完全对称。同样的设备，同样的剥漆位置，同样的螺栓数。包括你留下的痕迹——但痕迹是反的。',
    drift:
      '一切都镜像了，包括你上一个房间里踩出的那一串水印。它们在这里的位置是左右颠倒的，而且步序也是反的。',
    resonant:
      '对称是一种复制。复制需要一个模板，也需要一个执行者。执行者做得很好，它连你的犹豫都镜像了。',
  }),
  room({
    id: 'rv.void.mobius-segment',
    archetype: 'void',
    name: '莫比乌斯走廊',
    decks: D.d345,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { noiseFloor: 0.03, temperature: 5, presence: 0.74, airQuality: 0.42 },
    props: [
      ['prop.icon.hull-weld-sigil', 0.8],
      ['prop.terminal.dead-screen', 0.5],
      ['prop.locker.crew-personal', 0.5],
      ['prop.porthole.taped-over', 0.4],
      ['prop.mirror.polished-bulkhead', 0.4],
    ],
    tags: ['setpiece', 'topology', 'loop'],
    lucid:
      '一条笔直的走廊，尽头是一扇门。你推门走出去，又从这条走廊的另一头走了进来。走廊没有变，但少了一件东西。',
    drift:
      '第二次回来，墙上的灭火器不在了。第三次，储物柜不在了。走廊在变短，不是长度，是内容。',
    resonant:
      '第四次你走回起点，走廊是空的，四壁是裸钢，你是唯一剩下的东西。它一件件把走廊里的东西收走，剩下最后一件。',
  }),

  // ============================================================ 淹水区 flooded
  room({
    id: 'rv.flooded.knee-deep-compartment',
    archetype: 'flooded',
    name: '半淹舱段·水面齐膝',
    decks: D.d2345,
    weight: 14,
    ambient: { flooding: 0.4, temperature: 8, noiseFloor: 0.2, airQuality: 0.48 },
    floodRate: 0.0022,
    props: [
      ['prop.pipe.ruptured-main', 0.5],
      ['prop.valve.bilge-c', 0.35],
      ['prop.specimen.growth-on-hull', 0.35],
      ['prop.corpse.valve-clutcher', 0.25],
    ],
    tags: ['wet'],
    lucid: '这个舱进了水，齐膝。漂浮物都聚集在一个角落，说明水在缓慢地朝那个方向流。',
    drift: '漂浮物聚在一角，可是那一角的地板比别处高。水在往上坡的方向流。',
    resonant: '水在朝一个地方去。所有的水都在往那里去，因为那里在喝。',
  }),
  room({
    id: 'rv.flooded.chest-deep',
    archetype: 'flooded',
    name: '深水舱·水面齐胸',
    decks: D.d2345,
    weight: 13,
    ambient: { flooding: 0.68, temperature: 6, noiseFloor: 0.16, airQuality: 0.4, presence: 0.4 },
    floodRate: 0.0028,
    props: [
      ['prop.specimen.growth-on-hull', 0.45],
      ['prop.specimen.folded-crewman', 0.25],
      ['prop.pipe.frozen-branch', 0.3],
      ['prop.nest.egg-cluster', 0.25],
    ],
    tags: ['wet', 'cold'],
    lucid: '水到胸口。冷得让你的呼吸变浅。每走一步都要推开一整个房间的水，很费气。',
    drift: '你推水，水推回来。推回来的力比水该有的大，而且有节奏，和你的步子错开半拍。',
    resonant: '水不是在被你推开。它是在让开，一次一点点，刚好让你能走，但不让你走快。',
  }),
  room({
    id: 'rv.flooded.submerged-passage',
    archetype: 'flooded',
    name: '全淹通道·需屏息通过',
    decks: D.d345,
    weight: 11,
    ambient: { flooding: 0.95, temperature: 4, noiseFloor: 0.06, airQuality: 0.1, presence: 0.5 },
    noiseThreshold: 96,
    floodRate: 0,
    props: [
      ['prop.specimen.growth-on-hull', 0.5],
      ['prop.pipe.frozen-branch', 0.35],
      ['prop.specimen.folded-crewman', 0.25],
      ['prop.nest.egg-cluster', 0.3],
    ],
    tags: ['wet', 'breath-hold'],
    lucid: '这段通道完全在水下。要过去必须屏住呼吸。目测长度大约十五米，中间有一个转角。',
    drift: '十五米，一个转角。水很清。转角之后看不见，那一段的长度你只能猜。',
    resonant: '你在水里，肺开始要东西。转角之后的通道比你估的长。它每次都比你估的长一点。',
  }),
  room({
    id: 'rv.flooded.sump-chamber',
    archetype: 'flooded',
    name: '积水舱·油膜厚得反光',
    decks: D.d2345,
    weight: 10,
    ambient: { flooding: 0.56, temperature: 7, noiseFloor: 0.22, airQuality: 0.34 },
    floodRate: 0.0026,
    props: [
      ['prop.valve.bilge-c', 0.5],
      ['prop.breaker.pump-contactor', 0.4],
      ['prop.pipe.ruptured-main', 0.4],
      ['prop.nest.metal-hoard', 0.25],
    ],
    tags: ['wet'],
    lucid: '积水舱，水面浮着厚油膜，反光是彩色的。油味重到你的面罩滤不掉。',
    drift: '油膜的花纹固定不动，水在动。膜下面有东西把它撑住了，撑成一个不变的图案。',
    resonant: '油膜的图案是这一层的走廊图，比例正确。它在标出你走过的路，用一条更亮的线。',
  }),
  room({
    id: 'rv.flooded.collapsed-space',
    archetype: 'flooded',
    name: '坍塌舱段·钢板折成锐角',
    decks: D.d345,
    weight: 9,
    ambient: { flooding: 0.62, temperature: 5, noiseFloor: 0.18, airQuality: 0.36, presence: 0.48 },
    floodRate: 0.0024,
    props: [
      ['prop.nest.listener-sign', 0.55],
      ['prop.specimen.folded-crewman', 0.35],
      ['prop.icon.hull-weld-sigil', 0.3],
      ['prop.specimen.growth-on-hull', 0.3],
    ],
    tags: ['wet', 'listener-evidence'],
    lucid: '舱段的一侧被压进来了，钢板折成锐角。折痕是平滑的，没有撕裂，说明力是缓慢施加的。',
    drift: '折痕平滑，说明是慢慢挤的。挤的宽度约一米八，从地板连到舱顶，是一个通过的剖面。',
    resonant: '剖面是温的。它从这里过去的时候没有急，它有时间，因为它不需要呼吸。',
  }),
  room({
    id: 'rv.flooded.ice-cold-hold',
    archetype: 'flooded',
    name: '冰冷货舱·水面结了薄壳',
    decks: D.d45,
    weight: 8,
    ambient: { flooding: 0.6, temperature: 0.5, noiseFloor: 0.1, airQuality: 0.38, presence: 0.54 },
    floodRate: 0.002,
    props: [
      ['prop.pipe.frozen-branch', 0.6],
      ['prop.specimen.dredge-tray', 0.35],
      ['prop.nest.egg-cluster', 0.3],
      ['prop.specimen.growth-on-hull', 0.3],
    ],
    tags: ['wet', 'cold'],
    lucid: '货舱，水面结了一层薄冰壳，踩破会响。海水在这个压力下不该结冰。',
    drift: '海水在 -2,100 m 不会结冰，除非有东西在抽走热。冰壳是从中心往外长的。',
    resonant: '冰壳的中心是一个人形的凹陷，仰面躺着的姿势。热是从那里被抽走的，一直在抽。',
  }),
  room({
    id: 'rv.flooded.inverted-ballast',
    archetype: 'flooded',
    name: '倒悬压载舱',
    decks: D.d45,
    weight: 4,
    unique: true,
    manualOnly: true,
    ambient: { flooding: 0.78, temperature: 3, noiseFloor: 0.12, airQuality: 0.3, presence: 0.82 },
    noiseThreshold: 58,
    floodRate: 0,
    props: [
      ['prop.valve.bilge-c', 1],
      ['prop.breaker.pump-contactor', 0.7],
      ['prop.specimen.growth-on-hull', 0.6],
      ['prop.nest.bone-arrangement', 0.4],
    ],
    tags: ['setpiece', 'topology', 'wet'],
    lucid:
      '水在天花板上。它贴着舱顶铺成一层，厚约一米二，边缘平整。地板是干的，你站在干的那一侧。舱顶的水面上有涟漪，从上面看是从下往上落的。',
    drift:
      '水在天花板上，不滴。这不是失重——你身上的水在往下滴，你的血在往下走。只有那一片水的上下是反的。',
    resonant:
      '天花板上的水里有东西在游，倒着。要过这个舱，你得让水回到地板上，而水回到地板上意味着下面那一层要腾出位置。',
  }),
];
