/**
 * world/content/rooms.cmd.ts — 指挥层系房间变体
 *
 * 通道 / 隔舱 / 舰桥 / 声呐室 / 档案 / 观测。
 * D3 是信息层：这一层的房间不给玩家道具，给**判断依据**。
 * 写作纪律：真相永远以"两份互相矛盾的记录"的形式出现，从不由旁白宣布。
 */

import { D, room } from './helpers';
import type { RoomVariant } from '../types';

export const CMD_ROOMS: readonly RoomVariant[] = [
  // ============================================================ 通道 corridor
  room({
    id: 'rv.corridor.command-passage',
    archetype: 'corridor',
    name: '指挥通道·地板铺了隔声胶垫',
    decks: D.d34,
    weight: 12,
    ambient: { noiseFloor: 0.06, airQuality: 0.62, presence: 0.3, temperature: 8 },
    noiseThreshold: 52,
    props: [
      ['prop.terminal.depth-readout', 0.4],
      ['prop.icon.hull-weld-sigil', 0.35],
      ['prop.radio.bulkhead-set', 0.3],
      ['prop.altar.name-wall', 0.2],
    ],
    tags: ['spine', 'quiet'],
    lucid: '通往舰桥的通道，地板铺了厚胶垫。走上去没有声音。胶垫是后铺的，压住了原来的编号漆。',
    drift: '胶垫是后铺的，铺得很讲究，接缝对齐。铺的人不想让自己的脚步被听见，在自己的船上。',
    resonant: '你走上去没有声音，可是你听见了脚步。脚步比你快半步，在你前面，一直在你前面。',
  }),
  room({
    id: 'rv.corridor.archive-stacks-aisle',
    archetype: 'corridor',
    name: '档案架间通道·纸味很重',
    decks: D.d34,
    weight: 10,
    ambient: { noiseFloor: 0.05, airQuality: 0.58, temperature: 7 },
    props: [
      ['prop.logbook.deck-log', 0.45],
      ['prop.terminal.dead-screen', 0.3],
      ['prop.icon.wax-tablet', 0.25],
    ],
    tags: ['spine', 'quiet'],
    lucid: '两侧是移动式档案架，通道被压到只有六十公分宽。纸和防霉剂的味道很重。',
    drift: '档案架是可以移动的。现在的位置把这条通道压到最窄，而且压的方向是朝着你进来的方向。',
    resonant: '你走过之后，身后的架子合上了。它们不是滑动，是靠过来，像人群闭合。',
  }),
  room({
    id: 'rv.corridor.periscope-well',
    archetype: 'corridor',
    name: '潜望镜井周道·筒身冰凉',
    decks: D.d34,
    weight: 9,
    ambient: { noiseFloor: 0.08, temperature: 6, presence: 0.34 },
    props: [
      ['prop.terminal.depth-readout', 0.35],
      ['prop.mirror.polished-bulkhead', 0.35],
      ['prop.porthole.small-round', 0.3],
      ['prop.icon.inverted-cross-staff', 0.2],
    ],
    tags: ['spine'],
    lucid: '环绕潜望镜筒的窄道。筒身是冰的。镜筒被降到底并锁定，锁杆上挂了一把锁，钥匙不在。',
    drift: '筒身比这个房间冷十几度。冷源是上面，也就是海的方向——可是海水在这个深度是四度，不是这个温度。',
    resonant: '你贴在筒身上，能听见筒里有东西在往下滑，很慢。它从海那一头进来了，正在下来。',
  }),

  // ============================================================ 隔舱 bulkhead
  room({
    id: 'rv.bulkhead.command-vestibule',
    archetype: 'bulkhead',
    name: '指挥前厅·值更簿钉在门边',
    decks: D.d34,
    weight: 12,
    ambient: { noiseFloor: 0.07, temperature: 7, presence: 0.3 },
    props: [
      ['prop.logbook.deck-log', 0.55],
      ['prop.hatch.deck-trunk', 0.45],
      ['prop.radio.bulkhead-set', 0.35],
      ['prop.altar.name-wall', 0.25],
    ],
    tags: ['spine', 'junction'],
    lucid: '进入指挥区的前厅。门边钉着值更簿，签名一直签到最后。最后一班的签名比前面的都整齐。',
    drift: '最后一班的签名整齐，而且每一个名字的笔迹都一样。是一个人代签了全部四十一个。',
    resonant: '签名下面还有一行，正在被写。你能看见笔压在纸上留下的凹，凹出来的是你的名字。',
  }),
  room({
    id: 'rv.bulkhead.pressure-door-bank',
    archetype: 'bulkhead',
    name: '压力门组·五扇门四个编号',
    decks: D.d345,
    weight: 10,
    ambient: { noiseFloor: 0.1, temperature: 6, presence: 0.4 },
    props: [
      ['prop.icon.hull-weld-sigil', 0.55],
      ['prop.hatch.deck-trunk', 0.4],
      ['prop.terminal.engineering-mimic', 0.25],
      ['prop.mirror.mirrored-room-seam', 0.2],
    ],
    tags: ['spine', 'junction', 'unstable-hint'],
    lucid: '一个小舱，五扇压力门。门框上的编号只有四个：3、4、5、7。有一扇门没有编号。',
    drift: '缺 6 号。没有编号那一扇门的门框漆比其他四扇新，而且它的合页是新的。',
    resonant:
      '没有编号那一扇每次都通往不同的地方。它是这条船改动自己时用的那一扇，编号留空是因为目的地会变。',
  }),
  room({
    id: 'rv.bulkhead.sanctum-threshold',
    archetype: 'bulkhead',
    name: '圣所门限前室·地面磨出浅坑',
    decks: D.d34,
    weight: 9,
    ambient: { noiseFloor: 0.04, temperature: 5, presence: 0.58, airQuality: 0.5 },
    props: [
      ['prop.hatch.sanctum-portal', 0.7],
      ['prop.icon.listening-ear', 0.45],
      ['prop.altar.threshold-stone', 0.3],
      ['prop.icon.wax-tablet', 0.3],
    ],
    tags: ['junction', 'cult'],
    lucid: '通往圣所的前室。地面在门前被磨出一个浅坑，坑的形状是跪姿的两个膝盖，位置很固定。',
    drift: '浅坑很深。要磨出这个深度，需要的跪拜次数远超四十一个人的一生。',
    resonant: '坑在等。你走近，膝盖后侧的肌肉自己松了一下 —— 你的身体记得这个动作，你不记得。',
  }),

  // ============================================================== 舰桥 bridge
  room({
    id: 'rv.bridge.attack-center',
    archetype: 'bridge',
    name: '攻击指挥所·所有座位朝外',
    decks: D.d3,
    weight: 14,
    ambient: { noiseFloor: 0.1, temperature: 8, airQuality: 0.62, presence: 0.34 },
    props: [
      ['prop.terminal.sonar-console', 0.6],
      ['prop.terminal.crew-roster', 0.5],
      ['prop.logbook.deck-log', 0.55],
      ['prop.corpse.radio-operator', 0.4],
      ['prop.breaker.command-bus', 0.3],
    ],
    tags: ['anchor'],
    lucid:
      '攻击指挥所。控制台围成一圈，座椅在圈内。所有座椅都被转向了圈外，朝着舱壁，而不是朝着控制台。',
    drift: '所有座椅朝外。圈外没有任何可看的东西，只有舱壁。他们不是在操船，他们是在听。',
    resonant: '每把椅子的靠背上都有一个头的凹痕，凹痕的位置是仰着的。他们在听头顶上的东西。',
  }),
  room({
    id: 'rv.bridge.helm-station',
    archetype: 'bridge',
    name: '操舵位·舵角指示为满舵',
    decks: D.d3,
    weight: 11,
    ambient: { noiseFloor: 0.08, temperature: 8, presence: 0.3 },
    props: [
      ['prop.terminal.depth-readout', 0.55],
      ['prop.logbook.deck-log', 0.4],
      ['prop.terminal.engineering-mimic', 0.4],
      ['prop.radio.mother-speaker', 0.35],
    ],
    lucid: '操舵位。舵角指示器在满舵，一直没回中。深度计和纵倾仪都在正常范围，与船体现状不符。',
    drift: '深度计读数是 -340。你现在在 -1,120。仪表不是坏了——它显示的是这条船认为自己在的地方。',
    resonant: '仪表是对的。这条船真的在 -340 米，一直都在。往下的是别的东西，而你在那个东西里面。',
  }),
  room({
    id: 'rv.bridge.radio-shack',
    archetype: 'bridge',
    name: '无线电室·频率旋钮被胶带固定',
    decks: D.d3,
    weight: 10,
    ambient: { noiseFloor: 0.06, temperature: 9, airQuality: 0.6, presence: 0.38 },
    props: [
      ['prop.corpse.radio-operator', 0.6],
      ['prop.radio.bulkhead-set', 0.5],
      ['prop.radio.self-recorder', 0.4],
      ['prop.logbook.sonar-tape-log', 0.35],
    ],
    tags: ['lore'],
    lucid:
      '很小的无线电室。主收发机的频率旋钮被胶带固定在一个位置上，胶带缠了很多圈。那个频率在民用与军用之间的空白段。',
    drift: '空白段不该有任何信号。旋钮被固定住是为了不让它偏，说明那里一直有东西在播。',
    resonant: '扬声器里在播。是一个人在报深度，一位一位地报，报到的位数比仪表能显示的还多。',
  }),
  room({
    id: 'rv.bridge.chart-table',
    archetype: 'bridge',
    name: '海图台·本船位置画了一个圈',
    decks: D.d34,
    weight: 9,
    ambient: { noiseFloor: 0.06, temperature: 8, presence: 0.32 },
    props: [
      ['prop.terminal.sonar-console', 0.45],
      ['prop.terminal.blueprint-station', 0.4],
      ['prop.icon.inverted-cross-staff', 0.35],
      ['prop.logbook.deck-log', 0.4],
    ],
    tags: ['lore', 'puzzle'],
    lucid:
      '倾斜的海图台，压着一张大比例海图。航迹用铅笔画着，一直画到图上一片没有等深线的空白，在那里画了一个圈。',
    drift: '空白区域周围的等深线都在往里收，收到边缘就停了。测绘的人到这里就停了测，不是因为测不到。',
    resonant: '圈在变大，很慢。它把周围的等深线一条条吃掉。图上被吃掉的那些地方，现实里也没有了。',
  }),

  // ========================================================= 声呐室 sonar-room
  room({
    id: 'rv.sonar.main-shack',
    archetype: 'sonar-room',
    name: '声呐舱·示波管仍有余辉',
    decks: D.d3,
    weight: 14,
    ambient: { noiseFloor: 0.05, temperature: 7, airQuality: 0.6, presence: 0.4 },
    noiseThreshold: 50,
    props: [
      ['prop.terminal.sonar-console', 0.85],
      ['prop.breaker.sonar-array', 0.6],
      ['prop.logbook.sonar-tape-log', 0.6],
      ['prop.corpse.radio-operator', 0.4],
      ['prop.specimen.jar-row', 0.25],
    ],
    tags: ['anchor', 'sonar', 'quiet'],
    lucid:
      '声呐舱，三个工位。示波管还有余辉。工位之间挂着隔声帘。桌上有一本贴满热敏纸波形的记录册。',
    drift: '示波管上有一条距离为零的回波。零距离的回波只能来自换能器本身，或者来自这个房间里的东西。',
    resonant: '三个工位的耳机都在响。三副耳机里是同一个声音，而它是你的呼吸，延迟不同。',
  }),
  room({
    id: 'rv.sonar.hydrophone-bay',
    archetype: 'sonar-room',
    name: '水听器舱·前置放大器全开',
    decks: D.d34,
    weight: 11,
    ambient: { noiseFloor: 0.03, temperature: 6, airQuality: 0.56, presence: 0.46 },
    noiseThreshold: 46,
    props: [
      ['prop.breaker.sonar-array', 0.6],
      ['prop.terminal.sonar-console', 0.45],
      ['prop.icon.listening-ear', 0.4],
      ['prop.pipe.conduit-bundle', 0.3],
    ],
    tags: ['sonar', 'quiet'],
    lucid: '被动水听器的前置放大器机架。所有增益旋钮都推到了顶。这样的增益下，人的心跳都会过载。',
    drift: '增益推到顶，而且有人用漆把旋钮和面板一起封住了，不让它被调回来。',
    resonant: '增益到顶是为了听见那个几乎不存在的东西。它现在不是几乎不存在了。它就在隔壁。',
  }),
  room({
    id: 'rv.sonar.tape-library',
    archetype: 'sonar-room',
    name: '磁带库·第七卷的位置是空的',
    decks: D.d34,
    weight: 10,
    ambient: { noiseFloor: 0.04, temperature: 6, airQuality: 0.58 },
    props: [
      ['prop.logbook.sonar-tape-log', 0.7],
      ['prop.radio.self-recorder', 0.5],
      ['prop.specimen.dredge-tray', 0.3],
      ['prop.terminal.dead-screen', 0.3],
    ],
    tags: ['sonar', 'lore', 'quiet'],
    lucid: '架子上排着磁带盒，编号连续。第七卷的位置空着，盒子不在，卡槽里的灰尘轮廓完整。',
    drift: '第七卷不在架上，可是每一卷的标签上都写着「参见第七卷」。所有的路都指向缺的那一卷。',
    resonant: '第七卷在放音机里，一直在放。你听不见，因为它录的是低于你听觉下限的东西，而你在听。',
  }),
  room({
    id: 'rv.sonar.transducer-trunk',
    archetype: 'sonar-room',
    name: '换能器竖井·维修平台已上水',
    decks: D.d345,
    weight: 8,
    ambient: { flooding: 0.5, noiseFloor: 0.12, temperature: 4, presence: 0.52, airQuality: 0.46 },
    floodRate: 0.0024,
    props: [
      ['prop.breaker.sonar-array', 0.5],
      ['prop.specimen.growth-on-hull', 0.45],
      ['prop.pipe.frozen-branch', 0.3],
      ['prop.nest.listener-sign', 0.25],
    ],
    tags: ['sonar', 'wet'],
    lucid: '通往球鼻艏换能器的竖井。维修平台已经被水淹到脚踝。换能器阵面从下方透出微弱的震动。',
    drift: '阵面在震动，但没人在发脉冲。它在被从外面敲，敲的力度刚好不足以让它响。',
    resonant: '它不是在被敲，是在被**说话**。外面的东西在用你的换能器说话，声音进到船里就成了你的想法。',
  }),

  // ============================================================= 档案 archive
  room({
    id: 'rv.archive.records-room',
    archetype: 'archive',
    name: '档案舱·柜门全部敞开',
    decks: D.d34,
    weight: 13,
    ambient: { noiseFloor: 0.05, temperature: 7, airQuality: 0.58, presence: 0.3 },
    props: [
      ['prop.terminal.crew-roster', 0.6],
      ['prop.terminal.liturgy-index', 0.5],
      ['prop.logbook.chaplain-journal', 0.4],
      ['prop.terminal.blueprint-station', 0.4],
      ['prop.icon.wax-tablet', 0.3],
    ],
    tags: ['anchor', 'lore', 'quiet'],
    lucid: '档案舱，所有柜门都敞开着，卷宗被抽走大半。留下的是不重要的那些：采购单、维修记录。',
    drift: '被抽走的都是人事和医疗。留下的都是物。有人在离开前把「人」的部分带走了。',
    resonant: '柜子里现在满了。卷宗全回来了，每一份的封面上都是你的名字，编号从 001 到 041。',
  }),
  room({
    id: 'rv.archive.microfiche-room',
    archetype: 'archive',
    name: '缩微胶片室·阅读机还亮着',
    decks: D.d34,
    weight: 11,
    ambient: { noiseFloor: 0.04, temperature: 7, airQuality: 0.56 },
    props: [
      ['prop.terminal.blueprint-station', 0.7],
      ['prop.terminal.crew-roster', 0.4],
      ['prop.logbook.deck-log', 0.35],
      ['prop.terminal.dead-screen', 0.3],
    ],
    tags: ['lore', 'puzzle', 'quiet'],
    lucid: '几台胶片阅读机，其中一台还亮着，屏幕上停在一张船体总图。总图的甲板数是五。',
    drift: '亮着那一台的手轮还是温的。屏幕上的总图有一个用铅笔在玻璃上画的箭头，指向图纸的空白处。',
    resonant: '总图的甲板数变成了六。第六层没有名字，它的形状是前五层的外轮廓，从外面包住它们。',
  }),
  room({
    id: 'rv.archive.liturgy-vault',
    archetype: 'archive',
    name: '仪轨库·四十一册，缺第零册',
    decks: D.d34,
    weight: 10,
    ambient: { noiseFloor: 0.03, temperature: 6, airQuality: 0.52, presence: 0.44 },
    props: [
      ['prop.terminal.liturgy-index', 0.7],
      ['prop.logbook.chaplain-journal', 0.55],
      ['prop.icon.choir-plate', 0.4],
      ['prop.icon.wax-tablet', 0.35],
    ],
    tags: ['cult', 'lore', 'quiet'],
    lucid: '恒温恒湿的小库房。架上四十一册手抄仪轨，编号从 1 到 41。零号的卡位存在，是空的。',
    drift: '零号的卡位比其他都宽。零号册比其他都厚，或者零号不是一本书。',
    resonant: '零号在你手上。你不记得拿起它。它很薄，只有一页，那一页上是这条船的平面图，画着你现在站的位置。',
  }),
  room({
    id: 'rv.archive.personnel-files',
    archetype: 'archive',
    name: '人事档案间·有一份档案是重复的',
    decks: D.d34,
    weight: 9,
    ambient: { noiseFloor: 0.05, temperature: 7, presence: 0.34 },
    props: [
      ['prop.terminal.crew-roster', 0.75],
      ['prop.specimen.your-own-lung', 0.25],
      ['prop.logbook.medical-chart', 0.4],
      ['prop.mirror.two-way-observation', 0.25],
    ],
    tags: ['lore', 'self', 'quiet'],
    lucid: '人事档案，四十一份，按姓氏排列。其中有一份出现了两次，位置在正确的排序位和最后一位。',
    drift: '重复的那一份内容不完全相同。最后一位那一份的照片格是空的，其他字段都填了。',
    resonant: '重复的那一份是你的。它一共有四十一份副本，这个抽屉里的是第四十一份，前四十份已经归档。',
  }),
  room({
    id: 'rv.archive.blueprint-room',
    archetype: 'archive',
    name: '图纸室·总图之外还有一叠',
    decks: D.d345,
    weight: 8,
    ambient: { noiseFloor: 0.04, temperature: 6, airQuality: 0.54, presence: 0.38 },
    props: [
      ['prop.terminal.blueprint-station', 0.8],
      ['prop.icon.hull-weld-sigil', 0.45],
      ['prop.terminal.engineering-mimic', 0.35],
      ['prop.logbook.engineering-rounds', 0.3],
    ],
    tags: ['lore', 'topology', 'quiet'],
    lucid:
      '图纸室，大幅蓝图卷在管子里。标准总图在架上。另有一叠标着「非结构」的图，卷得更紧，绳子打了死结。',
    drift: '「非结构」那一叠的图纸上画的舱段不在总图上。它们的边界线是虚线，注释写着「按需」。',
    resonant: '「按需」。这条船有一批可以按需出现的舱段。零号舱是其中一个，而清单的第一行是它。',
  }),

  // ========================================================= 观测 observation
  room({
    id: 'rv.observation.main-gallery',
    archetype: 'observation',
    name: '观测廊·长凳朝着窗',
    decks: D.d34,
    weight: 13,
    ambient: { noiseFloor: 0.04, temperature: 5, airQuality: 0.52, presence: 0.6 },
    noiseThreshold: 48,
    props: [
      ['prop.porthole.observation-pane', 0.85],
      ['prop.altar.listening-bench', 0.6],
      ['prop.icon.listening-ear', 0.35],
      ['prop.corpse.choir-member', 0.3],
    ],
    tags: ['anchor', 'cult', 'quiet'],
    lucid: '一条弧形的观测廊，外舷是连续的观察窗。窗前摆着长凳，朝着窗。窗外是黑的。',
    drift: '长凳上的磨痕说明有人在这里坐了很久。可是窗外没有任何可看的东西，一直都没有。',
    resonant: '他们不是在看。他们是在被看。长凳的位置是从外面能看得最清楚的角度摆的。',
  }),
  room({
    id: 'rv.observation.blister',
    archetype: 'observation',
    name: '半球观测泡·玻璃内表面有细裂',
    decks: D.d345,
    weight: 10,
    ambient: { noiseFloor: 0.03, temperature: 4, airQuality: 0.48, presence: 0.66 },
    props: [
      ['prop.porthole.observation-pane', 0.7],
      ['prop.porthole.cracked-pane', 0.4],
      ['prop.altar.listening-bench', 0.35],
      ['prop.icon.inverted-cross-staff', 0.3],
    ],
    tags: ['cult', 'hazard', 'quiet'],
    lucid:
      '一个突出船体的半球玻璃泡，直径三米。你站在里面，四周和脚下都是玻璃。内表面有均匀的细裂纹。',
    drift: '细裂纹在内表面。这个深度的压力只会让玻璃从外表面开裂。有一次力是从里面往外的。',
    resonant: '你站在玻璃泡里，周围是黑的。黑里有东西的轮廓，不是靠光看出来的，是靠它挡住了更远的黑。',
  }),
  room({
    id: 'rv.observation.wet-gallery',
    archetype: 'observation',
    name: '进水的观测廊·水面齐膝',
    decks: D.d45,
    weight: 9,
    ambient: { flooding: 0.46, noiseFloor: 0.1, temperature: 3, presence: 0.64, airQuality: 0.44 },
    floodRate: 0.0026,
    props: [
      ['prop.porthole.cracked-pane', 0.6],
      ['prop.porthole.observation-pane', 0.5],
      ['prop.specimen.growth-on-hull', 0.4],
      ['prop.altar.drowning-basin', 0.25],
    ],
    tags: ['cult', 'wet'],
    lucid: '观测廊已经进水，齐膝。水面很平。窗外是黑的，窗内的水把黑反射成一条连续的带。',
    drift: '水面反射的黑带里有一处比别处亮。你顺着找那个光源，在这个房间里找不到。',
    resonant: '亮的那一处是一只眼睛的反光，在窗外，贴着玻璃，在水下的那一半。它一直在看水里的你。',
  }),
  room({
    id: 'rv.observation.choir-loft',
    archetype: 'observation',
    name: '唱诗台·六个位置面朝舱壁',
    decks: D.d34,
    weight: 8,
    ambient: { noiseFloor: 0.02, temperature: 5, airQuality: 0.5, presence: 0.7 },
    noiseThreshold: 44,
    props: [
      ['prop.corpse.choir-member', 0.7, 3],
      ['prop.icon.choir-plate', 0.6],
      ['prop.altar.listening-bench', 0.45],
      ['prop.altar.name-wall', 0.35],
    ],
    tags: ['cult', 'quiet', 'gore'],
    lucid: '一个抬高的小平台，六个跪位，全部面朝舱壁而非面朝下方的礼拜堂。跪位上有人。',
    drift: '六个跪位，六个人。他们面朝的那面舱壁上没有任何东西，只有一道焊缝，齐耳高。',
    resonant: '六个人在唱。声音不从嘴里出来，从那道焊缝里出来，然后回到他们的耳朵。他们是扬声器。',
  }),
];
