/**
 * world/content/rooms.mech.ts — 机械层系房间变体
 *
 * 通道 / 引擎 / 反应堆 / 压载 / 鱼雷 / 爬行管道。
 * D2 的任务是**最高的解谜密度与最大的噪音**：这一层的每个房间都该让玩家
 * 在"我需要它"和"它会让整条船听见我"之间做一次真实的取舍。
 *
 * 爬行管道的设计契约（GDD §6.2）：noiseFloor 极低、noiseThreshold 极高，
 * 但 presence 高、airQuality 低 —— 噪音最省，SAN 最贵。
 */

import { D, room } from './helpers';
import type { RoomVariant } from '../types';

export const MECH_ROOMS: readonly RoomVariant[] = [
  // ============================================================ 通道 corridor
  room({
    id: 'rv.corridor.machinery-catwalk',
    archetype: 'corridor',
    name: '机舱栈桥·格栅下方是水',
    decks: D.d23,
    weight: 12,
    ambient: { flooding: 0.24, noiseFloor: 0.38, temperature: 18, airQuality: 0.52 },
    props: [
      ['prop.pipe.conduit-bundle', 0.45],
      ['prop.breaker.lighting-panel', 0.35],
      ['prop.pipe.ruptured-main', 0.3],
    ],
    tags: ['spine', 'loud'],
    lucid: '钢格栅栈桥，架在机舱上方两米。格栅下面是水，水面漂着油膜，反光是彩色的。',
    drift: '油膜的花纹在同一个位置反复出现。水在动，膜不动——膜下面有东西固定着它。',
    resonant: '你的脚步在格栅上响，下面的水按同样的节拍回响，但少一拍。少的那一拍你正踩着。',
  }),
  room({
    id: 'rv.corridor.steam-alley',
    archetype: 'corridor',
    name: '蒸汽走廊·能见度两米',
    decks: D.d2,
    weight: 10,
    ambient: { temperature: 34, airQuality: 0.4, noiseFloor: 0.46, presence: 0.2 },
    props: [
      ['prop.valve.steam-crossover', 0.5],
      ['prop.pipe.ruptured-main', 0.4],
      ['prop.corpse.valve-clutcher', 0.25],
    ],
    tags: ['spine', 'loud', 'hot'],
    lucid: '一条被蒸汽填满的走廊。能见度两米，皮肤上立刻挂满水珠。蒸汽的嘶声盖住了一切。',
    drift: '蒸汽的嘶声盖住了一切，包括你自己的脚步。这里你听不见任何东西，任何东西也听不见你。',
    resonant: '蒸汽里有一个不动的密度更高的区域，大约人高。你走近，它移开，始终保持两米。',
  }),
  room({
    id: 'rv.corridor.cable-run',
    archetype: 'corridor',
    name: '电缆通道·线束沿壁延伸',
    decks: D.d234,
    weight: 10,
    ambient: { noiseFloor: 0.18, airQuality: 0.56, presence: 0.22 },
    props: [
      ['prop.pipe.conduit-bundle', 0.65],
      ['prop.icon.hull-weld-sigil', 0.3],
      ['prop.breaker.lighting-panel', 0.3],
    ],
    tags: ['spine'],
    lucid: '狭窄通道，两侧墙面被线束占满。线束按功能分色，分色标签还在，读得清。',
    drift: '有一束没有分色标签，比其他束粗一倍，走向和所有别的束都不一样。它往下走。',
    resonant: '那一束是温的，有脉动，周期四秒。它不是线，只是外皮是线的样子。',
  }),

  // ============================================================== 引擎 engine
  room({
    id: 'rv.engine.main-room',
    archetype: 'engine',
    name: '主机舱·两台柴油机静止',
    decks: D.d2,
    weight: 14,
    ambient: { flooding: 0.2, temperature: 22, noiseFloor: 0.42, airQuality: 0.46 },
    props: [
      ['prop.locker.tool-cage', 0.6],
      ['prop.valve.trunk-a', 0.3],
      ['prop.logbook.engineering-rounds', 0.5],
      ['prop.corpse.valve-clutcher', 0.35],
      ['prop.breaker.command-bus', 0.2],
    ],
    tags: ['anchor', 'loud'],
    lucid:
      '两台主机并排，都停了。曲轴箱盖开着，里面的机油还是干净的。工具按顺序摆在机身上，像在拆到一半。',
    drift: '拆到一半，但拆的顺序是错的——他先卸了最难的部分。那是拆给别人看的，不是修。',
    resonant: '其中一台在转。你摸不到振动，可是你听得见，而且转速在跟着你的心率。',
  }),
  room({
    id: 'rv.engine.auxiliary-machinery',
    archetype: 'engine',
    name: '辅机舱·空压机仍在启停',
    decks: D.d23,
    weight: 11,
    ambient: { flooding: 0.16, temperature: 20, noiseFloor: 0.5, airQuality: 0.48 },
    props: [
      ['prop.valve.oxygen-bleed', 0.55],
      ['prop.breaker.pump-contactor', 0.45],
      ['prop.locker.tool-cage', 0.4],
      ['prop.pipe.conduit-bundle', 0.3],
    ],
    tags: ['loud', 'resource'],
    lucid: '辅机舱。空压机每隔一段时间自己启动一次，打到压力就停。它一直在做这件事。',
    drift: '空压机在给某个储气罐充气，可是全船的储气罐都满了。它充的那个罐不在图纸上。',
    resonant: '每次空压机启动，你的面罩里就多一点气。它一直在替你准备，准备得比你需要的多。',
  }),
  room({
    id: 'rv.engine.shaft-alley',
    archetype: 'engine',
    name: '轴隧·艉轴仍在缓慢转动',
    decks: D.d23,
    weight: 10,
    ambient: { flooding: 0.36, temperature: 16, noiseFloor: 0.34, presence: 0.3 },
    props: [
      ['prop.pipe.knocking-line', 0.4],
      ['prop.breaker.hull-ground', 0.3],
      ['prop.specimen.growth-on-hull', 0.3],
      ['prop.corpse.valve-clutcher', 0.25],
    ],
    tags: ['wet', 'narrow'],
    lucid: '很低的隧道，中间是艉轴。轴在转，很慢，大约每十秒一圈。主机停了，轴不该转。',
    drift: '轴每十秒一圈。它在被外面的什么东西带着转，而那个东西的转速是恒定的。',
    resonant: '轴是逆时针转的。柴油机只能顺时针带它。有东西在从外面推螺旋桨，稳定地，一直在推。',
  }),
  room({
    id: 'rv.engine.workshop',
    archetype: 'engine',
    name: '机修间·台钳上夹着东西',
    decks: D.d23,
    weight: 10,
    ambient: { temperature: 17, noiseFloor: 0.24, airQuality: 0.54 },
    props: [
      ['prop.locker.tool-cage', 0.75],
      ['prop.logbook.engineering-rounds', 0.4],
      ['prop.pipe.conduit-bundle', 0.35],
      ['prop.terminal.engineering-mimic', 0.25],
    ],
    tags: ['loot'],
    lucid: '车床、钻床、一张钳工台。台钳上夹着一件东西，加工到一半，形状看不出用途。',
    drift: '台钳上那件东西是骨头，加工成了一个带螺纹的接头。螺纹是标准的，能接进船上的管路。',
    resonant: '台钳上夹的是一节指骨，正在被加工成钥匙。它加工得很好，因为加工的人很熟练了。',
  }),
  room({
    id: 'rv.engine.evaporator-bay',
    archetype: 'engine',
    name: '造水机舱·盐垢结成钟乳',
    decks: D.d23,
    weight: 8,
    ambient: { flooding: 0.26, temperature: 24, noiseFloor: 0.3, airQuality: 0.44 },
    props: [
      ['prop.valve.bilge-c', 0.45],
      ['prop.pipe.ruptured-main', 0.4],
      ['prop.pipe.frozen-branch', 0.2],
      ['prop.valve.oxygen-bleed', 0.3],
    ],
    tags: ['wet'],
    lucid: '造水机的管束上结满盐垢，垢层垂下来，像一片白色的钟乳。踩上去会碎，声音很脆。',
    drift: '盐垢只在一个方向生长——朝舱室出口。盐不会这样生长，除非有持续的气流带着盐走。',
    resonant: '盐垢里嵌着东西：指甲、扣子、一枚牙。它们被盐一层层包起来，像被慢慢吃掉。',
  }),
  room({
    id: 'rv.engine.hydraulic-plant',
    archetype: 'engine',
    name: '液压站·压力表全部归零',
    decks: D.d234,
    weight: 8,
    ambient: { temperature: 19, noiseFloor: 0.28, airQuality: 0.5, presence: 0.26 },
    props: [
      ['prop.valve.steam-crossover', 0.35],
      ['prop.breaker.pump-contactor', 0.4],
      ['prop.locker.tool-cage', 0.35],
      ['prop.terminal.engineering-mimic', 0.3],
    ],
    lucid: '液压站，四台泵，十二块压力表。所有表都是零。油箱是满的，油也是干净的。',
    drift: '表全是零，可是液压管路是硬的——里面有压力。表不是坏了，是被调过了。',
    resonant: '管路在轻微地鼓胀收缩。整个液压系统在替某个东西做它的循环，而它的循环比你的慢很多。',
  }),

  // ============================================================ 反应堆 reactor
  room({
    id: 'rv.reactor.control-cubicle',
    archetype: 'reactor',
    name: '堆控制间·记录纸仍在走',
    decks: D.d2,
    weight: 13,
    ambient: { temperature: 23, noiseFloor: 0.26, airQuality: 0.42, presence: 0.32 },
    props: [
      ['prop.breaker.reactor-scram', 0.6],
      ['prop.breaker.command-bus', 0.45],
      ['prop.terminal.engineering-mimic', 0.5],
      ['prop.logbook.engineering-rounds', 0.35],
    ],
    tags: ['anchor'],
    lucid: '控制间，仪表墙。走纸记录仪还在走，笔在纸上画着一条平直的线。堆功率稳定。',
    drift: '记录纸上的线在某个时刻有一个很小的台阶，之后一直平直。台阶的时刻是这艘船沉的时刻。',
    resonant: '记录纸上的线是你的呼吸曲线。它记的不是堆，从来都不是。',
  }),
  room({
    id: 'rv.reactor.shield-annulus',
    archetype: 'reactor',
    name: '屏蔽环形间·计数器在响',
    decks: D.d2,
    weight: 10,
    ambient: { temperature: 28, noiseFloor: 0.2, airQuality: 0.36, presence: 0.36 },
    props: [
      ['prop.breaker.hull-ground', 0.45],
      ['prop.pipe.conduit-bundle', 0.4],
      ['prop.specimen.growth-on-hull', 0.35],
      ['prop.breaker.sonar-array', 0.25],
    ],
    tags: ['hazard', 'hot'],
    lucid: '环绕堆体的窄环间。剂量计数器挂在墙上，在响，但频率在安全范围内。混凝土屏蔽层有裂缝。',
    drift: '裂缝是从内往外的。屏蔽层是为了挡住里面的东西，而里面的东西正在往外挤。',
    resonant: '裂缝里有光，不是蓝的。它在缓慢地愈合，也在缓慢地睁开，两件事同时。',
  }),
  room({
    id: 'rv.reactor.primary-loop-space',
    archetype: 'reactor',
    name: '一回路间·冷却水取自海',
    decks: D.d23,
    weight: 9,
    ambient: { flooding: 0.3, temperature: 31, noiseFloor: 0.36, airQuality: 0.38 },
    props: [
      ['prop.valve.steam-crossover', 0.45],
      ['prop.pipe.ruptured-main', 0.45],
      ['prop.breaker.hull-ground', 0.3],
      ['prop.valve.oxygen-bleed', 0.25],
    ],
    tags: ['hot', 'wet'],
    lucid: '一回路管道间，很热。取水口的过滤网被完全堵住，堵的是白色的絮状物，厚达半米。',
    drift: '絮状物堵住了取水口，可是水还在流。水从别的地方进来了。',
    resonant: '絮状物是活的，而且它在过滤 —— 它替过滤网在工作，把不该进来的东西挡在外面。你在里面。',
  }),
  room({
    id: 'rv.reactor.spent-cask-bay',
    archetype: 'reactor',
    name: '乏燃料罐间·罐子多了一个',
    decks: D.d23,
    weight: 7,
    ambient: { temperature: 26, noiseFloor: 0.14, airQuality: 0.4, presence: 0.44 },
    props: [
      ['prop.specimen.jar-row', 0.4],
      ['prop.breaker.reactor-scram', 0.3],
      ['prop.icon.hull-weld-sigil', 0.35],
      ['prop.nest.metal-hoard', 0.25],
    ],
    tags: ['hazard'],
    lucid: '铅罐存放间，地面有八个固定卡位，放着九个罐子。第九个没有卡位，直接立在地上。',
    drift: '第九个罐子没有编号，封条是新的，而且封条上的手印是从罐内一侧按的——不可能。',
    resonant: '第九个罐子在你走近时安静了。之前它在响，很轻，节奏是三短两长一短。',
  }),

  // ============================================================= 压载 ballast
  room({
    id: 'rv.ballast.main-tank-top',
    archetype: 'ballast',
    name: '主压载舱顶·人孔盖已打开',
    decks: D.d2,
    weight: 13,
    ambient: { flooding: 0.42, temperature: 11, noiseFloor: 0.28, airQuality: 0.48 },
    floodRate: 0.0026,
    props: [
      ['prop.valve.trunk-a', 0.35],
      ['prop.valve.ballast-blow', 0.4],
      ['prop.logbook.ballast-order-book', 0.45],
      ['prop.hatch.bilge-plate', 0.35],
      ['prop.breaker.pump-contactor', 0.35],
    ],
    tags: ['anchor', 'wet'],
    lucid: '压载舱顶板，一排人孔盖。有一个打开着，往下是水，看不见底。水面比舱顶低半米。',
    drift: '打开的那个人孔的螺栓整齐地摆在旁边，一颗不少。开它的人打算再关上，然后没回来。',
    resonant: '人孔下面的水面在上升，非常慢。水面上有呼气形成的雾，雾在扩大。',
  }),
  room({
    id: 'rv.ballast.trim-pump-room',
    archetype: 'ballast',
    name: '纵倾泵舱·泵轴还是温的',
    decks: D.d23,
    weight: 11,
    ambient: { flooding: 0.34, temperature: 15, noiseFloor: 0.4 },
    props: [
      ['prop.breaker.pump-contactor', 0.7],
      ['prop.valve.bilge-c', 0.5],
      ['prop.logbook.ballast-order-book', 0.35],
      ['prop.locker.tool-cage', 0.3],
    ],
    tags: ['loud', 'wet'],
    lucid: '纵倾泵舱，两台泵。其中一台的轴是温的，刚停不久。接触器上没有挂停电检修牌。',
    drift: '泵刚停。你到这层用了多久，泵停了多久，两个数差不多。它是听见你来才停的。',
    resonant: '泵一停，水位就开始升。它在等你决定：启泵，让整条船听见你；还是让水慢慢上来。',
  }),
  room({
    id: 'rv.ballast.negative-tank',
    archetype: 'ballast',
    name: '负浮力水舱·内部可通行',
    decks: D.d234,
    weight: 9,
    ambient: { flooding: 0.66, temperature: 8, noiseFloor: 0.18, presence: 0.34, airQuality: 0.4 },
    floodRate: 0.0034,
    props: [
      ['prop.valve.bilge-c', 0.5],
      ['prop.specimen.growth-on-hull', 0.4],
      ['prop.nest.metal-hoard', 0.3],
      ['prop.pipe.knocking-line', 0.3],
    ],
    tags: ['wet', 'crawl-adjacent'],
    lucid: '一个可以走进去的水舱，内部有加强肋作踏脚。水深到胸口，冷。舱壁上有水位刻度。',
    drift: '水位刻度被人用凿子加长了，往上加了四道。加的位置已经高过这个舱的舱顶。',
    resonant: '水面不平。中央有一块低下去，像有东西在下面吸气，把水面吸出一个浅坑。',
  }),
  room({
    id: 'rv.ballast.bilge-sump',
    archetype: 'ballast',
    name: '舱底集水井·滤网上有东西',
    decks: D.d23,
    weight: 9,
    ambient: { flooding: 0.58, temperature: 9, noiseFloor: 0.22, airQuality: 0.42 },
    floodRate: 0.003,
    props: [
      ['prop.valve.bilge-c', 0.6],
      ['prop.hatch.bilge-plate', 0.45],
      ['prop.specimen.folded-crewman', 0.25],
      ['prop.nest.metal-hoard', 0.25],
    ],
    tags: ['wet', 'gore'],
    lucid: '最低点的集水井，水在这里汇集。吸口滤网被堵住了，堵的是头发和布，缠得很紧。',
    drift: '头发和布缠成了一个球，球的直径比吸口大。它是从吸口另一侧被塞进来的。',
    resonant: '球在缓慢转动。它是被编出来的，而且还在被编——编的人从吸口里伸出一只手在编。',
  }),
  room({
    id: 'rv.ballast.blow-manifold',
    archetype: 'ballast',
    name: '吹除总管间·保险处于已执行位',
    decks: D.d23,
    weight: 8,
    ambient: { temperature: 13, noiseFloor: 0.24, airQuality: 0.5 },
    props: [
      ['prop.valve.ballast-blow', 0.85],
      ['prop.logbook.ballast-order-book', 0.6],
      ['prop.terminal.engineering-mimic', 0.35],
      ['prop.valve.trunk-a', 0.25],
    ],
    tags: ['puzzle'],
    lucid: '高压气吹除总管，一排阀。总保险在「已执行」位。气瓶压力表的读数是全空。',
    drift: '气瓶全空，说明吹除真的执行过，而且执行到了底。船还是在这个深度。',
    resonant: '气瓶在缓慢地回压。没有压气机在工作。有东西在往瓶里吹气，为了让你再试一次。',
  }),

  // ============================================================= 鱼雷 torpedo
  room({
    id: 'rv.torpedo.forward-room',
    archetype: 'torpedo',
    name: '前鱼雷舱·发射管一号后盖已开',
    decks: D.d12,
    weight: 13,
    ambient: { flooding: 0.18, temperature: 10, noiseFloor: 0.2, presence: 0.28 },
    props: [
      ['prop.hatch.torpedo-tube', 0.8],
      ['prop.locker.tool-cage', 0.4],
      ['prop.corpse.crushed-by-hatch', 0.3],
      ['prop.hatch.escape-trunk', 0.3],
    ],
    tags: ['anchor'],
    lucid: '四根发射管，管架上没有鱼雷。一号管后盖开着。舱里有备用铺位，因为这里最宽敞。',
    drift: '管架是空的，但管架上的固定带是用过的形状——装过东西，尺寸和鱼雷不一样，更细更长。',
    resonant: '一号管里有东西在往外挪，每次一点点，在你不看的时候。它想出来，不着急。',
  }),
  room({
    id: 'rv.torpedo.reload-space',
    archetype: 'torpedo',
    name: '装填间·吊链还挂着载荷',
    decks: D.d12,
    weight: 10,
    ambient: { temperature: 11, noiseFloor: 0.22, airQuality: 0.56 },
    props: [
      ['prop.locker.tool-cage', 0.45],
      ['prop.hatch.torpedo-tube', 0.35],
      ['prop.specimen.folded-crewman', 0.3],
      ['prop.pipe.conduit-bundle', 0.3],
    ],
    lucid: '装填轨道和吊链。吊链上挂着一个帆布包，按人形捆扎，长度超过两米。绳结在内侧。',
    drift: '绳结打在内侧，需要从包里伸手出来打。捆的是自己。',
    resonant: '帆布包在随船体的应力轻轻晃。晃的周期比船体应力的周期短，说明它自己也在动。',
  }),
  room({
    id: 'rv.torpedo.warhead-magazine',
    archetype: 'torpedo',
    name: '战雷头舱·库存卡对不上',
    decks: D.d2,
    weight: 8,
    ambient: { temperature: 9, noiseFloor: 0.12, airQuality: 0.52, presence: 0.24 },
    props: [
      ['prop.locker.tool-cage', 0.4],
      ['prop.logbook.deck-log', 0.35],
      ['prop.nest.metal-hoard', 0.3],
      ['prop.icon.hull-weld-sigil', 0.25],
    ],
    tags: ['loot'],
    lucid: '弹头存放架，编号卡位十二个，实物十一个。库存卡上写十二。差的那一个是七号位。',
    drift: '七号位的卡槽里插着一张手写的替代卡，写的不是弹头编号，是一个人名。',
    resonant: '七号位不是空的。里面立着一个人，和弹头一样的姿势，头朝前，脚被固定带缠着。',
  }),
  room({
    id: 'rv.torpedo.escape-trunk-base',
    archetype: 'torpedo',
    name: '鱼雷舱逃生筒底·梯子被拆走三级',
    decks: D.d12,
    weight: 8,
    ambient: { flooding: 0.3, temperature: 9, noiseFloor: 0.18 },
    props: [
      ['prop.hatch.escape-trunk', 0.75],
      ['prop.locker.dive-suit-rack', 0.45],
      ['prop.terminal.depth-readout', 0.3],
      ['prop.radio.emergency-beacon', 0.3],
    ],
    tags: ['escape'],
    lucid: '逃生筒的底部。筒内有爬梯，最下面三级被拆走了，切口是新的，锯痕整齐。',
    drift: '最下面三级被锯走，说明有人不想让人从下面上去，或者不想让东西从上面下来。',
    resonant: '筒里往上看有光。这个深度不该有光。光在动，在下来。',
  }),

  // ========================================================= 爬行管道 crawlspace
  room({
    id: 'rv.crawlspace.cable-trunk',
    archetype: 'crawlspace',
    name: '电缆爬管·仅容一人侧身',
    decks: D.d1234,
    weight: 14,
    ambient: { noiseFloor: 0.03, airQuality: 0.38, presence: 0.42, temperature: 14 },
    noiseThreshold: 62,
    props: [['prop.pipe.conduit-bundle', 0.55], ['prop.pipe.crawl-junction', 0.5], ['prop.radio.pipe-voice', 0.35]],
    tags: ['crawl', 'quiet'],
    lucid: '一条只能侧身通过的电缆爬管。安静到你能听见自己的关节。手肘在钢板上的每一下都很响。',
    drift: '你听得见自己的关节。也听得见前面某个转角后面有关节的声音，节奏和你的相反。',
    resonant: '管子的内径在你爬到一半时变小了。它不是塌了，它是在收紧，慢慢地，很有耐心。',
  }),
  room({
    id: 'rv.crawlspace.vent-plenum',
    archetype: 'crawlspace',
    name: '通风静压箱·内壁贴满吸音棉',
    decks: D.d1234,
    weight: 12,
    ambient: { noiseFloor: 0.01, airQuality: 0.34, presence: 0.46, temperature: 16 },
    noiseThreshold: 74,
    props: [['prop.pipe.breathing-duct', 0.6], ['prop.pipe.crawl-junction', 0.4], ['prop.nest.hair-and-cloth', 0.3]],
    tags: ['crawl', 'quiet'],
    lucid:
      '一个大到能爬进去的静压箱，内壁贴着吸音棉。这里是全船最安静的地方——声音一进来就死了。',
    drift: '吸音棉上有一片片压扁的区域，尺寸是躺着的人。有人在这里睡过，很多次，为了安静。',
    resonant: '吸音棉吸掉了所有声音，除了一种：一个很低的、四秒一次的起伏。它不是声音，是箱子在动。',
  }),
  room({
    id: 'rv.crawlspace.bilge-crawl',
    archetype: 'crawlspace',
    name: '舱底爬行道·水面离舱顶三十公分',
    decks: D.d234,
    weight: 11,
    ambient: { flooding: 0.72, temperature: 7, noiseFloor: 0.06, airQuality: 0.3, presence: 0.5 },
    noiseThreshold: 66,
    floodRate: 0.0028,
    props: [
      ['prop.pipe.crawl-junction', 0.45],
      ['prop.specimen.growth-on-hull', 0.4],
      ['prop.hatch.bilge-plate', 0.35],
      ['prop.specimen.folded-crewman', 0.2],
    ],
    tags: ['crawl', 'wet', 'quiet'],
    lucid: '舱底爬行道，水面离舱顶三十公分。你必须把脸侧着才能呼吸。水很冷，油味很重。',
    drift: '你的脸侧着贴在舱顶。三十公分的空气层里，有别人呼出来的温度。',
    resonant: '空气层在变窄。不是水在涨，是舱顶在下来。它在测量你的极限，记录下来，然后再收一点。',
  }),
  room({
    id: 'rv.crawlspace.between-hulls',
    archetype: 'crawlspace',
    name: '双层壳之间·外壳有规律敲击',
    decks: D.d2345,
    weight: 10,
    ambient: { noiseFloor: 0.04, temperature: 5, airQuality: 0.32, presence: 0.62 },
    noiseThreshold: 70,
    props: [
      ['prop.pipe.knocking-line', 0.6],
      ['prop.icon.hull-weld-sigil', 0.4],
      ['prop.breaker.hull-ground', 0.3],
      ['prop.nest.listener-sign', 0.25],
    ],
    tags: ['crawl', 'quiet', 'eerie'],
    lucid: '耐压壳和外壳之间的空隙，五十公分。外壳那一侧一直有敲击，三短两长一短，间隔严格。',
    drift: '敲击来自外壳的**外**侧，也就是海那一侧。海里的东西在用一种船员的节奏敲。',
    resonant: '敲击跟着你移动。你爬三米，敲击的位置也挪三米，始终在你耳朵正对着的那块钢板上。',
  }),
  room({
    id: 'rv.crawlspace.overhead-run',
    archetype: 'crawlspace',
    name: '舱顶夹层·可俯视下方舱室',
    decks: D.d1234,
    weight: 9,
    ambient: { noiseFloor: 0.05, airQuality: 0.4, presence: 0.44, temperature: 18 },
    noiseThreshold: 60,
    props: [
      ['prop.pipe.crawl-junction', 0.4],
      ['prop.pipe.breathing-duct', 0.4],
      ['prop.mirror.polished-bulkhead', 0.25],
      ['prop.terminal.dead-screen', 0.2],
    ],
    tags: ['crawl', 'quiet', 'vantage'],
    lucid: '舱顶和上层甲板之间的夹层。格栅的缝隙能看到下面的舱室，也能看到下面的人看不到的角度。',
    drift: '从缝隙往下看，下面那个房间里有一个人在抬头看格栅。你退开，他还在看那个位置。',
    resonant: '下面那个房间是你刚刚离开的。里面有一个你，正在抬头，正在发现夹层里有东西。',
  }),
  room({
    id: 'rv.crawlspace.sanctum-duct',
    archetype: 'crawlspace',
    name: '圣所送风管·内壁刻满字',
    decks: D.d45,
    weight: 9,
    ambient: { noiseFloor: 0.02, temperature: 4, airQuality: 0.3, presence: 0.72 },
    noiseThreshold: 72,
    props: [
      ['prop.altar.name-wall', 0.45],
      ['prop.icon.listening-ear', 0.4],
      ['prop.radio.pipe-voice', 0.4],
      ['prop.pipe.breathing-duct', 0.35],
    ],
    tags: ['crawl', 'quiet', 'cult'],
    lucid: '通往圣所的送风管，内壁被刻满了字，从入口一直刻到看不见的深处。字很小，刻得很深。',
    drift: '刻的字全是同一句话，重复了成千上万次。句子很短，三个音节，你读不出来但能数出来。',
    resonant:
      '三个音节是你的名字。刻的人是在爬过去的时候一边爬一边刻的，所以字越往里越稳——他越来越熟练。',
  }),
];
