import assert from 'node:assert/strict';
import {Box3,Vector3} from 'three';
import {harborHullClear,sweepHarborHeading} from '../src/pod/sim/harbor-navigation';
const box=(a:number[],b:number[])=>new Box3(new Vector3(...a),new Vector3(...b));
const passage=[box([-3.5,-3,-50],[3.5,4,50])];
assert.ok(harborHullClear(new Vector3(),0,passage,[]));
assert.equal(harborHullClear(new Vector3(2.5,0,0),0,passage,[]),false);
assert.equal(harborHullClear(new Vector3(),0,passage,[box([-.1,-2,-1],[.1,2,-.9])]),false,'thin obstacles between samples still collide');
assert.ok(harborHullClear(new Vector3(0,-20,0),0,[box([-5,-23,-10],[5,-15,10])],[]),'real lower level is reachable');
assert.equal(harborHullClear(new Vector3(0,-20,0),0,passage,[]),false);
console.log('PASS hull footprint, thin-solid SAT, and lower-level clearance');
const nearWall=new Vector3(1.9,0,0);
const clear=(h:number)=>harborHullClear(nearWall,h,passage,[]);
assert.ok(clear(0));assert.equal(clear(56),false,'old unchecked yaw embeds hull');
const limited=sweepHarborHeading(0,56,clear);
assert.ok(clear(limited));assert.ok(limited<56,'rotation stops before hull intersects');
const repaired=sweepHarborHeading(56,0,clear);
assert.ok(clear(repaired),'legacy embedded yaw recovers in place');
const backwards=nearWall.clone().add(new Vector3(-Math.sin(repaired*Math.PI/180)*.08,0,Math.cos(repaired*Math.PI/180)*.08));
assert.ok(harborHullClear(backwards,repaired,passage,[]),'reverse works after recovery');
assert.ok(clear(sweepHarborHeading(limited,-56,clear)),'turning away remains possible');
console.log('PASS wall-adjacent yaw sweep, legacy recovery, reverse and turning away');
