import assert from 'node:assert/strict';
import {Box3,Vector3} from 'three';
import {sonarRay,scanNavigationSonar,sonarSweepAngle,sonarEchoAlpha,SONAR_STATIC,SONAR_THREAT} from '../src/pod/sim/navigation-sonar';
const box=(a:number[],b:number[])=>new Box3(new Vector3(...a),new Vector3(...b));
const wall=box([-10,-3,-10],[10,4,-9]);
const crate=box([-1,-1,-5],[1,1,-4]);
const p=new Vector3();
assert.equal(sonarRay(p,0,-1,[wall]),9);
assert.equal(sonarRay(p,0,-1,[wall,crate]),4,'near crate occludes wall');
assert.equal(sonarRay(p,0,-1,[box([-1,8,-5],[1,10,-4])]),24,'other deck not false obstruction');
assert.equal(scanNavigationSonar(p,0,[wall])[0].distance,9);
assert.equal(scanNavigationSonar(p,90,[wall])[0].distance,24,'heading-up rotation');
assert.equal(sonarRay(p,0,-1,[]),24,'open door disappears');
assert.notEqual(SONAR_STATIC,SONAR_THREAT);
console.log('PASS real geometry, occlusion, depth filtering, heading, open doors, distinct threat colour; no lamp dependency');
assert.ok(Math.abs(sonarSweepAngle(.6)-Math.PI/2)<1e-9);
assert.ok(Math.abs(sonarSweepAngle(2.4))<1e-9);
assert.equal(sonarEchoAlpha(0,0),1);
assert.ok(sonarEchoAlpha(1,0)<sonarEchoAlpha(.1,0),'phosphor decays after sweep');
assert.ok(sonarEchoAlpha(2.3,0)>=.25,'continuous safety trace never disappears');
console.log('PASS live sweep rotation, wrap, echo decay and persistent safety channel');
