import './style.css';
import {campaign} from './campaign';
import {StoryEngine} from './engine';
import {rankCandidates} from './director';
import type {Condition,StoryScene} from './types';
import currentStory from '../../docs/story-split-route-2026-09-30.md?raw';
import rewriteAudit from '../../docs/story-investigation-audit.md?raw';

const engine=new StoryEngine(campaign);
const root=document.querySelector<HTMLDivElement>('#app')!;
let selected=0,tab=new URLSearchParams(location.search).get('view')==='legacy'?'flow':'story',storyChapter=1,zoom=.8,message='叙事试玩从接驳层开始。先取得侦察片，再作出决定。';
const storyHeadings=[...currentStory.replace(/\r/g,'').matchAll(/^(#{1,3}) (.+)$/gm)];
const storyChapters=storyHeadings.flatMap((m,index)=>m[1]==='##'&&/^第[一二三四五]章/.test(m[2])?[{title:m[2],anchor:`section-${index}`}]:[]);
let last=performance.now(),lastRender=0;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const phaseNames:Record<string,string>={scout:'01 侦察摄影',decision:'02 判断与行动',result:'03 结果摄影',resolve:'04 结果后的决定',next:'05 准备离开',ended:'终局'};
const speakerNames:Record<string,string>={vance:'万斯',elias:'埃利亚斯',niko:'尼科',lena:'莱娜',player:'罗温'};
const condition=(c?:Condition):string=>!c?'true':'all'in c?`(${c.all.map(condition).join(' && ')})`:'any'in c?`(${c.any.map(condition).join(' || ')})`:`${c.path} ${c.op} ${JSON.stringify(c.value)}`;
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
function budget(scene:StoryScene){const p=scene.plannedSeconds;return p.travel+p.reading+p.action;}
function exportFile(name:string,value:unknown){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function graph(){
 const state=engine.snapshot();let paths='';
 const loc=(i:number)=>({x:30+Math.floor(i/3)*296,y:145+(i%3)*305});
 for(let i=0;i<campaign.scenes.length-1;i++){const a=loc(i),b=loc(i+1);if(Math.floor(i/3)===Math.floor((i+1)/3))paths+=`<path d="M ${a.x+125} ${a.y+235} L ${b.x+125} ${b.y}"/>`;else paths+=`<path d="M ${a.x+250} ${a.y+105} C ${a.x+280} ${a.y+105}, ${b.x-20} ${b.y+105}, ${b.x} ${b.y+105}"/>`;}
 return `<div class="flow" style="transform:scale(${zoom})"><svg width="1520" height="1220" style="position:absolute;pointer-events:none"><g fill="none" stroke="#5e7282" stroke-width="1.4">${paths}</g></svg>${campaign.chapters.map((c,i)=>`<div class="lane" style="left:${30+i*296}px">CHAPTER 0${c.id} · ${esc(c.title)}<small>${c.depth} m · ${Math.round(campaign.scenes.filter(s=>s.chapter===c.id).reduce((a,s)=>a+budget(s),0)/60)} 分钟设计预算</small></div>`).join('')}${campaign.scenes.map((s,i)=>{const p=loc(i);return `<button class="node ${selected===i?'selected':''} ${state.sceneIndex===i?'current':''} ${state.sceneIndex>i?'done':''}" data-select="${i}" style="left:${p.x}px;top:${p.y}px;height:235px"><div class="node-head">FLOW FRAGMENT / ${esc(s.id)}</div><h3>${esc(s.title)}</h3><p>${esc(s.location)}<br>${esc(s.entryText.slice(0,53))}…</p><div class="pins"><span>▣ 侦察片</span><span class="condition">◇ 条件判断</span><span>▣ 结果片</span></div><div class="pins"><span class="condition">◇ 二次决定</span><span class="pin-end">→ 状态写入</span><span>${s.choices.length} 行动分支</span></div></button>`;}).join('')}<div class="legend"><b>●</b> 当前可玩环节　<span style="color:#ecb56e">▣</span> 正在检查的节点　◇ Condition　→ Instruction<br>点击任意节点检查条件和效果；不会跳过剧情进度。此工作台模拟叙事，不冒充五关 3D 实机。</div></div>`;
}
function central(){
 const state=engine.snapshot(),scene=campaign.scenes[selected];
 if(tab==='flow')return graph();
 if(tab==='branches'){
  const count=Math.max(scene.choices.length,scene.resolutions.length),height=180+count*245;
  const paths=scene.choices.map((_,i)=>`<path d="M 270 220 C 290 220,295 ${145+i*245},320 ${145+i*245}"/><path d="M 570 ${145+i*245} L 635 ${145+i*245}"/>`).join('')+scene.choices.map((_,i)=>`<path d="M 885 ${145+i*245} L 915 ${145+i*245}"/>`).join('')+`<path d="M 915 145 L 915 ${145+(count-1)*245}"/>`+scene.resolutions.map((_,i)=>`<path d="M 915 ${145+i*245} L 955 ${145+i*245}"/>`).join('');
  return `<div style="position:relative;width:1250px;height:${height}px"><div class="lane" style="left:20px;top:20px;width:1160px">${esc(scene.id)} · ${esc(scene.title)}　/　分支展开：所有入口都由条件重新校验，线条不绕过守卫</div><svg width="1250" height="${height}" style="position:absolute;pointer-events:none"><g fill="none" stroke="#667f90">${paths}</g></svg><article class="node" style="left:20px;top:120px;height:215px"><div class="node-head">INPUT / 侦察证据</div><h3>曝光 → 处理 → 判读</h3><p>${esc(scene.scoutFootage.slice(0,100))}</p><p class="condition">授予 ${scene.scoutFacts.length} 项玩家知识</p></article>${scene.choices.map((c,i)=>`<article class="node" style="left:320px;top:${100+i*245}px;height:220px"><div class="node-head">CONDITION → INSTRUCTION</div><h3>${esc(c.label)}</h3><p title="${esc(condition(c.condition))}">${esc(condition(c.condition).slice(0,115))}</p><p>${c.instructions.length} 项状态效果 · 必须实际执行</p></article><article class="node" style="left:635px;top:${100+i*245}px;height:220px"><div class="node-head">RESULT / 冻结的行动结果</div><h3>再次拍摄与判读</h3><p>${esc(c.resultText.slice(0,115))}</p></article>`).join('')}${scene.resolutions.map((r,i)=>`<article class="node" style="left:955px;top:${100+i*245}px;height:220px"><div class="node-head">CONDITION → 第二次决定</div><h3>${esc(r.label)}</h3><p>${esc(condition(r.condition).slice(0,90))}</p><p>${esc(r.text.slice(0,75))}</p></article>`).join('')}</div>`;
 }
 if(tab==='variables')return `<div class="panel"><h2>状态与知识隔离</h2><p>编辑审查视图含剧透。World 保存客观事实；Knowledge 保存各角色实际取得的信息。关系只影响合作和措辞，不能改变身份或旧证据。</p><pre>${esc(JSON.stringify({player:state.player,pod:state.pod,relations:state.relations,world:state.world,knowledge:state.knowledge},null,2))}</pre></div>`;
 if(tab==='events')return `<div class="panel"><h2>因果事件账本</h2><p>每次状态改变保留事件、场景与时间。保存 / 恢复使用独立文件，不写正式游戏存档。</p>${state.events.slice().reverse().map(e=>`<div class="event"><b>#${e.id} · ${fmt(e.at)} · ${esc(e.sceneId)} · ${esc(e.type)}</b><br>${esc(e.detail)}${e.causedBy!==undefined?`<br><small>由事件 #${e.causedBy} 引起</small>`:''}</div>`).join('')}</div>`;
 if(tab==='budget')return `<div class="panel"><h2>60 分钟内容预算</h2><p>这是主线设计预算，不是已经实测的完成时长。这里的文字分镜、快速状态推演不能代替完整五关实机；摄影以真实 5 秒曝光、12 秒处理运行。旅行、操作与人物演出的预算必须在关卡接入后通过首次玩家测试校准。</p><div class="budget">${campaign.chapters.map(c=>{const scenes=campaign.scenes.filter(s=>s.chapter===c.id);return `<div>${esc(c.title)}<br><strong>${Math.round(scenes.reduce((a,s)=>a+budget(s),0)/60)} min</strong><br>${esc(c.dramaticQuestion)}</div>`;}).join('')}</div><h3>导出格式与来源</h3><p>采用 Flow Fragment、Condition、Instruction、变量与连线的 Articy:draft 工作方式。导出为本项目开放 JSON 设计蓝图，尚非经过 Articy 原生导入验证的工程文件。</p><p><a href="https://www.articy.com/help/legacy/Flow_Conditions_Instructions.html" target="_blank" rel="noreferrer">Articy 官方：条件与指令</a> · <a href="https://www.articy.com/help/legacy/Presentation_Simulation.html" target="_blank" rel="noreferrer">Articy 官方：流程模拟</a></p><p><a href="https://gdcvault.com/play/1034616/Larian-Cinematics-A-Top-Down" target="_blank" rel="noreferrer">Larian / GDC：BG3 过场工作管线</a>。借鉴反应式内容的制作与迭代思路；不声称 BG3 使用本项目的生成式 AI 或 Articy 工程。</p></div>`;
 return `<div class="panel"><h2>${esc(scene.title)} · 节点定义</h2><p>${esc(scene.entryText)}</p>${scene.choices.map(c=>`<h3>${esc(c.label)}</h3><pre>Condition: ${esc(condition(c.condition))}\nInstruction: ${esc(JSON.stringify(c.instructions,null,2))}\nEvidence: ${esc(c.evidence.join(', '))}</pre><p>${esc(c.consequence)}</p>`).join('')}<h3>结果后的决策</h3>${scene.resolutions.map(r=>`<pre>${esc(r.label)}\nCondition: ${esc(condition(r.condition))}\nInstruction: ${esc(JSON.stringify(r.instructions,null,2))}\n${esc(r.text)}</pre>`).join('')}</div>`;
}
function inspector(){
 const s=engine.snapshot(),scene=engine.scene;const active=s.tapes.find(t=>t.id===s.activeTapeId);const latest=[...s.tapes].reverse().find(t=>t.sceneId===scene.id);
 const chosen=scene.choices.find(c=>c.id===s.selectedChoice);
 const followup=scene.resolutions.find(r=>r.id===s.selectedResolution);
 const passage=s.phase==='next'?followup?.text??scene.resolveText:s.phase==='resolve'?scene.resolveText:s.phase==='result'?`你已执行：${chosen?.label??'刚才的操作'}。收回机械臂后，拍一段录像，看看外面现在怎么样。`:s.phase==='ended'?'':scene.entryText;
 const capturing=s.captureRemaining>0,developing=s.developRemaining>0;
 let actions='';
 if(s.phase==='scout'||s.phase==='result'){
  actions=capturing||developing?`<div class="callout">${capturing?'曝光中 · 5 秒':'处理感光记录 · 12 秒'}<div class="timebar"><i style="width:${100*(1-(capturing?s.captureRemaining/5:s.developRemaining/12))}%"></i></div><span data-countdown>${(capturing?s.captureRemaining:s.developRemaining).toFixed(1)} 秒</span></div>`:latest?.ready&&!latest.analyzed&&latest.epoch===s.epoch?`<button class="primary" data-action="analyze">查看录像</button>`:`<button class="primary" data-action="shoot">${s.phase==='scout'?'拍摄侦察片':'拍摄行动结果'}</button>`;
 }else if(s.phase==='decision')actions=engine.getChoices().map(c=>`<button class="choice" data-choice="${esc(c.id)}" ${c.allowed?'':'disabled'}>${esc(c.choice.label)}${!c.allowed?`<small>${esc(c.reason)}</small>`:''}</button>`).join('');
 else if(s.phase==='resolve')actions=engine.getResolutions().map(c=>`<button class="choice" data-resolution="${esc(c.resolution.id)}" ${c.allowed?'':'disabled'}>${esc(c.resolution.label)}${!c.allowed?`<small>${esc(c.reason)}</small>`:''}</button>`).join('')+`<details><summary>返回现场采取不同动作（需要重新拍结果）</summary>${engine.getChoices().map(c=>`<button class="choice" data-choice="${esc(c.id)}" ${c.allowed?'':'disabled'}>${esc(c.choice.label)}</button>`).join('')}</details>`;
 else if(s.phase==='next')actions='<button class="primary" data-action="advance">继续前进 →</button>';
 else {const end=campaign.endings.find(e=>e.id===s.endingId);actions=`<div class="callout"><strong>${esc(end?.title??s.endingId)}</strong><p>${esc(end?.summary)}</p></div><button data-action="reset">重新推演另一条路线</button>`;}
 return `<div class="session-tag">LIVE STORY SIMULATION · 叙事试玩</div><h2>${esc(scene.title)}</h2><div class="where">${esc(scene.location)} / ${esc(scene.id)}</div><div class="stat-grid"><div class="stat"><small>潜艇电量</small><b>${Math.round(s.pod.power*100)}%</b></div><div class="stat"><small>艇壳完整度</small><b>${Math.round(s.pod.hull*100)}%</b></div><div class="stat"><small>模拟钟</small><b>${fmt(s.clock)}</b></div></div><div class="stepbar">${['scout','decision','result','resolve','next'].map(p=>`<span class="${p===s.phase?'on':''}"></span>`).join('')}</div><div class="eyebrow">${phaseNames[s.phase]}</div><div class="message" role="status">${esc(message)}</div><div class="copy">${esc(passage)}</div>${latest?.ready?`<div class="evidence"><div class="stamp">${esc(latest.id)} · ${fmt(latest.capturedAt)} · EPOCH ${latest.epoch}<br>受控文字分镜 / 非实拍视频</div><p>${esc(latest.text)}</p></div>`:''}<div class="actions">${actions}</div>${engine.getNpcLines().map(l=>`<div class="dialogue"><b>${speakerNames[l.speaker]}</b>　${esc(l.text)}</div>`).join('')}<div class="secondary"><button data-action="report">把已知证据报告万斯</button><button data-action="resupply">安全补给 / 修复</button><button data-action="candidate">查询合法候选</button></div><div class="muted">本工具的现场影像以受控文字分镜呈现，读取锁定的曝光快照。补给为叙事模拟安全设施；真实关卡可达性仍需实机验证。</div><details><summary>编辑器：证据编号</summary>${s.knowledge.player.map(f=>`<span class="fact">${esc(f)}</span>`).join('')||'<p class="muted">尚无已核验事实</p>'}</details><details><summary>编辑器：关系与角色知识</summary><pre>${esc(JSON.stringify({relations:s.relations,vance:s.knowledge.vance},null,2))}</pre></details><details><summary>摄影测试工具（非正常游玩）</summary><p class="muted">快进只用于验证时序边界，不计为实际 60 分钟试玩。</p><button data-action="fast">推进模拟钟 17 秒</button></details>`;
}
function render(){
 if(tab==='story'||tab==='story-audit'||tab==='story-branches'||tab==='story-design'){
  const chapter=storyChapters[storyChapter-1];
  root.innerHTML=`<div style="height:100vh;display:flex;flex-direction:column;background:#11191e"><header class="top" style="flex-shrink:0;flex-wrap:wrap;padding:12px 20px"><div class="brand"><div class="mark">◇</div><div><strong>迟到的目击者</strong><small>五章正文 · 事故调查线修订</small></div></div><div class="toolbar" style="flex-wrap:wrap"><button data-tab="story">当前剧情</button><button data-tab="story-branches">分支场景</button><button data-tab="story-design">制作资料</button><button data-tab="story-audit">本轮约束检查</button><button data-tab="flow">旧稿状态机（未迁移）</button></div></header><nav style="display:flex;flex-wrap:wrap;gap:8px;padding:12px 20px;flex-shrink:0;border-bottom:1px solid #34434b" aria-label="当前剧情章节">${storyChapters.map((c,i)=>`<button data-story-chapter="${i+1}" style="${storyChapter===i+1?'border-color:#d6b579;color:#ffd38d':''}">${esc(c.title)}</button>`).join('')}</nav>${tab!=='story-audit'?`<iframe title="当前剧情阅读稿" src="/story.html${tab==='story-branches'?'?view=branches':tab==='story-design'?'?view=design':'#'+(chapter?.anchor??'')}" style="width:100%;flex:1;min-height:0;border:0"></iframe>`:`<main style="overflow:auto;flex:1;min-height:0;padding:28px"><pre style="white-space:pre-wrap;overflow-wrap:anywhere;max-width:1100px;margin:auto;font:16px/1.9 'Microsoft YaHei',sans-serif;color:#dbe5e7">${esc(rewriteAudit)}</pre></main>`}</div>`;
  return;
 }
 const opened=new Set(Array.from(root.querySelectorAll('details[open]')).map(d=>d.querySelector('summary')?.textContent));
 const savedScroll=root.querySelector('.canvas') as HTMLElement|null;const scroll=savedScroll?{x:savedScroll.scrollLeft,y:savedScroll.scrollTop}:null;
 const right=root.querySelector('.inspector')?.scrollTop??0;
 root.innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="mark">◇</div><div><strong>迟到的目击者</strong><small>NARRATIVE WORKSPACE / 五关因果图</small></div></div><div class="top-note">旧版剧情状态机（未迁移）</div><div class="toolbar"><button data-tab="story">当前修订稿</button><a href="/story.html" style="color:#ffd38d;padding:8px">阅读当前修订稿 →</a><button data-action="export">导出节点蓝图</button><button data-action="save">保存推演</button><button data-action="load">读取推演</button><button data-action="reset">重置</button></div></header><div class="workspace"><nav class="tree"><p class="eyebrow">PROJECT EXPLORER</p><h2>五关 · 十五个摄影环节</h2>${campaign.chapters.map(c=>`<button class="chapter ${campaign.scenes[selected].chapter===c.id?'active':''}" data-chapter="${c.id}">▾ 0${c.id}　${esc(c.title)}<span>3 FLOW FRAGMENTS</span></button>`).join('')}<div class="tree-rule"><strong>叙事契约</strong><br>客观事实 ≠ 录像快照<br>玩家知道 ≠ NPC 知道<br>关系变化 ≠ 身份变化<br>AI 提议 ≠ 权威状态写入</div><div class="tree-rule"><strong>第一章硬约束</strong><br>真实救出埃利亚斯。<br>没有谎言或异常身份伏笔。<br>不把救援追溯为骗局。</div><a href="/whitebox.html" class="muted">打开现有 3D 救援白模 ↗</a></nav><main class="main"><div class="tabs">${[['flow','流程图'],['branches','分支展开'],['definition','节点定义'],['variables','全局变量'],['events','时间线'],['budget','预算 / 来源']].map(([id,label])=>`<button class="tab ${tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}<div class="zoom"><button class="small" data-action="zoomout">−</button>${Math.round(zoom*100)}%<button class="small" data-action="zoomin">+</button></div></div><div class="canvas">${central()}</div></main><aside class="inspector">${inspector()}</aside></div><footer class="footer"><span>● 状态机权威裁决　 /　 ${campaign.scenes.length} 节点 · ${campaign.endings.length} 终局</span><span>60 min 为设计预算 · 原生 Articy 导入与真人盲测尚未验证</span></footer></div>`;
 if(scroll){const el=root.querySelector('.canvas')!;el.scrollLeft=scroll.x;el.scrollTop=scroll.y;}root.querySelector('.inspector')!.scrollTop=right;
 root.querySelectorAll('details').forEach(d=>{if(opened.has(d.querySelector('summary')?.textContent))d.open=true;});
}
root.addEventListener('click',async event=>{
 const el=(event.target as Element).closest<HTMLButtonElement>('button');if(!el||el.disabled)return;
 if(el.dataset.storyChapter){storyChapter=Number(el.dataset.storyChapter);tab='story';render();return;}
 if(el.dataset.select){selected=Number(el.dataset.select);render();return;}
 if(el.dataset.chapter){selected=campaign.scenes.findIndex(s=>s.chapter===Number(el.dataset.chapter));tab='flow';render();const canvas=root.querySelector('.canvas')!;canvas.scrollLeft=Math.floor(selected/3)*296*zoom;return;}
 if(el.dataset.tab){tab=el.dataset.tab;render();return;}
 let result:{ok:boolean;message:string}|undefined;
 if(el.dataset.choice)result=engine.act(el.dataset.choice);
 else if(el.dataset.resolution)result=engine.resolve(el.dataset.resolution);
 else switch(el.dataset.action){
  case 'shoot':result=engine.shoot();break;case 'analyze':result=engine.analyze();break;case 'report':result=engine.report();break;case 'resupply':result=engine.resupply();break;
  case 'advance':result=engine.advance();selected=engine.snapshot().sceneIndex;break;
  case 'candidate':{const c=rankCandidates(engine.snapshot(),engine.getChoices())[0],authored=engine.chooseCandidate();message=c?`${authored&&authored.id!==c.id?`叙事路线：${authored.choice.label}。资源建议：`:'合法候选：'}${c.choice.label}。${c.reasons.join('；')}。资源排序不代表最佳结局，决定仍由你作出。`:'当前没有可执行的行动候选。';break;}
  case 'fast':engine.tick(17);message='测试快进了 17 秒；不作为实玩时长证据。';break;
  case 'reset':if(confirm('从首章重新开始这次叙事推演？正式游戏存档不会改变。')){engine.reset();selected=0;message='已重新开始独立叙事推演。';}break;
  case 'save':exportFile('narrative-session.json',JSON.parse(engine.serialize()));message='推演存档已导出为本地文件。';break;
  case 'load':{const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{if(input.files?.[0]){const r=engine.restore(await input.files[0].text());message=r.message;selected=engine.snapshot().sceneIndex;render();}};input.click();break;}
  case 'export':exportFile('narrative-flow-blueprint.json',{format:'ironlung.articy-style-blueprint',nativeArticyProject:false,campaign});message='已导出开放 JSON 蓝图；未声称是原生 Articy 工程文件。';break;
  case 'zoomin':zoom=Math.min(1.25,zoom+.1);break;case 'zoomout':zoom=Math.max(.4,zoom-.1);break;
 }
 if(result)message=result.message;render();
});
Object.defineProperty(window,'__narrativeLab',{value:{engine,campaign},configurable:true});
function frame(now:number){const dt=Math.max(0,Math.min(.25,(now-last)/1000));last=now;const before=engine.snapshot();engine.tick(dt);const after=engine.snapshot();const wasBusy=before.captureRemaining>0||before.developRemaining>0;const completed=wasBusy&&after.captureRemaining===0&&after.developRemaining===0;if(!tab.startsWith('story')&&(completed||(wasBusy&&now-lastRender>300))){render();lastRender=now;}requestAnimationFrame(frame);}
render();requestAnimationFrame(frame);
